In [1]:
import pandas as pd

df = pd.read_excel(
    "../data/QS_2026_Top150_Europe_Sampling_Frame.xlsx",
    sheet_name="Europe Sampling Frame"
)

df.head()

,QS 2026 Rank,University,Country,Region,Programme Check,Eligible Programme Name,Search Term Match,Official Programme URL,Screening Notes
0,2,Imperial College London,United Kingdom,Europe,Pending,NaN,NaN,NaN,NaN
1,4,University of Oxford,United Kingdom,Europe,Pending,NaN,NaN,NaN,NaN
2,6,University of Cambridge,United Kingdom,Europe,Pending,NaN,NaN,NaN,NaN
3,7,ETH Zurich,Switzerland,Europe,Pending,NaN,NaN,NaN,NaN
4,9,UCL,United Kingdom,Europe,Pending,NaN,NaN,NaN,NaN

In [2]:
SEARCH_TERMS = [
    "Business Analytics",
    "Data Science",
    "Data Analytics",
    "Applied Analytics",
    "Business Intelligence",
    "Applied Data Science",
    "Statistics and Data Science",
    "Analytics and Data Science"
]

SEARCH_TERMS

['Business Analytics',
 'Data Science',
 'Data Analytics',
 'Applied Analytics',
 'Business Intelligence',
 'Applied Data Science',
 'Statistics and Data Science',
 'Analytics and Data Science']

In [3]:
search_tasks = []

for university in df["University"]:
    for term in SEARCH_TERMS:
        search_tasks.append({
            "university": university,
            "search_term": term,
            "query": f"{university} {term} master's"
        })

search_df = pd.DataFrame(search_tasks)

search_df.head(10)

,university,search_term,query
0,Imperial College London,Business Analytics,Imperial College London Business Analytics mas...
1,Imperial College London,Data Science,Imperial College London Data Science master's
2,Imperial College London,Data Analytics,Imperial College London Data Analytics master's
3,Imperial College London,Applied Analytics,Imperial College London Applied Analytics mast...
4,Imperial College London,Business Intelligence,Imperial College London Business Intelligence ...
5,Imperial College London,Applied Data Science,Imperial College London Applied Data Science m...
6,Imperial College London,Statistics and Data Science,Imperial College London Statistics and Data Sc...
7,Imperial College London,Analytics and Data Science,Imperial College London Analytics and Data Sci...
8,University of Oxford,Business Analytics,University of Oxford Business Analytics master's
9,University of Oxford,Data Science,University of Oxford Data Science master's

In [4]:
print("Number of universities:", len(df))
print("Number of search terms:", len(SEARCH_TERMS))
print("Number of search tasks:", len(search_df))

Number of universities: 61
Number of search terms: 8
Number of search tasks: 488

In [5]:
from urllib.parse import quote_plus

search_df["search_url"] = search_df["query"].apply(
    lambda x: "https://www.google.com/search?q=" + quote_plus(x)
)

search_df[["university", "search_term", "search_url"]].head(10)

,university,search_term,search_url
0,Imperial College London,Business Analytics,https://www.google.com/search?q=Imperial+Colle...
1,Imperial College London,Data Science,https://www.google.com/search?q=Imperial+Colle...
2,Imperial College London,Data Analytics,https://www.google.com/search?q=Imperial+Colle...
3,Imperial College London,Applied Analytics,https://www.google.com/search?q=Imperial+Colle...
4,Imperial College London,Business Intelligence,https://www.google.com/search?q=Imperial+Colle...
5,Imperial College London,Applied Data Science,https://www.google.com/search?q=Imperial+Colle...
6,Imperial College London,Statistics and Data Science,https://www.google.com/search?q=Imperial+Colle...
7,Imperial College London,Analytics and Data Science,https://www.google.com/search?q=Imperial+Colle...
8,University of Oxford,Business Analytics,https://www.google.com/search?q=University+of+...
9,University of Oxford,Data Science,https://www.google.com/search?q=University+of+...

In [6]:
search_tasks = []

for university in df["University"]:
    for term in SEARCH_TERMS:
        query = f'"{university}" "{term}" MSc OR Master'

        search_tasks.append({
            "university": university,
            "search_term": term,
            "query": query
        })

search_df = pd.DataFrame(search_tasks)

search_df["search_url"] = search_df["query"].apply(
    lambda x: "https://www.google.com/search?q=" + quote_plus(x)
)

search_df.head(10)

,university,search_term,query,search_url
0,Imperial College London,Business Analytics,"""Imperial College London"" ""Business Analytics""...",https://www.google.com/search?q=%22Imperial+Co...
1,Imperial College London,Data Science,"""Imperial College London"" ""Data Science"" MSc O...",https://www.google.com/search?q=%22Imperial+Co...
2,Imperial College London,Data Analytics,"""Imperial College London"" ""Data Analytics"" MSc...",https://www.google.com/search?q=%22Imperial+Co...
3,Imperial College London,Applied Analytics,"""Imperial College London"" ""Applied Analytics"" ...",https://www.google.com/search?q=%22Imperial+Co...
4,Imperial College London,Business Intelligence,"""Imperial College London"" ""Business Intelligen...",https://www.google.com/search?q=%22Imperial+Co...
5,Imperial College London,Applied Data Science,"""Imperial College London"" ""Applied Data Scienc...",https://www.google.com/search?q=%22Imperial+Co...
6,Imperial College London,Statistics and Data Science,"""Imperial College London"" ""Statistics and Data...",https://www.google.com/search?q=%22Imperial+Co...
7,Imperial College London,Analytics and Data Science,"""Imperial College London"" ""Analytics and Data ...",https://www.google.com/search?q=%22Imperial+Co...
8,University of Oxford,Business Analytics,"""University of Oxford"" ""Business Analytics"" MS...",https://www.google.com/search?q=%22University+...
9,University of Oxford,Data Science,"""University of Oxford"" ""Data Science"" MSc OR M...",https://www.google.com/search?q=%22University+...

In [7]:
imperial_search = search_df[
    search_df["university"] == "Imperial College London"
]

imperial_search[["search_term", "query", "search_url"]]

,search_term,query,search_url
0,Business Analytics,"""Imperial College London"" ""Business Analytics""...",https://www.google.com/search?q=%22Imperial+Co...
1,Data Science,"""Imperial College London"" ""Data Science"" MSc O...",https://www.google.com/search?q=%22Imperial+Co...
2,Data Analytics,"""Imperial College London"" ""Data Analytics"" MSc...",https://www.google.com/search?q=%22Imperial+Co...
3,Applied Analytics,"""Imperial College London"" ""Applied Analytics"" ...",https://www.google.com/search?q=%22Imperial+Co...
4,Business Intelligence,"""Imperial College London"" ""Business Intelligen...",https://www.google.com/search?q=%22Imperial+Co...
5,Applied Data Science,"""Imperial College London"" ""Applied Data Scienc...",https://www.google.com/search?q=%22Imperial+Co...
6,Statistics and Data Science,"""Imperial College London"" ""Statistics and Data...",https://www.google.com/search?q=%22Imperial+Co...
7,Analytics and Data Science,"""Imperial College London"" ""Analytics and Data ...",https://www.google.com/search?q=%22Imperial+Co...

In [8]:
%pip install -q ddgs

Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~upyterlab (D:\Lib\site-packages)
WARNING: Ignoring invalid distribution ~upyterlab (D:\Lib\site-packages)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
from ddgs import DDGS

query = '"Imperial College London" "Business Analytics" MSc'

results = list(
    DDGS().text(
        query,
        max_results=5
    )
)

results

[{'title': 'MSc Business Analytics & AI - Imperial College London',
  'href': 'https://www.imperial.ac.uk/business-school/masters/business-analytics/',
  'body': "Harness the power of big data by studying the Master's in Business Analytics & AI at Imperial Business School in London. Apply now."},
 {'title': 'Business Analytics and AI MSc | Study | Imperial College London',
  'href': 'https://www.imperial.ac.uk/study/courses/postgraduate-taught/business-analytics/',
  'body': 'Learn how to apply the latest academic thinking and analytical and computing tools to help make business decisions. MSc Business Analytics and AI equips you to make data-driven and evidence-based decisions and drive transformation within businesses.'},
 {'title': 'Business Analytics & AI - Imperial College London | Prospects ...',
  'href': 'https://www.prospects.ac.uk/universities/imperial-college-london-3838/imperial-business-school-3839/courses/business-analytics-112280',
  'body': 'Our MSc in Business Analytics & AI will equip you with the computational and technical skills you need to succeed in an increasingly data-driven world.'},
 {'title': 'Business Analytics | Imperial College London | UCAS',
  'href': 'https://www.ucas.com/explore/courses/950f2a6e-e3ad-4363-be6a-98640bc764d9/business-analytics?studyYear=2026',
  'body': 'Drive business transformation through data-driven decision-making. With the emergence of new technologies such as AI and machine learning, the ability to analyse and interpret complex data sets is crucial for future business leaders.'},
 {'title': 'MSc Business Analytics & AI Postgraduate Programme By ...',
  'href': 'https://www.topuniversities.com/universities/imperial-college-london/imperial-business-school/postgrad/msc-business-analytics-ai',
  'body': 'Jan 7, 2026 · Imperial College London is consistently ranked in the top 10 universities globally, recognised as a world leader in the study and analysis of data. Prepare for your future driving business transformation through data. MSc Business Analytics equips you to make data-driven and evidence-based decisions and drive...'}]

In [10]:
from ddgs import DDGS
import pandas as pd
import time

def search_programmes(university, search_term, max_results=5):
    query = f'"{university}" "{search_term}" MSc OR Master'
    
    try:
        results = list(
            DDGS().text(
                query,
                max_results=max_results
            )
        )
        
        rows = []
        
        for result in results:
            rows.append({
                "university": university,
                "search_term": search_term,
                "title": result.get("title"),
                "url": result.get("href"),
                "snippet": result.get("body")
            })
        
        return rows
    
    except Exception as e:
        print(f"Error: {university} | {search_term} | {e}")
        return []

In [11]:
test = search_programmes(
    "Imperial College London",
    "Business Analytics"
)

test_df = pd.DataFrame(test)

test_df

,university,search_term,title,url,snippet
0,Imperial College London,Business Analytics,MSc Business Analytics & AI - Business School,https://www.imperial.ac.uk/business-school/mas...,Harness the power of big data by studying the ...
1,Imperial College London,Business Analytics,"Imperial MSBA | Class Profile, Fees, Career & ...",https://www.mim-essay.com/imperial-msba,"April 18, 2026 - The Imperial MSc Business Ana..."
2,Imperial College London,Business Analytics,How is the MSc in Business Analytics program a...,https://www.quora.com/How-is-the-MSc-in-Busine...,Answer (1 of 2): I am currently one of the 57 ...
3,Imperial College London,Business Analytics,Business Analytics and AI MSc | Study | Imperi...,https://www.imperial.ac.uk/study/courses/postg...,Apply nowRequest a brochureSign up to our news...
4,Imperial College London,Business Analytics,"MSc programmes, London UK - Business School",https://www.imperial.ac.uk/business-school/mas...,MSc Business Analytics & AI prepares graduates...

In [12]:
imperial_results = []

for term in SEARCH_TERMS:
    
    print("Searching:", term)
    
    result = search_programmes(
        "Imperial College London",
        term
    )
    
    imperial_results.extend(result)
    
    time.sleep(1)

imperial_df = pd.DataFrame(imperial_results)

imperial_df

Searching: Business Analytics
Searching: Data Science
Searching: Data Analytics
Searching: Applied Analytics
Searching: Business Intelligence
Searching: Applied Data Science
Searching: Statistics and Data Science
Searching: Analytics and Data Science

,university,search_term,title,url,snippet
0,Imperial College London,Business Analytics,MSc Business Analytics & AI - Imperial College...,https://www.imperial.ac.uk/business-school/mas...,Harness the power of big data by studying the ...
1,Imperial College London,Business Analytics,Business Analytics and AI MSc | Study | Imperi...,https://www.imperial.ac.uk/study/courses/postg...,MSc Business Analytics and AI equips you to ma...
2,Imperial College London,Business Analytics,QS Business Master's Rankings 2027: Business A...,https://www.topmba.com/business-masters-rankin...,"Sep 16, 2026 · Explore the world's top busines..."
3,Imperial College London,Business Analytics,MSc Business Analytics & AI admissions - Busin...,https://www.imperial.ac.uk/business-school/mas...,Find out how to apply for MSc Business Analyti...
4,Imperial College London,Business Analytics,"MSc programmes, London UK - Business School",https://www.imperial.ac.uk/business-school/mas...,Transform your career with a Master's from Imp...
5,Imperial College London,Data Science,Data science | Study | Imperial College London,https://www.imperial.ac.uk/study/subjects/data...,Our courses cover a wide range of data science...
6,Imperial College London,Data Science,MSc Statistics (Data Science) 12 months Postgr...,https://www.topuniversities.com/universities/i...,Home Universities Imperial College London MSc ...
7,Imperial College London,Data Science,Machine Learning and Data Science (Online) MSc...,https://www.imperial.ac.uk/study/pg/mathematic...,"February 13, 2020 - Accelerate your career in ..."
8,Imperial College London,Data Science,Statistics (Data Science and Machine Learning)...,https://www.imperial.ac.uk/study/courses/postg...,Become fluent in the most common data science ...
9,Imperial College London,Data Science,MSc Machine Learning and Data Science (Online)...,https://www.imperial.ac.uk/natural-sciences/de...,Accelerate your career in engineering or data ...
10,Imperial College London,Data Analytics,MSc Business Analytics & AI - Business School,https://www.imperial.ac.uk/business-school/pro...,Harness the power of big data by studying the ...
11,Imperial College London,Data Analytics,Machine Learning and Data Science (Online) MSc...,https://www.imperial.ac.uk/study/courses/postg...,"Accelerate your career in industry ... course,..."
12,Imperial College London,Data Analytics,Data science | Study | Imperial College London,https://www.imperial.ac.uk/study/subjects/data...,Focus your study of computing on artificial in...
13,Imperial College London,Data Analytics,Business Analytics and AI MSc | Study | Imperi...,https://www.imperial.ac.uk/study/pg/business-s...,Real-world data sets and cutting edge tools an...
14,Imperial College London,Data Analytics,MSc in Health Data Analytics and Machine Learn...,https://yocket.com/universities/imperial-colle...,MSc in Health Data Analytics and Machine Learn...
15,Imperial College London,Applied Analytics,MSc Business Analytics & AI - Business School,https://www.imperial.ac.uk/business-school/mas...,Discover our admissions process for the MSc Bu...
16,Imperial College London,Applied Analytics,Business Analytics and AI MSc | Study | Imperi...,https://www.imperial.ac.uk/study/pg/business-s...,GMAT is not required for MSc Business Analytic...
17,Imperial College London,Applied Analytics,MSc Business Analytics & AI admissions - Busin...,https://www.imperial.ac.uk/business-school/mas...,"We take a holistic approach to admissions, con..."
18,Imperial College London,Applied Analytics,Business Analytics and AI M.Sc. at Imperial | ...,https://www.mastersportal.com/studies/65254/bu...,With the emergence of technologies ... Analyti...
19,Imperial College London,Applied Analytics,"MSc programmes, London UK - Business School",https://www.imperial.ac.uk/business-school/mas...,Our Masters programmes in London will equip yo...
20,Imperial College London,Business Intelligence,Business Analytics and AI MSc | Study | Imperi...,https://www.imperial.ac.uk/study/courses/postg...,"There is a careful balance of teaching, hands-..."
21,Imperial College London,Business Intelligence,MSc Business Analytics & AI - Business School,https://www.imperial.ac.uk/business-school/mas...,Harness the power of big data by studying the ...
22,Imperial College London,Business Intelligence,Business Analytics and AI M.Sc. at Imperial | ...,https://www.mastersportal.com/studies/65254/bu...,With the emergence of technologies ... Analyti...
23,Imperial College London,Business Intelligence,"All about this master, MSc Business Analytics ...",https://www.best-masters.com/ranking-master-bu...,"All about this master, MSc Business Analytics ..."
24,Imperial College London,Business Intelligence,M.Sc. in Business Analytics from Imperial Coll...,https://collegedunia.com/uk/university/835-imp...,"June 18, 2026 - Imperial College London's MSc ..."
25,Imperial College London,Applied Data Science,Statistics (Data Science and Machine Learning)...,https://www.imperial.ac.uk/study/courses/postg...,Develop your appreciation of data science tech...
26,Imperial College London,Applied Data Science,Data science | Study | Imperial College London,https://www.imperial.ac.uk/study/subjects/data...,2027 · Undergraduate · BSc Compare · A first-o...
27,Imperial College London,Applied Data Science,Machine Learning and Data Science (Online) MSc...,https://www.imperial.ac.uk/study/courses/postg...,Applications are now closed for 2026 entry.Req...
28,Imperial College London,Applied Data Science,MSc Statistics (Data Science) 12 months Postgr...,https://www.topuniversities.com/universities/i...,"You may wish to consider our General stream, o..."
29,Imperial College London,Applied Data Science,Environmental Data Science and Machine Learnin...,https://www.imperial.ac.uk/study/courses/postg...,Applications open on Wednesday 30 September 20...
30,Imperial College London,Statistics and Data Science,Statistics (Data Science and Machine Learning)...,https://www.imperial.ac.uk/study/courses/postg...,Become fluent in the most common data science ...
31,Imperial College London,Statistics and Data Science,MSc Statistics (Data Science and Machine Learn...,https://www.thecompleteuniversityguide.co.uk/c...,MSc - Master of Science · Imperial College Lon...
32,Imperial College London,Statistics and Data Science,MSc Statistics (Data Science) 12 months Postgr...,https://www.topuniversities.com/universities/i...,Home Universities Imperial College London MSc ...
33,Imperial College London,Statistics and Data Science,M.Sc. in Statistics - Data Science from Imperi...,https://collegedunia.com/uk/university/835-imp...,"May 1, 2020 - Imperial College London MSc Stat..."
34,Imperial College London,Statistics and Data Science,MSc Statistics (Data Science and Machine Learn...,https://www.postgraduatesearch.com/courses/sea...,... Build familiarity with a wide ... settings...
35,Imperial College London,Analytics and Data Science,Data science | Study | Imperial College London,https://www.imperial.ac.uk/study/subjects/data...,Focus your study of computing on artificial in...
36,Imperial College London,Analytics and Data Science,MSc Business Analytics & AI - Business School,https://www.imperial.ac.uk/business-school/mas...,Harness the power of big data by studying the ...
37,Imperial College London,Analytics and Data Science,Machine Learning and Data Science (Online) MSc...,https://www.imperial.ac.uk/study/courses/postg...,"Accelerate your career in industry ... course,..."
38,Imperial College London,Analytics and Data Science,MSc Health Data Analytics and Machine Learning...,https://unischolars.com/universities/uk/imperi...,MSc in Health Data Analytics and Machine Learn...
39,Imperial College London,Analytics and Data Science,Statistics (Data Science and Machine Learning)...,https://www.imperial.ac.uk/study/courses/postg...,Find out more about how to apply for a Master'...

In [13]:
imperial_official = imperial_df[
    imperial_df["url"]
    .fillna("")
    .str.contains("imperial.ac.uk", case=False)
].copy()

imperial_official[
    ["search_term", "title", "url"]
]

,search_term,title,url
0,Business Analytics,MSc Business Analytics & AI - Imperial College...,https://www.imperial.ac.uk/business-school/mas...
1,Business Analytics,Business Analytics and AI MSc | Study | Imperi...,https://www.imperial.ac.uk/study/courses/postg...
3,Business Analytics,MSc Business Analytics & AI admissions - Busin...,https://www.imperial.ac.uk/business-school/mas...
4,Business Analytics,"MSc programmes, London UK - Business School",https://www.imperial.ac.uk/business-school/mas...
5,Data Science,Data science | Study | Imperial College London,https://www.imperial.ac.uk/study/subjects/data...
7,Data Science,Machine Learning and Data Science (Online) MSc...,https://www.imperial.ac.uk/study/pg/mathematic...
8,Data Science,Statistics (Data Science and Machine Learning)...,https://www.imperial.ac.uk/study/courses/postg...
9,Data Science,MSc Machine Learning and Data Science (Online)...,https://www.imperial.ac.uk/natural-sciences/de...
10,Data Analytics,MSc Business Analytics & AI - Business School,https://www.imperial.ac.uk/business-school/pro...
11,Data Analytics,Machine Learning and Data Science (Online) MSc...,https://www.imperial.ac.uk/study/courses/postg...
12,Data Analytics,Data science | Study | Imperial College London,https://www.imperial.ac.uk/study/subjects/data...
13,Data Analytics,Business Analytics and AI MSc | Study | Imperi...,https://www.imperial.ac.uk/study/pg/business-s...
15,Applied Analytics,MSc Business Analytics & AI - Business School,https://www.imperial.ac.uk/business-school/mas...
16,Applied Analytics,Business Analytics and AI MSc | Study | Imperi...,https://www.imperial.ac.uk/study/pg/business-s...
17,Applied Analytics,MSc Business Analytics & AI admissions - Busin...,https://www.imperial.ac.uk/business-school/mas...
19,Applied Analytics,"MSc programmes, London UK - Business School",https://www.imperial.ac.uk/business-school/mas...
20,Business Intelligence,Business Analytics and AI MSc | Study | Imperi...,https://www.imperial.ac.uk/study/courses/postg...
21,Business Intelligence,MSc Business Analytics & AI - Business School,https://www.imperial.ac.uk/business-school/mas...
25,Applied Data Science,Statistics (Data Science and Machine Learning)...,https://www.imperial.ac.uk/study/courses/postg...
26,Applied Data Science,Data science | Study | Imperial College London,https://www.imperial.ac.uk/study/subjects/data...
27,Applied Data Science,Machine Learning and Data Science (Online) MSc...,https://www.imperial.ac.uk/study/courses/postg...
29,Applied Data Science,Environmental Data Science and Machine Learnin...,https://www.imperial.ac.uk/study/courses/postg...
30,Statistics and Data Science,Statistics (Data Science and Machine Learning)...,https://www.imperial.ac.uk/study/courses/postg...
35,Analytics and Data Science,Data science | Study | Imperial College London,https://www.imperial.ac.uk/study/subjects/data...
36,Analytics and Data Science,MSc Business Analytics & AI - Business School,https://www.imperial.ac.uk/business-school/mas...
37,Analytics and Data Science,Machine Learning and Data Science (Online) MSc...,https://www.imperial.ac.uk/study/courses/postg...
39,Analytics and Data Science,Statistics (Data Science and Machine Learning)...,https://www.imperial.ac.uk/study/courses/postg...

In [14]:
imperial_unique = (
    imperial_official
    .drop_duplicates(subset=["url"])
    .copy()
)

print("Before deduplication:", len(imperial_official))
print("After deduplication:", len(imperial_unique))

imperial_unique[
    ["search_term", "title", "url"]
]

Before deduplication: 27
After deduplication: 12

,search_term,title,url
0,Business Analytics,MSc Business Analytics & AI - Imperial College...,https://www.imperial.ac.uk/business-school/mas...
1,Business Analytics,Business Analytics and AI MSc | Study | Imperi...,https://www.imperial.ac.uk/study/courses/postg...
3,Business Analytics,MSc Business Analytics & AI admissions - Busin...,https://www.imperial.ac.uk/business-school/mas...
4,Business Analytics,"MSc programmes, London UK - Business School",https://www.imperial.ac.uk/business-school/mas...
5,Data Science,Data science | Study | Imperial College London,https://www.imperial.ac.uk/study/subjects/data...
7,Data Science,Machine Learning and Data Science (Online) MSc...,https://www.imperial.ac.uk/study/pg/mathematic...
8,Data Science,Statistics (Data Science and Machine Learning)...,https://www.imperial.ac.uk/study/courses/postg...
9,Data Science,MSc Machine Learning and Data Science (Online)...,https://www.imperial.ac.uk/natural-sciences/de...
10,Data Analytics,MSc Business Analytics & AI - Business School,https://www.imperial.ac.uk/business-school/pro...
11,Data Analytics,Machine Learning and Data Science (Online) MSc...,https://www.imperial.ac.uk/study/courses/postg...
13,Data Analytics,Business Analytics and AI MSc | Study | Imperi...,https://www.imperial.ac.uk/study/pg/business-s...
29,Applied Data Science,Environmental Data Science and Machine Learnin...,https://www.imperial.ac.uk/study/courses/postg...

In [15]:
MASTER_KEYWORDS = [
    "msc",
    "master",
    "masters",
    "postgraduate"
]

PROGRAMME_KEYWORDS = [
    "business analytics",
    "data science",
    "data analytics",
    "applied analytics",
    "business intelligence",
    "applied data science",
    "statistics and data science",
    "analytics and data science"
]

def looks_like_programme(title):
    title = str(title).lower()
    
    has_master = any(
        word in title
        for word in MASTER_KEYWORDS
    )
    
    has_programme = any(
        word in title
        for word in PROGRAMME_KEYWORDS
    )
    
    return has_master and has_programme

In [16]:
imperial_unique["programme_candidate"] = (
    imperial_unique["title"]
    .apply(looks_like_programme)
)

imperial_candidates = imperial_unique[
    imperial_unique["programme_candidate"]
].copy()

imperial_candidates[
    ["search_term", "title", "url"]
]

,search_term,title,url
0,Business Analytics,MSc Business Analytics & AI - Imperial College...,https://www.imperial.ac.uk/business-school/mas...
1,Business Analytics,Business Analytics and AI MSc | Study | Imperi...,https://www.imperial.ac.uk/study/courses/postg...
3,Business Analytics,MSc Business Analytics & AI admissions - Busin...,https://www.imperial.ac.uk/business-school/mas...
7,Data Science,Machine Learning and Data Science (Online) MSc...,https://www.imperial.ac.uk/study/pg/mathematic...
8,Data Science,Statistics (Data Science and Machine Learning)...,https://www.imperial.ac.uk/study/courses/postg...
9,Data Science,MSc Machine Learning and Data Science (Online)...,https://www.imperial.ac.uk/natural-sciences/de...
10,Data Analytics,MSc Business Analytics & AI - Business School,https://www.imperial.ac.uk/business-school/pro...
11,Data Analytics,Machine Learning and Data Science (Online) MSc...,https://www.imperial.ac.uk/study/courses/postg...
13,Data Analytics,Business Analytics and AI MSc | Study | Imperi...,https://www.imperial.ac.uk/study/pg/business-s...
29,Applied Data Science,Environmental Data Science and Machine Learnin...,https://www.imperial.ac.uk/study/courses/postg...

In [17]:
imperial_candidates["manual_review"] = "Pending"
imperial_candidates["eligible"] = ""
imperial_candidates["review_notes"] = ""

imperial_candidates[
    [
        "search_term",
        "title",
        "url",
        "manual_review",
        "eligible",
        "review_notes"
    ]
]

,search_term,title,url,manual_review,eligible,review_notes
0,Business Analytics,MSc Business Analytics & AI - Imperial College...,https://www.imperial.ac.uk/business-school/mas...,Pending,,
1,Business Analytics,Business Analytics and AI MSc | Study | Imperi...,https://www.imperial.ac.uk/study/courses/postg...,Pending,,
3,Business Analytics,MSc Business Analytics & AI admissions - Busin...,https://www.imperial.ac.uk/business-school/mas...,Pending,,
7,Data Science,Machine Learning and Data Science (Online) MSc...,https://www.imperial.ac.uk/study/pg/mathematic...,Pending,,
8,Data Science,Statistics (Data Science and Machine Learning)...,https://www.imperial.ac.uk/study/courses/postg...,Pending,,
9,Data Science,MSc Machine Learning and Data Science (Online)...,https://www.imperial.ac.uk/natural-sciences/de...,Pending,,
10,Data Analytics,MSc Business Analytics & AI - Business School,https://www.imperial.ac.uk/business-school/pro...,Pending,,
11,Data Analytics,Machine Learning and Data Science (Online) MSc...,https://www.imperial.ac.uk/study/courses/postg...,Pending,,
13,Data Analytics,Business Analytics and AI MSc | Study | Imperi...,https://www.imperial.ac.uk/study/pg/business-s...,Pending,,
29,Applied Data Science,Environmental Data Science and Machine Learnin...,https://www.imperial.ac.uk/study/courses/postg...,Pending,,

In [22]:
from urllib.parse import urlparse
from ddgs import DDGS

EXCLUDED_DOMAINS = [
    "wikipedia.org",
    "topuniversities.com",
    "linkedin.com",
    "facebook.com",
    "instagram.com",
    "youtube.com",
    "timeshighereducation.com",
    "usnews.com",
    "mastersportal.com",
    "findamasters.com",
    "prospects.ac.uk",
    "ucas.com"
]

def find_official_domain(university):
    
    query = f'"{university}" official website'
    
    try:
        results = list(
            DDGS().text(
                query,
                max_results=10
            )
        )
        
        for result in results:
            
            url = result.get("href", "")
            
            if not url:
                continue
            
            domain = urlparse(url).netloc.lower()
            domain = domain.replace("www.", "")
            
            # Skip known third-party websites
            if any(
                excluded in domain
                for excluded in EXCLUDED_DOMAINS
            ):
                continue
            
            return domain
        
        return None
    
    except Exception as e:
        print(f"Error: {university} | {e}")
        return None

In [23]:
find_official_domain("Imperial College London")

'imperial.ac.uk'

In [24]:
find_official_domain("University of Oxford")

'ox.ac.uk'

In [25]:
find_official_domain("University of Cambridge")

'cam.ac.uk'

In [26]:
import time

domains = []

for i, university in enumerate(df["University"], start=1):
    
    print(f"[{i}/{len(df)}] Finding domain: {university}")
    
    domain = find_official_domain(university)
    domains.append(domain)
    
    print("   →", domain)
    
    time.sleep(1)

df["official_domain_candidate"] = domains

[1/61] Finding domain: Imperial College London
   → imperial.ac.uk
[2/61] Finding domain: University of Oxford
   → ox.ac.uk
[3/61] Finding domain: University of Cambridge
   → cam.ac.uk
[4/61] Finding domain: ETH Zurich
   → ethz.ch
[5/61] Finding domain: UCL
   → london.ac.uk
[6/61] Finding domain: EPFL – École polytechnique fédérale de Lausanne
   → social.epfl.ch
[7/61] Finding domain: Technical University of Munich
   → tum.de
[8/61] Finding domain: PSL University
   → psl.eu
[9/61] Finding domain: King's College London
   → kcl.ac.uk
[10/61] Finding domain: University of Edinburgh
Error: University of Edinburgh | No results found.
   → None
[11/61] Finding domain: The University of Manchester
   → manchester.ac.uk
[12/61] Finding domain: Institut Polytechnique de Paris
   → ip-paris.fr
[13/61] Finding domain: Delft University of Technology
   → tudelft.nl
[14/61] Finding domain: University of Bristol
Error: University of Bristol | No results found.
   → None
[15/61] Finding domain: University of Amsterdam
   → uva.nl
[16/61] Finding domain: London School of Economics and Political Science (LSE)
Error: London School of Economics and Political Science (LSE) | No results found.
   → None
[17/61] Finding domain: Ludwig-Maximilians-Universität München
   → lmu.de
[18/61] Finding domain: KU Leuven
Error: KU Leuven | No results found.
   → None
[19/61] Finding domain: Université Paris-Saclay
Error: Université Paris-Saclay | No results found.
   → None
[20/61] Finding domain: Lund University
Error: Lund University | No results found.
   → None
[21/61] Finding domain: Sorbonne University
   → sorbonne-universite.fr
[22/61] Finding domain: The University of Warwick
   → warwick.ac.uk
[23/61] Finding domain: Trinity College Dublin, The University of Dublin
   → trinity-college-dublin.ie
[24/61] Finding domain: University of Birmingham
Error: University of Birmingham | No results found.
   → None
[25/61] Finding domain: KTH Royal Institute of Technology
   → kth.se
[26/61] Finding domain: University of Glasgow
   → gla.ac.uk
[27/61] Finding domain: Heidelberg University
Error: Heidelberg University | No results found.
   → None
[28/61] Finding domain: University of Leeds
   → courses.leeds.ac.uk
[29/61] Finding domain: University of Southampton
   → southampton.ac.uk
[30/61] Finding domain: Freie Universität Berlin
   → fu-berlin.de
[31/61] Finding domain: The University of Sheffield
   → sheffield.ac.uk
[32/61] Finding domain: Uppsala University
Error: Uppsala University | No results found.
   → None
[33/61] Finding domain: Durham University
Error: Durham University | No results found.
   → None
[34/61] Finding domain: The University of Nottingham
   → nottingham.ac.uk
[35/61] Finding domain: KIT, Karlsruhe Institute of Technology
   → None
[36/61] Finding domain: Politecnico di Milano
   → polimi.it
[37/61] Finding domain: University of Zurich
   → uzh.ch
[38/61] Finding domain: University of Copenhagen
   → about.ku.dk
[39/61] Finding domain: Utrecht University
   → uu.nl
[40/61] Finding domain: Lomonosov Moscow State University
   → archive.government.ru
[41/61] Finding domain: RWTH Aachen University
Error: RWTH Aachen University | No results found.
   → None
[42/61] Finding domain: Technical University of Denmark
   → dtu.dk
[43/61] Finding domain: Queen Mary University of London (QMUL)
   → uni-uk.com
[44/61] Finding domain: University of St Andrews
   → st-andrews.ac.uk
[45/61] Finding domain: Aalto University
   → aalto.fi
[46/61] Finding domain: University of Helsinki
   → helsinki.fi
[47/61] Finding domain: University College Dublin
   → ucd.ie
[48/61] Finding domain: Leiden University
   → universiteitleiden.nl
[49/61] Finding domain: University of Oslo
   → uio.no
[50/61] Finding domain: Sapienza University of Rome
Error: Sapienza University of Rome | No results found.
   → None
[51/61] Finding domain: Humboldt-Universität zu Berlin
   → hu-berlin.de
[52/61] Finding domain: Aarhus University
   → international.au.dk
[53/61] Finding domain: University of Bath
   → bathuniversity.com
[54/61] Finding domain: Newcastle University
   → ncl.ac.uk
[55/61] Finding domain: Alma Mater Studiorum - University of Bologna
   → unibo.it
[56/61] Finding domain: Eindhoven University of Technology
   → unilion.eu
[57/61] Finding domain: Erasmus University Rotterdam
   → eur.nl
[58/61] Finding domain: Technische Universität Berlin (TU Berlin)
   → tu.berlin
[59/61] Finding domain: Stockholm University
   → su.se
[60/61] Finding domain: University of Groningen
   → rug.nl
[61/61] Finding domain: University of Liverpool
   → liverpool.ac.uk

In [27]:
# Check universities where no domain was found

missing_domains = df[
    df["official_domain_candidate"].isna()
][
    ["QS 2026 Rank", "University", "Country"]
]

print("Number of missing domains:", len(missing_domains))

missing_domains

Number of missing domains: 13

,QS 2026 Rank,University,Country
9,34,University of Edinburgh,United Kingdom
13,51,University of Bristol,United Kingdom
15,56,London School of Economics and Political Scien...,United Kingdom
17,60,KU Leuven,Belgium
18,70,Université Paris-Saclay,France
19,72,Lund University,Sweden
23,76,University of Birmingham,United Kingdom
26,80,Heidelberg University,Germany
31,93,Uppsala University,Sweden
32,94,Durham University,United Kingdom
34,98,"KIT, Karlsruhe Institute of Technology",Germany
40,105,RWTH Aachen University,Germany
49,128,Sapienza University of Rome,Italy

In [28]:
# Summary

print("Total universities:", len(df))
print(
    "Domains found:",
    df["official_domain_candidate"].notna().sum()
)
print(
    "Domains missing:",
    df["official_domain_candidate"].isna().sum()
)

Total universities: 61
Domains found: 48
Domains missing: 13

In [30]:
missing_domains = df[
    df["official_domain_candidate"].isna()
][
    ["QS 2026 Rank", "University", "Country"]
]

missing_domains

,QS 2026 Rank,University,Country
9,34,University of Edinburgh,United Kingdom
13,51,University of Bristol,United Kingdom
15,56,London School of Economics and Political Scien...,United Kingdom
17,60,KU Leuven,Belgium
18,70,Université Paris-Saclay,France
19,72,Lund University,Sweden
23,76,University of Birmingham,United Kingdom
26,80,Heidelberg University,Germany
31,93,Uppsala University,Sweden
32,94,Durham University,United Kingdom
34,98,"KIT, Karlsruhe Institute of Technology",Germany
40,105,RWTH Aachen University,Germany
49,128,Sapienza University of Rome,Italy

In [31]:
print(missing_domains["University"].tolist())

['University of Edinburgh', 'University of Bristol', 'London School of Economics and Political Science (LSE)', 'KU Leuven', 'Université Paris-Saclay', 'Lund University', 'University of Birmingham', 'Heidelberg University', 'Uppsala University', 'Durham University', 'KIT, Karlsruhe Institute of Technology', 'RWTH Aachen University', 'Sapienza University of Rome']

In [32]:
manual_domains = {
    "University of Edinburgh": "ed.ac.uk",
    "University of Bristol": "bristol.ac.uk",
    "London School of Economics and Political Science (LSE)": "lse.ac.uk",
    "KU Leuven": "kuleuven.be",
    "Université Paris-Saclay": "universite-paris-saclay.fr",
    "Lund University": "lu.se",
    "University of Birmingham": "birmingham.ac.uk",
    "Heidelberg University": "uni-heidelberg.de",
    "Uppsala University": "uu.se",
    "Durham University": "durham.ac.uk",
    "KIT, Karlsruhe Institute of Technology": "kit.edu",
    "RWTH Aachen University": "rwth-aachen.de",
    "Sapienza University of Rome": "uniroma1.it"
}

for university, domain in manual_domains.items():
    df.loc[
        df["University"] == university,
        "official_domain_candidate"
    ] = domain

In [33]:
print("Total universities:", len(df))
print(
    "Domains found:",
    df["official_domain_candidate"].notna().sum()
)
print(
    "Domains missing:",
    df["official_domain_candidate"].isna().sum()
)

Total universities: 61
Domains found: 61
Domains missing: 0

In [34]:
df["domain_source"] = "Automated search"

df.loc[
    df["University"].isin(manual_domains.keys()),
    "domain_source"
] = "Manual fallback"

In [35]:
df[
    [
        "University",
        "official_domain_candidate",
        "domain_source"
    ]
].head(20)

,University,official_domain_candidate,domain_source
0,Imperial College London,imperial.ac.uk,Automated search
1,University of Oxford,ox.ac.uk,Automated search
2,University of Cambridge,cam.ac.uk,Automated search
3,ETH Zurich,ethz.ch,Automated search
4,UCL,london.ac.uk,Automated search
5,EPFL – École polytechnique fédérale de Lausanne,social.epfl.ch,Automated search
6,Technical University of Munich,tum.de,Automated search
7,PSL University,psl.eu,Automated search
8,King's College London,kcl.ac.uk,Automated search
9,University of Edinburgh,ed.ac.uk,Manual fallback
10,The University of Manchester,manchester.ac.uk,Automated search
11,Institut Polytechnique de Paris,ip-paris.fr,Automated search
12,Delft University of Technology,tudelft.nl,Automated search
13,University of Bristol,bristol.ac.uk,Manual fallback
14,University of Amsterdam,uva.nl,Automated search
15,London School of Economics and Political Scien...,lse.ac.uk,Manual fallback
16,Ludwig-Maximilians-Universität München,lmu.de,Automated search
17,KU Leuven,kuleuven.be,Manual fallback
18,Université Paris-Saclay,universite-paris-saclay.fr,Manual fallback
19,Lund University,lu.se,Manual fallback

In [36]:
domain_corrections = {
    "UCL": "ucl.ac.uk",
    "EPFL – École polytechnique fédérale": "epfl.ch"
}

for university, domain in domain_corrections.items():
    df.loc[
        df["University"] == university,
        "official_domain_candidate"
    ] = domain

    df.loc[
        df["University"] == university,
        "domain_source"
    ] = "Manual correction"

In [37]:
df[
    df["University"].isin(
        ["UCL", "EPFL – École polytechnique fédérale"]
    )
][
    ["University", "official_domain_candidate", "domain_source"]
]

  University official_domain_candidate      domain_source
4        UCL                 ucl.ac.uk  Manual correction

In [38]:
df[
    df["University"]
    .str.contains("EPFL", case=False, na=False)
][
    ["University", "official_domain_candidate", "domain_source"]
]

,University,official_domain_candidate,domain_source
5,EPFL – École polytechnique fédérale de Lausanne,social.epfl.ch,Automated search

In [39]:
epfl_mask = df["University"].str.contains(
    "EPFL",
    case=False,
    na=False
)

df.loc[
    epfl_mask,
    "official_domain_candidate"
] = "epfl.ch"

df.loc[
    epfl_mask,
    "domain_source"
] = "Manual correction"

In [40]:
df[
    df["University"]
    .str.contains("EPFL|UCL", case=False, na=False)
][
    ["University", "official_domain_candidate", "domain_source"]
]

,University,official_domain_candidate,domain_source
4,UCL,ucl.ac.uk,Manual correction
5,EPFL – École polytechnique fédérale de Lausanne,epfl.ch,Manual correction

In [41]:
PILOT_UNIVERSITIES = [
    "Imperial College London",
    "University of Oxford",
    "ETH Zurich",
    "UCL",
    "KU Leuven"
]

pilot_df = df[
    df["University"].isin(PILOT_UNIVERSITIES)
][
    ["University", "official_domain_candidate"]
].copy()

pilot_df

                 University official_domain_candidate
0   Imperial College London            imperial.ac.uk
1      University of Oxford                  ox.ac.uk
3                ETH Zurich                   ethz.ch
4                       UCL                 ucl.ac.uk
17                KU Leuven               kuleuven.be

In [45]:
from ddgs import DDGS
from urllib.parse import urlparse
import time

def search_official_programmes(
    university,
    official_domain,
    search_term,
    max_results=5
):
    
    query = f"{university} {search_term} MSc Master"
    
    rows = []
    
    try:
        results = list(
            DDGS().text(
                query,
                max_results=max_results
            )
        )
        
        for rank, result in enumerate(results, start=1):
            
            url = result.get("href", "")
            
            if not url:
                continue
            
            result_domain = (
                urlparse(url)
                .netloc
                .lower()
                .replace("www.", "")
            )
            
            # Keep only university official-domain results
            if (
                result_domain == official_domain
                or result_domain.endswith("." + official_domain)
            ):
                
                rows.append({
                    "university": university,
                    "search_term": search_term,
                    "query": query,
                    "result_rank": rank,
                    "title": result.get("title"),
                    "url": url,
                    "result_domain": result_domain,
                    "snippet": result.get("body")
                })
    
    except Exception as e:
        print(
            f"Error: {university} | "
            f"{search_term} | {e}"
        )
    
    return rows

In [46]:
test_results = search_official_programmes(
    university="Imperial College London",
    official_domain="imperial.ac.uk",
    search_term="Business Analytics",
    max_results=5
)

test_results

[{'university': 'Imperial College London',
  'search_term': 'Business Analytics',
  'query': 'Imperial College London Business Analytics MSc Master',
  'result_rank': 1,
  'title': 'MSc Business Analytics & AI - Imperial College London',
  'url': 'https://www.imperial.ac.uk/business-school/masters/business-analytics/',
  'result_domain': 'imperial.ac.uk',
  'snippet': 'Our MSc in Business Analytics & AI will equip you with advanced computational, machine learning, and AI capabilities to succeed in an increasingly data-driven world.'},
 {'university': 'Imperial College London',
  'search_term': 'Business Analytics',
  'query': 'Imperial College London Business Analytics MSc Master',
  'result_rank': 2,
  'title': 'Business Analytics and AI MSc | Study | Imperial College London',
  'url': 'https://www.imperial.ac.uk/study/courses/postgraduate-taught/business-analytics/',
  'result_domain': 'imperial.ac.uk',
  'snippet': 'Learn how to apply the latest academic thinking and analytical and computing tools to help make business decisions. MSc Business Analytics and AI equips you to make data-driven and evidence-based decisions and drive transformation within businesses.'}]

In [48]:
first_5 = df.head(5)[
    ["QS 2026 Rank", "University", "Country", "official_domain_candidate"]
]

first_5

,QS 2026 Rank,University,Country,official_domain_candidate
0,2,Imperial College London,United Kingdom,imperial.ac.uk
1,4,University of Oxford,United Kingdom,ox.ac.uk
2,6,University of Cambridge,United Kingdom,cam.ac.uk
3,7,ETH Zurich,Switzerland,ethz.ch
4,9,UCL,United Kingdom,ucl.ac.uk

In [49]:
candidate_results = []

for _, row in first_5.iterrows():

    university = row["University"]
    domain = row["official_domain_candidate"]

    print(f"Searching: {university}")

    for term in SEARCH_TERMS:

        results = search_official_programmes(
            university=university,
            official_domain=domain,
            search_term=term,
            max_results=5
        )

        candidate_results.extend(results)

        time.sleep(1)

candidate_df = pd.DataFrame(candidate_results)

print("Finished.")
print("Official results found:", len(candidate_df))

Searching: Imperial College London
Error: Imperial College London | Applied Analytics | No results found.
Error: Imperial College London | Applied Data Science | No results found.
Searching: University of Oxford
Error: University of Oxford | Applied Data Science | No results found.
Searching: University of Cambridge
Error: University of Cambridge | Data Analytics | No results found.
Error: University of Cambridge | Business Intelligence | No results found.
Error: University of Cambridge | Statistics and Data Science | No results found.
Searching: ETH Zurich
Error: ETH Zurich | Business Intelligence | No results found.
Searching: UCL
Finished.
Official results found: 104

In [50]:
candidate_unique = (
    candidate_df
    .drop_duplicates(subset=["url"])
    .copy()
)

print("Before URL deduplication:", len(candidate_df))
print("After URL deduplication:", len(candidate_unique))

Before URL deduplication: 104
After URL deduplication: 52

In [52]:
candidate_unique[
    [
        "university",
        "search_term",
        "title",
        "url"
    ]
].sort_values(
    ["university", "search_term"]
).reset_index(drop=True)

,university,search_term,title,url
0,ETH Zurich,Applied Analytics,Master's programmes – Department of Mathematic...,https://math.ethz.ch/studies/master-programmes...
1,ETH Zurich,Applied Data Science,Master Data Science – Departement Mathematik |...,https://math.ethz.ch/de/studium/master/master-...
2,ETH Zurich,Business Analytics,Business Analytics | ETH Zurich,https://ethz.ch/en/the-eth-zurich/education/in...
3,ETH Zurich,Business Analytics,Master’s degree studies | ETH Zurich,https://ethz.ch/en/studies/master.html
4,ETH Zurich,Business Analytics,Master's Programmes – Department of Computer S...,https://inf.ethz.ch/studies/master.html
5,ETH Zurich,Data Analytics,Master in Data Science - Departement Mathemati...,https://math.ethz.ch/de/studium/master/data-sc...
6,ETH Zurich,Data Science,Master Data Science | ETH Zurich,https://ethz.ch/en/studies/master/degree-progr...
7,ETH Zurich,Data Science,Data Science MSc | ETH Zurich,https://ethz.ch/en/studies/master/application/...
8,ETH Zurich,Data Science,Master in Data Science – Department of Compute...,https://inf.ethz.ch/studies/master/master-ds.html
9,ETH Zurich,Data Science,Master's in Data Science – Department of Mathe...,https://math.ethz.ch/studies/master-programmes...
10,ETH Zurich,Statistics and Data Science,Master Statistics | ETH Zurich,https://ethz.ch/en/studies/master/degree-progr...
11,ETH Zurich,Statistics and Data Science,Master of Science in Statistics – Seminar for ...,https://math.ethz.ch/sfs/education/msc-in-stat...
12,Imperial College London,Analytics and Data Science,Health Data Analytics and Machine Learning MSc,https://www.imperial.ac.uk/study/courses/postg...
13,Imperial College London,Business Analytics,MSc Business Analytics & AI - Imperial College...,https://www.imperial.ac.uk/business-school/mas...
14,Imperial College London,Business Analytics,Business Analytics and AI MSc | Study | Imperi...,https://www.imperial.ac.uk/study/courses/postg...
15,Imperial College London,Business Intelligence,"MSc programmes, London UK - Business School",https://www.imperial.ac.uk/business-school/mas...
16,Imperial College London,Data Science,Statistics (Data Science and Machine Learning)...,https://www.imperial.ac.uk/study/courses/postg...
17,Imperial College London,Data Science,Data science | Study | Imperial College London,https://www.imperial.ac.uk/study/subjects/data...
18,Imperial College London,Data Science,MSc Machine Learning and Data Science (Online),https://www.imperial.ac.uk/mathematics/postgra...
19,Imperial College London,Data Science,Machine Learning and Data Science (Online) MSc,https://www.imperial.ac.uk/study/courses/postg...
20,Imperial College London,Statistics and Data Science,MSc in Statistics | Faculty of Natural Science...,https://www.imperial.ac.uk/mathematics/postgra...
21,UCL,Applied Analytics,Applied Analytical Chemistry MSc | Prospective...,https://www.ucl.ac.uk/prospective-students/gra...
22,UCL,Applied Analytics,MSc in Applied Analytical Chemistry | Faculty ...,https://www.ucl.ac.uk/mathematical-physical-sc...
23,UCL,Applied Data Science,Social and Geographic Data Science MSc | Prosp...,https://www.ucl.ac.uk/prospective-students/gra...
24,UCL,Applied Data Science,Data Science and Public Policy (Political Scie...,https://www.ucl.ac.uk/prospective-students/gra...
25,UCL,Business Analytics,Business Analytics MSc | Prospective Students ...,https://www.ucl.ac.uk/prospective-students/gra...
26,UCL,Business Analytics,Business Analytics MSc | Study at UCL,https://www.ucl.ac.uk/study/prospective-studen...
27,UCL,Business Analytics,MSc Business Analytics | UCL School of Managem...,https://www.mgmt.ucl.ac.uk/business-analytics
28,UCL,Business Analytics,Postgraduate Study | UCL School of Management,https://www.mgmt.ucl.ac.uk/postgraduate-study
29,UCL,Business Intelligence,Business Analytics MSc | Prospective Students ...,https://www.ucl.ac.uk/prospective-students/gra...
30,UCL,Data Analytics,MSc Business Analytics | UCL School of Management,http://www.mgmt.ucl.ac.uk/business-analytics
31,UCL,Data Science,MSc Data Science | Faculty of Mathematical & P...,https://www.ucl.ac.uk/mathematical-physical-sc...
32,UCL,Data Science,Data Science MSc | Study at UCL,https://www.ucl.ac.uk/study/prospective-studen...
33,UCL,Statistics and Data Science,Data Science MSc | Prospective Students Gradua...,https://www.ucl.ac.uk/prospective-students/gra...
34,University of Cambridge,Business Analytics,Business Analytics and AI: Decision-Making Usi...,https://www.jbs.cam.ac.uk/executive-education/...
35,University of Cambridge,Business Analytics,Masters degrees - Cambridge Judge Business School,https://www.jbs.cam.ac.uk/masters-degrees/
36,University of Cambridge,Business Analytics,Business Analytics and AI | Cambridge Judge Ex...,https://online.em.jbs.cam.ac.uk/business-analy...
37,University of Cambridge,Data Science,MPhil in Data Intensive Science | Postgraduate...,https://www.postgraduate.study.cam.ac.uk/cours...
38,University of Cambridge,Data Science,MPhil in Data Intensive Science | Postgraduate...,https://www.postgraduate.study.cam.ac.uk/cours...
39,University of Cambridge,Data Science,MPhil in Economics & Data Science | Faculty of...,https://www.econ.cam.ac.uk/apply/postgraduate/...
40,University of Oxford,Applied Analytics,MSc Courses | Mathematical Institute - Univers...,https://www.maths.ox.ac.uk/study-here/postgrad...
41,University of Oxford,Business Analytics,Find your postgraduate course | Oxford University,https://www.ox.ac.uk/admissions/graduate/cours...
42,University of Oxford,Business Analytics,Degrees - Saïd Business School,https://www.sbs.ox.ac.uk/programmes/degrees
43,University of Oxford,Business Analytics,Saïd Business School | Oxford University,https://www.ox.ac.uk/admissions/graduate/cours...
44,University of Oxford,Business Intelligence,MSc in Artificial Intelligence for Business | ...,https://www.ox.ac.uk/admissions/graduate/cours...
45,University of Oxford,Business Intelligence,MSc AI for Business | Saïd Business School,https://www.sbs.ox.ac.uk/programmes/degrees/ms...
46,University of Oxford,Business Intelligence,Find your programme - Saïd Business School,https://www.sbs.ox.ac.uk/programmes
47,University of Oxford,Data Science,MSc in Social Data Science - University of Oxford,https://www.ox.ac.uk/admissions/graduate/cours...
48,University of Oxford,Data Science,MSc in Statistical Science - University of Oxford,https://www.ox.ac.uk/admissions/graduate/cours...
49,University of Oxford,Statistics and Data Science,MSc/PGDip in Statistical Science - University ...,https://www.stats.ox.ac.uk/msc-statistical-sci...
50,University of Oxford,Statistics and Data Science,Department of Statistics | Oxford University,https://www.ox.ac.uk/admissions/graduate/cours...
51,University of Oxford,Statistics and Data Science,MSc in Statistical Science Student Resources,https://www.stats.ox.ac.uk/msc-statistical-sci...

In [53]:
PROGRAMME_TITLE_KEYWORDS = [
    "business analytics",
    "data science",
    "data analytics",
    "applied analytics",
    "business intelligence",
    "applied data science",
    "statistics and data science",
    "analytics and data science"
]

def likely_programme_page(title):
    title = str(title).lower()

    return any(
        keyword in title
        for keyword in PROGRAMME_TITLE_KEYWORDS
    )

programme_candidates = candidate_unique[
    candidate_unique["title"].apply(likely_programme_page)
].copy()

print("All unique official pages:", len(candidate_unique))
print("Likely programme-related pages:", len(programme_candidates))

All unique official pages: 52
Likely programme-related pages: 29

In [54]:
programme_candidates[
    [
        "university",
        "title",
        "url"
    ]
].sort_values(
    ["university", "title"]
).reset_index(drop=True)

,university,title,url
0,ETH Zurich,Business Analytics | ETH Zurich,https://ethz.ch/en/the-eth-zurich/education/in...
1,ETH Zurich,Data Science MSc | ETH Zurich,https://ethz.ch/en/studies/master/application/...
2,ETH Zurich,Master Data Science | ETH Zurich,https://ethz.ch/en/studies/master/degree-progr...
3,ETH Zurich,Master Data Science – Departement Mathematik |...,https://math.ethz.ch/de/studium/master/master-...
4,ETH Zurich,Master in Data Science - Departement Mathemati...,https://math.ethz.ch/de/studium/master/data-sc...
5,ETH Zurich,Master in Data Science – Department of Compute...,https://inf.ethz.ch/studies/master/master-ds.html
6,ETH Zurich,Master of Science in Statistics – Seminar for ...,https://math.ethz.ch/sfs/education/msc-in-stat...
7,ETH Zurich,Master's in Data Science – Department of Mathe...,https://math.ethz.ch/studies/master-programmes...
8,Imperial College London,Business Analytics and AI MSc | Study | Imperi...,https://www.imperial.ac.uk/study/courses/postg...
9,Imperial College London,Data science | Study | Imperial College London,https://www.imperial.ac.uk/study/subjects/data...
10,Imperial College London,Health Data Analytics and Machine Learning MSc,https://www.imperial.ac.uk/study/courses/postg...
11,Imperial College London,MSc Business Analytics & AI - Imperial College...,https://www.imperial.ac.uk/business-school/mas...
12,Imperial College London,MSc Machine Learning and Data Science (Online),https://www.imperial.ac.uk/mathematics/postgra...
13,Imperial College London,Machine Learning and Data Science (Online) MSc,https://www.imperial.ac.uk/study/courses/postg...
14,Imperial College London,Statistics (Data Science and Machine Learning)...,https://www.imperial.ac.uk/study/courses/postg...
15,UCL,Business Analytics MSc | Prospective Students ...,https://www.ucl.ac.uk/prospective-students/gra...
16,UCL,Business Analytics MSc | Prospective Students ...,https://www.ucl.ac.uk/prospective-students/gra...
17,UCL,Business Analytics MSc | Study at UCL,https://www.ucl.ac.uk/study/prospective-studen...
18,UCL,Data Science MSc | Prospective Students Gradua...,https://www.ucl.ac.uk/prospective-students/gra...
19,UCL,Data Science MSc | Study at UCL,https://www.ucl.ac.uk/study/prospective-studen...
20,UCL,Data Science and Public Policy (Political Scie...,https://www.ucl.ac.uk/prospective-students/gra...
21,UCL,MSc Business Analytics | UCL School of Management,http://www.mgmt.ucl.ac.uk/business-analytics
22,UCL,MSc Business Analytics | UCL School of Managem...,https://www.mgmt.ucl.ac.uk/business-analytics
23,UCL,MSc Data Science | Faculty of Mathematical & P...,https://www.ucl.ac.uk/mathematical-physical-sc...
24,UCL,Social and Geographic Data Science MSc | Prosp...,https://www.ucl.ac.uk/prospective-students/gra...
25,University of Cambridge,Business Analytics and AI | Cambridge Judge Ex...,https://online.em.jbs.cam.ac.uk/business-analy...
26,University of Cambridge,Business Analytics and AI: Decision-Making Usi...,https://www.jbs.cam.ac.uk/executive-education/...
27,University of Cambridge,MPhil in Economics & Data Science | Faculty of...,https://www.econ.cam.ac.uk/apply/postgraduate/...
28,University of Oxford,MSc in Social Data Science - University of Oxford,https://www.ox.ac.uk/admissions/graduate/cours...

In [55]:
review_df = programme_candidates[
    [
        "university",
        "title",
        "url"
    ]
].sort_values(
    ["university", "title"]
).reset_index(drop=True).copy()

review_df["programme_name"] = ""
review_df["decision"] = ""
review_df["reason"] = ""

review_df

,university,title,url,programme_name,decision,reason
0,ETH Zurich,Business Analytics | ETH Zurich,https://ethz.ch/en/the-eth-zurich/education/in...,,,
1,ETH Zurich,Data Science MSc | ETH Zurich,https://ethz.ch/en/studies/master/application/...,,,
2,ETH Zurich,Master Data Science | ETH Zurich,https://ethz.ch/en/studies/master/degree-progr...,,,
3,ETH Zurich,Master Data Science – Departement Mathematik |...,https://math.ethz.ch/de/studium/master/master-...,,,
4,ETH Zurich,Master in Data Science - Departement Mathemati...,https://math.ethz.ch/de/studium/master/data-sc...,,,
5,ETH Zurich,Master in Data Science – Department of Compute...,https://inf.ethz.ch/studies/master/master-ds.html,,,
6,ETH Zurich,Master of Science in Statistics – Seminar for ...,https://math.ethz.ch/sfs/education/msc-in-stat...,,,
7,ETH Zurich,Master's in Data Science – Department of Mathe...,https://math.ethz.ch/studies/master-programmes...,,,
8,Imperial College London,Business Analytics and AI MSc | Study | Imperi...,https://www.imperial.ac.uk/study/courses/postg...,,,
9,Imperial College London,Data science | Study | Imperial College London,https://www.imperial.ac.uk/study/subjects/data...,,,
10,Imperial College London,Health Data Analytics and Machine Learning MSc,https://www.imperial.ac.uk/study/courses/postg...,,,
11,Imperial College London,MSc Business Analytics & AI - Imperial College...,https://www.imperial.ac.uk/business-school/mas...,,,
12,Imperial College London,MSc Machine Learning and Data Science (Online),https://www.imperial.ac.uk/mathematics/postgra...,,,
13,Imperial College London,Machine Learning and Data Science (Online) MSc,https://www.imperial.ac.uk/study/courses/postg...,,,
14,Imperial College London,Statistics (Data Science and Machine Learning)...,https://www.imperial.ac.uk/study/courses/postg...,,,
15,UCL,Business Analytics MSc | Prospective Students ...,https://www.ucl.ac.uk/prospective-students/gra...,,,
16,UCL,Business Analytics MSc | Prospective Students ...,https://www.ucl.ac.uk/prospective-students/gra...,,,
17,UCL,Business Analytics MSc | Study at UCL,https://www.ucl.ac.uk/study/prospective-studen...,,,
18,UCL,Data Science MSc | Prospective Students Gradua...,https://www.ucl.ac.uk/prospective-students/gra...,,,
19,UCL,Data Science MSc | Study at UCL,https://www.ucl.ac.uk/study/prospective-studen...,,,
20,UCL,Data Science and Public Policy (Political Scie...,https://www.ucl.ac.uk/prospective-students/gra...,,,
21,UCL,MSc Business Analytics | UCL School of Management,http://www.mgmt.ucl.ac.uk/business-analytics,,,
22,UCL,MSc Business Analytics | UCL School of Managem...,https://www.mgmt.ucl.ac.uk/business-analytics,,,
23,UCL,MSc Data Science | Faculty of Mathematical & P...,https://www.ucl.ac.uk/mathematical-physical-sc...,,,
24,UCL,Social and Geographic Data Science MSc | Prosp...,https://www.ucl.ac.uk/prospective-students/gra...,,,
25,University of Cambridge,Business Analytics and AI | Cambridge Judge Ex...,https://online.em.jbs.cam.ac.uk/business-analy...,,,
26,University of Cambridge,Business Analytics and AI: Decision-Making Usi...,https://www.jbs.cam.ac.uk/executive-education/...,,,
27,University of Cambridge,MPhil in Economics & Data Science | Faculty of...,https://www.econ.cam.ac.uk/apply/postgraduate/...,,,
28,University of Oxford,MSc in Social Data Science - University of Oxford,https://www.ox.ac.uk/admissions/graduate/cours...,,,

In [56]:
review_df.to_csv(
    "../data/europe_programme_review.csv",
    index=False
)

print("Saved.")

Saved.

In [57]:
selected_programmes = pd.DataFrame([
    {
        "university": "Imperial College London",
        "programme_name": "MSc Business Analytics & AI",
        "official_domain": "imperial.ac.uk",
        "decision": "Include"
    },
    {
        "university": "ETH Zurich",
        "programme_name": "MSc Data Science",
        "official_domain": "ethz.ch",
        "decision": "Include"
    },
    {
        "university": "UCL",
        "programme_name": "MSc Business Analytics",
        "official_domain": "ucl.ac.uk",
        "decision": "Include"
    },
    {
        "university": "UCL",
        "programme_name": "MSc Data Science",
        "official_domain": "ucl.ac.uk",
        "decision": "Include"
    }
])

selected_programmes

,university,programme_name,official_domain,decision
0,Imperial College London,MSc Business Analytics & AI,imperial.ac.uk,Include
1,ETH Zurich,MSc Data Science,ethz.ch,Include
2,UCL,MSc Business Analytics,ucl.ac.uk,Include
3,UCL,MSc Data Science,ucl.ac.uk,Include

In [58]:
new_programmes = pd.DataFrame([
    {
        "university": "Imperial College London",
        "programme_name": "MSc Statistics (Data Science and Machine Learning)",
        "official_domain": "imperial.ac.uk",
        "decision": "Include"
    },
    {
        "university": "University of Oxford",
        "programme_name": "MSc in Social Data Science",
        "official_domain": "ox.ac.uk",
        "decision": "Include"
    },
    {
        "university": "UCL",
        "programme_name": "MSc Data Science and Public Policy",
        "official_domain": "ucl.ac.uk",
        "decision": "Include"
    }
])

selected_programmes = pd.concat(
    [selected_programmes, new_programmes],
    ignore_index=True
)

selected_programmes

,university,programme_name,official_domain,decision
0,Imperial College London,MSc Business Analytics & AI,imperial.ac.uk,Include
1,ETH Zurich,MSc Data Science,ethz.ch,Include
2,UCL,MSc Business Analytics,ucl.ac.uk,Include
3,UCL,MSc Data Science,ucl.ac.uk,Include
4,Imperial College London,MSc Statistics (Data Science and Machine Learn...,imperial.ac.uk,Include
5,University of Oxford,MSc in Social Data Science,ox.ac.uk,Include
6,UCL,MSc Data Science and Public Policy,ucl.ac.uk,Include

In [59]:
next_5 = df.iloc[5:10][
    ["QS 2026 Rank", "University", "Country", "official_domain_candidate"]
].copy()

next_5

,QS 2026 Rank,University,Country,official_domain_candidate
5,22,EPFL – École polytechnique fédérale de Lausanne,Switzerland,epfl.ch
6,22,Technical University of Munich,Germany,tum.de
7,28,PSL University,France,psl.eu
8,31,King's College London,United Kingdom,kcl.ac.uk
9,34,University of Edinburgh,United Kingdom,ed.ac.uk

In [60]:
next_results = []

for _, row in next_5.iterrows():

    university = row["University"]
    domain = row["official_domain_candidate"]

    print(f"\nSearching: {university}")

    for term in SEARCH_TERMS:

        results = search_official_programmes(
            university=university,
            official_domain=domain,
            search_term=term,
            max_results=5
        )

        next_results.extend(results)

        time.sleep(1)

next_df = pd.DataFrame(next_results)

print("\nFinished.")
print("Official results found:", len(next_df))

Searching: EPFL – École polytechnique fédérale de Lausanne
Error: EPFL – École polytechnique fédérale de Lausanne | Applied Analytics | No results found.

Searching: Technical University of Munich

Searching: PSL University
Error: PSL University | Business Analytics | No results found.
Error: PSL University | Data Science | No results found.
Error: PSL University | Applied Analytics | No results found.
Error: PSL University | Statistics and Data Science | No results found.

Searching: King's College London
Error: King's College London | Data Analytics | No results found.

Searching: University of Edinburgh
Error: University of Edinburgh | Business Intelligence | No results found.
Error: University of Edinburgh | Statistics and Data Science | No results found.

Finished.
Official results found: 99

In [61]:
next_unique = (
    next_df
    .drop_duplicates(subset=["url"])
    .copy()
)

print("Before URL deduplication:", len(next_df))
print("After URL deduplication:", len(next_unique))

Before URL deduplication: 99
After URL deduplication: 50

In [62]:
next_candidates = next_unique[
    next_unique["title"].apply(likely_programme_page)
].copy()

print("Likely programme-related pages:", len(next_candidates))

Likely programme-related pages: 21

In [63]:
next_candidates[
    [
        "university",
        "title",
        "url"
    ]
].sort_values(
    ["university", "title"]
).reset_index(drop=True)

,university,title,url
0,EPFL – École polytechnique fédérale de Lausanne,Cycle Master - Data Science - EPFL,https://edu.epfl.ch/studyplan/fr/master/data-s...
1,EPFL – École polytechnique fédérale de Lausanne,Data Science ‒ Master ‐ EPFL,https://www.epfl.ch/education/master/programs/...
2,EPFL – École polytechnique fédérale de Lausanne,Data Science ‒ Master ‐ EPFL,https://www.epfl.ch/education/master/fr/progra...
3,EPFL – École polytechnique fédérale de Lausanne,Master Cycle - Data Science - EPFL,https://edu.epfl.ch/studyplan/en/master/data-s...
4,EPFL – École polytechnique fédérale de Lausanne,Master in Data Science ‒ IC ‐ EPFL,https://www.epfl.ch/schools/ic/education/maste...
5,King's College London,Applied Statistical Modelling & Health Informa...,https://www.kcl.ac.uk/study/postgraduate-taugh...
6,King's College London,Data Science - Entry Requirements | King's Col...,https://www.kcl.ac.uk/study/postgraduate-taugh...
7,King's College London,Data Science MSc - King's College LondonData S...,https://www.kcl.ac.uk/study/postgraduate-taugh...
8,PSL University,"Computer Science, Decision and Data Science - ...",https://dauphine.psl.eu/en/training/masters-de...
9,PSL University,DATA Program: study AI and data science at Uni...,https://psl.eu/en/programmes-gradues/programme...
10,Technical University of Munich,Master Mathematics in Data Science - TUM - TUM...,https://www.cit.tum.de/en/cit/studies/degree-p...
11,Technical University of Munich,Mathematics in Data Science - Master of Scienc...,https://www.tum.de/en/studies/degree-programs/...
12,University of Edinburgh,Applied Data Science (Online Learning) MSc,https://study.ed.ac.uk/programmes/postgraduate...
13,University of Edinburgh,Business Analytics MSc - Postgraduate taught p...,https://study.ed.ac.uk/programmes/postgraduate...
14,University of Edinburgh,DPT: Applied Data Science (MSc) - 1 Year (Full...,https://www.drps.ed.ac.uk/26_27_Archive_at_01-...
15,University of Edinburgh,Data Science MSc - Postgraduate taught program...,https://study.ed.ac.uk/programmes/postgraduate...
16,University of Edinburgh,Data Science MSc | Taught students | School of...,https://informatics.ed.ac.uk/taught-students/m...
17,University of Edinburgh,MSc Business Analytics - University of Edinbur...,https://www.business-school.ed.ac.uk/msc/busin...
18,University of Edinburgh,MSc Business Analytics | ApplyComputational Ap...,https://www.business-school.ed.ac.uk/msc/busin...
19,University of Edinburgh,MSc Business Analytics | Joining Information,https://www.join.business-school.ed.ac.uk/msc/...
20,University of Edinburgh,Statistics with Data Science MSc - Postgraduat...,https://study.ed.ac.uk/programmes/postgraduate...

In [64]:
pd.set_option("display.max_colwidth", None)

next_candidates[
    ["university", "title", "url"]
].sort_values(
    ["university", "title"]
).reset_index(drop=True)

,university,title,url
0,EPFL – École polytechnique fédérale de Lausanne,Cycle Master - Data Science - EPFL,https://edu.epfl.ch/studyplan/fr/master/data-science/
1,EPFL – École polytechnique fédérale de Lausanne,Data Science ‒ Master ‐ EPFL,https://www.epfl.ch/education/master/programs/data-science/
2,EPFL – École polytechnique fédérale de Lausanne,Data Science ‒ Master ‐ EPFL,https://www.epfl.ch/education/master/fr/programmes/data-science/
3,EPFL – École polytechnique fédérale de Lausanne,Master Cycle - Data Science - EPFL,https://edu.epfl.ch/studyplan/en/master/data-science/
4,EPFL – École polytechnique fédérale de Lausanne,Master in Data Science ‒ IC ‐ EPFL,https://www.epfl.ch/schools/ic/education/master/data-science/
5,King's College London,"Applied Statistical Modelling & Health Informatics MSc/PGDip ...Applied Artificial Intelligence MSc (Online) | King’s College ...King's College London - Online master’s programmesGlobal Finance Analytics MSc (online, part-time) - King'sMSc Business Analytics & AI - Imperial College LondonData Analytics MSc - Queen Mary University of London",https://www.kcl.ac.uk/study/postgraduate-taught/courses/applied-statistical-modelling-health-informatics
6,King's College London,Data Science - Entry Requirements | King's College London,https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc/requirements
7,King's College London,"Data Science MSc - King's College LondonData Science - Entry Requirements | King's College LondonData Science | King's College London, University of London | UCASData Science MSc at King's College London, University of ...Data Science MSc – King's College London, University of LondonData Science MSc at King's College London, University of ...MSc Data Science at KCL: Fees Dates & Requirements",https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc
8,PSL University,"Computer Science, Decision and Data Science - Master's Year 1",https://dauphine.psl.eu/en/training/masters-degrees/computer-science/m1-i2d
9,PSL University,DATA Program: study AI and data science at Université PSL,https://psl.eu/en/programmes-gradues/programme-data
10,Technical University of Munich,Master Mathematics in Data Science - TUM - TUM School of ...,https://www.cit.tum.de/en/cit/studies/degree-programs/master-mathematics-data-science/
11,Technical University of Munich,Mathematics in Data Science - Master of Science (M.Sc.) - TUM,https://www.tum.de/en/studies/degree-programs/detail/mathematics-in-data-science-master-of-science-msc
12,University of Edinburgh,Applied Data Science (Online Learning) MSc,https://study.ed.ac.uk/programmes/postgraduate-taught/1149-applied-data-science-online-learning
13,University of Edinburgh,Business Analytics MSc - Postgraduate taught programmes | The University of Edinburgh,https://study.ed.ac.uk/programmes/postgraduate-taught/929-business-analytics
14,University of Edinburgh,DPT: Applied Data Science (MSc) - 1 Year (Full-time) (PTMSCAPDSE1F),https://www.drps.ed.ac.uk/26_27_Archive_at_01-09-2026/dpt/ptmscapdse1f.htm
15,University of Edinburgh,Data Science MSc - Postgraduate taught programmes | The University of Edinburgh,https://study.ed.ac.uk/programmes/postgraduate-taught/902-data-science
16,University of Edinburgh,Data Science MSc | Taught students | School of Informatics,https://informatics.ed.ac.uk/taught-students/msc-students/taught-msc-handbook-202526/degree-programmes-and-courses/data-science
17,University of Edinburgh,MSc Business Analytics - University of Edinburgh Business School,https://www.business-school.ed.ac.uk/msc/business-analytics
18,University of Edinburgh,MSc Business Analytics | ApplyComputational Applied Mathematics MSc - Postgraduate taught ...MSc Business Analytics | Joining InformationUniversity of Edinburgh MSc Business Analytics 2026:Admission ...Business Analytics MSc at The University of Edinburgh | The ...,https://www.business-school.ed.ac.uk/msc/business-analytics/apply
19,University of Edinburgh,MSc Business Analytics | Joining Information,https://www.join.business-school.ed.ac.uk/msc/business-analytics
20,University of Edinburgh,Statistics with Data Science MSc - Postgraduate taught ...,https://study.ed.ac.uk/programmes/postgraduate-taught/916-statistics-with-data-science

In [65]:
batch_2_selected = pd.DataFrame([
    {
        "university": "EPFL",
        "programme_name": "Master in Data Science",
        "official_domain": "epfl.ch",
        "decision": "Include"
    },
    {
        "university": "Technical University of Munich",
        "programme_name": "MSc Mathematics in Data Science",
        "official_domain": "tum.de",
        "decision": "Include"
    },
    {
        "university": "King's College London",
        "programme_name": "MSc Data Science",
        "official_domain": "kcl.ac.uk",
        "decision": "Include"
    },
    {
        "university": "University of Edinburgh",
        "programme_name": "MSc Business Analytics",
        "official_domain": "ed.ac.uk",
        "decision": "Include"
    },
    {
        "university": "University of Edinburgh",
        "programme_name": "MSc Data Science",
        "official_domain": "ed.ac.uk",
        "decision": "Include"
    }
])

selected_programmes = pd.concat(
    [selected_programmes, batch_2_selected],
    ignore_index=True
)

selected_programmes

,university,programme_name,official_domain,decision
0,Imperial College London,MSc Business Analytics & AI,imperial.ac.uk,Include
1,ETH Zurich,MSc Data Science,ethz.ch,Include
2,UCL,MSc Business Analytics,ucl.ac.uk,Include
3,UCL,MSc Data Science,ucl.ac.uk,Include
4,Imperial College London,MSc Statistics (Data Science and Machine Learning),imperial.ac.uk,Include
5,University of Oxford,MSc in Social Data Science,ox.ac.uk,Include
6,UCL,MSc Data Science and Public Policy,ucl.ac.uk,Include
7,EPFL,Master in Data Science,epfl.ch,Include
8,Technical University of Munich,MSc Mathematics in Data Science,tum.de,Include
9,King's College London,MSc Data Science,kcl.ac.uk,Include
10,University of Edinburgh,MSc Business Analytics,ed.ac.uk,Include
11,University of Edinburgh,MSc Data Science,ed.ac.uk,Include

In [66]:
mid_rank_candidates = df[
    (df["QS 2026 Rank"] >= 35) &
    (df["QS 2026 Rank"] <= 100)
][
    [
        "QS 2026 Rank",
        "University",
        "Country",
        "official_domain_candidate"
    ]
].copy()

mid_rank_candidates

,QS 2026 Rank,University,Country,official_domain_candidate
10,35,The University of Manchester,United Kingdom,manchester.ac.uk
11,41,Institut Polytechnique de Paris,France,ip-paris.fr
12,47,Delft University of Technology,Netherlands,tudelft.nl
13,51,University of Bristol,United Kingdom,bristol.ac.uk
14,53,University of Amsterdam,Netherlands,uva.nl
15,56,London School of Economics and Political Science (LSE),United Kingdom,lse.ac.uk
16,58,Ludwig-Maximilians-Universität München,Germany,lmu.de
17,60,KU Leuven,Belgium,kuleuven.be
18,70,Université Paris-Saclay,France,universite-paris-saclay.fr
19,72,Lund University,Sweden,lu.se
20,72,Sorbonne University,France,sorbonne-universite.fr
21,74,The University of Warwick,United Kingdom,warwick.ac.uk
22,75,"Trinity College Dublin, The University of Dublin",Ireland,trinity-college-dublin.ie
23,76,University of Birmingham,United Kingdom,birmingham.ac.uk
24,78,KTH Royal Institute of Technology,Sweden,kth.se
25,79,University of Glasgow,United Kingdom,gla.ac.uk
26,80,Heidelberg University,Germany,uni-heidelberg.de
27,86,University of Leeds,United Kingdom,courses.leeds.ac.uk
28,87,University of Southampton,United Kingdom,southampton.ac.uk
29,88,Freie Universität Berlin,Germany,fu-berlin.de
30,92,The University of Sheffield,United Kingdom,sheffield.ac.uk
31,93,Uppsala University,Sweden,uu.se
32,94,Durham University,United Kingdom,durham.ac.uk
33,97,The University of Nottingham,United Kingdom,nottingham.ac.uk
34,98,"KIT, Karlsruhe Institute of Technology",Germany,kit.edu
35,98,Politecnico di Milano,Italy,polimi.it
36,100,University of Zurich,Switzerland,uzh.ch

In [67]:
target_universities = [
    "Institut Polytechnique de Paris",
    "Delft University of Technology",
    "KU Leuven",
    "Université Paris-Saclay",
    "Lund University",
    "Politecnico di Milano"
]

next_6 = df[
    df["University"].isin(target_universities)
][
    [
        "QS 2026 Rank",
        "University",
        "Country",
        "official_domain_candidate"
    ]
].copy()

next_6 = next_6.sort_values("QS 2026 Rank")

next_6

,QS 2026 Rank,University,Country,official_domain_candidate
11,41,Institut Polytechnique de Paris,France,ip-paris.fr
12,47,Delft University of Technology,Netherlands,tudelft.nl
17,60,KU Leuven,Belgium,kuleuven.be
18,70,Université Paris-Saclay,France,universite-paris-saclay.fr
19,72,Lund University,Sweden,lu.se
35,98,Politecnico di Milano,Italy,polimi.it

In [68]:
batch_3_results = []

for _, row in next_6.iterrows():

    university = row["University"]
    domain = row["official_domain_candidate"]

    print(f"\nSearching: {university}")

    for term in SEARCH_TERMS:

        results = search_official_programmes(
            university=university,
            official_domain=domain,
            search_term=term,
            max_results=5
        )

        batch_3_results.extend(results)

        time.sleep(1)

batch_3_df = pd.DataFrame(batch_3_results)

print("\nFinished.")
print("Official results found:", len(batch_3_df))

Searching: Institut Polytechnique de Paris
Error: Institut Polytechnique de Paris | Statistics and Data Science | No results found.

Searching: Delft University of Technology
Error: Delft University of Technology | Data Analytics | No results found.

Searching: KU Leuven
Error: KU Leuven | Data Science | No results found.
Error: KU Leuven | Applied Analytics | No results found.
Error: KU Leuven | Business Intelligence | No results found.

Searching: Université Paris-Saclay
Error: Université Paris-Saclay | Applied Data Science | No results found.
Error: Université Paris-Saclay | Statistics and Data Science | No results found.

Searching: Lund University
Error: Lund University | Statistics and Data Science | No results found.

Searching: Politecnico di Milano
Error: Politecnico di Milano | Business Analytics | No results found.
Error: Politecnico di Milano | Statistics and Data Science | No results found.

Finished.
Official results found: 108

In [69]:
batch_3_unique = (
    batch_3_df
    .drop_duplicates(subset=["url"])
    .copy()
)

print("Before URL deduplication:", len(batch_3_df))
print("After URL deduplication:", len(batch_3_unique))

Before URL deduplication: 108
After URL deduplication: 47

In [70]:
batch_3_candidates = batch_3_unique[
    batch_3_unique["title"].apply(likely_programme_page)
].copy()

print(
    "Likely programme-related pages:",
    len(batch_3_candidates)
)

batch_3_candidates[
    ["university", "title", "url"]
].sort_values(
    ["university", "title"]
).reset_index(drop=True)

Likely programme-related pages: 28

,university,title,url
0,Delft University of Technology,Data Science and Artificial Intelligence Technology - TU Delft,https://www.tudelft.nl/en/education/programmes/masters/dsait/msc-data-science-and-artificial-intelligence-technology/programme
1,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,https://www.tudelft.nl/en/education/programmes/masters/dsait/msc-data-science-and-artificial-intelligence-technology
2,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology - TU Delft,https://www.tudelft.nl/onderwijs/opleidingen/masters/dsait/msc-data-science-and-artificial-intelligence-technology
3,Institut Polytechnique de Paris,Master Year 2 Data Science - Institut Polytechnique de ParisMSc Data Science For Business Master - École PolytechniqueM2DS - M2 DS - Data Science | SynapseS - École PolytechniqueMaster & PhD Programs | Polytechnique ProgramMaster Institut Polytechnique de ParisMaster in Data Sciences 12 months Postgraduate Program By ...,https://www.ip-paris.fr/education/masters/mention-mathematiques-appliquees-statistique/master-year-2-data-science
4,Institut Polytechnique de Paris,Master Year 2 Data Science | Institut Polytechnique de ParisMaster Year 2 Data Science - Institut Polytechnique de ParisMSc Data Science For Business Master - École PolytechniqueM2DS - M2 DS - Data Science | SynapseS - École PolytechniqueMaster & PhD Programs | Polytechnique ProgramMaster Institut Polytechnique de ParisMaster in Data Sciences 12 months Postgraduate Program By ...,https://www.ip-paris.fr/en/education/masters/applied-mathematics-and-statistics-program/master-year-2-data-science
5,KU Leuven,Business Analytics | KU Leuven,https://onderwijsaanbod.kuleuven.be/syllabi/e/H0Q44AE.htm
6,KU Leuven,Master of Science in Statistics and Data Science — Leuven Statistics ...,https://lstat.kuleuven.be/masterBologna
7,KU Leuven,Master of Statistics and Data Science,https://onderwijsaanbod.kuleuven.be/opleidingen/e/SC_58942261
8,KU Leuven,Master of Statistics and Data Science - KU Leuven,https://onderwijsaanbod.kuleuven.be/opleidingen/e/SC_51016989/diploma_omschrijving
9,KU Leuven,Master of Statistics and Data Science - KU Leuven,https://www.kuleuven.be/programmes/master-statistics-data-science/?mtm_campaign=international-students&mtm_source=keystone&mtm_medium=listing
10,KU Leuven,Master of Statistics and Data Science - KU Leuven,https://onderwijsaanbod.kuleuven.be/opleidingen/e/SC_56139245
11,KU Leuven,Postgraduate Studies in Business Analytics and AI — Faculteit Economie en Bedrijfswetenschappen,https://feb.kuleuven.be/levenslang-leren/bigdataanalytics
12,Lund University,Data Analytics and Business Economics - Magisterprogram - Lu,https://www.lu.se/studera/data-analytics-and-business-economics-magisterprogram-EAGDA
13,Lund University,Data Analytics and Business Economics - Master's Programme | Lund University,https://www.lunduniversity.lu.se/study/data-analytics-and-business-economics-masters-programme-EAGDA
14,Lund University,How to apply | Data Analytics and Business Economics - Master ...,https://www.lunduniversity.lu.se/study/data-analytics-and-business-economics-masters-programme-EAGDA/how-to-apply
15,Lund University,Programme structure | Data Analytics and Business Economics ...,https://www.lunduniversity.lu.se/study/data-analytics-and-business-economics-masters-programme-EAGDA/programme-structure
16,Lund University,Statistics: Programming for Data Science | Lund University,https://www.lunduniversity.lu.se/lubas/i-uoh-lu-STAN48
17,Politecnico di Milano,BUSINESS ANALYTICS AND DATA SCIENCE - polimi - Politecnico di Milano,https://www.polimi.it/formazione/formazione-oltre-la-laurea/master-universitari-e-corsi-post-laurea/dettaglio-master/2650
18,Politecnico di Milano,DATA SCIENCE AND BUSINESS ANALYTICS - polimi - Politecnico di Milano,https://www.polimi.it/en/education/specializing-masters-and-postgraduate-programmes/master-detail/3072
19,Politecnico di Milano,DATA SCIENCE AND BUSINESS ANALYTICS - polimi - Politecnico di Milano,https://www.polimi.it/formazione/formazione-oltre-la-laurea/master-universitari-e-corsi-post-laurea/dettaglio-master/3072
20,Politecnico di Milano,Data Science | EIT Digital - polimi.it,https://www.mastereit.polimi.it/data-science/
21,Politecnico di Milano,Master in Business Analytics and Data Science - POLIMI GSoM,https://www.gsom.polimi.it/en/course/master-business-analytics-data-science
22,Politecnico di Milano,Master in Business Analytics and Data Science - POLIMI GSoM,https://www.gsom.polimi.it/course/master-business-analytics-data-science
23,Politecnico di Milano,business analytics and data science - Politecnico di Milano,https://www.polimi.it/en/education/specializing-masters-and-postgraduate-programmes/master-detail/2889
24,Université Paris-Saclay,"M2 Data Science : Health, Insurance and Finance | Université Paris-Saclay",https://www.universite-paris-saclay.fr/en/education/master/mathematics-and-applications/m2-data-science-health-insurance-and-finance
25,Université Paris-Saclay,"M2 Data Science : santé, assurance et finance | Université ...",https://www.universite-paris-saclay.fr/formation/master/mathematiques-et-applications/m2-data-science-sante-assurance-et-finance
26,Université Paris-Saclay,M2 Data Sciences - Université Paris-Saclay,https://www.universite-paris-saclay.fr/en/m2-data-sciences
27,Université Paris-Saclay,Master 2 Data Sciences - Université Paris-Saclay,https://www.imo.universite-paris-saclay.fr/~hans.rugh/notes/JPO/M2+Data+Sciences+-+Web.pdf

In [71]:
priority_countries = [
    "Delft University of Technology",
    "KU Leuven",
    "Lund University",
    "Politecnico di Milano"
]

priority_candidates = batch_3_candidates[
    batch_3_candidates["university"].isin(priority_countries)
][
    ["university", "title", "url"]
].sort_values(
    ["university", "title"]
).reset_index(drop=True)

pd.set_option("display.max_colwidth", None)

priority_candidates

,university,title,url
0,Delft University of Technology,Data Science and Artificial Intelligence Technology - TU Delft,https://www.tudelft.nl/en/education/programmes/masters/dsait/msc-data-science-and-artificial-intelligence-technology/programme
1,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,https://www.tudelft.nl/en/education/programmes/masters/dsait/msc-data-science-and-artificial-intelligence-technology
2,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology - TU Delft,https://www.tudelft.nl/onderwijs/opleidingen/masters/dsait/msc-data-science-and-artificial-intelligence-technology
3,KU Leuven,Business Analytics | KU Leuven,https://onderwijsaanbod.kuleuven.be/syllabi/e/H0Q44AE.htm
4,KU Leuven,Master of Science in Statistics and Data Science — Leuven Statistics ...,https://lstat.kuleuven.be/masterBologna
5,KU Leuven,Master of Statistics and Data Science,https://onderwijsaanbod.kuleuven.be/opleidingen/e/SC_58942261
6,KU Leuven,Master of Statistics and Data Science - KU Leuven,https://onderwijsaanbod.kuleuven.be/opleidingen/e/SC_51016989/diploma_omschrijving
7,KU Leuven,Master of Statistics and Data Science - KU Leuven,https://www.kuleuven.be/programmes/master-statistics-data-science/?mtm_campaign=international-students&mtm_source=keystone&mtm_medium=listing
8,KU Leuven,Master of Statistics and Data Science - KU Leuven,https://onderwijsaanbod.kuleuven.be/opleidingen/e/SC_56139245
9,KU Leuven,Postgraduate Studies in Business Analytics and AI — Faculteit Economie en Bedrijfswetenschappen,https://feb.kuleuven.be/levenslang-leren/bigdataanalytics
10,Lund University,Data Analytics and Business Economics - Magisterprogram - Lu,https://www.lu.se/studera/data-analytics-and-business-economics-magisterprogram-EAGDA
11,Lund University,Data Analytics and Business Economics - Master's Programme | Lund University,https://www.lunduniversity.lu.se/study/data-analytics-and-business-economics-masters-programme-EAGDA
12,Lund University,How to apply | Data Analytics and Business Economics - Master ...,https://www.lunduniversity.lu.se/study/data-analytics-and-business-economics-masters-programme-EAGDA/how-to-apply
13,Lund University,Programme structure | Data Analytics and Business Economics ...,https://www.lunduniversity.lu.se/study/data-analytics-and-business-economics-masters-programme-EAGDA/programme-structure
14,Lund University,Statistics: Programming for Data Science | Lund University,https://www.lunduniversity.lu.se/lubas/i-uoh-lu-STAN48
15,Politecnico di Milano,BUSINESS ANALYTICS AND DATA SCIENCE - polimi - Politecnico di Milano,https://www.polimi.it/formazione/formazione-oltre-la-laurea/master-universitari-e-corsi-post-laurea/dettaglio-master/2650
16,Politecnico di Milano,DATA SCIENCE AND BUSINESS ANALYTICS - polimi - Politecnico di Milano,https://www.polimi.it/en/education/specializing-masters-and-postgraduate-programmes/master-detail/3072
17,Politecnico di Milano,DATA SCIENCE AND BUSINESS ANALYTICS - polimi - Politecnico di Milano,https://www.polimi.it/formazione/formazione-oltre-la-laurea/master-universitari-e-corsi-post-laurea/dettaglio-master/3072
18,Politecnico di Milano,Data Science | EIT Digital - polimi.it,https://www.mastereit.polimi.it/data-science/
19,Politecnico di Milano,Master in Business Analytics and Data Science - POLIMI GSoM,https://www.gsom.polimi.it/en/course/master-business-analytics-data-science
20,Politecnico di Milano,Master in Business Analytics and Data Science - POLIMI GSoM,https://www.gsom.polimi.it/course/master-business-analytics-data-science
21,Politecnico di Milano,business analytics and data science - Politecnico di Milano,https://www.polimi.it/en/education/specializing-masters-and-postgraduate-programmes/master-detail/2889

In [72]:
batch_3_selected = pd.DataFrame([
    {
        "university": "Delft University of Technology",
        "programme_name": "MSc Data Science and Artificial Intelligence Technology",
        "official_domain": "tudelft.nl",
        "decision": "Include"
    },
    {
        "university": "KU Leuven",
        "programme_name": "Master of Statistics and Data Science",
        "official_domain": "kuleuven.be",
        "decision": "Include"
    },
    {
        "university": "Lund University",
        "programme_name": "MSc Data Analytics and Business Economics",
        "official_domain": "lu.se",
        "decision": "Include"
    },
    {
        "university": "Politecnico di Milano",
        "programme_name": "Data Science and Business Analytics",
        "official_domain": "polimi.it",
        "decision": "Include"
    }
])

selected_programmes = pd.concat(
    [selected_programmes, batch_3_selected],
    ignore_index=True
)

selected_programmes

,university,programme_name,official_domain,decision
0,Imperial College London,MSc Business Analytics & AI,imperial.ac.uk,Include
1,ETH Zurich,MSc Data Science,ethz.ch,Include
2,UCL,MSc Business Analytics,ucl.ac.uk,Include
3,UCL,MSc Data Science,ucl.ac.uk,Include
4,Imperial College London,MSc Statistics (Data Science and Machine Learning),imperial.ac.uk,Include
5,University of Oxford,MSc in Social Data Science,ox.ac.uk,Include
6,UCL,MSc Data Science and Public Policy,ucl.ac.uk,Include
7,EPFL,Master in Data Science,epfl.ch,Include
8,Technical University of Munich,MSc Mathematics in Data Science,tum.de,Include
9,King's College London,MSc Data Science,kcl.ac.uk,Include
10,University of Edinburgh,MSc Business Analytics,ed.ac.uk,Include
11,University of Edinburgh,MSc Data Science,ed.ac.uk,Include
12,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,tudelft.nl,Include
13,KU Leuven,Master of Statistics and Data Science,kuleuven.be,Include
14,Lund University,MSc Data Analytics and Business Economics,lu.se,Include
15,Politecnico di Milano,Data Science and Business Analytics,polimi.it,Include

In [73]:
lower_rank_candidates = df[
    (df["QS 2026 Rank"] > 100) &
    (df["QS 2026 Rank"] <= 150)
][
    [
        "QS 2026 Rank",
        "University",
        "Country",
        "official_domain_candidate"
    ]
].copy()

lower_rank_candidates = lower_rank_candidates.sort_values(
    "QS 2026 Rank"
)

lower_rank_candidates

,QS 2026 Rank,University,Country,official_domain_candidate
37,101,University of Copenhagen,Denmark,about.ku.dk
38,103,Utrecht University,Netherlands,uu.nl
39,105,Lomonosov Moscow State University,Russia,archive.government.ru
40,105,RWTH Aachen University,Germany,rwth-aachen.de
41,107,Technical University of Denmark,Denmark,dtu.dk
42,110,Queen Mary University of London (QMUL),United Kingdom,uni-uk.com
43,113,University of St Andrews,United Kingdom,st-andrews.ac.uk
44,114,Aalto University,Finland,aalto.fi
45,116,University of Helsinki,Finland,helsinki.fi
46,118,University College Dublin,Ireland,ucd.ie
47,119,Leiden University,Netherlands,universiteitleiden.nl
48,119,University of Oslo,Norway,uio.no
49,128,Sapienza University of Rome,Italy,uniroma1.it
50,130,Humboldt-Universität zu Berlin,Germany,hu-berlin.de
51,131,Aarhus University,Denmark,international.au.dk
52,132,University of Bath,United Kingdom,bathuniversity.com
53,137,Newcastle University,United Kingdom,ncl.ac.uk
54,138,Alma Mater Studiorum - University of Bologna,Italy,unibo.it
55,140,Eindhoven University of Technology,Netherlands,unilion.eu
56,140,Erasmus University Rotterdam,Netherlands,eur.nl
57,145,Technische Universität Berlin (TU Berlin),Germany,tu.berlin
58,147,Stockholm University,Sweden,su.se
59,147,University of Groningen,Netherlands,rug.nl
60,147,University of Liverpool,United Kingdom,liverpool.ac.uk

In [74]:
target_final_universities = [
    "University of Copenhagen",
    "Utrecht University",
    "RWTH Aachen University",
    "Technical University of Denmark",
    "Aalto University",
    "University of Helsinki"
]

final_6 = df[
    df["University"].isin(target_final_universities)
][
    [
        "QS 2026 Rank",
        "University",
        "Country",
        "official_domain_candidate"
    ]
].copy()

final_6 = final_6.sort_values("QS 2026 Rank")

final_6

,QS 2026 Rank,University,Country,official_domain_candidate
37,101,University of Copenhagen,Denmark,about.ku.dk
38,103,Utrecht University,Netherlands,uu.nl
40,105,RWTH Aachen University,Germany,rwth-aachen.de
41,107,Technical University of Denmark,Denmark,dtu.dk
44,114,Aalto University,Finland,aalto.fi
45,116,University of Helsinki,Finland,helsinki.fi

In [75]:
final_results = []

for _, row in final_6.iterrows():

    university = row["University"]
    domain = row["official_domain_candidate"]

    print(f"\nSearching: {university}")

    for term in SEARCH_TERMS:

        results = search_official_programmes(
            university=university,
            official_domain=domain,
            search_term=term,
            max_results=5
        )

        final_results.extend(results)

        time.sleep(1)

final_df = pd.DataFrame(final_results)

print("\nFinished.")
print("Official results found:", len(final_df))

Searching: University of Copenhagen

Searching: Utrecht University

Searching: RWTH Aachen University
Error: RWTH Aachen University | Business Intelligence | No results found.

Searching: Technical University of Denmark

Searching: Aalto University
Error: Aalto University | Data Science | No results found.
Error: Aalto University | Data Analytics | No results found.
Error: Aalto University | Applied Analytics | No results found.
Error: Aalto University | Applied Data Science | No results found.
Error: Aalto University | Analytics and Data Science | No results found.

Searching: University of Helsinki

Finished.
Official results found: 99

In [76]:
final_unique = (
    final_df
    .drop_duplicates(subset=["url"])
    .copy()
)

print("Before URL deduplication:", len(final_df))
print("After URL deduplication:", len(final_unique))

Before URL deduplication: 99
After URL deduplication: 50

In [77]:
final_candidates = final_unique[
    final_unique["title"].apply(likely_programme_page)
].copy()

print(
    "Likely programme-related pages:",
    len(final_candidates)
)

final_candidates[
    ["university", "title", "url"]
].sort_values(
    ["university", "title"]
).reset_index(drop=True)

Likely programme-related pages: 37

,university,title,url
0,Aalto University,Aalto SCI MS Mathematical Statistics and Data Science,https://math.aalto.fi/en/research/stochastics/
1,Aalto University,Aalto SCI MS Teaching in Statistics and Mathematical Data Science,https://math.aalto.fi/en/research/stochastics/teaching/
2,Aalto University,"Business Analytics, Master of Science (Economics and ... - Aalto",https://www.aalto.fi/en/study-options/business-analytics-master-of-science-economics-and-business-administration
3,Aalto University,"Data Science - ICT Innovation (EIT Digital Master School), Master of Science (Technology) | Aalto University",https://www.aalto.fi/en/study-options/data-science-ict-innovation-eit-digital-master-school-master-of-science-technology
4,Aalto University,"Data Science, Bachelor of Science and Master of Science (Technology) | Aalto University",https://www.aalto.fi/en/study-options/data-science-bachelor-of-science-and-master-of-science-technology
5,Aalto University,Master's Programme in Business Analytics | Aalto University,https://www.aalto.fi/en/programmes/masters-programme-in-business-analytics
6,Aalto University,"Signal Processing and Data Science, Master of Science (Technology) | Aalto University",https://www.aalto.fi/en/study-options/signal-processing-and-data-science-master-of-science-technology
7,RWTH Aachen University,Data Analytics & Decision Science M.Sc. - RWTH Aachen University,https://www.rwth-aachen.de/go/id/puiq/lidx/1
8,RWTH Aachen University,Data Analytics & Decision Science M.Sc. - RWTH Aachen University,https://www.rwth-aachen.de/cms/root/studium/vor-dem-studium/studiengaenge/liste-aktuelle-studiengaenge/studiengangbeschreibung/management-and-engineering-in-technology/~puiq/data-analytics-decision-science-m-sc/
9,RWTH Aachen University,Data Analytics & Decision Science M.Sc. | RWTH Aachen University | EN,https://www.rwth-aachen.de/cms/root/studium/vor-dem-studium/studiengaenge/liste-aktuelle-studiengaenge/studiengangbeschreibung/management-and-engineering-in-technology/~puiq/data-analytics-decision-science-m-sc/?lidx=1
10,RWTH Aachen University,Data Science M.Sc. - RWTH Aachen University | DE,https://www.rwth-aachen.de/cms/root/Studium/Vor-dem-Studium/Studiengaenge/Liste-Aktuelle-Studiengaenge/Studiengangbeschreibung/~pzpc/Data-Science-M-Sc/?mobile=1
11,RWTH Aachen University,Data Science M.Sc. - RWTH Aachen University | DE,https://www.rwth-aachen.de/cms/root/Studium/Vor-dem-Studium/Studiengaenge/Liste-Aktuelle-Studiengaenge/Studiengangbeschreibung/~pzpc/Data-Science-M-Sc/
12,RWTH Aachen University,Data Science M.Sc. - RWTH Aachen University | EN,https://www.rwth-aachen.de/go/id/pzpc/lidx/1?mobile=1
13,RWTH Aachen University,Data Science M.Sc. | RWTH Aachen University | EN,https://www.rwth-aachen.de/cms/root/studium/vor-dem-studium/studiengaenge/liste-aktuelle-studiengaenge/studiengangbeschreibung/~pzpc/data-science-m-sc/?lidx=1
14,RWTH Aachen University,Data Science M.Sc. | RWTH Aachen University | ENM.Sc. Data Analytics and Decision Science | School of ...Master Data Science - RWTH Aachen UniversityRWTH Aachen: all 112 Master's (2026) - MyGermanUniversityMSc Data Analytics and Decision Science (DDS) - International ...,https://www.rwth-aachen.de/go/id/pzpc/lidx/1
15,RWTH Aachen University,M.Sc. Data Analytics and Decision Science (DDS) - RWTH Aachen University,https://www.wiwi.rwth-aachen.de/cms/wirtschaftswissenschaften/studium/internationales/studiengaenge-der-rwth-aachen-business-s/~ruiex/m-sc-data-analytics-and-decision-scienc/?lidx=1
16,RWTH Aachen University,Master Data Science - RWTH Aachen University,https://sc.informatik.rwth-aachen.de/en/studium/master/master-data-science/program-structure/
17,RWTH Aachen University,Master Data Science - RWTH Aachen University,https://sc.informatik.rwth-aachen.de/en/studium/master/master-data-science/application-for-admission/
18,RWTH Aachen University,Master Data Science – Studiencenter Informatik - RWTH Aachen University,https://sc.informatik.rwth-aachen.de/en/studium/master/master-data-science/
19,Technical University of Denmark,Business Analytics - student.dtu.dk,https://student.dtu.dk/en/programme-specifications/master-of-science-in-engineering/business-analytics
20,Technical University of Denmark,Curriculum for Business Analytics - DTU,https://www.dtu.dk/english/education/graduate/msc-programmes/business-analytics/curriculum
21,Technical University of Denmark,Data Science (Big Data) - compute.dtu.dk,https://www.compute.dtu.dk/education/study-programme/data-science-big-data
22,Technical University of Denmark,Data Science - Specialization - DTU,https://www.dtu.dk/english/education/graduate/msc-programmes/human-centered-artificial-intelligence/specialization/data-science
23,Technical University of Denmark,Get a Master's degree in Business Analytics - DTU,https://www.dtu.dk/english/education/graduate/msc-programmes/business-analytics
24,University of Helsinki,Data Science | Master's programme | University of Helsinki,https://www.helsinki.fi/en/degree-programmes/data-science-masters-programme
25,University of Helsinki,Degree programme MH50_010 Master's Programme in Data Science ...,https://studies.helsinki.fi/degree-structure/degree-programme/otm-e2615cc3-e87f-451f-8062-e596c32c0201/MH50_010
26,University of Helsinki,MH50 010 Master's Programme in Data Science - studies.helsinki.fi,https://studies.helsinki.fi/system/files/inline-files/Opetussuunnitelma_29032023_105951_en_0.pdf
27,University of Helsinki,MSc PROGRAMME in DATA SCIENCE - studies.helsinki.fi,https://studies.helsinki.fi/api/courses/cur/file/pub/system/files/attachments/2022-08/Welcome-to-Data-science-MSc-Prg-2022.pdf?hmac=7d744b5f7f298baa7adacc1258245782ef9bbef1e4ed598a26f00ef05da5cd24
28,University of Helsinki,Studying | Data Science | Master's programme | University of Helsinki,https://www.helsinki.fi/en/degree-programmes/data-science-masters-programme/studying
29,Utrecht University,Applied Data Science - Students UU,https://students.uu.nl/en/science/applied-data-science
30,Utrecht University,Applied Data Science - Utrecht University,https://www.uu.nl/en/masters/applied-data-science
31,Utrecht University,Applied Data Science - Utrecht University,https://www.uu.nl/en/research/applied-data-science
32,Utrecht University,Curriculum - Applied Data Science - Students UU,https://students.uu.nl/en/science/applied-data-science/my-studies/curriculum
33,Utrecht University,Data Science - Students UU,https://students.uu.nl/en/science/data-science
34,Utrecht University,Data Science - Utrecht University,https://www.uu.nl/en/masters/data-science
35,Utrecht University,"Methodology, Statistics and Data Science - Utrecht University",https://www.uu.nl/en/masters/methodology-statistics-and-data-science
36,Utrecht University,Study programme - Applied Data Science - Utrecht University,https://www.uu.nl/en/masters/applied-data-science/study-programme

In [78]:
final_4_selected = pd.DataFrame([
    {
        "university": "Utrecht University",
        "programme_name": "MSc Data Science",
        "official_domain": "uu.nl",
        "decision": "Include"
    },
    {
        "university": "RWTH Aachen University",
        "programme_name": "MSc Data Science",
        "official_domain": "rwth-aachen.de",
        "decision": "Include"
    },
    {
        "university": "Technical University of Denmark",
        "programme_name": "MSc Business Analytics",
        "official_domain": "dtu.dk",
        "decision": "Include"
    },
    {
        "university": "Aalto University",
        "programme_name": "Master's Programme in Business Analytics",
        "official_domain": "aalto.fi",
        "decision": "Include"
    }
])

selected_programmes = pd.concat(
    [selected_programmes, final_4_selected],
    ignore_index=True
)

selected_programmes

,university,programme_name,official_domain,decision
0,Imperial College London,MSc Business Analytics & AI,imperial.ac.uk,Include
1,ETH Zurich,MSc Data Science,ethz.ch,Include
2,UCL,MSc Business Analytics,ucl.ac.uk,Include
3,UCL,MSc Data Science,ucl.ac.uk,Include
4,Imperial College London,MSc Statistics (Data Science and Machine Learning),imperial.ac.uk,Include
5,University of Oxford,MSc in Social Data Science,ox.ac.uk,Include
6,UCL,MSc Data Science and Public Policy,ucl.ac.uk,Include
7,EPFL,Master in Data Science,epfl.ch,Include
8,Technical University of Munich,MSc Mathematics in Data Science,tum.de,Include
9,King's College London,MSc Data Science,kcl.ac.uk,Include
10,University of Edinburgh,MSc Business Analytics,ed.ac.uk,Include
11,University of Edinburgh,MSc Data Science,ed.ac.uk,Include
12,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,tudelft.nl,Include
13,KU Leuven,Master of Statistics and Data Science,kuleuven.be,Include
14,Lund University,MSc Data Analytics and Business Economics,lu.se,Include
15,Politecnico di Milano,Data Science and Business Analytics,polimi.it,Include
16,Utrecht University,MSc Data Science,uu.nl,Include
17,RWTH Aachen University,MSc Data Science,rwth-aachen.de,Include
18,Technical University of Denmark,MSc Business Analytics,dtu.dk,Include
19,Aalto University,Master's Programme in Business Analytics,aalto.fi,Include

In [79]:
print("Final number of programmes:", len(selected_programmes))

selected_programmes

Final number of programmes: 20

,university,programme_name,official_domain,decision
0,Imperial College London,MSc Business Analytics & AI,imperial.ac.uk,Include
1,ETH Zurich,MSc Data Science,ethz.ch,Include
2,UCL,MSc Business Analytics,ucl.ac.uk,Include
3,UCL,MSc Data Science,ucl.ac.uk,Include
4,Imperial College London,MSc Statistics (Data Science and Machine Learning),imperial.ac.uk,Include
5,University of Oxford,MSc in Social Data Science,ox.ac.uk,Include
6,UCL,MSc Data Science and Public Policy,ucl.ac.uk,Include
7,EPFL,Master in Data Science,epfl.ch,Include
8,Technical University of Munich,MSc Mathematics in Data Science,tum.de,Include
9,King's College London,MSc Data Science,kcl.ac.uk,Include
10,University of Edinburgh,MSc Business Analytics,ed.ac.uk,Include
11,University of Edinburgh,MSc Data Science,ed.ac.uk,Include
12,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,tudelft.nl,Include
13,KU Leuven,Master of Statistics and Data Science,kuleuven.be,Include
14,Lund University,MSc Data Analytics and Business Economics,lu.se,Include
15,Politecnico di Milano,Data Science and Business Analytics,polimi.it,Include
16,Utrecht University,MSc Data Science,uu.nl,Include
17,RWTH Aachen University,MSc Data Science,rwth-aachen.de,Include
18,Technical University of Denmark,MSc Business Analytics,dtu.dk,Include
19,Aalto University,Master's Programme in Business Analytics,aalto.fi,Include

In [80]:
programme_master = selected_programmes.merge(
    df[
        [
            "University",
            "Country",
            "QS 2026 Rank"
        ]
    ],
    left_on="university",
    right_on="University",
    how="left"
)

programme_master = programme_master.drop(
    columns=["University"]
)

programme_master

,university,programme_name,official_domain,decision,Country,QS 2026 Rank
0,Imperial College London,MSc Business Analytics & AI,imperial.ac.uk,Include,United Kingdom,2.0
1,ETH Zurich,MSc Data Science,ethz.ch,Include,Switzerland,7.0
2,UCL,MSc Business Analytics,ucl.ac.uk,Include,United Kingdom,9.0
3,UCL,MSc Data Science,ucl.ac.uk,Include,United Kingdom,9.0
4,Imperial College London,MSc Statistics (Data Science and Machine Learning),imperial.ac.uk,Include,United Kingdom,2.0
5,University of Oxford,MSc in Social Data Science,ox.ac.uk,Include,United Kingdom,4.0
6,UCL,MSc Data Science and Public Policy,ucl.ac.uk,Include,United Kingdom,9.0
7,EPFL,Master in Data Science,epfl.ch,Include,NaN,NaN
8,Technical University of Munich,MSc Mathematics in Data Science,tum.de,Include,Germany,22.0
9,King's College London,MSc Data Science,kcl.ac.uk,Include,United Kingdom,31.0
10,University of Edinburgh,MSc Business Analytics,ed.ac.uk,Include,United Kingdom,34.0
11,University of Edinburgh,MSc Data Science,ed.ac.uk,Include,United Kingdom,34.0
12,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,tudelft.nl,Include,Netherlands,47.0
13,KU Leuven,Master of Statistics and Data Science,kuleuven.be,Include,Belgium,60.0
14,Lund University,MSc Data Analytics and Business Economics,lu.se,Include,Sweden,72.0
15,Politecnico di Milano,Data Science and Business Analytics,polimi.it,Include,Italy,98.0
16,Utrecht University,MSc Data Science,uu.nl,Include,Netherlands,103.0
17,RWTH Aachen University,MSc Data Science,rwth-aachen.de,Include,Germany,105.0
18,Technical University of Denmark,MSc Business Analytics,dtu.dk,Include,Denmark,107.0
19,Aalto University,Master's Programme in Business Analytics,aalto.fi,Include,Finland,114.0

In [81]:
programme_master[
    [
        "university",
        "programme_name",
        "Country",
        "QS 2026 Rank"
    ]
]

,university,programme_name,Country,QS 2026 Rank
0,Imperial College London,MSc Business Analytics & AI,United Kingdom,2.0
1,ETH Zurich,MSc Data Science,Switzerland,7.0
2,UCL,MSc Business Analytics,United Kingdom,9.0
3,UCL,MSc Data Science,United Kingdom,9.0
4,Imperial College London,MSc Statistics (Data Science and Machine Learning),United Kingdom,2.0
5,University of Oxford,MSc in Social Data Science,United Kingdom,4.0
6,UCL,MSc Data Science and Public Policy,United Kingdom,9.0
7,EPFL,Master in Data Science,NaN,NaN
8,Technical University of Munich,MSc Mathematics in Data Science,Germany,22.0
9,King's College London,MSc Data Science,United Kingdom,31.0
10,University of Edinburgh,MSc Business Analytics,United Kingdom,34.0
11,University of Edinburgh,MSc Data Science,United Kingdom,34.0
12,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,Netherlands,47.0
13,KU Leuven,Master of Statistics and Data Science,Belgium,60.0
14,Lund University,MSc Data Analytics and Business Economics,Sweden,72.0
15,Politecnico di Milano,Data Science and Business Analytics,Italy,98.0
16,Utrecht University,MSc Data Science,Netherlands,103.0
17,RWTH Aachen University,MSc Data Science,Germany,105.0
18,Technical University of Denmark,MSc Business Analytics,Denmark,107.0
19,Aalto University,Master's Programme in Business Analytics,Finland,114.0

In [82]:
df[
    df["University"]
    .str.contains("EPFL|Lausanne", case=False, na=False)
][
    ["QS 2026 Rank", "University", "Country"]
]

   QS 2026 Rank                                       University      Country
5            22  EPFL – École polytechnique fédérale de Lausanne  Switzerland

In [83]:
programme_master.loc[
    programme_master["university"] == "EPFL",
    ["Country", "QS 2026 Rank"]
] = ["Switzerland", 22]

In [84]:
programme_master[
    ["university", "programme_name", "Country", "QS 2026 Rank"]
].isna().sum()

university        0
programme_name    0
Country           0
QS 2026 Rank      0
dtype: int64

In [85]:
programme_master["QS 2026 Rank"] = (
    programme_master["QS 2026 Rank"].astype(int)
)

programme_master[
    ["university", "programme_name", "Country", "QS 2026 Rank"]
]

,university,programme_name,Country,QS 2026 Rank
0,Imperial College London,MSc Business Analytics & AI,United Kingdom,2
1,ETH Zurich,MSc Data Science,Switzerland,7
2,UCL,MSc Business Analytics,United Kingdom,9
3,UCL,MSc Data Science,United Kingdom,9
4,Imperial College London,MSc Statistics (Data Science and Machine Learning),United Kingdom,2
5,University of Oxford,MSc in Social Data Science,United Kingdom,4
6,UCL,MSc Data Science and Public Policy,United Kingdom,9
7,EPFL,Master in Data Science,Switzerland,22
8,Technical University of Munich,MSc Mathematics in Data Science,Germany,22
9,King's College London,MSc Data Science,United Kingdom,31
10,University of Edinburgh,MSc Business Analytics,United Kingdom,34
11,University of Edinburgh,MSc Data Science,United Kingdom,34
12,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,Netherlands,47
13,KU Leuven,Master of Statistics and Data Science,Belgium,60
14,Lund University,MSc Data Analytics and Business Economics,Sweden,72
15,Politecnico di Milano,Data Science and Business Analytics,Italy,98
16,Utrecht University,MSc Data Science,Netherlands,103
17,RWTH Aachen University,MSc Data Science,Germany,105
18,Technical University of Denmark,MSc Business Analytics,Denmark,107
19,Aalto University,Master's Programme in Business Analytics,Finland,114

In [86]:
programme_master = programme_master.reset_index(drop=True)

programme_master["programme_id"] = [
    f"EU_{i:02d}"
    for i in range(1, len(programme_master) + 1)
]

programme_master[
    [
        "programme_id",
        "university",
        "programme_name",
        "Country",
        "QS 2026 Rank"
    ]
]

,programme_id,university,programme_name,Country,QS 2026 Rank
0,EU_01,Imperial College London,MSc Business Analytics & AI,United Kingdom,2
1,EU_02,ETH Zurich,MSc Data Science,Switzerland,7
2,EU_03,UCL,MSc Business Analytics,United Kingdom,9
3,EU_04,UCL,MSc Data Science,United Kingdom,9
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),United Kingdom,2
5,EU_06,University of Oxford,MSc in Social Data Science,United Kingdom,4
6,EU_07,UCL,MSc Data Science and Public Policy,United Kingdom,9
7,EU_08,EPFL,Master in Data Science,Switzerland,22
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,Germany,22
9,EU_10,King's College London,MSc Data Science,United Kingdom,31
10,EU_11,University of Edinburgh,MSc Business Analytics,United Kingdom,34
11,EU_12,University of Edinburgh,MSc Data Science,United Kingdom,34
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,Netherlands,47
13,EU_14,KU Leuven,Master of Statistics and Data Science,Belgium,60
14,EU_15,Lund University,MSc Data Analytics and Business Economics,Sweden,72
15,EU_16,Politecnico di Milano,Data Science and Business Analytics,Italy,98
16,EU_17,Utrecht University,MSc Data Science,Netherlands,103
17,EU_18,RWTH Aachen University,MSc Data Science,Germany,105
18,EU_19,Technical University of Denmark,MSc Business Analytics,Denmark,107
19,EU_20,Aalto University,Master's Programme in Business Analytics,Finland,114

In [87]:
programme_master["official_url"] = ""
programme_master["screening_status"] = "Included"
programme_master["verified_date"] = "2026-09-23"

programme_master = programme_master[
    [
        "programme_id",
        "university",
        "programme_name",
        "Country",
        "QS 2026 Rank",
        "official_domain",
        "official_url",
        "screening_status",
        "verified_date"
    ]
]

programme_master

,programme_id,university,programme_name,Country,QS 2026 Rank,official_domain,official_url,screening_status,verified_date
0,EU_01,Imperial College London,MSc Business Analytics & AI,United Kingdom,2,imperial.ac.uk,,Included,2026-09-23
1,EU_02,ETH Zurich,MSc Data Science,Switzerland,7,ethz.ch,,Included,2026-09-23
2,EU_03,UCL,MSc Business Analytics,United Kingdom,9,ucl.ac.uk,,Included,2026-09-23
3,EU_04,UCL,MSc Data Science,United Kingdom,9,ucl.ac.uk,,Included,2026-09-23
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),United Kingdom,2,imperial.ac.uk,,Included,2026-09-23
5,EU_06,University of Oxford,MSc in Social Data Science,United Kingdom,4,ox.ac.uk,,Included,2026-09-23
6,EU_07,UCL,MSc Data Science and Public Policy,United Kingdom,9,ucl.ac.uk,,Included,2026-09-23
7,EU_08,EPFL,Master in Data Science,Switzerland,22,epfl.ch,,Included,2026-09-23
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,Germany,22,tum.de,,Included,2026-09-23
9,EU_10,King's College London,MSc Data Science,United Kingdom,31,kcl.ac.uk,,Included,2026-09-23
10,EU_11,University of Edinburgh,MSc Business Analytics,United Kingdom,34,ed.ac.uk,,Included,2026-09-23
11,EU_12,University of Edinburgh,MSc Data Science,United Kingdom,34,ed.ac.uk,,Included,2026-09-23
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,Netherlands,47,tudelft.nl,,Included,2026-09-23
13,EU_14,KU Leuven,Master of Statistics and Data Science,Belgium,60,kuleuven.be,,Included,2026-09-23
14,EU_15,Lund University,MSc Data Analytics and Business Economics,Sweden,72,lu.se,,Included,2026-09-23
15,EU_16,Politecnico di Milano,Data Science and Business Analytics,Italy,98,polimi.it,,Included,2026-09-23
16,EU_17,Utrecht University,MSc Data Science,Netherlands,103,uu.nl,,Included,2026-09-23
17,EU_18,RWTH Aachen University,MSc Data Science,Germany,105,rwth-aachen.de,,Included,2026-09-23
18,EU_19,Technical University of Denmark,MSc Business Analytics,Denmark,107,dtu.dk,,Included,2026-09-23
19,EU_20,Aalto University,Master's Programme in Business Analytics,Finland,114,aalto.fi,,Included,2026-09-23

In [88]:
programme_master.to_csv(
    "../data/europe_final_programme_sample.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Saved: ../data/europe_final_programme_sample.csv")
print("Programmes:", len(programme_master))

Saved: ../data/europe_final_programme_sample.csv
Programmes: 20

In [89]:
[x for x in [
    "first_5_df",
    "batch_2_df",
    "batch_3_df",
    "final_df"
] if x in globals()]

['batch_3_df', 'final_df']

In [90]:
search_df_names = [
    "first_5_df",
    "batch_2_df",
    "batch_3_df",
    "final_df"
]

available_search_dfs = [
    globals()[name]
    for name in search_df_names
    if name in globals()
]

all_search_results = pd.concat(
    available_search_dfs,
    ignore_index=True
)

all_search_results = (
    all_search_results
    .drop_duplicates(subset=["url"])
    .reset_index(drop=True)
)

print("Search result tables found:", len(available_search_dfs))
print("Unique official URLs:", len(all_search_results))

Search result tables found: 2
Unique official URLs: 97

In [91]:
def programme_url_candidates(university, programme_name, top_n=5):

    temp = all_search_results[
        all_search_results["university"] == university
    ].copy()

    if temp.empty:
        return temp

    programme_words = [
        word.lower()
        for word in programme_name
        .replace("(", " ")
        .replace(")", " ")
        .replace("&", " ")
        .split()
        if len(word) > 3
        and word.lower() not in [
            "master",
            "masters",
            "programme",
            "science"
        ]
    ]

    def score_title(title):
        title = str(title).lower()
        return sum(
            word in title
            for word in programme_words
        )

    temp["match_score"] = (
        temp["title"]
        .apply(score_title)
    )

    return (
        temp
        .sort_values(
            ["match_score", "result_rank"],
            ascending=[False, True]
        )
        .head(top_n)
    )

In [93]:
candidate_tables = []

for _, row in programme_master.iterrows():

    candidates = programme_url_candidates(
        row["university"],
        row["programme_name"],
        top_n=5
    )

    if not candidates.empty:

        candidates = candidates.copy()

        candidates["programme_id"] = row["programme_id"]
        candidates["programme_name"] = row["programme_name"]

        candidate_tables.append(
            candidates[
                [
                    "programme_id",
                    "university",
                    "programme_name",
                    "title",
                    "url",
                    "match_score"
                ]
            ]
        )

url_review = pd.concat(
    candidate_tables,
    ignore_index=True
)

url_review

,programme_id,university,programme_name,title,url,match_score
0,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,MSc Data Science and Artificial Intelligence Technology,https://www.tudelft.nl/en/education/programmes/masters/dsait/msc-data-science-and-artificial-intelligence-technology,4
1,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,MSc Data Science and Artificial Intelligence Technology - TU Delft,https://www.tudelft.nl/onderwijs/opleidingen/masters/dsait/msc-data-science-and-artificial-intelligence-technology,4
2,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,Data Science and Artificial Intelligence Technology - TU Delft,https://www.tudelft.nl/en/education/programmes/masters/dsait/msc-data-science-and-artificial-intelligence-technology/programme,4
3,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,Master programmes - TU Delft,https://www.tudelft.nl/en/education/programmes/masters/,0
4,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,Master programmes - TU Delft,https://www.tudelft.nl/en/faculty-of-applied-sciences/education/master-programmes/,0
5,EU_14,KU Leuven,Master of Statistics and Data Science,Master of Statistics and Data Science - KU Leuven,https://onderwijsaanbod.kuleuven.be/opleidingen/e/SC_51016989/diploma_omschrijving,2
6,EU_14,KU Leuven,Master of Statistics and Data Science,Master of Science in Statistics and Data Science — Leuven Statistics ...,https://lstat.kuleuven.be/masterBologna,2
7,EU_14,KU Leuven,Master of Statistics and Data Science,Master of Statistics and Data Science - KU Leuven,https://www.kuleuven.be/programmes/master-statistics-data-science/?mtm_campaign=international-students&mtm_source=keystone&mtm_medium=listing,2
8,EU_14,KU Leuven,Master of Statistics and Data Science,Master of Statistics and Data Science - KU Leuven,https://onderwijsaanbod.kuleuven.be/opleidingen/e/SC_56139245,2
9,EU_14,KU Leuven,Master of Statistics and Data Science,Master of Statistics and Data Science,https://onderwijsaanbod.kuleuven.be/opleidingen/e/SC_58942261,2
10,EU_15,Lund University,MSc Data Analytics and Business Economics,How to apply | Data Analytics and Business Economics - Master ...,https://www.lunduniversity.lu.se/study/data-analytics-and-business-economics-masters-programme-EAGDA/how-to-apply,4
11,EU_15,Lund University,MSc Data Analytics and Business Economics,Programme structure | Data Analytics and Business Economics ...,https://www.lunduniversity.lu.se/study/data-analytics-and-business-economics-masters-programme-EAGDA/programme-structure,4
12,EU_15,Lund University,MSc Data Analytics and Business Economics,Data Analytics and Business Economics - Magisterprogram - Lu,https://www.lu.se/studera/data-analytics-and-business-economics-magisterprogram-EAGDA,4
13,EU_15,Lund University,MSc Data Analytics and Business Economics,Data Analytics and Business Economics - Master's Programme | Lund University,https://www.lunduniversity.lu.se/study/data-analytics-and-business-economics-masters-programme-EAGDA,4
14,EU_15,Lund University,MSc Data Analytics and Business Economics,Social Scientific Data Analysis - Master of Science programme | Lund University,https://www.lunduniversity.lu.se/lubas/i-uoh-lu-SASDA,1
15,EU_16,Politecnico di Milano,Data Science and Business Analytics,DATA SCIENCE AND BUSINESS ANALYTICS - polimi - Politecnico di Milano,https://www.polimi.it/en/education/specializing-masters-and-postgraduate-programmes/master-detail/3072,3
16,EU_16,Politecnico di Milano,Data Science and Business Analytics,business analytics and data science - Politecnico di Milano,https://www.polimi.it/en/education/specializing-masters-and-postgraduate-programmes/master-detail/2889,3
17,EU_16,Politecnico di Milano,Data Science and Business Analytics,BUSINESS ANALYTICS AND DATA SCIENCE - polimi - Politecnico di Milano,https://www.polimi.it/formazione/formazione-oltre-la-laurea/master-universitari-e-corsi-post-laurea/dettaglio-master/2650,3
18,EU_16,Politecnico di Milano,Data Science and Business Analytics,DATA SCIENCE AND BUSINESS ANALYTICS - polimi - Politecnico di Milano,https://www.polimi.it/formazione/formazione-oltre-la-laurea/master-universitari-e-corsi-post-laurea/dettaglio-master/3072,3
19,EU_16,Politecnico di Milano,Data Science and Business Analytics,Master in Business Analytics and Data Science - POLIMI GSoM,https://www.gsom.polimi.it/en/course/master-business-analytics-data-science,3
20,EU_17,Utrecht University,MSc Data Science,Data Science - Utrecht University,https://www.uu.nl/en/masters/data-science,1
21,EU_17,Utrecht University,MSc Data Science,Study programme - Applied Data Science - Utrecht University,https://www.uu.nl/en/masters/applied-data-science/study-programme,1
22,EU_17,Utrecht University,MSc Data Science,Applied Data Science - Utrecht University,https://www.uu.nl/en/masters/applied-data-science,1
23,EU_17,Utrecht University,MSc Data Science,"Methodology, Statistics and Data Science - Utrecht University",https://www.uu.nl/en/masters/methodology-statistics-and-data-science,1
24,EU_17,Utrecht University,MSc Data Science,Applied Data Science - Students UU,https://students.uu.nl/en/science/applied-data-science,1
25,EU_18,RWTH Aachen University,MSc Data Science,Data Science M.Sc. - RWTH Aachen University | EN,https://www.rwth-aachen.de/go/id/pzpc/lidx/1?mobile=1,1
26,EU_18,RWTH Aachen University,MSc Data Science,Master Data Science – Studiencenter Informatik - RWTH Aachen University,https://sc.informatik.rwth-aachen.de/en/studium/master/master-data-science/,1
27,EU_18,RWTH Aachen University,MSc Data Science,Data Analytics & Decision Science M.Sc. | RWTH Aachen University | EN,https://www.rwth-aachen.de/cms/root/studium/vor-dem-studium/studiengaenge/liste-aktuelle-studiengaenge/studiengangbeschreibung/management-and-engineering-in-technology/~puiq/data-analytics-decision-science-m-sc/?lidx=1,1
28,EU_18,RWTH Aachen University,MSc Data Science,Data Science M.Sc. | RWTH Aachen University | ENM.Sc. Data Analytics and Decision Science | School of ...Master Data Science - RWTH Aachen UniversityRWTH Aachen: all 112 Master's (2026) - MyGermanUniversityMSc Data Analytics and Decision Science (DDS) - International ...,https://www.rwth-aachen.de/go/id/pzpc/lidx/1,1
29,EU_18,RWTH Aachen University,MSc Data Science,M.Sc. Data Analytics and Decision Science (DDS) - RWTH Aachen University,https://www.wiwi.rwth-aachen.de/cms/wirtschaftswissenschaften/studium/internationales/studiengaenge-der-rwth-aachen-business-s/~ruiex/m-sc-data-analytics-and-decision-scienc/?lidx=1,1
30,EU_19,Technical University of Denmark,MSc Business Analytics,Get a Master's degree in Business Analytics - DTU,https://www.dtu.dk/english/education/graduate/msc-programmes/business-analytics,2
31,EU_19,Technical University of Denmark,MSc Business Analytics,Curriculum for Business Analytics - DTU,https://www.dtu.dk/english/education/graduate/msc-programmes/business-analytics/curriculum,2
32,EU_19,Technical University of Denmark,MSc Business Analytics,Business Analytics - student.dtu.dk,https://student.dtu.dk/en/programme-specifications/master-of-science-in-engineering/business-analytics,2
33,EU_19,Technical University of Denmark,MSc Business Analytics,Get your Master's at DTU,https://www.dtu.dk/english/education/graduate/msc-programmes,0
34,EU_19,Technical University of Denmark,MSc Business Analytics,Data Science - Specialization - DTU,https://www.dtu.dk/english/education/graduate/msc-programmes/human-centered-artificial-intelligence/specialization/data-science,0
35,EU_20,Aalto University,Master's Programme in Business Analytics,Master's Programme in Business Analytics | Aalto University,https://www.aalto.fi/en/programmes/masters-programme-in-business-analytics,3
36,EU_20,Aalto University,Master's Programme in Business Analytics,"Business Analytics, Master of Science (Economics and ... - Aalto",https://www.aalto.fi/en/study-options/business-analytics-master-of-science-economics-and-business-administration,2
37,EU_20,Aalto University,Master's Programme in Business Analytics,Aalto SCI MS Mathematical Statistics and Data Science,https://math.aalto.fi/en/research/stochastics/,0
38,EU_20,Aalto University,Master's Programme in Business Analytics,"Data Science, Bachelor of Science and Master of Science (Technology) | Aalto University",https://www.aalto.fi/en/study-options/data-science-bachelor-of-science-and-master-of-science-technology,0
39,EU_20,Aalto University,Master's Programme in Business Analytics,Aalto SCI MS Teaching in Statistics and Mathematical Data Science,https://math.aalto.fi/en/research/stochastics/teaching/,0

In [94]:
found_ids = set(url_review["programme_id"].unique())
all_ids = set(programme_master["programme_id"])

missing_ids = sorted(all_ids - found_ids)

print("Programme IDs with URL candidates:", sorted(found_ids))
print("Missing programme IDs:", missing_ids)
print("Number found:", len(found_ids))
print("Number missing:", len(missing_ids))

Programme IDs with URL candidates: ['EU_13', 'EU_14', 'EU_15', 'EU_16', 'EU_17', 'EU_18', 'EU_19', 'EU_20']
Missing programme IDs: ['EU_01', 'EU_02', 'EU_03', 'EU_04', 'EU_05', 'EU_06', 'EU_07', 'EU_08', 'EU_09', 'EU_10', 'EU_11', 'EU_12']
Number found: 8
Number missing: 12

In [95]:
missing_programmes = programme_master[
    programme_master["programme_id"].isin(missing_ids)
].copy()

missing_programmes[
    [
        "programme_id",
        "university",
        "programme_name",
        "official_domain"
    ]
]

,programme_id,university,programme_name,official_domain
0,EU_01,Imperial College London,MSc Business Analytics & AI,imperial.ac.uk
1,EU_02,ETH Zurich,MSc Data Science,ethz.ch
2,EU_03,UCL,MSc Business Analytics,ucl.ac.uk
3,EU_04,UCL,MSc Data Science,ucl.ac.uk
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),imperial.ac.uk
5,EU_06,University of Oxford,MSc in Social Data Science,ox.ac.uk
6,EU_07,UCL,MSc Data Science and Public Policy,ucl.ac.uk
7,EU_08,EPFL,Master in Data Science,epfl.ch
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,tum.de
9,EU_10,King's College London,MSc Data Science,kcl.ac.uk
10,EU_11,University of Edinburgh,MSc Business Analytics,ed.ac.uk
11,EU_12,University of Edinburgh,MSc Data Science,ed.ac.uk

In [96]:
missing_search_results = []

for _, row in missing_programmes.iterrows():

    programme_id = row["programme_id"]
    university = row["university"]
    programme_name = row["programme_name"]
    domain = row["official_domain"]

    print(f"Searching: {programme_id} | {university} | {programme_name}")

    results = search_official_programmes(
        university=university,
        official_domain=domain,
        search_term=programme_name,
        max_results=5
    )

    for result in results:
        result["programme_id"] = programme_id
        result["programme_name"] = programme_name

    missing_search_results.extend(results)

    time.sleep(1)

missing_url_review = pd.DataFrame(missing_search_results)

print("\nFinished.")
print("Results:", len(missing_url_review))

Searching: EU_01 | Imperial College London | MSc Business Analytics & AI
Searching: EU_02 | ETH Zurich | MSc Data Science
Searching: EU_03 | UCL | MSc Business Analytics
Searching: EU_04 | UCL | MSc Data Science
Error: UCL | MSc Data Science | No results found.
Searching: EU_05 | Imperial College London | MSc Statistics (Data Science and Machine Learning)
Searching: EU_06 | University of Oxford | MSc in Social Data Science
Error: University of Oxford | MSc in Social Data Science | No results found.
Searching: EU_07 | UCL | MSc Data Science and Public Policy
Searching: EU_08 | EPFL | Master in Data Science
Searching: EU_09 | Technical University of Munich | MSc Mathematics in Data Science
Searching: EU_10 | King's College London | MSc Data Science
Error: King's College London | MSc Data Science | No results found.
Searching: EU_11 | University of Edinburgh | MSc Business Analytics
Searching: EU_12 | University of Edinburgh | MSc Data Science

Finished.
Results: 25

In [98]:
missing_url_review[
    [
        "programme_id",
        "university",
        "programme_name",
        "title",
        "url",
        "result_rank"
    ]
].sort_values(
    ["programme_id", "result_rank"]
).reset_index(drop=True)

,programme_id,university,programme_name,title,url,result_rank
0,EU_01,Imperial College London,MSc Business Analytics & AI,MSc Business Analytics & AI - Imperial College London,https://www.imperial.ac.uk/business-school/masters/business-analytics/,1
1,EU_01,Imperial College London,MSc Business Analytics & AI,Business Analytics and AI MSc | Study | Imperial College London,https://www.imperial.ac.uk/study/courses/postgraduate-taught/business-analytics/,2
2,EU_02,ETH Zurich,MSc Data Science,Master Data Science | ETH Zurich,https://ethz.ch/en/studies/master/degree-programmes/engineering-sciences/data-science.html,1
3,EU_02,ETH Zurich,MSc Data Science,Data Science MSc | ETH Zurich,https://ethz.ch/en/studies/master/application/master-datascience.html,2
4,EU_02,ETH Zurich,MSc Data Science,Master in Data Science – Department of Computer Science | ETH ...,https://inf.ethz.ch/studies/master/master-ds.html,3
5,EU_02,ETH Zurich,MSc Data Science,Master's in Data Science – Department of Mathematics | ETH Zurich,https://math.ethz.ch/studies/master-programmes/master-data-science.html,4
6,EU_03,UCL,MSc Business Analytics,Business Analytics MSc | Prospective Students Graduate - UCL,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/business-analytics-msc-2026,1
7,EU_03,UCL,MSc Business Analytics,Business Analytics MSc | Study at UCL,https://www.ucl.ac.uk/study/prospective-students/graduate/courses/business-analytics-msc,2
8,EU_03,UCL,MSc Business Analytics,"MSc Business Analytics | UCL School of ManagementPostgraduate Study | UCL School of ManagementMSc Business Analytics at UCL (University College London ...MSc Business Analytics — UCL School Of Management — Access ...UCL Business Analytics MSc: Salary, Fees & ROI 2026",https://www.mgmt.ucl.ac.uk/business-analytics,3
9,EU_03,UCL,MSc Business Analytics,Postgraduate Study | UCL School of Management,https://www.mgmt.ucl.ac.uk/postgraduate-study,4
10,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),Statistics (Data Science and Machine Learning) MSc | Study | Imperial College London,https://www.imperial.ac.uk/study/courses/postgraduate-taught/statistics-data-science/,1
11,EU_07,UCL,MSc Data Science and Public Policy,Data Science and Public Policy (Political Science) MSc - UCL,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-and-public-policy-political-science-msc,1
12,EU_07,UCL,MSc Data Science and Public Policy,Data Science and Public Policy MSc - UCL,https://www.ucl.ac.uk/social-historical-sciences/economics/study/data-science-and-public-policy-msc,2
13,EU_08,EPFL,Master in Data Science,Data Science ‒ Master ‐ EPFL,https://www.epfl.ch/education/master/programs/data-science/,1
14,EU_08,EPFL,Master in Data Science,Master in Data Science ‒ IC ‐ EPFL,https://www.epfl.ch/schools/ic/education/master/data-science/,2
15,EU_08,EPFL,Master in Data Science,Master Cycle - Data Science - EPFL,https://edu.epfl.ch/studyplan/en/master/data-science/,3
16,EU_08,EPFL,Master in Data Science,Cycle Master - Data Science - EPFL,https://edu.epfl.ch/studyplan/fr/master/data-science/,4
17,EU_09,Technical University of Munich,MSc Mathematics in Data Science,Mathematics in Data Science - Master of Science (M.Sc.) - TUM,https://www.tum.de/en/studies/degree-programs/detail/mathematics-in-data-science-master-of-science-msc,1
18,EU_09,Technical University of Munich,MSc Mathematics in Data Science,Master Mathematics in Data Science - TUM - TUM School of ...,https://www.cit.tum.de/en/cit/studies/degree-programs/master-mathematics-data-science/,2
19,EU_09,Technical University of Munich,MSc Mathematics in Data Science,Mathematics in Data Science - Master of Science (M.Sc.) - TUM,https://www.tum.de/studium/studienangebot/detail/mathematics-in-data-science-master-of-science-msc/,3
20,EU_09,Technical University of Munich,MSc Mathematics in Data Science,Master Mathematics in Data Science - TUM - TUM School of ...,https://www.cit.tum.de/cit/studium/studiengaenge/master-mathematics-data-science/,5
21,EU_11,University of Edinburgh,MSc Business Analytics,MSc Business Analytics - University of Edinburgh Business School,https://www.business-school.ed.ac.uk/msc/business-analytics,1
22,EU_11,University of Edinburgh,MSc Business Analytics,Business Analytics MSc - Postgraduate taught programmes | The University of Edinburgh,https://study.ed.ac.uk/programmes/postgraduate-taught/929-business-analytics,4
23,EU_12,University of Edinburgh,MSc Data Science,Data Science MSc - Postgraduate taught programmes | The University of Edinburgh,https://study.ed.ac.uk/programmes/postgraduate-taught/902-data-science,1
24,EU_12,University of Edinburgh,MSc Data Science,Statistics with Data Science MSc - Postgraduate taught programmes | The University of Edinburgh,https://study.ed.ac.uk/programmes/postgraduate-taught/916-statistics-with-data-science,2

In [99]:
all_url_candidates = pd.concat(
    [
        url_review,
        missing_url_review
    ],
    ignore_index=True
)

all_url_candidates = (
    all_url_candidates
    .drop_duplicates(
        subset=["programme_id", "url"]
    )
    .reset_index(drop=True)
)

print(
    "Programmes with URL candidates:",
    all_url_candidates["programme_id"].nunique()
)

print(
    "Programme IDs:",
    sorted(
        all_url_candidates["programme_id"].unique()
    )
)

Programmes with URL candidates: 17
Programme IDs: ['EU_01', 'EU_02', 'EU_03', 'EU_05', 'EU_07', 'EU_08', 'EU_09', 'EU_11', 'EU_12', 'EU_13', 'EU_14', 'EU_15', 'EU_16', 'EU_17', 'EU_18', 'EU_19', 'EU_20']

In [100]:
all_programme_ids = set(
    programme_master["programme_id"]
)

found_programme_ids = set(
    all_url_candidates["programme_id"]
)

still_missing = sorted(
    all_programme_ids - found_programme_ids
)

print("Still missing:", still_missing)

Still missing: ['EU_04', 'EU_06', 'EU_10']

In [101]:
manual_url_rows = pd.DataFrame([
    {
        "programme_id": "EU_04",
        "university": "UCL",
        "programme_name": "MSc Data Science",
        "title": "Data Science MSc | UCL",
        "url": "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc"
    },
    {
        "programme_id": "EU_06",
        "university": "University of Oxford",
        "programme_name": "MSc in Social Data Science",
        "title": "MSc in Social Data Science | University of Oxford",
        "url": "https://www.ox.ac.uk/admissions/graduate/courses/msc-social-data-science"
    },
    {
        "programme_id": "EU_10",
        "university": "King's College London",
        "programme_name": "MSc Data Science",
        "title": "Data Science MSc | King's College London",
        "url": "https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc"
    }
])

all_url_candidates = pd.concat(
    [all_url_candidates, manual_url_rows],
    ignore_index=True
)

print(
    "Programmes with URL candidates:",
    all_url_candidates["programme_id"].nunique()
)

Programmes with URL candidates: 20

In [102]:
still_missing = sorted(
    set(programme_master["programme_id"])
    -
    set(all_url_candidates["programme_id"])
)

print("Still missing:", still_missing)

Still missing: []

In [103]:
url_candidate_summary = (
    all_url_candidates
    .groupby(
        ["programme_id", "university", "programme_name"]
    )
    .size()
    .reset_index(name="candidate_url_count")
    .sort_values("programme_id")
)

url_candidate_summary

,programme_id,university,programme_name,candidate_url_count
0,EU_01,Imperial College London,MSc Business Analytics & AI,2
1,EU_02,ETH Zurich,MSc Data Science,4
2,EU_03,UCL,MSc Business Analytics,4
3,EU_04,UCL,MSc Data Science,1
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),1
5,EU_06,University of Oxford,MSc in Social Data Science,1
6,EU_07,UCL,MSc Data Science and Public Policy,2
7,EU_08,EPFL,Master in Data Science,4
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,4
9,EU_10,King's College London,MSc Data Science,1
10,EU_11,University of Edinburgh,MSc Business Analytics,2
11,EU_12,University of Edinburgh,MSc Data Science,2
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,5
13,EU_14,KU Leuven,Master of Statistics and Data Science,5
14,EU_15,Lund University,MSc Data Analytics and Business Economics,5
15,EU_16,Politecnico di Milano,Data Science and Business Analytics,5
16,EU_17,Utrecht University,MSc Data Science,5
17,EU_18,RWTH Aachen University,MSc Data Science,5
18,EU_19,Technical University of Denmark,MSc Business Analytics,5
19,EU_20,Aalto University,Master's Programme in Business Analytics,5

In [104]:
def primary_url_score(row):
    title = str(row["title"]).lower()
    url = str(row["url"]).lower()

    score = 0

    # Programme/master pages get priority
    if "master" in title or "msc" in title:
        score += 3

    # Exact programme keywords
    programme_words = [
        w.lower()
        for w in str(row["programme_name"])
        .replace("(", " ")
        .replace(")", " ")
        .replace("&", " ")
        .split()
        if len(w) > 3
    ]

    score += sum(
        word in title
        for word in programme_words
    )

    # Penalise obvious sub-pages
    bad_words = [
        "curriculum",
        "programme structure",
        "how to apply",
        "admission",
        "fees",
        "student",
        "studyplan",
        "research"
    ]

    for word in bad_words:
        if word in title or word in url:
            score -= 3

    return score


all_url_candidates["primary_score"] = (
    all_url_candidates.apply(
        primary_url_score,
        axis=1
    )
)

In [105]:
primary_url_candidates = (
    all_url_candidates
    .sort_values(
        ["programme_id", "primary_score"],
        ascending=[True, False]
    )
    .groupby("programme_id")
    .first()
    .reset_index()
)

primary_url_candidates[
    [
        "programme_id",
        "university",
        "programme_name",
        "title",
        "url",
        "primary_score"
    ]
]

,programme_id,university,programme_name,title,url,primary_score
0,EU_01,Imperial College London,MSc Business Analytics & AI,MSc Business Analytics & AI - Imperial College London,https://www.imperial.ac.uk/business-school/masters/business-analytics/,5
1,EU_02,ETH Zurich,MSc Data Science,Master Data Science | ETH Zurich,https://ethz.ch/en/studies/master/degree-programmes/engineering-sciences/data-science.html,5
2,EU_03,UCL,MSc Business Analytics,Business Analytics MSc | Prospective Students Graduate - UCL,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/business-analytics-msc-2026,2
3,EU_04,UCL,MSc Data Science,Data Science MSc | UCL,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc,2
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),Statistics (Data Science and Machine Learning) MSc | Study | Imperial College London,https://www.imperial.ac.uk/study/courses/postgraduate-taught/statistics-data-science/,8
5,EU_06,University of Oxford,MSc in Social Data Science,MSc in Social Data Science | University of Oxford,https://www.ox.ac.uk/admissions/graduate/courses/msc-social-data-science,3
6,EU_07,UCL,MSc Data Science and Public Policy,Data Science and Public Policy MSc - UCL,https://www.ucl.ac.uk/social-historical-sciences/economics/study/data-science-and-public-policy-msc,7
7,EU_08,EPFL,Master in Data Science,Data Science ‒ Master ‐ EPFL,https://www.epfl.ch/education/master/programs/data-science/,6
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,Mathematics in Data Science - Master of Science (M.Sc.) - TUM,https://www.tum.de/en/studies/degree-programs/detail/mathematics-in-data-science-master-of-science-msc,6
9,EU_10,King's College London,MSc Data Science,Data Science MSc | King's College London,https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc,5
10,EU_11,University of Edinburgh,MSc Business Analytics,MSc Business Analytics - University of Edinburgh Business School,https://www.business-school.ed.ac.uk/msc/business-analytics,5
11,EU_12,University of Edinburgh,MSc Data Science,Data Science MSc - Postgraduate taught programmes | The University of Edinburgh,https://study.ed.ac.uk/programmes/postgraduate-taught/902-data-science,5
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,MSc Data Science and Artificial Intelligence Technology,https://www.tudelft.nl/en/education/programmes/masters/dsait/msc-data-science-and-artificial-intelligence-technology,8
13,EU_14,KU Leuven,Master of Statistics and Data Science,Master of Statistics and Data Science - KU Leuven,https://onderwijsaanbod.kuleuven.be/opleidingen/e/SC_51016989/diploma_omschrijving,7
14,EU_15,Lund University,MSc Data Analytics and Business Economics,Data Analytics and Business Economics - Master's Programme | Lund University,https://www.lunduniversity.lu.se/study/data-analytics-and-business-economics-masters-programme-EAGDA,7
15,EU_16,Politecnico di Milano,Data Science and Business Analytics,Master in Business Analytics and Data Science - POLIMI GSoM,https://www.gsom.polimi.it/en/course/master-business-analytics-data-science,7
16,EU_17,Utrecht University,MSc Data Science,Data Science - Utrecht University,https://www.uu.nl/en/masters/data-science,2
17,EU_18,RWTH Aachen University,MSc Data Science,Master Data Science – Studiencenter Informatik - RWTH Aachen University,https://sc.informatik.rwth-aachen.de/en/studium/master/master-data-science/,5
18,EU_19,Technical University of Denmark,MSc Business Analytics,Get a Master's degree in Business Analytics - DTU,https://www.dtu.dk/english/education/graduate/msc-programmes/business-analytics,5
19,EU_20,Aalto University,Master's Programme in Business Analytics,Master's Programme in Business Analytics | Aalto University,https://www.aalto.fi/en/programmes/masters-programme-in-business-analytics,7

In [106]:
primary_url_candidates[
    primary_url_candidates["primary_score"] <= 3
][
    [
        "programme_id",
        "university",
        "programme_name",
        "title",
        "url",
        "primary_score"
    ]
]

,programme_id,university,programme_name,title,url,primary_score
2,EU_03,UCL,MSc Business Analytics,Business Analytics MSc | Prospective Students Graduate - UCL,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/business-analytics-msc-2026,2
3,EU_04,UCL,MSc Data Science,Data Science MSc | UCL,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc,2
5,EU_06,University of Oxford,MSc in Social Data Science,MSc in Social Data Science | University of Oxford,https://www.ox.ac.uk/admissions/graduate/courses/msc-social-data-science,3
16,EU_17,Utrecht University,MSc Data Science,Data Science - Utrecht University,https://www.uu.nl/en/masters/data-science,2

In [107]:
programme_master.loc[
    programme_master["programme_id"] == "EU_16",
    "programme_name"
] = "Master in Business Analytics and Data Science"

primary_url_candidates.loc[
    primary_url_candidates["programme_id"] == "EU_16",
    "programme_name"
] = "Master in Business Analytics and Data Science"

In [108]:
primary_urls = (
    primary_url_candidates[
        ["programme_id", "url"]
    ]
    .rename(
        columns={"url": "selected_official_url"}
    )
)

programme_master = programme_master.merge(
    primary_urls,
    on="programme_id",
    how="left"
)

programme_master["official_url"] = (
    programme_master["selected_official_url"]
)

programme_master = programme_master.drop(
    columns=["selected_official_url"]
)

In [109]:
print(
    "Total programmes:",
    len(programme_master)
)

print(
    "Missing official URLs:",
    programme_master["official_url"].isna().sum()
)

print(
    "Unique programme IDs:",
    programme_master["programme_id"].nunique()
)

programme_master[
    [
        "programme_id",
        "university",
        "programme_name",
        "Country",
        "QS 2026 Rank",
        "official_url"
    ]
]

Total programmes: 20
Missing official URLs: 0
Unique programme IDs: 20

,programme_id,university,programme_name,Country,QS 2026 Rank,official_url
0,EU_01,Imperial College London,MSc Business Analytics & AI,United Kingdom,2,https://www.imperial.ac.uk/business-school/masters/business-analytics/
1,EU_02,ETH Zurich,MSc Data Science,Switzerland,7,https://ethz.ch/en/studies/master/degree-programmes/engineering-sciences/data-science.html
2,EU_03,UCL,MSc Business Analytics,United Kingdom,9,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/business-analytics-msc-2026
3,EU_04,UCL,MSc Data Science,United Kingdom,9,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),United Kingdom,2,https://www.imperial.ac.uk/study/courses/postgraduate-taught/statistics-data-science/
5,EU_06,University of Oxford,MSc in Social Data Science,United Kingdom,4,https://www.ox.ac.uk/admissions/graduate/courses/msc-social-data-science
6,EU_07,UCL,MSc Data Science and Public Policy,United Kingdom,9,https://www.ucl.ac.uk/social-historical-sciences/economics/study/data-science-and-public-policy-msc
7,EU_08,EPFL,Master in Data Science,Switzerland,22,https://www.epfl.ch/education/master/programs/data-science/
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,Germany,22,https://www.tum.de/en/studies/degree-programs/detail/mathematics-in-data-science-master-of-science-msc
9,EU_10,King's College London,MSc Data Science,United Kingdom,31,https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc
10,EU_11,University of Edinburgh,MSc Business Analytics,United Kingdom,34,https://www.business-school.ed.ac.uk/msc/business-analytics
11,EU_12,University of Edinburgh,MSc Data Science,United Kingdom,34,https://study.ed.ac.uk/programmes/postgraduate-taught/902-data-science
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,Netherlands,47,https://www.tudelft.nl/en/education/programmes/masters/dsait/msc-data-science-and-artificial-intelligence-technology
13,EU_14,KU Leuven,Master of Statistics and Data Science,Belgium,60,https://onderwijsaanbod.kuleuven.be/opleidingen/e/SC_51016989/diploma_omschrijving
14,EU_15,Lund University,MSc Data Analytics and Business Economics,Sweden,72,https://www.lunduniversity.lu.se/study/data-analytics-and-business-economics-masters-programme-EAGDA
15,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,Italy,98,https://www.gsom.polimi.it/en/course/master-business-analytics-data-science
16,EU_17,Utrecht University,MSc Data Science,Netherlands,103,https://www.uu.nl/en/masters/data-science
17,EU_18,RWTH Aachen University,MSc Data Science,Germany,105,https://sc.informatik.rwth-aachen.de/en/studium/master/master-data-science/
18,EU_19,Technical University of Denmark,MSc Business Analytics,Denmark,107,https://www.dtu.dk/english/education/graduate/msc-programmes/business-analytics
19,EU_20,Aalto University,Master's Programme in Business Analytics,Finland,114,https://www.aalto.fi/en/programmes/masters-programme-in-business-analytics

In [110]:
programme_master.to_csv(
    "../data/europe_final_programme_sample.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Saved final programme sample.")

Saved final programme sample.

## 2026 Programme-Level Data Collection

Create the 2026 programme-year dataset for the final European sample.
Variables are collected and validated using official university sources.

In [112]:
europe_2026 = programme_master[
    [
        "programme_id",
        "university",
        "programme_name",
        "Country",
        "official_url"
    ]
].copy()

europe_2026 = europe_2026.rename(
    columns={
        "Country": "country",
        "official_url": "source_url"
    }
)

europe_2026["year"] = 2026
europe_2026["region"] = "Europe"

europe_2026.head()

,programme_id,university,programme_name,country,source_url,year,region
0,EU_01,Imperial College London,MSc Business Analytics & AI,United Kingdom,https://www.imperial.ac.uk/business-school/masters/business-analytics/,2026,Europe
1,EU_02,ETH Zurich,MSc Data Science,Switzerland,https://ethz.ch/en/studies/master/degree-programmes/engineering-sciences/data-science.html,2026,Europe
2,EU_03,UCL,MSc Business Analytics,United Kingdom,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/business-analytics-msc-2026,2026,Europe
3,EU_04,UCL,MSc Data Science,United Kingdom,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc,2026,Europe
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),United Kingdom,https://www.imperial.ac.uk/study/courses/postgraduate-taught/statistics-data-science/,2026,Europe

In [113]:
coding_columns = [
    "school_type",
    "college_type",
    "ranking_tier",
    "statistics_core",
    "programming_core",
    "machine_learning_core",
    "data_visualization_core",
    "business_analytics_core",
    "core_category_count",
    "prerequisites",
    "GRE_GMAT_policy",
    "tuition_amount",
    "currency",
    "tuition_basis",
    "duration_months",
    "outcomes_reported",
    "new_programme",
    "source_type",
    "access_date"
]

for col in coding_columns:
    europe_2026[col] = pd.NA

In [114]:
europe_2026 = europe_2026[
    [
        "programme_id",
        "university",
        "programme_name",
        "year",
        "country",
        "region",
        "school_type",
        "college_type",
        "ranking_tier",
        "statistics_core",
        "programming_core",
        "machine_learning_core",
        "data_visualization_core",
        "business_analytics_core",
        "core_category_count",
        "prerequisites",
        "GRE_GMAT_policy",
        "tuition_amount",
        "currency",
        "tuition_basis",
        "duration_months",
        "outcomes_reported",
        "new_programme",
        "source_type",
        "source_url",
        "access_date"
    ]
]

print("Rows:", len(europe_2026))
print("Columns:", len(europe_2026.columns))

europe_2026.head()

Rows: 20
Columns: 26

,programme_id,university,programme_name,year,country,region,school_type,college_type,ranking_tier,statistics_core,...,GRE_GMAT_policy,tuition_amount,currency,tuition_basis,duration_months,outcomes_reported,new_programme,source_type,source_url,access_date
0,EU_01,Imperial College London,MSc Business Analytics & AI,2026,United Kingdom,Europe,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,https://www.imperial.ac.uk/business-school/masters/business-analytics/,<NA>
1,EU_02,ETH Zurich,MSc Data Science,2026,Switzerland,Europe,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,https://ethz.ch/en/studies/master/degree-programmes/engineering-sciences/data-science.html,<NA>
2,EU_03,UCL,MSc Business Analytics,2026,United Kingdom,Europe,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/business-analytics-msc-2026,<NA>
3,EU_04,UCL,MSc Data Science,2026,United Kingdom,Europe,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc,<NA>
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),2026,United Kingdom,Europe,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,https://www.imperial.ac.uk/study/courses/postgraduate-taught/statistics-data-science/,<NA>

In [115]:
europe_2026.to_csv(
    "../data/europe_2026_raw.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Saved: ../data/europe_2026_raw.csv")

Saved: ../data/europe_2026_raw.csv

### Pilot Collection: EU_01 — Imperial College London

In [116]:
eu01 = europe_2026[
    europe_2026["programme_id"] == "EU_01"
].copy()

eu01.T

                                                                                              0
programme_id                                                                              EU_01
university                                                              Imperial College London
programme_name                                                      MSc Business Analytics & AI
year                                                                                       2026
country                                                                          United Kingdom
region                                                                                   Europe
school_type                                                                                <NA>
college_type                                                                               <NA>
ranking_tier                                                                               <NA>
statistics_core                                                                            <NA>
programming_core                                                                           <NA>
machine_learning_core                                                                      <NA>
data_visualization_core                                                                    <NA>
business_analytics_core                                                                    <NA>
core_category_count                                                                        <NA>
prerequisites                                                                              <NA>
GRE_GMAT_policy                                                                            <NA>
tuition_amount                                                                             <NA>
currency                                                                                   <NA>
tuition_basis                                                                              <NA>
duration_months                                                                            <NA>
outcomes_reported                                                                          <NA>
new_programme                                                                              <NA>
source_type                                                                                <NA>
source_url               https://www.imperial.ac.uk/business-school/masters/business-analytics/
access_date                                                                                <NA>

In [117]:
mask = europe_2026["programme_id"] == "EU_01"

europe_2026.loc[mask, "statistics_core"] = 1
europe_2026.loc[mask, "programming_core"] = 1
europe_2026.loc[mask, "machine_learning_core"] = 1
europe_2026.loc[mask, "data_visualization_core"] = 1
europe_2026.loc[mask, "business_analytics_core"] = 1

europe_2026.loc[mask, "core_category_count"] = 5

In [118]:
europe_2026.loc[mask, "duration_months"] = 12

europe_2026.loc[mask, "tuition_amount"] = 47000
europe_2026.loc[mask, "currency"] = "GBP"
europe_2026.loc[mask, "tuition_basis"] = "Total programme tuition (international)"

europe_2026.loc[mask, "GRE_GMAT_policy"] = (
    "Not required; highly recommended for candidates "
    "with less quantitative degree backgrounds"
)

europe_2026.loc[mask, "prerequisites"] = (
    "Quantitative undergraduate degree; quantitative experience "
    "typically includes advanced calculus, probability, statistics, "
    "and linear algebra"
)

In [119]:
europe_2026.loc[mask, "outcomes_reported"] = 1

europe_2026.loc[mask, "new_programme"] = 0

europe_2026.loc[mask, "source_type"] = "Official university website"
europe_2026.loc[mask, "access_date"] = "2026-09-23"

In [120]:
europe_2026[
    europe_2026["programme_id"] == "EU_01"
].T

                                                                                                                                                                    0
programme_id                                                                                                                                                    EU_01
university                                                                                                                                    Imperial College London
programme_name                                                                                                                            MSc Business Analytics & AI
year                                                                                                                                                             2026
country                                                                                                                                                United Kingdom
region                                                                                                                                                         Europe
school_type                                                                                                                                                      <NA>
college_type                                                                                                                                                     <NA>
ranking_tier                                                                                                                                                     <NA>
statistics_core                                                                                                                                                     1
programming_core                                                                                                                                                    1
machine_learning_core                                                                                                                                               1
data_visualization_core                                                                                                                                             1
business_analytics_core                                                                                                                                             1
core_category_count                                                                                                                                                 5
prerequisites            Quantitative undergraduate degree; quantitative experience typically includes advanced calculus, probability, statistics, and linear algebra
GRE_GMAT_policy                                                             Not required; highly recommended for candidates with less quantitative degree backgrounds
tuition_amount                                                                                                                                                  47000
currency                                                                                                                                                          GBP
tuition_basis                                                                                                                 Total programme tuition (international)
duration_months                                                                                                                                                    12
outcomes_reported                                                                                                                                                   1
new_programme                                                                                                                                                       0
source_type                                                                                                                               Official university website
source_url                                                                                     https://www.imperial.ac.uk/business-school/masters/business-analytics/
access_date                                                                                                                                                2026-09-23

In [121]:
mask = europe_2026["programme_id"] == "EU_01"

europe_2026.loc[mask, "new_programme"] = pd.NA

### Automated Collection of 2026 Official Programme Pages

Retrieve current official programme pages for the 20 selected European programmes.
Automated extraction is treated as candidate information and will be manually validated.

In [122]:
import requests
from bs4 import BeautifulSoup
import time

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 Chrome/120 Safari/537.36"
    )
}

def fetch_page(url):
    try:
        response = requests.get(
            url,
            headers=headers,
            timeout=20
        )

        return {
            "status_code": response.status_code,
            "html": response.text,
            "error": None
        }

    except Exception as e:
        return {
            "status_code": None,
            "html": None,
            "error": str(e)
        }

In [123]:
test_programmes = programme_master[
    programme_master["programme_id"].isin(
        ["EU_01", "EU_02", "EU_03"]
    )
]

test_results = []

for _, row in test_programmes.iterrows():

    print(
        "Fetching:",
        row["programme_id"],
        row["university"]
    )

    result = fetch_page(
        row["official_url"]
    )

    test_results.append({
        "programme_id": row["programme_id"],
        "university": row["university"],
        "status_code": result["status_code"],
        "html_length": (
            len(result["html"])
            if result["html"]
            else 0
        ),
        "error": result["error"]
    })

    time.sleep(1)

test_fetch_df = pd.DataFrame(test_results)

test_fetch_df

Fetching: EU_01 Imperial College London
Fetching: EU_02 ETH Zurich
Fetching: EU_03 UCL

  programme_id               university  status_code  html_length error
0        EU_01  Imperial College London          200       346624  None
1        EU_02               ETH Zurich          200        53488  None
2        EU_03                      UCL          403         5880  None

In [124]:
fetch_results = []

for _, row in programme_master.iterrows():

    print(
        f"Fetching: {row['programme_id']} | "
        f"{row['university']}"
    )

    result = fetch_page(
        row["official_url"]
    )

    fetch_results.append({
        "programme_id": row["programme_id"],
        "university": row["university"],
        "programme_name": row["programme_name"],
        "url": row["official_url"],
        "status_code": result["status_code"],
        "html_length": (
            len(result["html"])
            if result["html"]
            else 0
        ),
        "error": result["error"]
    })

    time.sleep(1)

fetch_status = pd.DataFrame(fetch_results)

fetch_status[
    [
        "programme_id",
        "university",
        "status_code",
        "html_length",
        "error"
    ]
]

Fetching: EU_01 | Imperial College London
Fetching: EU_02 | ETH Zurich
Fetching: EU_03 | UCL
Fetching: EU_04 | UCL
Fetching: EU_05 | Imperial College London
Fetching: EU_06 | University of Oxford
Fetching: EU_07 | UCL
Fetching: EU_08 | EPFL
Fetching: EU_09 | Technical University of Munich
Fetching: EU_10 | King's College London
Fetching: EU_11 | University of Edinburgh
Fetching: EU_12 | University of Edinburgh
Fetching: EU_13 | Delft University of Technology
Fetching: EU_14 | KU Leuven
Fetching: EU_15 | Lund University
Fetching: EU_16 | Politecnico di Milano
Fetching: EU_17 | Utrecht University
Fetching: EU_18 | RWTH Aachen University
Fetching: EU_19 | Technical University of Denmark
Fetching: EU_20 | Aalto University

,programme_id,university,status_code,html_length,error
0,EU_01,Imperial College London,200,346624,None
1,EU_02,ETH Zurich,200,53488,None
2,EU_03,UCL,403,5880,None
3,EU_04,UCL,403,5826,None
4,EU_05,Imperial College London,200,161094,None
5,EU_06,University of Oxford,403,5748,None
6,EU_07,UCL,403,5895,None
7,EU_08,EPFL,200,96856,None
8,EU_09,Technical University of Munich,200,414514,None
9,EU_10,King's College London,200,452398,None
10,EU_11,University of Edinburgh,200,49329,None
11,EU_12,University of Edinburgh,200,122215,None
12,EU_13,Delft University of Technology,200,153924,None
13,EU_14,KU Leuven,200,52599,None
14,EU_15,Lund University,200,120794,None
15,EU_16,Politecnico di Milano,200,255268,None
16,EU_17,Utrecht University,200,38170,None
17,EU_18,RWTH Aachen University,200,142846,None
18,EU_19,Technical University of Denmark,200,206225,None
19,EU_20,Aalto University,200,129567,None

In [125]:
fetch_status["collection_status"] = (
    fetch_status["status_code"]
    .apply(
        lambda x:
        "Direct HTML available"
        if x == 200
        else "Manual / alternative collection needed"
    )
)

fetch_status[
    [
        "programme_id",
        "university",
        "status_code",
        "html_length",
        "collection_status"
    ]
]

,programme_id,university,status_code,html_length,collection_status
0,EU_01,Imperial College London,200,346624,Direct HTML available
1,EU_02,ETH Zurich,200,53488,Direct HTML available
2,EU_03,UCL,403,5880,Manual / alternative collection needed
3,EU_04,UCL,403,5826,Manual / alternative collection needed
4,EU_05,Imperial College London,200,161094,Direct HTML available
5,EU_06,University of Oxford,403,5748,Manual / alternative collection needed
6,EU_07,UCL,403,5895,Manual / alternative collection needed
7,EU_08,EPFL,200,96856,Direct HTML available
8,EU_09,Technical University of Munich,200,414514,Direct HTML available
9,EU_10,King's College London,200,452398,Direct HTML available
10,EU_11,University of Edinburgh,200,49329,Direct HTML available
11,EU_12,University of Edinburgh,200,122215,Direct HTML available
12,EU_13,Delft University of Technology,200,153924,Direct HTML available
13,EU_14,KU Leuven,200,52599,Direct HTML available
14,EU_15,Lund University,200,120794,Direct HTML available
15,EU_16,Politecnico di Milano,200,255268,Direct HTML available
16,EU_17,Utrecht University,200,38170,Direct HTML available
17,EU_18,RWTH Aachen University,200,142846,Direct HTML available
18,EU_19,Technical University of Denmark,200,206225,Direct HTML available
19,EU_20,Aalto University,200,129567,Direct HTML available

In [126]:
fetch_status["collection_status"].value_counts()

collection_status
Direct HTML available                     16
Manual / alternative collection needed     4
Name: count, dtype: int64

### Extract Text from Accessible 2026 Programme Pages

In [127]:
def extract_page_text(url):

    result = fetch_page(url)

    if result["status_code"] != 200:
        return None

    soup = BeautifulSoup(
        result["html"],
        "html.parser"
    )

    # Remove non-content elements
    for tag in soup([
        "script",
        "style",
        "nav",
        "footer",
        "header",
        "noscript"
    ]):
        tag.decompose()

    text = soup.get_text(
        separator=" ",
        strip=True
    )

    # Clean excessive whitespace
    text = " ".join(text.split())

    return text

In [128]:
page_text_rows = []

for _, row in fetch_status.iterrows():

    if row["status_code"] == 200:

        print(
            f"Extracting: "
            f"{row['programme_id']} | "
            f"{row['university']}"
        )

        text = extract_page_text(
            row["url"]
        )

        page_text_rows.append({
            "programme_id": row["programme_id"],
            "university": row["university"],
            "programme_name": row["programme_name"],
            "url": row["url"],
            "text_length": (
                len(text)
                if text
                else 0
            ),
            "page_text": text
        })

        time.sleep(1)

page_text_df = pd.DataFrame(
    page_text_rows
)

print("Pages extracted:", len(page_text_df))

Extracting: EU_01 | Imperial College London
Extracting: EU_02 | ETH Zurich
Extracting: EU_05 | Imperial College London
Extracting: EU_08 | EPFL
Extracting: EU_09 | Technical University of Munich
Extracting: EU_10 | King's College London
Extracting: EU_11 | University of Edinburgh
Extracting: EU_12 | University of Edinburgh
Extracting: EU_13 | Delft University of Technology
Extracting: EU_14 | KU Leuven
Extracting: EU_15 | Lund University
Extracting: EU_16 | Politecnico di Milano
Extracting: EU_17 | Utrecht University
Extracting: EU_18 | RWTH Aachen University
Extracting: EU_19 | Technical University of Denmark
Extracting: EU_20 | Aalto University
Pages extracted: 16

In [129]:
page_text_df[
    [
        "programme_id",
        "university",
        "programme_name",
        "text_length"
    ]
]

,programme_id,university,programme_name,text_length
0,EU_01,Imperial College London,MSc Business Analytics & AI,51054
1,EU_02,ETH Zurich,MSc Data Science,1996
2,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),18950
3,EU_08,EPFL,Master in Data Science,3245
4,EU_09,Technical University of Munich,MSc Mathematics in Data Science,9415
5,EU_10,King's College London,MSc Data Science,4816
6,EU_11,University of Edinburgh,MSc Business Analytics,4012
7,EU_12,University of Edinburgh,MSc Data Science,27676
8,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,1962
9,EU_14,KU Leuven,Master of Statistics and Data Science,8851
10,EU_15,Lund University,MSc Data Analytics and Business Economics,18734
11,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,10556
12,EU_17,Utrecht University,MSc Data Science,5713
13,EU_18,RWTH Aachen University,MSc Data Science,3413
14,EU_19,Technical University of Denmark,MSc Business Analytics,4647
15,EU_20,Aalto University,Master's Programme in Business Analytics,4164

In [130]:
page_text_df[
    [
        "programme_id",
        "page_text"
    ]
].assign(
    text_preview=lambda x:
        x["page_text"].str[:500]
)[
    [
        "programme_id",
        "text_preview"
    ]
]

,programme_id,text_preview
0,EU_01,"MSc Business Analytics & AI - Business School Skip to main content Study your MSc Business Analytics & AI at a world-leading university 2nd in the world (Imperial College London, QS World University Rankings 2027) 3rd in Europe (Imperial College London, Times Higher Education World University Rankings 2026) #3 city for students (London, QS Best Student City Rankings 2027) Drive business transformation through data-driven decision-making With the emergence of technologies such as AI and machine l"
1,EU_02,"Master Data Science | ETH Zurich Homepage Navigation Search Content Footer Contact Sitemap Master Data Science Research in the field of data science requires solid skills in managing and storing massive amounts of data as well as the ability to develop efficient mathematical algorithms for data analysis. These techniques are employed in complex applications in natural science, engineering and social science. The specialized Master's degree programme in data science equips students with all relev"
2,EU_05,Statistics (Data Science and Machine Learning) MSc | Study | Imperial College London Skip to main content View accessibility support page Skip to filters Course compare 0 Postgraduate taught MSc MSc Statistics (Data Science and Machine Learning) Build familiarity with a wide range of data science techniques and their application in a variety of settings. Applications open on Wednesday 30 September 2026 Request Info Add to course compare Course key facts Qualification MSc Duration 1 year Start da
3,EU_08,"Data Science ‒ Master ‐ EPFL Skip to content Data Science A revolution focused on Big Data. Mobile devices, sensors, web logs, instruments and transactions produce massive amounts of data by the second. As powerful new technologies emerge, Data science allows to gain insight by analyzing this large and often heterogeneous data. EPFL’s Master’s program in Data Science offers a comprehensive education, from the foundations to implementation, from algorithms to database architecture, and from infor"
4,EU_09,Mathematics in Data Science - Master of Science (M.Sc.) - TUM Show convenient version of this site Don't show this message again Skip to main content Close search overlay Search for content Submit Master of Science (M.Sc.) Mathematics in Data Science The Master’s degree program Mathematics in Data Science combines a high-profile education in Mathematics with an emphasis on the burgeoning areas of Data Science and Artificial Intelligence. Course Homepage Key Data Type of Study Full-time Standard
5,EU_10,"Data Science MSc | King's College London Skip to main content Overview Our Data Science MSc provides you with the essential knowledge and advanced skills for a successful career in data science. You'll learn to collect, curate, and analyse data, gaining a rigorous grounding in all aspects of data analytics and big data. This programme is designed for graduates and professionals with a background in quantitative subjects who want to master current methods and techniques in data science. The cours"
6,EU_11,"MSc Business Analytics - University of Edinburgh Business School This site uses cookies We use necessary cookies to make our sites work. We'd also like to set additional cookies to analyse how our sites are performing, to improve the relevance of our ads and to optimise your experience. These will be set only if you accept. To learn more, view our privacy policy . Accept all Reject all Manage preferences Privacy Preferences Necessary cookies Necessary cookies These cookies are necessary for the"
7,EU_12,Data Science MSc - Postgraduate taught programmes | The University of Edinburgh Skip to main content Data Science MSc This programme is not currently open for applications. Applications for the next intake usually open in October. Level: Postgraduate taught Subject: Computing and Informatics Year of entry: 2026 Study options Mode of study On campus Part-time MSc | up to 3 years | Start date: multiple dates Full-time MSc | 1 year | Start date: September 2026 Key facts School School of Informatics
8,EU_13,"MSc Data Science and Artificial Intelligence Technology Search Close search Item 1 of 1 MSc Data Science and Artificial Intelligence Technology Development of entire AI systems, and data-driven and other AI algorithms lie at the heart of real-world applications. They range from intelligent personal assistants to self-driving cars and from smart infrastructures and cities to smart industries and contribute to finding sustainable solutions. Consequently, there is a need for technical professionals"
9,EU_14,Master of Statistics and Data Science (on campus) (Programme for students started before 2026-2027) (Leuven) | KU Leuven Home Master of Statistics and Data Science (on campus) (Programme for students started before 2026-2027) (Leuven) Master of Statistics and Data Science Master of Science Master of Statistics and Data Science (on campus) (Programme for students started before 2026-2027) (Leuven) (120 sp.) Other programmes (3) keyboard_arrow_down Master of Statistics and Data Science (on campus)
10,EU_15,"Data Analytics and Business Economics - Master's Programme | Lund University Data Analytics and Business Economics - Master's Programme Master's programme • 1 year • 60 credits Transforming data into insights that can enhance decision-making is a key challenge for companies of every size, across all industries. In this programme, you will learn how to work the numbers, draw conclusions, and communicate your results. Application dates Play video Programme video: MSc Data Analytics and Business Ec"
11,EU_16,"Master in Business Analytics and Data Science - POLIMI GSoM Home Specialising Masters Master in Business Analytics and Data Science Master in Business Analytics and Data Sc... Master in Business Analytics and Data Science Overview Is it right for me? Why choose this master? Our partners Programme structure Our services Career Admissions Fees and Benefits Hear from our Ambassadors Meet with us Subject Artificial Intelligence & Data Science Intake October 2026 Format Full Time Individuals €25,000"
12,EU_17,Data Science - Utrecht University Skip to main content Menu How are we transitioning into an energy efficient and zero waste society? How do we detect and analyze fraud schemes and money laundry in an increasingly complex economy? How do we improve healthcare by developing personalized medicine? Data Science will play a pivotal role in solving the global challenges of the 21st century. Go to study programme Curious about this programme? Visit the Online Master's open day on Wednesday 7 October a
13,EU_18,"Master Data Science – Studiencenter Informatik Zum Inhalt wechseln Master Data Science​ Seite nur auf Englisch verfügbar (page available in English only) Die Information zum Master Data Science sind derzeit nur in English verfügbar. Englische Sprachkenntnisse sind eine Zugangsvoraussetzung für diesen Master-Studiengang. Welcome to the website of the Data Science master program offered by the Faculty of Computer Science of RWTH Aachen University . Data Science is a hot topic, which gains in impor"
14,EU_19,"Get a Master’s degree in Business Analytics Get a Master's degree in Business Analytics Explore Share on back Business Analytics Prerequisites Curriculum Specializations Career Master of Science (MSc) in Business Analytics In the years to come, digitization will have an enormous impact on the development of companies and on society as a whole. Oops, this feature requires cookies To view the content, you must change your cookie consent to allow functionality and targeting cookies Study Programme"
15,EU_20,"Master's Programme in Business Analytics | Aalto University Close side navigation Open side navigation Student Guide Master's Programme in Business Analytics For Aalto students This site contains the student study guide for Master's Programme in Business Analytics. Here you will find the programme curriculum as well as detailed guidelines for planning your studies. All the materials and instructions are for the students in the programme. If you are interested in applying to the programme, follow"

In [131]:
CURRICULUM_KEYWORDS = {
    "statistics": [
        "statistics",
        "statistical",
        "probability"
    ],
    
    "programming": [
        "programming",
        "python",
        "coding",
        "software"
    ],
    
    "machine_learning": [
        "machine learning",
        "deep learning"
    ],
    
    "data_visualization": [
        "data visualization",
        "data visualisation",
        "visualization",
        "visualisation"
    ],
    
    "business_analytics": [
        "business analytics",
        "decision analytics",
        "business intelligence",
        "decision models"
    ]
}

In [132]:
def find_keyword_context(
    text,
    keywords,
    context_chars=180
):
    if not text:
        return None

    text_lower = text.lower()
    matches = []

    for keyword in keywords:
        start = 0

        while True:
            pos = text_lower.find(
                keyword.lower(),
                start
            )

            if pos == -1:
                break

            left = max(
                0,
                pos - context_chars
            )

            right = min(
                len(text),
                pos + len(keyword) + context_chars
            )

            snippet = text[left:right]

            matches.append(
                f"[{keyword}] {snippet}"
            )

            start = pos + len(keyword)

            # 每个关键词最多保留3个结果
            if sum(
                m.startswith(f"[{keyword}]")
                for m in matches
            ) >= 3:
                break

    if not matches:
        return None

    return " || ".join(matches)

In [133]:
curriculum_evidence_rows = []

for _, row in page_text_df.iterrows():

    evidence_row = {
        "programme_id": row["programme_id"],
        "university": row["university"],
        "programme_name": row["programme_name"]
    }

    for category, keywords in CURRICULUM_KEYWORDS.items():

        evidence_row[
            f"{category}_evidence"
        ] = find_keyword_context(
            row["page_text"],
            keywords
        )

    curriculum_evidence_rows.append(
        evidence_row
    )

curriculum_evidence = pd.DataFrame(
    curriculum_evidence_rows
)

curriculum_evidence

,programme_id,university,programme_name,statistics_evidence,programming_evidence,machine_learning_evidence,data_visualization_evidence,business_analytics_evidence
0,EU_01,Imperial College London,MSc Business Analytics & AI,"[statistics] out more about career outcomes . / Discover the Imperial advantage Programme content Pre-study and Core modules will prepare you with essential foundation skills in areas such as statistics, machine learning, data visualisation and genAI, equipping you to analyse complex data and generate actionable insights. Elective modules allow you to tailor the programme to your || [statistics] nd methodologies to solve real world problems. The goal of the module is to enable you to be data-savvy, analytically minded and coding-literate problem solvers. Read more Maths & Statistics Foundations for Analytics This rigorous module will teach you concepts of probability, statistics and linear algebra. You will learn to summarise and analyse data using statistica || [statistics] savvy, analytically minded and coding-literate problem solvers. Read more Maths & Statistics Foundations for Analytics This rigorous module will teach you concepts of probability, statistics and linear algebra. You will learn to summarise and analyse data using statistical concepts and understand linear algebra to represent and manipulate data. This will ensure that y || [statistical] sation techniques in R and Tableau, emphasising how to ask insightful business questions and analyse data interactively. Exploratory data analysis methods will be discussed from a statistical point of view and with cases in a management context. Our discussions will be complemented by real datasets from retail, supply chain, finance, and other industries. You will be p || [statistical] Statistics Foundations for Analytics This rigorous module will teach you concepts of probability, statistics and linear algebra. You will learn to summarise and analyse data using statistical concepts and understand linear algebra to represent and manipulate data. This will ensure that you build a solid foundation of the mathematical concepts necessary to succeed on th || [statistical] al concepts necessary to succeed on the programme. This module will also serve as an introduction to R. Read more Optimisation and Decision Models Optimisation plays a key role in statistical, machine learning and business operational models. This module trains students on the fundamental optimisation tools available to the modeller and business analyst. You will obtai || [probability] u to be data-savvy, analytically minded and coding-literate problem solvers. Read more Maths & Statistics Foundations for Analytics This rigorous module will teach you concepts of probability, statistics and linear algebra. You will learn to summarise and analyse data using statistical concepts and understand linear algebra to represent and manipulate data. This will e || [probability] e experience statement, you need to list up to five of the most quantitative modules or elements of your studies to date. You should detail: The main topics of study (eg: algebra, probability etc) The level of study (eg: high school, undergraduate degree, short course etc) This will allow the selection committee to have an understanding of your quantitative experience","[programming] nded term. Taught within a world-leading university with STEMB roots, you will benefit from expertise in data, science and technology. From early on, you will learn how to code in programming languages such as Python and R, and gain the specialist skills you need to boost your career or start working as a business analyst, data scientist or consultant. Meanwhile, our t || [programming] ng-time analysis. You will develop a working knowledge of basic algorithms (for problems such as search, sorting, and shortest paths) and data structures, along with the necessary programming constructs. The module will also serve as an introduction to the Python programming language, with the goal of becoming proficient in organising and writing programs for practical || [programming] lems such as search, sorting, and shortest paths) and data structures, along with the necessary programming constructs. The module will also serve as an introduction to the Python programming language, with the goal of becoming proficient in organising and writing programs for practical problem-solving. Read more Data Wrangling and Visualisation This module introduces || [python] ld-leading university with STEMB roots, you will benefit from expertise in data, science and technology. From early on, you will learn how to code in programming languages such as Python and R, and gain the specialist skills you need to boost your career or start working as a business analyst, data scientist or consultant. Meanwhile, our tailored career support wi || [python] or problems such as search, sorting, and shortest paths) and data structures, along with the necessary programming constructs. The module will also serve as an introduction to the Python programming language, with the goal of becoming proficient in organising and writing programs for practical problem-solving. Read more Data Wrangling and Visualisation This module || [python] so be complemented by user cases and data sets from IT, supply chain, retail, finance, etc. Programming requirement: You are expected to be on a moderate level of familiarity with Python for taking the module. As a benchmark, you should participate a fair share in the group assignments of the Machine Learning module. Read more Healthcare and Medical Analytics Heal || [coding] e language models and multi-modal large language models) as machine learning models and showcase the state-of-the-art application contexts of these generative AI models on search, coding, text processing, etc. In particular, you will understand how the generative AI model platforms such as ChatGPT and Claude can be used for interactive data analytics and business || [coding] t will focus on the practical use of these skills and methodologies to solve real world problems. The goal of the module is to enable you to be data-savvy, analytically minded and coding-literate problem solvers. Read more Maths & Statistics Foundations for Analytics This rigorous module will teach you concepts of probability, statistics and linear algebra. You wi || [coding] ugee assistance, recommendation systems, online advertising, content moderation, and large-scale AI like LLMs. Emphasising intuition and implementation, the module features guided coding assignments, where you extend provided code while tackling realistic challenges, and a final exam. By the end of the module, you can design, evaluate, and deploy adaptive AI syste || [software] optimisation tools available to the modeller and business analyst. You will obtain hands-on experience with the key modelling (AIMMS, GAMS, AMPL) and optimisation (CPLEX, GUROBI) software packages. Read more Statistics and Econometrics This module provides an introduction to multiple regression analysis and related methods for analysing data in business application","[machine learning] city for students (London, QS Best Student City Rankings 2027) Drive business transformation through data-driven decision-making With the emergence of technologies such as AI and machine learning, the ability to analyse and interpret complex data sets is crucial for future business leaders. Our MSc in Business Analytics & AI will equip you with advanced computational, mach || [machine learning] ning, the ability to analyse and interpret complex data sets is crucial for future business leaders. Our MSc in Business Analytics & AI will equip you with advanced computational, machine learning, and AI capabilities to succeed in an increasingly data-driven world. You will develop expertise in predictive, prescriptive and AI-powered decision models while applying these to || [machine learning] and helping you build a global perspective. A forward-looking curriculum We update our curriculum to reflect changes in business analytics. With elective options such as Advanced Machine Learning, Causal Modelling, and Generative AI and Large Language Models, you can apply your knowledge directly to your chosen career. World-class faculty Taught by business-focussed academ || [deep learning] tasets from retail, supply chain, finance, and other industries. You will be prepared to use analytical and data-driven approaches to make informed management decisions. Read more Deep Learning and Generative AI The module provides a self-contained overview of deep learning and generative AI. The contents of the module consist of two parts. In the first part you will stu || [deep learning] ared to use analytical and data-driven approaches to make informed management decisions. Read more Deep Learning and Generative AI The module provides a self-contained overview of deep learning and generative AI. The contents of the module consist of two parts. In the first part you will study the general framework of loss function-based machine learning as the cornersto || [deep learning] he contents of the module consist of two parts. In the first part you will study the general framework of loss function-based machine learning as the cornerstone of all the modern deep learning models. You will connect the training of a machine learning model with optimisation algorithms of gradient descent and stochastic gradient descent. You will understand how the fra","[data visualisation] s . / Discover the Imperial advantage Programme content Pre-study and Core modules will prepare you with essential foundation skills in areas such as statistics, machine learning, data visualisation and genAI, equipping you to analyse complex data and generate actionable insights. Elective modules allow you to tailor the programme to your interests, with modules focused on di || [data visualisation] rial. Read more Our core modules are the backbone of the programme and will provide you with a solid combination of tools and knowledge across areas such such as machine learning, data visualisation and decision modelling. Data Structures and Algorithms This module introduces you to the design of algorithms and data structures for computational problem solving. The design of || [data visualisation] , our faculty are at the forefront of data science and business analytics. They’re using state-of-the-art technology such as the Data Observatory, one of the world’s most advanced data visualisation spaces. They combine theoretical knowledge from their cutting-edge research with the latest practical insights from their extensive network with industry and government. / Gah-Yi || [visualisation] Discover the Imperial advantage Programme content Pre-study and Core modules will prepare you with essential foundation skills in areas such as statistics, machine learning, data visualisation and genAI, equipping you to analyse complex data and generate actionable insights. Elective modules allow you to tailor the programme to your interests, with modules focused on di || [visualisation] Read more Our core modules are the backbone of the programme and will provide you with a solid combination of tools and knowledge across areas such such as machine learning, data visualisation and decision modelling. Data Structures and Algorithms This module introduces you to the design of algorithms and data structures for computational problem solving. The design of || [visualisation] ntroduction to the Python programming language, with the goal of becoming proficient in organising and writing programs for practical problem-solving. Read more Data Wrangling and Visualisation This module introduces practical data wrangling and visualisation techniques in R and Tableau, emphasising how to ask insightful business questions and analyse data interactively.","[business analytics] MSc Business Analytics & AI - Business School Skip to main content Study your MSc Business Analytics & AI at a world-leading university 2nd in the world (Imperial College London, QS World University Ran || [business analytics] MSc Business Analytics & AI - Business School Skip to main content Study your MSc Business Analytics & AI at a world-leading university 2nd in the world (Imperial College London, QS World University Rankings 2027) 3rd in Europe (Imperial College London, Times Higher Education Wor || [business analytics] aking With the emergence of technologies such as AI and machine learning, the ability to analyse and interpret complex data sets is crucial for future business leaders. Our MSc in Business Analytics & AI will equip you with advanced computational, machine learning, and AI capabilities to succeed in an increasingly data-driven world. You will develop expertise in predictive, p || [decision models] dvanced computational, machine learning, and AI capabilities to succeed in an increasingly data-driven world. You will develop expertise in predictive, prescriptive and AI-powered decision models while applying these tools to real-world business challenges through workshops, placement opportunities and our optional extended term. Taught within a world-leading university wi || [decision models] at you build a solid foundation of the mathematical concepts necessary to succeed on the programme. This module will also serve as an introduction to R. Read more Optimisation and Decision Models Optimisation plays a key role in statistical, machine learning and business operational models. This module trains students on the fundamental optimisation tools available to the"
1,EU_02,ETH Zurich,MSc Data Science,None,None,None,None,None
2,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),"[statistics] Statistics (Data Science and Machine Learning) MSc | Study | Imperial College London Skip to main content View accessibility support page Skip to filters Course compare 0 Postgraduate taught || [statistics] ience and Machine Learning) MSc | Study | Imperial College London Skip to main content View accessibility support page Skip to filters Course compare 0 Postgraduate taught MSc MSc Statistics (Data Science and Machine Learning) Build familiarity with a wide range of data science techniques and their application in a variety of settings. Applications open on Wednesday 3 || [statistics] ear Start date October 2027 Study mode Full-time Delivered by Department of Mathematics Location South Kensington Applications: places 25:1 (2024-25) Minimum entry standard 2:1 in Statistics, Mathematics, Engineering, Physics or Computer Science. View full entry requirements Course overview Develop your appreciation of data science techniques and their application in || [statistical] entry requirements Course overview Develop your appreciation of data science techniques and their application in statistics on this Master's course. You'll explore a wide range of statistical methods used in data science and machine learning and delve into current developments in the field. This course considers how these methods are used in a variety of areas. These i || [statistical] ailable at Imperial. You may wish to consider choosing one of the following streams: Statistics (generic stream) Applied Statistics Data Science and Machine Learning (this stream) Statistical Finance Theory and Methods Testimonials “Highly acclaimed and extremely supportive professors brought out the best in me and helped me attain well-rounded development ” Srishti Ar || [statistical] nials “I enjoyed studying at Imperial College London, especially the high-quality modules and the exciting research projects. The MSc Statistics programme helped me strengthen the statistical theory basis and improve the technical skill effectively.” Yining Chen (China) Find out more about our Alumni's experience Read our Alumni testimonials “I chose to study Statistic || [probability] ntals of Statistical Inference Appreciate different Bayesian and frequentist approaches to statistical inference and select and justify appropriate methods for hypothesis testing. Probability for Statistics Assess the key concepts of probability theory and learn how random variables and vectors and their distribution functions are defined. Data Science Become familiar || [probability] yesian and frequentist approaches to statistical inference and select and justify appropriate methods for hypothesis testing. Probability for Statistics Assess the key concepts of probability theory and learn how random variables and vectors and their distribution functions are defined. Data Science Become familiar with the most common data scientific methods and their","[python] academic staff and/or industry partner on a state-of-the-art research problem that suits your interests. Become fluent in the most common data science computing languages such as python, R, pyspark, Stan, or tensorflow, and deploy these skills to make statistics individually or in teams. Master Statistics through a focus on in-person problem-solving activities an","[machine learning] Statistics (Data Science and Machine Learning) MSc | Study | Imperial College London Skip to main content View accessibility support page Skip to filters Course compare 0 Postgraduate taught MSc MSc Statistics (Data Science a || [machine learning] Sc | Study | Imperial College London Skip to main content View accessibility support page Skip to filters Course compare 0 Postgraduate taught MSc MSc Statistics (Data Science and Machine Learning) Build familiarity with a wide range of data science techniques and their application in a variety of settings. Applications open on Wednesday 30 September 2026 Request Info Add t || [machine learning] ur appreciation of data science techniques and their application in statistics on this Master's course. You'll explore a wide range of statistical methods used in data science and machine learning and delve into current developments in the field. This course considers how these methods are used in a variety of areas. These include scientific, governmental, industrial and co || [deep learning] Data technology to perform a rigorous statistical analysis, and describe and apply mathematical techniques for fitting statistical models at scale and dealing with streaming data. Deep Learning (7.5 ECTS) Explore the building blocks of deep learning models, and how to design network architectures for specific applications. Nonparametric Statistics Learn modern techniques || [deep learning] is, and describe and apply mathematical techniques for fitting statistical models at scale and dealing with streaming data. Deep Learning (7.5 ECTS) Explore the building blocks of deep learning models, and how to design network architectures for specific applications. Nonparametric Statistics Learn modern techniques to solve various problems, including estimating distrib",None,"[business intelligence] utomotive, retail, healthcare, and pharmaceuticals. What jobs do our graduates do? Quantitative Analyst, Quantitative Researcher, Commodities Trader, Data Scientist, Data Analyst, Business Intelligence Developer, Engineering Analyst, Credit Risk Analyst, Management Trainee, Civil Servant. Who do our graduates work for? JP Morgan, Accenture, BCG, Amazon, PwC, Darktrace, Carrefour"

In [134]:
pd.set_option(
    "display.max_colwidth",
    1000
)

curriculum_evidence[
    curriculum_evidence["programme_id"]
    == "EU_02"
].T

                                            1
programme_id                            EU_02
university                         ETH Zurich
programme_name               MSc Data Science
statistics_evidence                      None
programming_evidence                     None
machine_learning_evidence                None
data_visualization_evidence              None
business_analytics_evidence              None

### Supporting Official Page Discovery

Search for official curriculum, admissions, tuition, and outcomes pages
for each selected programme. Search results are treated as candidate
sources and require manual validation.

In [136]:
SUPPORTING_PAGE_QUERIES = {
    "curriculum": "curriculum courses modules study plan",
    "admissions": "admission requirements entry requirements",
    "tuition": "tuition fees funding",
    "outcomes": "employment outcomes career report"
}

In [137]:
def search_supporting_pages(
    university,
    programme_name,
    official_domain,
    page_type,
    query_terms,
    max_results=5
):
    query = (
        f'"{programme_name}" '
        f'{query_terms} '
        f'site:{official_domain}'
    )

    rows = []

    try:
        results = list(
            DDGS().text(
                query,
                max_results=max_results
            )
        )

        for rank, result in enumerate(
            results,
            start=1
        ):
            url = result.get("href", "")

            if not url:
                continue

            result_domain = (
                urlparse(url)
                .netloc
                .lower()
                .replace("www.", "")
            )

            if (
                result_domain == official_domain
                or result_domain.endswith(
                    "." + official_domain
                )
            ):
                rows.append({
                    "page_type": page_type,
                    "result_rank": rank,
                    "title": result.get("title"),
                    "url": url,
                    "snippet": result.get("body")
                })

    except Exception as e:
        print(
            f"Error | {university} | "
            f"{page_type} | {e}"
        )

    return rows

In [138]:
eth = programme_master[
    programme_master["programme_id"]
    == "EU_02"
].iloc[0]

eth_supporting_rows = []

for page_type, query_terms in (
    SUPPORTING_PAGE_QUERIES.items()
):

    print(
        f"Searching EU_02 | {page_type}"
    )

    results = search_supporting_pages(
        university=eth["university"],
        programme_name=eth["programme_name"],
        official_domain=eth["official_domain"],
        page_type=page_type,
        query_terms=query_terms,
        max_results=5
    )

    for result in results:

        result["programme_id"] = "EU_02"

        eth_supporting_rows.append(
            result
        )

    time.sleep(1)

eth_supporting = pd.DataFrame(
    eth_supporting_rows
)

eth_supporting[
    [
        "programme_id",
        "page_type",
        "result_rank",
        "title",
        "url"
    ]
]

Searching EU_02 | curriculum
Searching EU_02 | admissions
Searching EU_02 | tuition
Searching EU_02 | outcomes

,programme_id,page_type,result_rank,title,url
0,EU_02,curriculum,1,PDF Appendix requirement profile MSc Data Science - ETH Zürich,https://ethz.ch/content/dam/ethz/special-interest/infk/department/Images+and+Content/Studies/Master/DS/MSc-DataScience-Appendix.pdf
1,EU_02,curriculum,2,Courses – Social Networks Lab | ETH Zurich,https://sn.ethz.ch/teaching/courses.html
2,EU_02,admissions,1,Appendix requirement profile MSc Data Science,https://ethz.ch/content/dam/ethz/special-interest/infk/department/Images+and+Content/Studies/Master/DS/MSc-DataScience-Appendix.pdf
3,EU_02,admissions,2,Minimum overall average grades | ETH Zurich,https://ethz.ch/en/studies/master/application/international-bachelor/prerequisites/minimum-grade-requirements.html
4,EU_02,tuition,1,Appendix requirement profile MSc Data Science,https://ethz.ch/content/dam/ethz/special-interest/infk/department/Images+and+Content/Studies/Master/DS/MSc-DataScience-Appendix.pdf
5,EU_02,tuition,2,Exchange semester at a partner university – Department of Computer Science | ETH Zurich,https://inf.ethz.ch/studies/studentmobility/exchange-semester.html
6,EU_02,outcomes,1,Data Science - ETH Zürich,https://ethz.ch/content/dam/ethz/special-interest/infk/department/Images+and+Content/Studies/Master/DS/BrochureMasterDataScience.pdf
7,EU_02,outcomes,2,Master Data Science | ETH Zurich,https://ethz.ch/en/studies/master/degree-programmes/engineering-sciences/data-science.html
8,EU_02,outcomes,3,Master in Data Science – Department of Computer Science - ETH Z,https://inf.ethz.ch/studies/master/master-ds.html
9,EU_02,outcomes,4,Master's in Data Science – Department of Mathematics | ETH Zurich,https://math.ethz.ch/studies/master-programmes/master-data-science.html
10,EU_02,outcomes,5,DAS in Data Science – Department of Computer Science | ETH Zurich,https://inf.ethz.ch/continuing-education/das-datascience.html

In [139]:
PAGE_TYPE_KEYWORDS = {
    "curriculum": [
        "curriculum",
        "course",
        "courses",
        "module",
        "modules",
        "study plan",
        "programme structure"
    ],

    "admissions": [
        "admission",
        "admissions",
        "entry requirement",
        "entry requirements",
        "requirement profile",
        "application requirement"
    ],

    "tuition": [
        "tuition",
        "fee",
        "fees",
        "funding",
        "cost"
    ],

    "outcomes": [
        "employment",
        "career",
        "careers",
        "outcome",
        "outcomes",
        "graduate destinations"
    ]
}

In [140]:
def supporting_relevance_score(row):

    page_type = row["page_type"]

    searchable_text = (
        str(row["title"]) + " " +
        str(row["url"]) + " " +
        str(row.get("snippet", ""))
    ).lower()

    keywords = PAGE_TYPE_KEYWORDS[
        page_type
    ]

    score = sum(
        keyword in searchable_text
        for keyword in keywords
    )

    return score

In [141]:
eth_supporting[
    "relevance_score"
] = eth_supporting.apply(
    supporting_relevance_score,
    axis=1
)

eth_supporting[
    [
        "page_type",
        "result_rank",
        "relevance_score",
        "title",
        "url"
    ]
].sort_values(
    [
        "page_type",
        "relevance_score",
        "result_rank"
    ],
    ascending=[
        True,
        False,
        True
    ]
)

,page_type,result_rank,relevance_score,title,url
2,admissions,1,2,Appendix requirement profile MSc Data Science,https://ethz.ch/content/dam/ethz/special-interest/infk/department/Images+and+Content/Studies/Master/DS/MSc-DataScience-Appendix.pdf
3,admissions,2,1,Minimum overall average grades | ETH Zurich,https://ethz.ch/en/studies/master/application/international-bachelor/prerequisites/minimum-grade-requirements.html
1,curriculum,2,3,Courses – Social Networks Lab | ETH Zurich,https://sn.ethz.ch/teaching/courses.html
0,curriculum,1,0,PDF Appendix requirement profile MSc Data Science - ETH Zürich,https://ethz.ch/content/dam/ethz/special-interest/infk/department/Images+and+Content/Studies/Master/DS/MSc-DataScience-Appendix.pdf
6,outcomes,1,1,Data Science - ETH Zürich,https://ethz.ch/content/dam/ethz/special-interest/infk/department/Images+and+Content/Studies/Master/DS/BrochureMasterDataScience.pdf
7,outcomes,2,0,Master Data Science | ETH Zurich,https://ethz.ch/en/studies/master/degree-programmes/engineering-sciences/data-science.html
8,outcomes,3,0,Master in Data Science – Department of Computer Science - ETH Z,https://inf.ethz.ch/studies/master/master-ds.html
9,outcomes,4,0,Master's in Data Science – Department of Mathematics | ETH Zurich,https://math.ethz.ch/studies/master-programmes/master-data-science.html
10,outcomes,5,0,DAS in Data Science – Department of Computer Science | ETH Zurich,https://inf.ethz.ch/continuing-education/das-datascience.html
4,tuition,1,0,Appendix requirement profile MSc Data Science,https://ethz.ch/content/dam/ethz/special-interest/infk/department/Images+and+Content/Studies/Master/DS/MSc-DataScience-Appendix.pdf
5,tuition,2,0,Exchange semester at a partner university – Department of Computer Science | ETH Zurich,https://inf.ethz.ch/studies/studentmobility/exchange-semester.html

### Curriculum Coding Rule

For each curriculum category:

- **1 = Core/Required:** The programme requires students to complete
  a specified course in the category, or requires students to select
  a specified number of courses/credits from a core-course group that
  covers the category.

- **0 = Not Core/Required:** Sufficient curriculum information is
  available, but the category appears only as an optional/elective
  component and is not required for degree completion.

- **NA = Insufficient Evidence:** Available official sources do not
  provide enough information to determine whether the category is
  required.

Elective availability alone is not sufficient for coding a category as 1.
All coding decisions must be validated against official university sources.

In [142]:
supporting_rows = []

for _, programme in programme_master.iterrows():

    programme_id = programme["programme_id"]

    print(
        f"\nSearching supporting pages: "
        f"{programme_id} | "
        f"{programme['university']}"
    )

    for page_type, query_terms in (
        SUPPORTING_PAGE_QUERIES.items()
    ):

        results = search_supporting_pages(
            university=programme["university"],
            programme_name=programme["programme_name"],
            official_domain=programme["official_domain"],
            page_type=page_type,
            query_terms=query_terms,
            max_results=5
        )

        for result in results:

            result["programme_id"] = programme_id
            result["university"] = programme["university"]
            result["programme_name"] = programme["programme_name"]

            supporting_rows.append(result)

        time.sleep(0.8)

supporting_sources = pd.DataFrame(
    supporting_rows
)

print(
    "Candidate supporting sources:",
    len(supporting_sources)
)

Searching supporting pages: EU_01 | Imperial College London

Searching supporting pages: EU_02 | ETH Zurich

Searching supporting pages: EU_03 | UCL
Error | UCL | curriculum | No results found.

Searching supporting pages: EU_04 | UCL
Error | UCL | tuition | No results found.

Searching supporting pages: EU_05 | Imperial College London

Searching supporting pages: EU_06 | University of Oxford
Error | University of Oxford | outcomes | No results found.

Searching supporting pages: EU_07 | UCL
Error | UCL | tuition | No results found.

Searching supporting pages: EU_08 | EPFL
Error | EPFL | curriculum | No results found.
Error | EPFL | admissions | No results found.
Error | EPFL | tuition | No results found.
Error | EPFL | outcomes | No results found.

Searching supporting pages: EU_09 | Technical University of Munich
Error | Technical University of Munich | curriculum | No results found.
Error | Technical University of Munich | admissions | No results found.
Error | Technical University of Munich | tuition | No results found.
Error | Technical University of Munich | outcomes | No results found.

Searching supporting pages: EU_10 | King's College London

Searching supporting pages: EU_11 | University of Edinburgh
Error | University of Edinburgh | curriculum | No results found.
Error | University of Edinburgh | admissions | No results found.
Error | University of Edinburgh | outcomes | No results found.

Searching supporting pages: EU_12 | University of Edinburgh
Error | University of Edinburgh | curriculum | No results found.
Error | University of Edinburgh | outcomes | No results found.

Searching supporting pages: EU_13 | Delft University of Technology

Searching supporting pages: EU_14 | KU Leuven
Error | KU Leuven | curriculum | No results found.
Error | KU Leuven | admissions | No results found.
Error | KU Leuven | tuition | No results found.

Searching supporting pages: EU_15 | Lund University
Error | Lund University | admissions | No results found.
Error | Lund University | tuition | No results found.
Error | Lund University | outcomes | No results found.

Searching supporting pages: EU_16 | Politecnico di Milano
Error | Politecnico di Milano | curriculum | No results found.

Searching supporting pages: EU_17 | Utrecht University
Error | Utrecht University | admissions | No results found.
Error | Utrecht University | tuition | No results found.

Searching supporting pages: EU_18 | RWTH Aachen University
Error | RWTH Aachen University | tuition | No results found.

Searching supporting pages: EU_19 | Technical University of Denmark
Error | Technical University of Denmark | admissions | No results found.
Error | Technical University of Denmark | tuition | No results found.

Searching supporting pages: EU_20 | Aalto University
Error | Aalto University | outcomes | No results found.
Candidate supporting sources: 219

In [143]:
supporting_sources[
    "relevance_score"
] = supporting_sources.apply(
    supporting_relevance_score,
    axis=1
)

supporting_sources[
    "validation_status"
] = "Not reviewed"

In [144]:
supporting_summary = (
    supporting_sources
    .groupby(
        [
            "programme_id",
            "page_type"
        ]
    )
    .agg(
        candidate_count=("url", "count"),
        max_relevance_score=(
            "relevance_score",
            "max"
        )
    )
    .reset_index()
)

supporting_summary

   programme_id   page_type  candidate_count  max_relevance_score
0         EU_01  admissions                5                    4
1         EU_01  curriculum                5                    2
2         EU_01    outcomes                5                    3
3         EU_01     tuition                5                    4
4         EU_02  admissions                2                    2
5         EU_02  curriculum                2                    3
6         EU_02    outcomes                5                    1
7         EU_02     tuition                2                    0
8         EU_03  admissions                5                    4
9         EU_03    outcomes                5                    2
10        EU_03     tuition                5                    4
11        EU_04  admissions                3                    0
12        EU_04  curriculum                5                    4
13        EU_04    outcomes                5                    2
14        EU_05  admissions                5                    1
15        EU_05  curriculum                5                    4
16        EU_05    outcomes                5                    6
17        EU_05     tuition                5                    4
18        EU_06  admissions                5                    4
19        EU_06  curriculum                5                    2
20        EU_06     tuition                5                    3
21        EU_07  admissions                5                    2
22        EU_07  curriculum                5                    3
23        EU_07    outcomes                5                    1
24        EU_10  admissions                5                    2
25        EU_10  curriculum                3                    4
26        EU_10    outcomes                5                    2
27        EU_10     tuition                5                    4
28        EU_11     tuition                5                    5
29        EU_12  admissions                5                    2
30        EU_12     tuition                5                    4
31        EU_13  admissions                2                    0
32        EU_13  curriculum                5                    2
33        EU_13    outcomes                5                    1
34        EU_13     tuition                5                    3
35        EU_14    outcomes                5                    1
36        EU_16  admissions                5                    0
37        EU_16    outcomes                5                    1
38        EU_16     tuition                2                    0
39        EU_17  curriculum                5                    2
40        EU_17    outcomes                3                    1
41        EU_18  curriculum                5                    5
42        EU_18    outcomes                5                    1
43        EU_19  curriculum                5                    3
44        EU_19    outcomes                5                    1
45        EU_20  admissions                5                    2
46        EU_20  curriculum                5                    1
47        EU_20     tuition                5                    3

In [146]:
coverage_table = (
    supporting_summary
    .pivot(
        index="programme_id",
        columns="page_type",
        values="candidate_count"
    )
    .fillna(0)
    .astype(int)
)

coverage_table

page_type     admissions  curriculum  outcomes  tuition
programme_id
EU_01                  5           5         5        5
EU_02                  2           2         5        2
EU_03                  5           0         5        5
EU_04                  3           5         5        0
EU_05                  5           5         5        5
EU_06                  5           5         0        5
EU_07                  5           5         5        0
EU_10                  5           3         5        5
EU_11                  0           0         0        5
EU_12                  5           0         0        5
EU_13                  2           5         5        5
EU_14                  0           0         5        0
EU_16                  5           0         5        2
EU_17                  0           5         3        0
EU_18                  0           5         5        0
EU_19                  0           5         5        0
EU_20                  5           5         0        5

In [147]:
coverage_binary = (
    coverage_table > 0
).astype(int)

coverage_binary

page_type     admissions  curriculum  outcomes  tuition
programme_id
EU_01                  1           1         1        1
EU_02                  1           1         1        1
EU_03                  1           0         1        1
EU_04                  1           1         1        0
EU_05                  1           1         1        1
EU_06                  1           1         0        1
EU_07                  1           1         1        0
EU_10                  1           1         1        1
EU_11                  0           0         0        1
EU_12                  1           0         0        1
EU_13                  1           1         1        1
EU_14                  0           0         1        0
EU_16                  1           0         1        1
EU_17                  0           1         1        0
EU_18                  0           1         1        0
EU_19                  0           1         1        0
EU_20                  1           1         0        1

In [148]:
coverage_check = coverage_binary.copy()

coverage_check["sources_found"] = (
    coverage_check.sum(axis=1)
)

coverage_check["sources_missing"] = (
    4 - coverage_check["sources_found"]
)

coverage_check.sort_values(
    "sources_missing",
    ascending=False
)

page_type,admissions,curriculum,outcomes,tuition,sources_found,sources_missing
programme_id,,,,,,
EU_11,0,0,0,1,1,3
EU_14,0,0,1,0,1,3
EU_17,0,1,1,0,2,2
EU_12,1,0,0,1,2,2
EU_18,0,1,1,0,2,2
EU_19,0,1,1,0,2,2
EU_04,1,1,1,0,3,1
EU_06,1,1,0,1,3,1
EU_03,1,0,1,1,3,1
EU_20,1,1,0,1,3,1
EU_16,1,0,1,1,3,1
EU_07,1,1,1,0,3,1
EU_01,1,1,1,1,4,0
EU_10,1,1,1,1,4,0
EU_05,1,1,1,1,4,0
EU_02,1,1,1,1,4,0
EU_13,1,1,1,1,4,0

## 2026 Structured Data Extraction

Extract candidate information from validated official programme and
supporting pages. Automated extraction is used only to identify candidate
evidence. Final variable coding is manually validated against official
university sources.

In [149]:
import re

DURATION_PATTERNS = [
    r'(\d+)\s*months?',
    r'(\d+)\s*month',
    r'(\d+)\s*years?',
    r'(\d+)\s*year',
]

def find_duration_evidence(text):

    if not text:
        return None

    matches = []

    for pattern in DURATION_PATTERNS:

        for match in re.finditer(
            pattern,
            text,
            flags=re.IGNORECASE
        ):

            start = max(
                0,
                match.start() - 120
            )

            end = min(
                len(text),
                match.end() + 120
            )

            matches.append(
                text[start:end]
            )

            if len(matches) >= 5:
                break

        if len(matches) >= 5:
            break

    if not matches:
        return None

    return " || ".join(matches)

In [150]:
duration_candidates = (
    page_text_df[
        [
            "programme_id",
            "university",
            "programme_name",
            "page_text"
        ]
    ]
    .copy()
)

duration_candidates[
    "duration_evidence"
] = duration_candidates[
    "page_text"
].apply(
    find_duration_evidence
)

duration_candidates[
    [
        "programme_id",
        "programme_name",
        "duration_evidence"
    ]
]

,programme_id,programme_name,duration_evidence
0,EU_01,MSc Business Analytics & AI,"xperience? We are pleased to offer an optional extended term , that will allow you to extend your programme duration to 16 months. This will give you the opportunity to commit to a longer Work Placement, gaining even more professional and global exp || 0)20 7594 9000 Do you offer any programmes on a part-time basis? Almost all of the MSc programmes we have available are 12 month, full-time programmes. The only exception is our MSc Strategic Marketing (online, part-time) programme, which is availa || xperience? We are pleased to offer an optional extended term , that will allow you to extend your programme duration to 16 months. This will give you the opportunity to commit to a longer Work Placement, gaining even more professional and global ex || 0)20 7594 9000 Do you offer any programmes on a part-time basis? Almost all of the MSc programmes we have available are 12 month, full-time programmes. The only exception is our MSc Strategic Marketing (online, part-time) programme, which ..."
1,EU_02,MSc Data Science,ell as Information Technology and Electrical Engineering. Language of instruction English Credits | duration 120 ECTS | 2 years Academic title Master of Science ETH in Data Science Qualifying disciplines listed alphabetically: Computer Science Ele || ell as Information Technology and Electrical Engineering. Language of instruction English Credits | duration 120 ECTS | 2 years Academic title Master of Science ETH in Data Science Qualifying disciplines listed alphabetically: Computer Science El
2,EU_05,MSc Statistics (Data Science and Machine Learning),ions open on Wednesday 30 September 2026 Request Info Add to course compare Course key facts Qualification MSc Duration 1 year Start date October 2027 Study mode Full-time Delivered by Department of Mathematics Location South Kensington Applicati || ions open on Wednesday 30 September 2026 Request Info Add to course compare Course key facts Qualification MSc Duration 1 year Start date October 2027 Study mode Full-time Delivered by Department of Mathematics Location South Kensington Applicati
3,EU_08,Master in Data Science,None
4,EU_09,MSc Mathematics in Data Science,None
5,EU_10,MSc Data Science,"Florence Nightingale Faculty of Nursing & Midwifery (QS 2026). Related courses Artificial Intelligence for Science MSc 1 year full-time, September to September Full-time In person Computational Finance MSc 1 year full-time Full-time In person Ad || ial Intelligence for Science MSc 1 year full-time, September to September Full-time In person Computational Finance MSc 1 year full-time Full-time In person Advanced Computing MSc One year full-time, September to September Full-time In person Cyb || time In person Advanced Computing MSc One year full-time, September to September Full-time In person Cyber Security MSc 1 year full-time, September to September Full-time In person || Florence Nightingale Faculty of Nursing & Midwifery (QS 2026). Related courses Artificial Intelligence for Science MSc 1 year full-time, September to September Full-time In person Computational Finance MSc 1 year full-time Full-time In person Ad || ial Intelligence for Science MSc 1 year full-time, September t..."
6,EU_11,MSc Business Analytics,None
7,EU_12,MSc Data Science,"ught Subject: Computing and Informatics Year of entry: 2026 Study options Mode of study On campus Part-time MSc | up to 3 years | Start date: multiple dates Full-time MSc | 1 year | Start date: September 2026 Key facts School School of Informatics || : 2026 Study options Mode of study On campus Part-time MSc | up to 3 years | Start date: multiple dates Full-time MSc | 1 year | Start date: September 2026 Key facts School School of Informatics College College of Science and Engineering Programm || sentation delivered by Programme Director, Paolo Guagliardo. Study options This programme can be studied full-time over 1 year or part-time for up to 3 years. Part-time study Those studying the two-year part-time option take half of the taught cr || me Director, Paolo Guagliardo. Study options This programme can be studied full-time over 1 year or part-time for up to 3 years. Part-time study Those studying the two-year part-time option take half of the taught credits in their first year, an..."
8,EU_13,MSc Data Science and Artificial Intelligence Technology,"gree Master of Data Science and Artificial Intelligence Technology Accreditation Accredited by the NVAO Credits 120 EC, 24 Months Type Regular study programme Mode Full-time Language of instruction English Start September Explore this master's chall || gree Master of Data Science and Artificial Intelligence Technology Accreditation Accredited by the NVAO Credits 120 EC, 24 Months Type Regular study programme Mode Full-time Language of instruction English Start September Explore this master's chal"
9,EU_14,Master of Statistics and Data Science,None
10,EU_15,MSc Data Analytics and Business Economics,- Master's Programme | Lund University Data Analytics and Business Economics - Master's Programme Master's programme • 1 year • 60 credits Transforming data into insights that can enhance decision-making is a key challenge for companies of every || lts. Application dates Play video Programme video: MSc Data Analytics and Business Economics Start Autumn 2026 Duration 1 year Level Master's Language English Place of study Lund Application dates Overview Teaching and learning Career prospects O || - Master's Programme | Lund University Data Analytics and Business Economics - Master's Programme Master's programme • 1 year • 60 credits Transforming data into insights that can enhance decision-making is a key challenge for companies of every || lts. Application dates Play video Programme video: MSc Data Analytics and Business Economics Start Autumn 2026 Duration 1 year Level Master's Language English Place of study Lund Application dates Overview Teaching and learning Career prospects O
11,EU_16,Master in Business Analytics and Data Science,"n the class means the sooner you apply, the better. If you are a non-EU candidate, we recommend that you apply at least 3 months before the programme starts, to leave enough time for a Statement of Comparability of your degree and to apply for your || ur appointment. REGISTER NOW Subject Artificial Intelligence & Data Science Intake October 2026 Location Milan Duration 12 months Format Full Time Language English Individuals €25,000 € 13,000.00 (POLIMI MSc Alumni) Experience Less than 3 years Appl || n the class means the sooner you apply, the better. If you are a non-EU candidate, we recommend that you apply at least 3 months before the programme starts, to leave enough time for a Statement of Comparability of your degree and to apply for you || ur appointment. REGISTER NOW Subject Artificial Intelligence & Data Science Intake October 2026 Location Milan Duration 12 months Format Full Time Language English Individuals €25,000 € 13,000.00 (POLIMI MSc Alumni) Experience Less than 3 y..."
12,EU_17,MSc Data Science,"ble computers to represent knowledge and reason. Related Master’s Programmes This programme operates in parallel to the 1 year Master’s programme in Applied Data Science , that instead aims on how to apply existing data science tools and solution || yourself. Key facts Degree: Informatica (MSc) Language of instruction: English Mode of study: Full-time Study duration: 2 years Start: February, September Tuition fees: Dutch and other EU/EEA students (statutory fee, full-time) 2026-2027: € 2,694 || ble computers to represent knowledge and reason. Related Master’s Programmes This programme operates in parallel to the 1 year Master’s programme in Applied Data Science , that instead aims on how to apply existing data science tools and solution || yourself. Key facts Degree: Informatica (MSc) Language of instruction: English Mode of study: Full-time Study duration: 2 years Start: February, September Tuition fees: Dutch and other EU/EEA students (statutory fee, full-time) 2026-2027: € 2,694"
13,EU_18,MSc Data Science,None
14,EU_19,MSc Business Analytics,None
15,EU_20,Master's Programme in Business Analytics,None

In [151]:
duration_review = programme_master[
    [
        "programme_id",
        "university",
        "programme_name",
        "official_url"
    ]
].copy()

duration_review[
    "duration_months"
] = pd.NA

duration_review[
    "duration_evidence"
] = pd.NA

duration_review[
    "duration_source_url"
] = pd.NA

duration_review[
    "validation_status"
] = "Not reviewed"

duration_review

,programme_id,university,programme_name,official_url,duration_months,duration_evidence,duration_source_url,validation_status
0,EU_01,Imperial College London,MSc Business Analytics & AI,https://www.imperial.ac.uk/business-school/masters/business-analytics/,<NA>,<NA>,<NA>,Not reviewed
1,EU_02,ETH Zurich,MSc Data Science,https://ethz.ch/en/studies/master/degree-programmes/engineering-sciences/data-science.html,<NA>,<NA>,<NA>,Not reviewed
2,EU_03,UCL,MSc Business Analytics,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/business-analytics-msc-2026,<NA>,<NA>,<NA>,Not reviewed
3,EU_04,UCL,MSc Data Science,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc,<NA>,<NA>,<NA>,Not reviewed
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),https://www.imperial.ac.uk/study/courses/postgraduate-taught/statistics-data-science/,<NA>,<NA>,<NA>,Not reviewed
5,EU_06,University of Oxford,MSc in Social Data Science,https://www.ox.ac.uk/admissions/graduate/courses/msc-social-data-science,<NA>,<NA>,<NA>,Not reviewed
6,EU_07,UCL,MSc Data Science and Public Policy,https://www.ucl.ac.uk/social-historical-sciences/economics/study/data-science-and-public-policy-msc,<NA>,<NA>,<NA>,Not reviewed
7,EU_08,EPFL,Master in Data Science,https://www.epfl.ch/education/master/programs/data-science/,<NA>,<NA>,<NA>,Not reviewed
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,https://www.tum.de/en/studies/degree-programs/detail/mathematics-in-data-science-master-of-science-msc,<NA>,<NA>,<NA>,Not reviewed
9,EU_10,King's College London,MSc Data Science,https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc,<NA>,<NA>,<NA>,Not reviewed
10,EU_11,University of Edinburgh,MSc Business Analytics,https://www.business-school.ed.ac.uk/msc/business-analytics,<NA>,<NA>,<NA>,Not reviewed
11,EU_12,University of Edinburgh,MSc Data Science,https://study.ed.ac.uk/programmes/postgraduate-taught/902-data-science,<NA>,<NA>,<NA>,Not reviewed
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,https://www.tudelft.nl/en/education/programmes/masters/dsait/msc-data-science-and-artificial-intelligence-technology,<NA>,<NA>,<NA>,Not reviewed
13,EU_14,KU Leuven,Master of Statistics and Data Science,https://onderwijsaanbod.kuleuven.be/opleidingen/e/SC_51016989/diploma_omschrijving,<NA>,<NA>,<NA>,Not reviewed
14,EU_15,Lund University,MSc Data Analytics and Business Economics,https://www.lunduniversity.lu.se/study/data-analytics-and-business-economics-masters-programme-EAGDA,<NA>,<NA>,<NA>,Not reviewed
15,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,https://www.gsom.polimi.it/en/course/master-business-analytics-data-science,<NA>,<NA>,<NA>,Not reviewed
16,EU_17,Utrecht University,MSc Data Science,https://www.uu.nl/en/masters/data-science,<NA>,<NA>,<NA>,Not reviewed
17,EU_18,RWTH Aachen University,MSc Data Science,https://sc.informatik.rwth-aachen.de/en/studium/master/master-data-science/,<NA>,<NA>,<NA>,Not reviewed
18,EU_19,Technical University of Denmark,MSc Business Analytics,https://www.dtu.dk/english/education/graduate/msc-programmes/business-analytics,<NA>,<NA>,<NA>,Not reviewed
19,EU_20,Aalto University,Master's Programme in Business Analytics,https://www.aalto.fi/en/programmes/masters-programme-in-business-analytics,<NA>,<NA>,<NA>,Not reviewed

In [152]:
mask = (
    duration_review["programme_id"]
    == "EU_02"
)

duration_review.loc[
    mask,
    "duration_months"
] = 24

duration_review.loc[
    mask,
    "duration_evidence"
] = "120 ECTS | 2 years"

duration_review.loc[
    mask,
    "duration_source_url"
] = (
    "https://ethz.ch/en/studies/"
    "master/degree-programmes/"
    "engineering-sciences/"
    "data-science.html"
)

duration_review.loc[
    mask,
    "validation_status"
] = "Validated"

In [153]:
duration_review[
    duration_review["programme_id"]
    == "EU_02"
].T

                                                                                                              1
programme_id                                                                                              EU_02
university                                                                                           ETH Zurich
programme_name                                                                                 MSc Data Science
official_url         https://ethz.ch/en/studies/master/degree-programmes/engineering-sciences/data-science.html
duration_months                                                                                              24
duration_evidence                                                                            120 ECTS | 2 years
duration_source_url  https://ethz.ch/en/studies/master/degree-programmes/engineering-sciences/data-science.html
validation_status                                                                                     Validated

### Programme-Level Manual Validation

Each programme is reviewed using official university sources.
Automated search and extraction are used only to identify candidate
sources. Final coding is entered after manual validation.

Validation proceeds programme by programme so that curriculum,
admissions, tuition, duration, and outcomes can be reviewed together.

In [154]:
validation_table = programme_master[
    [
        "programme_id",
        "university",
        "programme_name",
        "official_url"
    ]
].copy()

validation_table["curriculum_source"] = pd.NA
validation_table["admissions_source"] = pd.NA
validation_table["tuition_source"] = pd.NA
validation_table["duration_source"] = pd.NA
validation_table["outcomes_source"] = pd.NA

validation_table["validation_notes"] = pd.NA
validation_table["validation_status"] = "Not reviewed"

validation_table

,programme_id,university,programme_name,official_url,curriculum_source,admissions_source,tuition_source,duration_source,outcomes_source,validation_notes,validation_status
0,EU_01,Imperial College London,MSc Business Analytics & AI,https://www.imperial.ac.uk/business-school/masters/business-analytics/,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed
1,EU_02,ETH Zurich,MSc Data Science,https://ethz.ch/en/studies/master/degree-programmes/engineering-sciences/data-science.html,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed
2,EU_03,UCL,MSc Business Analytics,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/business-analytics-msc-2026,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed
3,EU_04,UCL,MSc Data Science,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),https://www.imperial.ac.uk/study/courses/postgraduate-taught/statistics-data-science/,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed
5,EU_06,University of Oxford,MSc in Social Data Science,https://www.ox.ac.uk/admissions/graduate/courses/msc-social-data-science,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed
6,EU_07,UCL,MSc Data Science and Public Policy,https://www.ucl.ac.uk/social-historical-sciences/economics/study/data-science-and-public-policy-msc,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed
7,EU_08,EPFL,Master in Data Science,https://www.epfl.ch/education/master/programs/data-science/,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,https://www.tum.de/en/studies/degree-programs/detail/mathematics-in-data-science-master-of-science-msc,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed
9,EU_10,King's College London,MSc Data Science,https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed
10,EU_11,University of Edinburgh,MSc Business Analytics,https://www.business-school.ed.ac.uk/msc/business-analytics,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed
11,EU_12,University of Edinburgh,MSc Data Science,https://study.ed.ac.uk/programmes/postgraduate-taught/902-data-science,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,https://www.tudelft.nl/en/education/programmes/masters/dsait/msc-data-science-and-artificial-intelligence-technology,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed
13,EU_14,KU Leuven,Master of Statistics and Data Science,https://onderwijsaanbod.kuleuven.be/opleidingen/e/SC_51016989/diploma_omschrijving,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed
14,EU_15,Lund University,MSc Data Analytics and Business Economics,https://www.lunduniversity.lu.se/study/data-analytics-and-business-economics-masters-programme-EAGDA,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed
15,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,https://www.gsom.polimi.it/en/course/master-business-analytics-data-science,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed
16,EU_17,Utrecht University,MSc Data Science,https://www.uu.nl/en/masters/data-science,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed
17,EU_18,RWTH Aachen University,MSc Data Science,https://sc.informatik.rwth-aachen.de/en/studium/master/master-data-science/,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed
18,EU_19,Technical University of Denmark,MSc Business Analytics,https://www.dtu.dk/english/education/graduate/msc-programmes/business-analytics,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed
19,EU_20,Aalto University,Master's Programme in Business Analytics,https://www.aalto.fi/en/programmes/masters-programme-in-business-analytics,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed

In [155]:
mask = (
    validation_table["programme_id"]
    == "EU_01"
)

validation_table.loc[
    mask,
    "curriculum_source"
] = (
    "https://www.imperial.ac.uk/"
    "business-school/masters/"
    "business-analytics/"
)

validation_table.loc[
    mask,
    "admissions_source"
] = (
    "https://www.imperial.ac.uk/"
    "business-school/masters/"
    "business-analytics/admissions/"
)

validation_table.loc[
    mask,
    "tuition_source"
] = (
    "https://www.imperial.ac.uk/"
    "business-school/masters/"
    "business-analytics/fees-and-funding/"
)

validation_table.loc[
    mask,
    "duration_source"
] = (
    "https://www.imperial.ac.uk/"
    "business-school/masters/"
    "business-analytics/"
)

validation_table.loc[
    mask,
    "outcomes_source"
] = (
    "https://www.imperial.ac.uk/"
    "business-school/masters/"
    "business-analytics/"
)

validation_table.loc[
    mask,
    "validation_notes"
] = (
    "Official Imperial Business School sources reviewed."
)

validation_table.loc[
    mask,
    "validation_status"
] = "Validated"

In [156]:
validation_table[
    validation_table["programme_id"]
    == "EU_01"
].T

                                                                                                         0
programme_id                                                                                         EU_01
university                                                                         Imperial College London
programme_name                                                                 MSc Business Analytics & AI
official_url                        https://www.imperial.ac.uk/business-school/masters/business-analytics/
curriculum_source                   https://www.imperial.ac.uk/business-school/masters/business-analytics/
admissions_source        https://www.imperial.ac.uk/business-school/masters/business-analytics/admissions/
tuition_source     https://www.imperial.ac.uk/business-school/masters/business-analytics/fees-and-funding/
duration_source                     https://www.imperial.ac.uk/business-school/masters/business-analytics/
outcomes_source                     https://www.imperial.ac.uk/business-school/masters/business-analytics/
validation_notes                                       Official Imperial Business School sources reviewed.
validation_status                                                                                Validated

In [157]:
mask = (
    europe_2026["programme_id"]
    == "EU_01"
)

europe_2026.loc[
    mask,
    "GRE_GMAT_policy"
] = "Not required"

europe_2026.loc[
    mask,
    "tuition_amount"
] = 47000

europe_2026.loc[
    mask,
    "currency"
] = "GBP"

europe_2026.loc[
    mask,
    "tuition_basis"
] = "Total programme tuition (international)"

europe_2026.loc[
    mask,
    "duration_months"
] = 12

europe_2026.loc[
    mask,
    "outcomes_reported"
] = 1

europe_2026.loc[
    mask,
    "source_type"
] = "Official university website"

europe_2026.loc[
    mask,
    "access_date"
] = "2026-09-23"

In [158]:
europe_2026[
    europe_2026["programme_id"]
    == "EU_01"
].T

                                                                                                                                                                    0
programme_id                                                                                                                                                    EU_01
university                                                                                                                                    Imperial College London
programme_name                                                                                                                            MSc Business Analytics & AI
year                                                                                                                                                             2026
country                                                                                                                                                United Kingdom
region                                                                                                                                                         Europe
school_type                                                                                                                                                      <NA>
college_type                                                                                                                                                     <NA>
ranking_tier                                                                                                                                                     <NA>
statistics_core                                                                                                                                                     1
programming_core                                                                                                                                                    1
machine_learning_core                                                                                                                                               1
data_visualization_core                                                                                                                                             1
business_analytics_core                                                                                                                                             1
core_category_count                                                                                                                                                 5
prerequisites            Quantitative undergraduate degree; quantitative experience typically includes advanced calculus, probability, statistics, and linear algebra
GRE_GMAT_policy                                                                                                                                          Not required
tuition_amount                                                                                                                                                  47000
currency                                                                                                                                                          GBP
tuition_basis                                                                                                                 Total programme tuition (international)
duration_months                                                                                                                                                    12
outcomes_reported                                                                                                                                                   1
new_programme                                                                                                                                                    <NA>
source_type                                                                                                                               Official university website
source_url                                                                                     https://www.imperial.ac.uk/business-school/masters/business-analytics/
access_date                                                                                                                                                2026-09-23

In [159]:
mask = (
    validation_table["programme_id"]
    == "EU_02"
)

validation_table.loc[
    mask,
    "curriculum_source"
] = (
    "https://ethz.ch/en/studies/master/"
    "degree-programmes/engineering-sciences/"
    "data-science.html"
)

validation_table.loc[
    mask,
    "admissions_source"
] = (
    "https://ethz.ch/en/studies/master/"
    "application/master-datascience.html"
)

validation_table.loc[
    mask,
    "tuition_source"
] = (
    "https://ethz.ch/students/en/studies/"
    "financial/tuition-fees.html"
)

validation_table.loc[
    mask,
    "duration_source"
] = (
    "https://ethz.ch/en/studies/master/"
    "degree-programmes/engineering-sciences/"
    "data-science.html"
)

validation_table.loc[
    mask,
    "outcomes_source"
] = pd.NA

validation_table.loc[
    mask,
    "validation_notes"
] = (
    "Official ETH Zurich programme, admissions, "
    "requirement-profile and tuition sources reviewed. "
    "No programme-specific employment outcomes source "
    "validated yet."
)

validation_table.loc[
    mask,
    "validation_status"
] = "Validated"

In [160]:
mask = (
    europe_2026["programme_id"]
    == "EU_02"
)

europe_2026.loc[
    mask,
    "prerequisites"
] = (
    "Bachelor's degree of at least 180 ECTS; "
    "required background in Mathematics and "
    "Computer Science; discipline requirements "
    "profile totals 76 ECTS."
)

In [161]:
europe_2026.loc[
    mask,
    "GRE_GMAT_policy"
] = "Not reported"

In [162]:
europe_2026.loc[
    mask,
    "tuition_amount"
] = 2190

europe_2026.loc[
    mask,
    "currency"
] = "CHF"

europe_2026.loc[
    mask,
    "tuition_basis"
] = (
    "Per semester; threefold tuition fee "
    "for students assigned to fee group 2"
)

In [163]:
europe_2026.loc[
    mask,
    "duration_months"
] = 24

In [164]:
europe_2026.loc[
    mask,
    "outcomes_reported"
] = 0

In [165]:
europe_2026.loc[
    mask,
    "source_type"
] = "Official university website"

europe_2026.loc[
    mask,
    "access_date"
] = "2026-09-23"

In [166]:
europe_2026[
    europe_2026["programme_id"]
    == "EU_02"
].T

                                                                                                                                                                        1
programme_id                                                                                                                                                        EU_02
university                                                                                                                                                     ETH Zurich
programme_name                                                                                                                                           MSc Data Science
year                                                                                                                                                                 2026
country                                                                                                                                                       Switzerland
region                                                                                                                                                             Europe
school_type                                                                                                                                                          <NA>
college_type                                                                                                                                                         <NA>
ranking_tier                                                                                                                                                         <NA>
statistics_core                                                                                                                                                      <NA>
programming_core                                                                                                                                                     <NA>
machine_learning_core                                                                                                                                                <NA>
data_visualization_core                                                                                                                                              <NA>
business_analytics_core                                                                                                                                              <NA>
core_category_count                                                                                                                                                  <NA>
prerequisites            Bachelor's degree of at least 180 ECTS; required background in Mathematics and Computer Science; discipline requirements profile totals 76 ECTS.
GRE_GMAT_policy                                                                                                                                              Not reported
tuition_amount                                                                                                                                                       2190
currency                                                                                                                                                              CHF
tuition_basis                                                                                    Per semester; threefold tuition fee for students assigned to fee group 2
duration_months                                                                                                                                                        24
outcomes_reported                                                                                                                                                       0
new_programme                                                                                                                                                        <NA>
source_type                                                                                                                                   Official university website
source_url                                                                     https://ethz.ch/en/studies/master/degree-programmes/engineering-sciences/data-science.html
access_date                                                                                                                                                    2026-09-23

In [167]:
mask = (
    validation_table["programme_id"]
    == "EU_03"
)

ucl_2026_url = (
    "https://www.ucl.ac.uk/"
    "prospective-students/graduate/"
    "taught-degrees/business-analytics-msc"
)

validation_table.loc[
    mask,
    "curriculum_source"
] = ucl_2026_url

validation_table.loc[
    mask,
    "admissions_source"
] = ucl_2026_url

validation_table.loc[
    mask,
    "tuition_source"
] = ucl_2026_url

validation_table.loc[
    mask,
    "duration_source"
] = ucl_2026_url

validation_table.loc[
    mask,
    "outcomes_source"
] = pd.NA

validation_table.loc[
    mask,
    "validation_notes"
] = (
    "Official UCL 2026/27 programme page reviewed. "
    "Programme-specific quantitative employment "
    "outcomes not yet validated."
)

validation_table.loc[
    mask,
    "validation_status"
] = "Validated"

In [168]:
mask = (
    europe_2026["programme_id"]
    == "EU_03"
)

europe_2026.loc[
    mask,
    "prerequisites"
] = (
    "Typically an upper second-class Bachelor's "
    "degree (UK 2:1) or overseas equivalent; "
    "lower second-class degrees may be considered "
    "with strong relevant experience."
)

In [169]:
europe_2026.loc[
    mask,
    "GRE_GMAT_policy"
] = "Not reported"

In [170]:
europe_2026.loc[
    mask,
    "tuition_amount"
] = 46700

europe_2026.loc[
    mask,
    "currency"
] = "GBP"

europe_2026.loc[
    mask,
    "tuition_basis"
] = (
    "Full-time overseas tuition fee "
    "for 2026/27"
)

In [171]:
europe_2026.loc[
    mask,
    "duration_months"
] = 12

europe_2026.loc[
    mask,
    "outcomes_reported"
] = 0

In [172]:
europe_2026.loc[
    mask,
    "source_type"
] = "Official university website"

europe_2026.loc[
    mask,
    "access_date"
] = "2026-09-23"

In [173]:
europe_2026[
    europe_2026["programme_id"]
    == "EU_03"
].T

                                                                                                                                                                                        2
programme_id                                                                                                                                                                        EU_03
university                                                                                                                                                                            UCL
programme_name                                                                                                                                                     MSc Business Analytics
year                                                                                                                                                                                 2026
country                                                                                                                                                                    United Kingdom
region                                                                                                                                                                             Europe
school_type                                                                                                                                                                          <NA>
college_type                                                                                                                                                                         <NA>
ranking_tier                                                                                                                                                                         <NA>
statistics_core                                                                                                                                                                      <NA>
programming_core                                                                                                                                                                     <NA>
machine_learning_core                                                                                                                                                                <NA>
data_visualization_core                                                                                                                                                              <NA>
business_analytics_core                                                                                                                                                              <NA>
core_category_count                                                                                                                                                                  <NA>
prerequisites            Typically an upper second-class Bachelor's degree (UK 2:1) or overseas equivalent; lower second-class degrees may be considered with strong relevant experience.
GRE_GMAT_policy                                                                                                                                                              Not reported
tuition_amount                                                                                                                                                                      46700
currency                                                                                                                                                                              GBP
tuition_basis                                                                                                                                  Full-time overseas tuition fee for 2026/27
duration_months                                                                                                                                                                        12
outcomes_reported                                                                                                                                                                       0
new_programme                                                                                                                                                                        <NA>
source_type                                                                                                                                                   Official university website
source_url                                                                                 https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/business-analytics-msc-2026
access_date                                                                                                                                                                    2026-09-23

In [174]:
# ============================================================
# Batch review table: EU_04 - EU_20
# ============================================================

batch_ids = [
    f"EU_{i:02d}"
    for i in range(4, 21)
]

batch_review = programme_master[
    programme_master["programme_id"].isin(batch_ids)
][
    [
        "programme_id",
        "university",
        "programme_name",
        "official_url"
    ]
].copy()

# Candidate values extracted from official sources
batch_review["prerequisites_candidate"] = pd.NA
batch_review["GRE_GMAT_candidate"] = pd.NA

batch_review["tuition_candidate"] = pd.NA
batch_review["currency_candidate"] = pd.NA
batch_review["tuition_basis_candidate"] = pd.NA

batch_review["duration_candidate"] = pd.NA
batch_review["outcomes_candidate"] = pd.NA

# Curriculum evidence
batch_review["statistics_evidence"] = pd.NA
batch_review["programming_evidence"] = pd.NA
batch_review["machine_learning_evidence"] = pd.NA
batch_review["visualization_evidence"] = pd.NA
batch_review["business_analytics_evidence"] = pd.NA

# Evidence / source
batch_review["evidence_text"] = pd.NA
batch_review["source_url"] = pd.NA

# Human validation
batch_review["validation_status"] = "Not reviewed"
batch_review["validation_notes"] = pd.NA

batch_review.reset_index(
    drop=True,
    inplace=True
)

batch_review

,programme_id,university,programme_name,official_url,prerequisites_candidate,GRE_GMAT_candidate,tuition_candidate,currency_candidate,tuition_basis_candidate,duration_candidate,outcomes_candidate,statistics_evidence,programming_evidence,machine_learning_evidence,visualization_evidence,business_analytics_evidence,evidence_text,source_url,validation_status,validation_notes
0,EU_04,UCL,MSc Data Science,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed,<NA>
1,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),https://www.imperial.ac.uk/study/courses/postgraduate-taught/statistics-data-science/,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed,<NA>
2,EU_06,University of Oxford,MSc in Social Data Science,https://www.ox.ac.uk/admissions/graduate/courses/msc-social-data-science,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed,<NA>
3,EU_07,UCL,MSc Data Science and Public Policy,https://www.ucl.ac.uk/social-historical-sciences/economics/study/data-science-and-public-policy-msc,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed,<NA>
4,EU_08,EPFL,Master in Data Science,https://www.epfl.ch/education/master/programs/data-science/,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed,<NA>
5,EU_09,Technical University of Munich,MSc Mathematics in Data Science,https://www.tum.de/en/studies/degree-programs/detail/mathematics-in-data-science-master-of-science-msc,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed,<NA>
6,EU_10,King's College London,MSc Data Science,https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed,<NA>
7,EU_11,University of Edinburgh,MSc Business Analytics,https://www.business-school.ed.ac.uk/msc/business-analytics,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed,<NA>
8,EU_12,University of Edinburgh,MSc Data Science,https://study.ed.ac.uk/programmes/postgraduate-taught/902-data-science,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed,<NA>
9,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,https://www.tudelft.nl/en/education/programmes/masters/dsait/msc-data-science-and-artificial-intelligence-technology,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed,<NA>
10,EU_14,KU Leuven,Master of Statistics and Data Science,https://onderwijsaanbod.kuleuven.be/opleidingen/e/SC_51016989/diploma_omschrijving,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed,<NA>
11,EU_15,Lund University,MSc Data Analytics and Business Economics,https://www.lunduniversity.lu.se/study/data-analytics-and-business-economics-masters-programme-EAGDA,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed,<NA>
12,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,https://www.gsom.polimi.it/en/course/master-business-analytics-data-science,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed,<NA>
13,EU_17,Utrecht University,MSc Data Science,https://www.uu.nl/en/masters/data-science,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed,<NA>
14,EU_18,RWTH Aachen University,MSc Data Science,https://sc.informatik.rwth-aachen.de/en/studium/master/master-data-science/,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed,<NA>
15,EU_19,Technical University of Denmark,MSc Business Analytics,https://www.dtu.dk/english/education/graduate/msc-programmes/business-analytics,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed,<NA>
16,EU_20,Aalto University,Master's Programme in Business Analytics,https://www.aalto.fi/en/programmes/masters-programme-in-business-analytics,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Not reviewed,<NA>

In [175]:
print(supporting_summary.columns.tolist())

display(
    supporting_summary.head(10)
)

['programme_id', 'page_type', 'candidate_count', 'max_relevance_score']

  programme_id   page_type  candidate_count  max_relevance_score
0        EU_01  admissions                5                    4
1        EU_01  curriculum                5                    2
2        EU_01    outcomes                5                    3
3        EU_01     tuition                5                    4
4        EU_02  admissions                2                    2
5        EU_02  curriculum                2                    3
6        EU_02    outcomes                5                    1
7        EU_02     tuition                2                    0
8        EU_03  admissions                5                    4
9        EU_03    outcomes                5                    2

In [176]:
# Find DataFrames that may contain the actual supporting-page URLs

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        cols = obj.columns.tolist()

        if (
            "programme_id" in cols
            and "url" in cols
        ):
            print(
                name,
                "->",
                obj.shape,
                "->",
                cols
            )

_92 -> (40, 6) -> ['programme_id', 'university', 'programme_name', 'title', 'url', 'match_score']
candidates -> (5, 11) -> ['university', 'search_term', 'query', 'result_rank', 'title', 'url', 'result_domain', 'snippet', 'match_score', 'programme_id', 'programme_name']
url_review -> (40, 6) -> ['programme_id', 'university', 'programme_name', 'title', 'url', 'match_score']
_93 -> (40, 6) -> ['programme_id', 'university', 'programme_name', 'title', 'url', 'match_score']
missing_url_review -> (25, 10) -> ['university', 'search_term', 'query', 'result_rank', 'title', 'url', 'result_domain', 'snippet', 'programme_id', 'programme_name']
_98 -> (25, 6) -> ['programme_id', 'university', 'programme_name', 'title', 'url', 'result_rank']
all_url_candidates -> (68, 12) -> ['programme_id', 'university', 'programme_name', 'title', 'url', 'match_score', 'search_term', 'query', 'result_rank', 'result_domain', 'snippet', 'primary_score']
manual_url_rows -> (3, 5) -> ['programme_id', 'university', 'programme_name', 'title', 'url']
primary_url_candidates -> (20, 12) -> ['programme_id', 'university', 'programme_name', 'title', 'url', 'match_score', 'search_term', 'query', 'result_rank', 'result_domain', 'snippet', 'primary_score']
_105 -> (20, 6) -> ['programme_id', 'university', 'programme_name', 'title', 'url', 'primary_score']
_106 -> (4, 6) -> ['programme_id', 'university', 'programme_name', 'title', 'url', 'primary_score']
fetch_status -> (20, 8) -> ['programme_id', 'university', 'programme_name', 'url', 'status_code', 'html_length', 'error', 'collection_status']
page_text_df -> (16, 6) -> ['programme_id', 'university', 'programme_name', 'url', 'text_length', 'page_text']
eth_supporting -> (11, 7) -> ['page_type', 'result_rank', 'title', 'url', 'snippet', 'programme_id', 'relevance_score']
_138 -> (11, 5) -> ['programme_id', 'page_type', 'result_rank', 'title', 'url']
supporting_sources -> (219, 10) -> ['page_type', 'result_rank', 'title', 'url', 'snippet', 'programme_id', 'university', 'programme_name', 'relevance_score', 'validation_status']

In [177]:
# ============================================================
# Select the best candidate supporting page
# for each programme × page type
# ============================================================

best_supporting_sources = (
    supporting_sources[
        supporting_sources["programme_id"].isin(batch_ids)
    ]
    .sort_values(
        [
            "programme_id",
            "page_type",
            "relevance_score",
            "result_rank"
        ],
        ascending=[True, True, False, True]
    )
    .drop_duplicates(
        subset=["programme_id", "page_type"],
        keep="first"
    )
    [
        [
            "programme_id",
            "page_type",
            "title",
            "url",
            "snippet",
            "relevance_score"
        ]
    ]
    .reset_index(drop=True)
)

display(best_supporting_sources)

,programme_id,page_type,title,url,snippet,relevance_score
0,EU_04,admissions,Data Science MSc | Study at UCL,https://www.ucl.ac.uk/study/prospective-students/graduate/courses/data-science-msc,"Graduate destinations Graduates of the MSc Data Science in UCL Statistical Science progress into professional, normally data-driven roles such as data scientist, machine learning engineer, data analyst and data engineer or pursue further academic study.",0
1,EU_04,curriculum,Data Science MSc | Study at UCL,https://www.ucl.ac.uk/study/prospective-students/graduate/courses/data-science-msc,"The course combines training in core statistical and machine learning methodology, beginning at an introductory level, with a range of optional modules covering more specialised knowledge in statistical computing and modelling.",4
2,EU_04,outcomes,MSc Finance with Data Science | UCL School of Management,https://www.msi.ucl.ac.uk/msc-finance-data-science,"Mar 18, 2026 · Our graduates pursue global careers across a wide range of roles, sectors, and geographies. Popular sectors include Consulting, Banking and Finance, Marketing, Technology, and Data & Analytics.",2
3,EU_05,admissions,MSc Statistics (Data Science and Machine Learning),https://www.imperial.ac.uk/study/courses/postgraduate-taught/statistics-data-science/,"For admission to this course, you must achieve the higher university requirement in the appropriate English language qualification. For details of the minimum grades required to achieve this requirement, please see the English language requirements.",1
4,EU_05,curriculum,MSc Statistics (Data Science and Machine Learning),https://www.imperial.ac.uk/study/courses/postgraduate-taught/statistics-data-science/,Become familiar with the most common data scientific methods and their uses and misuses. You choose at least three modules from Group A and the remainder from Group B to total 25-27.5 ECTS. Each module is worth 5 ECTS unless otherwise stated.,4
5,EU_05,outcomes,MSc Business Analytics & AI - Business School,https://imperial.ac.uk/business-school/programmes/msc-business-analytics/careers/employment-report,"With the range of electives, you can tailor the programme content to suit your career goals and interests. The flexibility of the content is reflected in the range of graduate destinations, from technology companies like Amazon and Google to finance organisations like HSBC or Mastercard. Our graduates also work in a range of other sectors including healthcare, advertising or luxury. Employment outcomes below refer to the Class of 2024.",6
6,EU_05,tuition,MSc Statistics (Data Science and Machine Learning),https://www.imperial.ac.uk/study/courses/postgraduate-taught/statistics-data-science/,"These include key information about your tuition fees, funding, visas, accommodation and more. You can find further information about your course, including degree classifications, regulations, progression and awards in the programme specification for your course.",4
7,EU_06,admissions,MSc in Social Data Science - University of Oxford,https://www.ox.ac.uk/admissions/graduate/courses/msc-social-data-science,"The course is designed for students with some familiarity with programming and a strong background in social sciences, although applications are welcomed from all disciplinary backgrounds who meet the course entry requirements.",4
8,EU_06,curriculum,MSc in Social Data Science - University of Oxford,https://www.ox.ac.uk/admissions/graduate/courses/msc-social-data-science,"Course structure This section provides an overview of the course structure, while details of the individual course components are provided below. During the first term, you will receive core training in data science and machine learning, research design, and social science theory.",2
9,EU_06,tuition,Course Information Sheet for entry in 2025-26: MSc in Social Data Science,https://www.ox.ac.uk/sites/files/oxford/TM_FB1+-+MSc+in+Social+Data+Science+-+2025-26+entry+-+27Aug2025.pdf,"In addition to your course fees and any additional course-specific costs, you will need to ensure that you have adequate · funds to support your living costs for the duration of your course.",3
10,EU_07,admissions,Data Science and Public Policy (Political Science) MSc | Prospective Students Graduate - UCL – University College London,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-and-public-policy-political-science-msc,"August 27, 2025 - Each route has its own set of entry requirements to reflect the emphasis of that route. You can apply for a place on either the Economics or Political Science route of this programme, according to your experience and career direction.",2
11,EU_07,curriculum,Programme Overview and Curriculum | UCL Faculty of Social & Historical Sciences,https://www.ucl.ac.uk/economics/study/msc-data-science-and-public-policy/programme-overview-and-curriculum,"In the data science modules of the programme, you will undertake diverse, practical and rigorous quantitative methods training, which will equip you to understand, develop, and apply cutting-edge statistical methods.",3
12,EU_07,outcomes,Data Science and Public Policy (Economics) MSc | Prospective Students Graduate - UCL – University College London,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-and-public-policy-economics-msc,"August 27, 2025 - Alumni from current MSc programmes in UCL's Political Science and Economics departments have gone on to attain employment in diverse areas:",1
13,EU_10,admissions,Data Science - Entry Requirements | King's College London,https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc/requirements,"Due to the large volume of applications, this programme operates a partial “gathered-field” approach to decision making for applicants who meet our advertised academic entry requirements.",2
14,EU_10,curriculum,Teaching modules msc data science | King's College London,https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc/teaching-and-modules,"MSc Data Science We often use lectures, seminars, and group tutorials to deliver most of the modules on the course. We use a flipped classroom approach that creates opportunities for active learning engagement and interaction with world-class experts. You will also be expected to undertake a significant amount of independent study. Typically, one credit equates to 10 hours of work, e.g. 150 ...",4
15,EU_10,outcomes,Careers MSc Data Science | King's College London,https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc/careers,"Completing a degree in Data Science opens the door to a wide range of job opportunities across diverse sectors, including finance, consultancy, tech, health and pharmaceuticals, retail and e-commerce, and government and public sector.",2
16,EU_10,tuition,Postgraduate taught fees and funding - King's College London,https://www.kcl.ac.uk/study/postgraduate-taught/fees-and-funding,Find out more about tuition fees and funding opportunities including scholarships and bursaries for postgraduate King's students.,4
17,EU_11,tuition,Business Analytics MSc - Postgraduate taught programmes,https://study.ed.ac.uk/programmes/postgraduate-taught/929-business-analytics,"Fees, costs and funding Tuition fees Tuition fees by award and duration Tuition fees for full-time and part-time options are listed for one academic year. Full-time MSc Business Analytics (1 year) tuition fees",5
18,EU_12,admissions,MSc in Applied Data Science | Education | Bayes Centre,https://bayes-centre.ed.ac.uk/education/applied-data-science,"Entry requirements: Academic requirements: Applicants are required to have at least a second class (2:1) undergraduate degree in any discipline. No prior knowledge of programming is necessary, and only school-level mathematics, making this program an ideal starting point for career changers and those new to data science.",2
19,EU_12,tuition,Tuition fee rates | Postgraduate study | The University of ...,https://study.ed.ac.uk/postgraduate/fees-funding/tuition-fees/rates,Tuition fees vary between degree programmes. You can find the specific fees for your chosen degree programme on our postgraduate degree finder.,4
20,EU_13,admissions,Data Science and Artificial Intelligence Technology - TU Delft,https://www.tudelft.nl/en/education/programmes/masters/dsait/msc-data-science-and-artificial-intelligence-technology/programme,Delft University of Technology Students & Education Programmes Masters DSAIT MSc Data Science and Artificial Intelligence Technology Programme,0
21,EU_13,curriculum,MSc Data Science and Artificial Intelligence TechnologyProgramme - Data Science and Artificial Intelligence ...Core courses - TU DelftProgramme - TU DelftThemes - TU DelftResearch course - TU DelftAdvanced Machine Learning - TU Delft,https://www.tudelft.nl/en/education/programmes/masters/dsait/msc-data-science-and-artificial-intelligence-technology,"Delft University of Technology Students & Education Programmes Masters DSAIT MSc Data Science and Artificial Intelligence Technology You choose two DSAIT themes to establish in-depth knowledge and you choose a research course to develop your research competence. In addition, you have the freedom to either deepen or broaden your knowledge and skills through electives. This course aims to explore and apply essential concepts and assumptions in Machine and Deep Learning. Topics covered include supervised learning, generalization, overfitting, model selection, and specialized architectures such as CNNs, RNNs, and Transformers. You choose two DSAIT themes to establish in-depth knowledge and you choose a research course to develop your research competence. In addition, you have the freedom to either deepen or broaden your knowledge and skills through electives. Themes Through our challenging themes, you obtain advanced knowledge and skills in subject areas of Data Science and AI Technolo...",2
22,EU_13,outcomes,MSc Data Science and Artificial Intelligence TechnologyProgramme - Data Science and Artificial Intelligence ...Computer Science - TU DelftTestimonials - TU DelftProgramme - TU DelftCore courses - TU DelftSoftware Engineering for Data Science and AI - TU Delft,https://www.tudelft.nl/onderwijs/opleidingen/masters/dsait/msc-data-science-and-artificial-intelligence-technology,"Technische Universiteit Delft Studenten & Onderwijs Opleidingen Masters DSAIT MSc Data Science and Artificial Intelligence Technology Delft University of Technology Students & Education Programmes Masters DSAIT MSc Data Science and Artificial Intelligence Technology Programme The DST track is meant to provide students with the knowledge and expertise needed for a professional career in the information and communication technology and related industries or doctoral studies in data and computer science. Technische Universiteit Delft Studenten & Onderwijs Opleidingen Masters DSAIT MSc Data Science and Artificial Intelligence Technology Testimonials Technische Universiteit Delft Studenten & Onderwijs Opleidingen Masters DSAIT MSc Data Science and Artificial Intelligence Technology Programme You will learn to make informed choices and reflect on Responsible Data Science and AI Engineering, acting with integrity, discuss your duties and roles in your professional career, connect differen...",1
23,EU_13,tuition,MSc Data Science and Artificial Intelligence TechnologyProgramme - Data Science and Artificial Intelligence ...Computer Science - TU DelftMSc Data Science and Artificial Intelligence TechnologyTuition Fee & Finances - TU DelftProgramme - TU DelftMaster programmes - TU Delft,https://www.tudelft.nl/onderwijs/opleidingen/masters/dsait/msc-data-science-and-artificial-intelligence-technology,"Technische Universiteit Delft Studenten & Onderwijs Opleidingen Masters DSAIT MSc Data Science and Artificial Intelligence Technology Delft University of Technology Students & Education Programmes Masters DSAIT MSc Data Science and Artificial Intelligence Technology Programme In the Data Science & Technology (DST) track, you will learn how to engineer and develop systems capable of processing and interpreting massive data sets to extract information and to gain understanding. Fundamental and practical issues of the analysis of data will be addressed. This includes security of data and software, visualisation of information, decision-making from data and high ... MSc Data Science and Artificial Intelligence Technology Faculties Electrical Engineering Mathematics and Computer Science Master MSc Data Science and Artificial Intelligence Technology DSAIT4010 Probabilistic AI and Reasoning DSAIT4080 3D Visualization DSAIT4105 Probabilistic Models and Inference For more information about ...",3
24,EU_14,outcomes,Master of Statistics and Data Science - KU Leuven,https://www.kuleuven.be/programmes/master-statistics-data-science/?mtm_campaign=international-students&mtm_source=keystone&mtm_medium=listing,"Nov 13, 2024 · Our Student Career Center is happy to put you on the right track towards your first work experience, but also coaches you in the search for an interesting job and helps you with job interviews.",1
25,EU_16,admissions,Master in Business Analytics and Data Science - POLIMI GSoM,https://www.gsom.polimi.it/en/course/master-business-analytics-data-science,"After successfully completing our Master in Business Analytics and Data Science, you will be able to attend two semesters at EDHEC Business School and obtain a Master of Science in Strategy, Organization & Consulting.",0
26,EU_16,outcomes,Master in Business Analytics and Data Science - POLIMI GSoM,https://www.gsom.polimi.it/en/course/master-business-analytics-data-science,"According to a report from the World Economic Forum, the employment of data analysts and scientists, is expected to grow on average by 30% by 2027. Moreover, data literacy will be the most in-demand skill by 2030.",1
27,EU_16,tuition,Master in Business Analytics and Data Science - POLIMI GSoM,https://www.gsom.polimi.it/en/course/master-business-analytics-data-science,Take part in the Master in Business Analytics and Data Science. It develops advanced skills in the analysis of company data.,0
28,EU_17,curriculum,Study programme - Data Science - Utrecht University,https://www.uu.nl/en/masters/data-science/study-programme,"Get to know more about the periods, courses and teaching methods of this Master’s.",2
29,EU_17,outcomes,Data Science - Utrecht University,https://www.uu.nl/en/masters/data-science,"While the Data Science Master’s programme primarily aims to prepare you for a career in academia (PhD), it also acknowledges diverse career paths including managerial roles or entrepreneurship in data science.",1
30,EU_18,curriculum,Data Science M.Sc. | RWTH Aachen University | ENData Science M.Sc. - RWTH Aachen University | DEMaster Data Science – Studiencenter InformatikM.Sc. Data Analytics and Decision Science | School of ...Data Analytics & Decision Science M.Sc. | RWTH Aachen ...Data Analytics & Decision Science M.Sc. | RWTH Aachen ...,https://www.rwth-aachen.de/go/id/pzpc/lidx/1,"The curriculum is divided into a foundational area with about 60 CP and an area of specialization with about 30 CP, plus some room for “additional skills” with a maximum of 12 CP. Courses offered in the specialization area form the basis of the final thesis with 30 CP. Following the idea of the Integrated Interdisciplinary University, the final the... See full list on rwth-aachen.de The program builds on the Bachelor’s degree programs in mathematics or computer science. It requires a Bachelor’s degree in mathematics, computer science, physics, or a related area. You can find more information about the prerequisites on the course of study web page. The required educational background is formulated in the examination regulations... See full list on rwth-aachen.de Data-Science methods are used in a broad spectrum of applications in science and industry. Data science gains increasing importance in the industry due to the desire and the need for utilizing the information that becomes av...",5
31,EU_18,outcomes,Data Science M.Sc. | RWTH Aachen University | EN,https://www.rwth-aachen.de/go/id/pzpc/lidx/1,Career Prospects Data-Science methods are used in a broad spectrum of applications in science and industry.,1
32,EU_19,curriculum,Curriculum for Business Analytics - DTU,https://www.dtu.dk/english/education/graduate/msc-programmes/business-analytics/curriculum,"Master students may choose as much as 10 credit points among the bachelor courses at DTU and courses at an equivalent level from other higher institutions. In addition, it is possible to take MSc-level courses at other Danish universities or abroad.",3
33,EU_19,outcomes,What can I do with an MSc in Business Analytics - DTU,https://www.dtu.dk/english/education/graduate/msc-programmes/business-analytics/career,"Graduates from Business Analytics will likely find jobs in banks, large production and service companies, in the transport industry, or in research institutions.",1
34,EU_20,admissions,Applications | Aalto University,https://www.aalto.fi/en/programmes/masters-programme-in-business-analytics/applications,"Aug 14, 2026 · Students admitted directly to a specific degree programme through a separate admissions procedure If you were admitted directly to a master’s programme, you cannot change to another degree programme.",2
35,EU_20,curriculum,Curriculum 2024-2026 | Aalto University,https://www.aalto.fi/en/programmes/masters-programme-in-business-analytics/curriculum-2024-2026,"Studying in the Master's Programme in Business Analytics offers students a unique combination of skills in leadership, business, and technology. The programme fits industry and future needs, and graduates are innovative leaders of the digital and sustainable era. The programme provides students with in-depth knowledge in data-based decision-making and analytics and allows them to specialise ...",1
36,EU_20,tuition,Master's Programme in Business Analytics | Aalto University,https://www.aalto.fi/en/programmes/masters-programme-in-business-analytics,"Jan 10, 2023 · Tuition fee for tuition-fee students in this programme is 15,000 EUR/academic year. For more information, please see the Tuition fees and scholarships webpage in the Student Guide.",3

In [178]:
coverage = (
    best_supporting_sources
    .pivot_table(
        index="programme_id",
        columns="page_type",
        values="url",
        aggfunc="first"
    )
    .reset_index()
)

display(coverage)

page_type,programme_id,admissions,curriculum,outcomes,tuition
0,EU_04,https://www.ucl.ac.uk/study/prospective-students/graduate/courses/data-science-msc,https://www.ucl.ac.uk/study/prospective-students/graduate/courses/data-science-msc,https://www.msi.ucl.ac.uk/msc-finance-data-science,NaN
1,EU_05,https://www.imperial.ac.uk/study/courses/postgraduate-taught/statistics-data-science/,https://www.imperial.ac.uk/study/courses/postgraduate-taught/statistics-data-science/,https://imperial.ac.uk/business-school/programmes/msc-business-analytics/careers/employment-report,https://www.imperial.ac.uk/study/courses/postgraduate-taught/statistics-data-science/
2,EU_06,https://www.ox.ac.uk/admissions/graduate/courses/msc-social-data-science,https://www.ox.ac.uk/admissions/graduate/courses/msc-social-data-science,NaN,https://www.ox.ac.uk/sites/files/oxford/TM_FB1+-+MSc+in+Social+Data+Science+-+2025-26+entry+-+27Aug2025.pdf
3,EU_07,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-and-public-policy-political-science-msc,https://www.ucl.ac.uk/economics/study/msc-data-science-and-public-policy/programme-overview-and-curriculum,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-and-public-policy-economics-msc,NaN
4,EU_10,https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc/requirements,https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc/teaching-and-modules,https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc/careers,https://www.kcl.ac.uk/study/postgraduate-taught/fees-and-funding
5,EU_11,NaN,NaN,NaN,https://study.ed.ac.uk/programmes/postgraduate-taught/929-business-analytics
6,EU_12,https://bayes-centre.ed.ac.uk/education/applied-data-science,NaN,NaN,https://study.ed.ac.uk/postgraduate/fees-funding/tuition-fees/rates
7,EU_13,https://www.tudelft.nl/en/education/programmes/masters/dsait/msc-data-science-and-artificial-intelligence-technology/programme,https://www.tudelft.nl/en/education/programmes/masters/dsait/msc-data-science-and-artificial-intelligence-technology,https://www.tudelft.nl/onderwijs/opleidingen/masters/dsait/msc-data-science-and-artificial-intelligence-technology,https://www.tudelft.nl/onderwijs/opleidingen/masters/dsait/msc-data-science-and-artificial-intelligence-technology
8,EU_14,NaN,NaN,https://www.kuleuven.be/programmes/master-statistics-data-science/?mtm_campaign=international-students&mtm_source=keystone&mtm_medium=listing,NaN
9,EU_16,https://www.gsom.polimi.it/en/course/master-business-analytics-data-science,NaN,https://www.gsom.polimi.it/en/course/master-business-analytics-data-science,https://www.gsom.polimi.it/en/course/master-business-analytics-data-science
10,EU_17,NaN,https://www.uu.nl/en/masters/data-science/study-programme,https://www.uu.nl/en/masters/data-science,NaN
11,EU_18,NaN,https://www.rwth-aachen.de/go/id/pzpc/lidx/1,https://www.rwth-aachen.de/go/id/pzpc/lidx/1,NaN
12,EU_19,NaN,https://www.dtu.dk/english/education/graduate/msc-programmes/business-analytics/curriculum,https://www.dtu.dk/english/education/graduate/msc-programmes/business-analytics/career,NaN
13,EU_20,https://www.aalto.fi/en/programmes/masters-programme-in-business-analytics/applications,https://www.aalto.fi/en/programmes/masters-programme-in-business-analytics/curriculum-2024-2026,NaN,https://www.aalto.fi/en/programmes/masters-programme-in-business-analytics

In [179]:
# ============================================================
# Build complete URL pool for EU_04 - EU_20
# Primary programme page + supporting pages
# ============================================================

# 1. Primary programme URLs
primary_pool = batch_review[
    [
        "programme_id",
        "university",
        "programme_name",
        "official_url"
    ]
].copy()

primary_pool = primary_pool.rename(
    columns={"official_url": "url"}
)

primary_pool["page_type"] = "primary"
primary_pool["source_priority"] = 1


# 2. Best supporting URLs
supporting_pool = best_supporting_sources[
    [
        "programme_id",
        "page_type",
        "url"
    ]
].copy()

supporting_pool = supporting_pool.merge(
    batch_review[
        [
            "programme_id",
            "university",
            "programme_name"
        ]
    ],
    on="programme_id",
    how="left"
)

supporting_pool["source_priority"] = 2


# 3. Combine
url_pool = pd.concat(
    [
        primary_pool[
            [
                "programme_id",
                "university",
                "programme_name",
                "page_type",
                "url",
                "source_priority"
            ]
        ],
        supporting_pool[
            [
                "programme_id",
                "university",
                "programme_name",
                "page_type",
                "url",
                "source_priority"
            ]
        ]
    ],
    ignore_index=True
)


# 4. Remove duplicate URLs within programme
url_pool = (
    url_pool
    .dropna(subset=["url"])
    .sort_values(
        ["programme_id", "source_priority"]
    )
    .drop_duplicates(
        subset=["programme_id", "url"],
        keep="first"
    )
    .reset_index(drop=True)
)

display(url_pool)

,programme_id,university,programme_name,page_type,url,source_priority
0,EU_04,UCL,MSc Data Science,primary,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc,1
1,EU_04,UCL,MSc Data Science,admissions,https://www.ucl.ac.uk/study/prospective-students/graduate/courses/data-science-msc,2
2,EU_04,UCL,MSc Data Science,outcomes,https://www.msi.ucl.ac.uk/msc-finance-data-science,2
3,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),primary,https://www.imperial.ac.uk/study/courses/postgraduate-taught/statistics-data-science/,1
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),outcomes,https://imperial.ac.uk/business-school/programmes/msc-business-analytics/careers/employment-report,2
5,EU_06,University of Oxford,MSc in Social Data Science,primary,https://www.ox.ac.uk/admissions/graduate/courses/msc-social-data-science,1
6,EU_06,University of Oxford,MSc in Social Data Science,tuition,https://www.ox.ac.uk/sites/files/oxford/TM_FB1+-+MSc+in+Social+Data+Science+-+2025-26+entry+-+27Aug2025.pdf,2
7,EU_07,UCL,MSc Data Science and Public Policy,primary,https://www.ucl.ac.uk/social-historical-sciences/economics/study/data-science-and-public-policy-msc,1
8,EU_07,UCL,MSc Data Science and Public Policy,admissions,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-and-public-policy-political-science-msc,2
9,EU_07,UCL,MSc Data Science and Public Policy,curriculum,https://www.ucl.ac.uk/economics/study/msc-data-science-and-public-policy/programme-overview-and-curriculum,2
10,EU_07,UCL,MSc Data Science and Public Policy,outcomes,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-and-public-policy-economics-msc,2
11,EU_08,EPFL,Master in Data Science,primary,https://www.epfl.ch/education/master/programs/data-science/,1
12,EU_09,Technical University of Munich,MSc Mathematics in Data Science,primary,https://www.tum.de/en/studies/degree-programs/detail/mathematics-in-data-science-master-of-science-msc,1
13,EU_10,King's College London,MSc Data Science,primary,https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc,1
14,EU_10,King's College London,MSc Data Science,admissions,https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc/requirements,2
15,EU_10,King's College London,MSc Data Science,curriculum,https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc/teaching-and-modules,2
16,EU_10,King's College London,MSc Data Science,outcomes,https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc/careers,2
17,EU_10,King's College London,MSc Data Science,tuition,https://www.kcl.ac.uk/study/postgraduate-taught/fees-and-funding,2
18,EU_11,University of Edinburgh,MSc Business Analytics,primary,https://www.business-school.ed.ac.uk/msc/business-analytics,1
19,EU_11,University of Edinburgh,MSc Business Analytics,tuition,https://study.ed.ac.uk/programmes/postgraduate-taught/929-business-analytics,2
20,EU_12,University of Edinburgh,MSc Data Science,primary,https://study.ed.ac.uk/programmes/postgraduate-taught/902-data-science,1
21,EU_12,University of Edinburgh,MSc Data Science,admissions,https://bayes-centre.ed.ac.uk/education/applied-data-science,2
22,EU_12,University of Edinburgh,MSc Data Science,tuition,https://study.ed.ac.uk/postgraduate/fees-funding/tuition-fees/rates,2
23,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,primary,https://www.tudelft.nl/en/education/programmes/masters/dsait/msc-data-science-and-artificial-intelligence-technology,1
24,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,admissions,https://www.tudelft.nl/en/education/programmes/masters/dsait/msc-data-science-and-artificial-intelligence-technology/programme,2
25,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,outcomes,https://www.tudelft.nl/onderwijs/opleidingen/masters/dsait/msc-data-science-and-artificial-intelligence-technology,2
26,EU_14,KU Leuven,Master of Statistics and Data Science,primary,https://onderwijsaanbod.kuleuven.be/opleidingen/e/SC_51016989/diploma_omschrijving,1
27,EU_14,KU Leuven,Master of Statistics and Data Science,outcomes,https://www.kuleuven.be/programmes/master-statistics-data-science/?mtm_campaign=international-students&mtm_source=keystone&mtm_medium=listing,2
28,EU_15,Lund University,MSc Data Analytics and Business Economics,primary,https://www.lunduniversity.lu.se/study/data-analytics-and-business-economics-masters-programme-EAGDA,1
29,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,primary,https://www.gsom.polimi.it/en/course/master-business-analytics-data-science,1
30,EU_17,Utrecht University,MSc Data Science,primary,https://www.uu.nl/en/masters/data-science,1
31,EU_17,Utrecht University,MSc Data Science,curriculum,https://www.uu.nl/en/masters/data-science/study-programme,2
32,EU_18,RWTH Aachen University,MSc Data Science,primary,https://sc.informatik.rwth-aachen.de/en/studium/master/master-data-science/,1
33,EU_18,RWTH Aachen University,MSc Data Science,curriculum,https://www.rwth-aachen.de/go/id/pzpc/lidx/1,2
34,EU_19,Technical University of Denmark,MSc Business Analytics,primary,https://www.dtu.dk/english/education/graduate/msc-programmes/business-analytics,1
35,EU_19,Technical University of Denmark,MSc Business Analytics,curriculum,https://www.dtu.dk/english/education/graduate/msc-programmes/business-analytics/curriculum,2
36,EU_19,Technical University of Denmark,MSc Business Analytics,outcomes,https://www.dtu.dk/english/education/graduate/msc-programmes/business-analytics/career,2
37,EU_20,Aalto University,Master's Programme in Business Analytics,primary,https://www.aalto.fi/en/programmes/masters-programme-in-business-analytics,1
38,EU_20,Aalto University,Master's Programme in Business Analytics,admissions,https://www.aalto.fi/en/programmes/masters-programme-in-business-analytics/applications,2
39,EU_20,Aalto University,Master's Programme in Business Analytics,curriculum,https://www.aalto.fi/en/programmes/masters-programme-in-business-analytics/curriculum-2024-2026,2

In [180]:
url_pool_check = (
    batch_review[
        [
            "programme_id",
            "university",
            "programme_name"
        ]
    ]
    .merge(
        url_pool.groupby(
            "programme_id"
        ).size().rename("url_count"),
        on="programme_id",
        how="left"
    )
)

url_pool_check["url_count"] = (
    url_pool_check["url_count"]
    .fillna(0)
    .astype(int)
)

display(url_pool_check)

print(
    "Programmes with at least one URL:",
    (url_pool_check["url_count"] > 0).sum(),
    "/",
    len(url_pool_check)
)

,programme_id,university,programme_name,url_count
0,EU_04,UCL,MSc Data Science,3
1,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),2
2,EU_06,University of Oxford,MSc in Social Data Science,2
3,EU_07,UCL,MSc Data Science and Public Policy,4
4,EU_08,EPFL,Master in Data Science,1
5,EU_09,Technical University of Munich,MSc Mathematics in Data Science,1
6,EU_10,King's College London,MSc Data Science,5
7,EU_11,University of Edinburgh,MSc Business Analytics,2
8,EU_12,University of Edinburgh,MSc Data Science,3
9,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,3
10,EU_14,KU Leuven,Master of Statistics and Data Science,2
11,EU_15,Lund University,MSc Data Analytics and Business Economics,1
12,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,1
13,EU_17,Utrecht University,MSc Data Science,2
14,EU_18,RWTH Aachen University,MSc Data Science,2
15,EU_19,Technical University of Denmark,MSc Business Analytics,3
16,EU_20,Aalto University,Master's Programme in Business Analytics,3

Programmes with at least one URL: 17 / 17

In [181]:
import requests
import pandas as pd
import time
from bs4 import BeautifulSoup

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 Chrome/120 Safari/537.36"
    )
}

def fetch_page_text(url):
    try:
        response = requests.get(
            url,
            headers=headers,
            timeout=15
        )

        status_code = response.status_code

        if status_code != 200:
            return {
                "status_code": status_code,
                "page_text": pd.NA,
                "text_length": 0,
                "fetch_status": "Failed"
            }

        soup = BeautifulSoup(
            response.text,
            "html.parser"
        )

        # Remove non-content elements
        for tag in soup(
            [
                "script",
                "style",
                "noscript",
                "svg"
            ]
        ):
            tag.decompose()

        text = " ".join(
            soup.stripped_strings
        )

        return {
            "status_code": status_code,
            "page_text": text,
            "text_length": len(text),
            "fetch_status": "Success"
        }

    except Exception as e:
        return {
            "status_code": pd.NA,
            "page_text": pd.NA,
            "text_length": 0,
            "fetch_status": f"Error: {str(e)[:80]}"
        }

In [182]:
batch_page_rows = []

total_urls = len(url_pool)

for i, row in url_pool.iterrows():

    print(
        f"[{i + 1}/{total_urls}] "
        f"{row['programme_id']} | "
        f"{row['page_type']}"
    )

    result = fetch_page_text(
        row["url"]
    )

    batch_page_rows.append({
        "programme_id":
            row["programme_id"],

        "university":
            row["university"],

        "programme_name":
            row["programme_name"],

        "page_type":
            row["page_type"],

        "url":
            row["url"],

        "status_code":
            result["status_code"],

        "fetch_status":
            result["fetch_status"],

        "text_length":
            result["text_length"],

        "page_text":
            result["page_text"]
    })

    # Be polite to university servers
    time.sleep(0.5)


batch_pages = pd.DataFrame(
    batch_page_rows
)

print("\nFinished.")
print("Total URLs:", len(batch_pages))

display(
    batch_pages[
        [
            "programme_id",
            "page_type",
            "status_code",
            "fetch_status",
            "text_length"
        ]
    ]
)

[1/40] EU_04 | primary
[2/40] EU_04 | admissions
[3/40] EU_04 | outcomes
[4/40] EU_05 | primary
[5/40] EU_05 | outcomes
[6/40] EU_06 | primary
[7/40] EU_06 | tuition
[8/40] EU_07 | primary
[9/40] EU_07 | admissions
[10/40] EU_07 | curriculum
[11/40] EU_07 | outcomes
[12/40] EU_08 | primary
[13/40] EU_09 | primary
[14/40] EU_10 | primary
[15/40] EU_10 | admissions
[16/40] EU_10 | curriculum
[17/40] EU_10 | outcomes
[18/40] EU_10 | tuition
[19/40] EU_11 | primary
[20/40] EU_11 | tuition
[21/40] EU_12 | primary
[22/40] EU_12 | admissions
[23/40] EU_12 | tuition
[24/40] EU_13 | primary
[25/40] EU_13 | admissions
[26/40] EU_13 | outcomes
[27/40] EU_14 | primary
[28/40] EU_14 | outcomes
[29/40] EU_15 | primary
[30/40] EU_16 | primary
[31/40] EU_17 | primary
[32/40] EU_17 | curriculum
[33/40] EU_18 | primary
[34/40] EU_18 | curriculum
[35/40] EU_19 | primary
[36/40] EU_19 | curriculum
[37/40] EU_19 | outcomes
[38/40] EU_20 | primary
[39/40] EU_20 | admissions
[40/40] EU_20 | curriculum

Finished.
Total URLs: 40

,programme_id,page_type,status_code,fetch_status,text_length
0,EU_04,primary,403,Failed,0
1,EU_04,admissions,403,Failed,0
2,EU_04,outcomes,<NA>,"Error: HTTPSConnectionPool(host='www.msi.ucl.ac.uk', port=443): Max retries exceeded wi",0
3,EU_05,primary,200,Success,26728
4,EU_05,outcomes,200,Success,54749
5,EU_06,primary,403,Failed,0
6,EU_06,tuition,403,Failed,0
7,EU_07,primary,403,Failed,0
8,EU_07,admissions,403,Failed,0
9,EU_07,curriculum,403,Failed,0
10,EU_07,outcomes,403,Failed,0
11,EU_08,primary,200,Success,7115
12,EU_09,primary,200,Success,29985
13,EU_10,primary,200,Success,12441
14,EU_10,admissions,200,Success,11290
15,EU_10,curriculum,200,Success,11413
16,EU_10,outcomes,200,Success,8588
17,EU_10,tuition,200,Success,8984
18,EU_11,primary,200,Success,5946
19,EU_11,tuition,200,Success,26335
20,EU_12,primary,200,Success,29654
21,EU_12,admissions,200,Success,5575
22,EU_12,tuition,200,Success,6804
23,EU_13,primary,200,Success,3802
24,EU_13,admissions,200,Success,3048
25,EU_13,outcomes,200,Success,3790
26,EU_14,primary,200,Success,9960
27,EU_14,outcomes,200,Success,9960
28,EU_15,primary,200,Success,21525
29,EU_16,primary,200,Success,11445
30,EU_17,primary,200,Success,6914
31,EU_17,curriculum,200,Success,10169
32,EU_18,primary,200,Success,8458
33,EU_18,curriculum,<NA>,"Error: HTTPSConnectionPool(host='www.rwth-aachen.de', port=443): Read timed out. (read",0
34,EU_19,primary,200,Success,5356
35,EU_19,curriculum,200,Success,5213
36,EU_19,outcomes,200,Success,1653
37,EU_20,primary,200,Success,8848
38,EU_20,admissions,200,Success,11876
39,EU_20,curriculum,200,Success,18302

In [183]:
print(
    batch_pages[
        "fetch_status"
    ].value_counts(
        dropna=False
    )
)

print("\nHTTP status:")
print(
    batch_pages[
        "status_code"
    ].value_counts(
        dropna=False
    )
)

fetch_status
Success                                                                                    30
Failed                                                                                      8
Error: HTTPSConnectionPool(host='www.msi.ucl.ac.uk', port=443): Max retries exceeded wi     1
Error: HTTPSConnectionPool(host='www.rwth-aachen.de', port=443): Read timed out. (read      1
Name: count, dtype: int64

HTTP status:
status_code
200     30
403      8
<NA>     2
Name: count, dtype: int64

In [184]:
programme_fetch_check = (
    batch_pages
    .assign(
        success=lambda x:
            x["fetch_status"]
            == "Success"
    )
    .groupby(
        "programme_id"
    )
    .agg(
        total_urls=(
            "url",
            "count"
        ),
        successful_pages=(
            "success",
            "sum"
        )
    )
    .reset_index()
)

display(programme_fetch_check)

   programme_id  total_urls  successful_pages
0         EU_04           3                 0
1         EU_05           2                 2
2         EU_06           2                 0
3         EU_07           4                 0
4         EU_08           1                 1
5         EU_09           1                 1
6         EU_10           5                 5
7         EU_11           2                 2
8         EU_12           3                 3
9         EU_13           3                 3
10        EU_14           2                 2
11        EU_15           1                 1
12        EU_16           1                 1
13        EU_17           2                 2
14        EU_18           2                 1
15        EU_19           3                 3
16        EU_20           3                 3

In [185]:
import re
import pandas as pd


EVIDENCE_KEYWORDS = {
    "prerequisites": [
        "entry requirements",
        "admission requirements",
        "admissions requirements",
        "bachelor",
        "bachelor's degree",
        "undergraduate degree",
        "prerequisite",
        "requirements profile"
    ],

    "GRE_GMAT": [
        "GRE",
        "GMAT",
        "Graduate Record Examination",
        "Graduate Management Admission Test"
    ],

    "tuition": [
        "tuition",
        "tuition fee",
        "tuition fees",
        "fees",
        "overseas tuition",
        "international tuition"
    ],

    "duration": [
        "duration",
        "calendar year",
        "months",
        "years",
        "ECTS"
    ],

    "statistics": [
        "statistics",
        "statistical",
        "probability",
        "regression",
        "econometrics"
    ],

    "programming": [
        "programming",
        "Python",
        "R programming",
        "coding",
        "computer programming"
    ],

    "machine_learning": [
        "machine learning",
        "deep learning",
        "artificial intelligence",
        "predictive analytics"
    ],

    "visualization": [
        "data visualization",
        "data visualisation",
        "visualization",
        "visualisation"
    ],

    "business_analytics": [
        "business analytics",
        "business intelligence",
        "decision analytics",
        "analytics for business"
    ],

    "outcomes": [
        "employment",
        "employed",
        "graduate outcomes",
        "career outcomes",
        "graduate destinations",
        "employers"
    ]
}


def extract_context(text, keywords, window=220):
    if pd.isna(text):
        return pd.NA

    text = str(text)

    matches = []

    for keyword in keywords:
        pattern = re.compile(
            re.escape(keyword),
            flags=re.IGNORECASE
        )

        match = pattern.search(text)

        if match:
            start = max(
                0,
                match.start() - window
            )

            end = min(
                len(text),
                match.end() + window
            )

            snippet = text[start:end]

            snippet = re.sub(
                r"\s+",
                " ",
                snippet
            ).strip()

            matches.append(snippet)

    if not matches:
        return pd.NA

    # Remove duplicate snippets
    unique_matches = list(
        dict.fromkeys(matches)
    )

    return " || ".join(
        unique_matches[:3]
    )

In [186]:
successful_pages = batch_pages[
    batch_pages["fetch_status"]
    == "Success"
].copy()


for field, keywords in EVIDENCE_KEYWORDS.items():

    successful_pages[
        f"{field}_evidence"
    ] = successful_pages[
        "page_text"
    ].apply(
        lambda x:
            extract_context(
                x,
                keywords
            )
    )


evidence_cols = [
    "programme_id",
    "page_type",
    "url",
    "prerequisites_evidence",
    "GRE_GMAT_evidence",
    "tuition_evidence",
    "duration_evidence",
    "statistics_evidence",
    "programming_evidence",
    "machine_learning_evidence",
    "visualization_evidence",
    "business_analytics_evidence",
    "outcomes_evidence"
]

display(
    successful_pages[
        evidence_cols
    ].head()
)

,programme_id,page_type,url,prerequisites_evidence,GRE_GMAT_evidence,tuition_evidence,duration_evidence,statistics_evidence,programming_evidence,machine_learning_evidence,visualization_evidence,business_analytics_evidence,outcomes_evidence
3,EU_05,primary,https://www.imperial.ac.uk/study/courses/postgraduate-taught/statistics-data-science/,"mperial Giving Shop Imperial User links navigation For staff Current students Imperial for business For schools Alumni Home Study navigation Course search Subjects Apply Undergraduate Application process Choose a course Entry requirements Accepted qualifications Deadlines Personal statement Application reference Teacher reference guidance Contextual admissions Admissions tests Engineering and Science Admissions Test (ESAT) Test of Mathematics for Univers || hematics, engineering, physics or computer science. Footnotes Please note that we receive many more applications than we can accommodate. Nearly all successful applicants hold a First Class degree in any of the eligible undergraduate degrees, and all successful applicants holding an undergraduate degree outside the mathematical sciences have substantive knowledge and experience in theoretical mathematical topics. English language requirement All candidates",chools Research Faculties Faculty of Engineering Faculty of Medicine Faculty of Natural Sciences Imperial Business School Administrative and support services News News Imperial Stories Imperial Magazine Events What's on Great Exhibition Road Festival Imperial Lates Graduation About President Provost and Deputy President Council Imperial Strategy League tables and rankings Imperial Global Sustainable Imperial School of Convergence Science G,"nglish language requirements English language exemption Visiting students Course changes Contact Support for displaced applicants School examinations cancelled or disrupted internationally Fees and funding Undergraduate Tuition fees Bursaries, grants and scholarships Imperial Bursary Sanctuary scholarships NHS Bursary for Medicine students Search our scholarships IB Excellence scholarships Presidential scholarships for students of Black herita || nglish language requirements English language exemption Visiting students Course changes Contact Support for displaced applicants School examinations cancelled or disrupted internationally Fees and funding Undergraduate Tuition fees Bursaries, grants and scholarships Imperial Bursary Sanctuary scholarships NHS Bursary for Medicine students Search our scholarships IB Excellence scholarships Presidential scholarships for students of Black heritage E || nglish language requirements English language exemption Visiting students Course changes C...","day 30 September 2026 Request Info Add to course compare Course details Overview Structure Teaching and assessment Entry requirements How to apply Fees and funding Careers Request info Course key facts Qualification MSc Duration 1 year Start date October 2027 Study mode Full-time Delivered by Department of Mathematics Location South Kensington Applications: places 25:1 (2024-25) Minimum entry standard 2:1 in Statistics, Mathematics, Engineering || r an interruption, your fees will only increase by the amount linked to inflation. Find out more about our tuition fees payment terms , including how inflationary increases are applied to your tuition fees in subsequent years of study. Which fee you pay Whether you pay the Home or Overseas fee depends on your fee status. This is assessed based on UK Government legislation and includes things like where you live and your nationality or reside || h Menu Study Research Faculties News Events About Get involved Giving Shop Imperial Search Sear...","Statistics (Data Science and Machine Learning) MSc | Study | Imperial College London Skip to main content View accessibility support page Skip to filters Search Search Menu Study Research Faculties News Events About Get involved G || Physics or Computer Science. View full entry requirements Course overview Develop your appreciation of data science techniques and their application in statistics on this Master's course. You'll explore a wide range of statistical methods used in data science and machine learning and delve into current developments in the field. This course considers how these methods are used in a variety of areas. These include scientific, governmental, industr || apply these methods confidently. Fundamentals of Statistical Inference Appreciate different Bayesian and frequentist approaches to statistical inference and select and justify appropriate methods for hypothesis testing. Probability for Statistics Assess the key concepts of probability theory and learn how r...","an opportunity to work with a member of academic staff and/or industry partner on a state-of-the-art research problem that suits your interests. Become fluent in the most common data science computing languages such as python, R, pyspark, Stan, or tensorflow, and deploy these skills to make statistics individually or in teams. Master Statistics through a focus on in-person problem-solving activities and classes, such as our summer research p","Statistics (Data Science and Machine Learning) MSc | Study | Imperial College London Skip to main content View accessibility support page Skip to filters Search Search Menu Study Research Faculties News Events About Get involved Giving Shop Imperial Search Search W || Hadoop and Spark), learn to utilise Big Data technology to perform a rigorous statistical analysis, and describe and apply mathematical techniques for fitting statistical models at scale and dealing with streaming data. Deep Learning (7.5 ECTS) Explore the building blocks of deep learning models, and how to design network architectures for specific applications. Nonparametric Statistics Learn modern techniques to solve various problems, including es",<NA>,"e, cyber security, government, energy, automotive, retail, healthcare, and pharmaceuticals. What jobs do our graduates do? Quantitative Analyst, Quantitative Researcher, Commodities Trader, Data Scientist, Data Analyst, Business Intelligence Developer, Engineering Analyst, Credit Risk Analyst, Management Trainee, Civil Servant. Who do our graduates work for? JP Morgan, Accenture, BCG, Amazon, PwC, Darktrace, Carrefour, Squarepoint Capital, Marshall Wace, Ro",<NA>
4,EU_05,outcomes,https://imperial.ac.uk/business-school/programmes/msc-business-analytics/careers/employment-report,"l. Read more Meet MSc Business Analytics student, Jamie Lim Admissions Applications for our MSc Business Analytics & AI 2027 intake are open. Discover our admissions process for the MSc Business Analytics & AI including entry requirements, how to apply and key dates and deadlines. This programme is highly competitive, so early application is advised; this will put you in a stronger position to be considered for a scholarship, and provide access to exclus || fications for postgraduate study at Imperial. We've provided general guidance in the country and region index. Here, understand how qualifications awarded by public institutions overseas may satisfy our minimum academic admission requirements. We review our requirements annually. Updates usually happen in September each year before the next academic year of entry. If your country or region is not listed, please contact the relevant Admissions team for furthe || n is our MSc Strategic Marketing (online, part-time) programme, whic...","xperience and earning additional credits. Please note, the extended term is subject to an additional tuition fee. Please note, programme content is subject to change. Candidates that fail to successfully complete this degree are not entitled to a Postgraduate Certificate or Postgraduate Diploma. View an example MSc Business Analytics & AI timetable Programme preparation Core modules Electives Projects Global experiences Through a combinati","s. This will give you the opportunity to commit to a longer Work Placement, gaining even more professional and global experience and earning additional credits. Please note, the extended term is subject to an additional tuition fee. Please note, programme content is subject to change. Candidates that fail to successfully complete this degree are not entitled to a Postgraduate Certificate or Postgraduate Diploma. View an example MSc Business An || s. This will give you the opportunity to commit to a longer Work Placement, gaining even more professional and global experience and earning additional credits. Please note, the extended term is subject to an additional tuition fee. Please note, programme content is subject to change. Candidates that fail to successfully complete this degree are not entitled to a Postgraduate Certificate or Postgraduate Diploma. View an example MSc Business Analyt || June. Requests submitted after 23rd June 2027 will only be approved in exceptional circums...","Blog Events Donate to Imperial Update your details Menu Breadcrumb Home Masters' Specialised Masters' MSc Business Analytics & AI Request a brochure MSc Business Analytics & AI Choose start date: Start date: August 2027 Duration: 12 months Next application deadline: 29 September 2026 Fee: £47,000 Location: London, UK Admissions Fees and funding Show page contents Overview Programme content Admissions Fees and funding Who attends Career impact F || onate to Imperial Update your details Menu Breadcrumb Home Masters' Specialised Masters' MSc Business Analytics & AI Request a brochure MSc Business Analytics & AI Choose start date: Start date: August 2027 Duration: 12 months Next application deadline: 29 September 2026 Fee: £47,000 Location: London, UK Admissions Fees and funding Show page contents Overview Programme content Admissions Fees and funding Who attends Career impact Faculty FAQs || text data, such as newspaper articles, job descriptions, and product reviews. The amount and a...","nance, tech and consulting sectors. Find out more about career outcomes . / Discover the Imperial advantage Programme content Pre-study and Core modules will prepare you with essential foundation skills in areas such as statistics, machine learning, data visualisation and genAI, equipping you to analyse complex data and generate actionable insights. Elective modules allow you to tailor the programme to your interests, with modules focused on diff || ces practical data wrangling and visualisation techniques in R and Tableau, emphasising how to ask insightful business questions and analyse data interactively. Exploratory data analysis methods will be discussed from a statistical point of view and with cases in a management context. Our discussions will be complemented by real datasets from retail, supply chain, finance, and other industries. You will be prepared to use analytical and data-drive || . The goal of the module is to enable you to be data-savvy, analytically minded and cod...","ment opportunities and our optional extended term. Taught within a world-leading university with STEMB roots, you will benefit from expertise in data, science and technology. From early on, you will learn how to code in programming languages such as Python and R, and gain the specialist skills you need to boost your career or start working as a business analyst, data scientist or consultant. Meanwhile, our tailored career support will help you pre || ional extended term. Taught within a world-leading university with STEMB roots, you will benefit from expertise in data, science and technology. From early on, you will learn how to code in programming languages such as Python and R, and gain the specialist skills you need to boost your career or start working as a business analyst, data scientist or consultant. Meanwhile, our tailored career support will help you prepare for your future driv || g the generative AI models (such as large language models and multi-modal large language mo...","ation World University Rankings 2026) #3 city for students (London, QS Best Student City Rankings 2027) Drive business transformation through data-driven decision-making With the emergence of technologies such as AI and machine learning, the ability to analyse and interpret complex data sets is crucial for future business leaders. Our MSc in Business Analytics & AI will equip you with advanced computational, machine learning, and AI capabilities to suc || cussions will be complemented by real datasets from retail, supply chain, finance, and other industries. You will be prepared to use analytical and data-driven approaches to make informed management decisions. Read more Deep Learning and Generative AI The module provides a self-contained overview of deep learning and generative AI. The contents of the module consist of two parts. In the first part you will study the general framework of loss functio","tors. Find out more about career outcomes . / Discover the Imperial advantage Programme content Pre-study and Core modules will prepare you with essential foundation skills in areas such as statistics, machine learning, data visualisation and genAI, equipping you to analyse complex data and generate actionable insights. Elective modules allow you to tailor the programme to your interests, with modules focused on different industries (e.g. finance, energy || Find out more about career outcomes . / Discover the Imperial advantage Programme content Pre-study and Core modules will prepare you with essential foundation skills in areas such as statistics, machine learning, data visualisation and genAI, equipping you to analyse complex data and generate actionable insights. Elective modules allow you to tailor the programme to your interests, with modules focused on different industries (e.g. finance, energy",MSc Business Analytics & AI - Business School Skip to main content Imperial Business School Secondary Top Navigation News Blogs Events Corporate Relations Search Close Search Menu About us Rankings and accreditations Meet the Dean School Lead,"graduate destinations, from technology companies like Amazon and Google to finance organisations like HSBC or Mastercard. Our graduates also work in a range of other sectors including healthcare, advertising or luxury. Employment outcomes below refer to the Class of 2024. 95 % 95 % employed within six months 56 % 56 % employed in the UK 38 % 38 % employed in finance Find out more about career outcomes What our students say “Imperial has helped m || prepare for your future driving business transformation through data. 4th in Europe (QS Business Master’s Rankings 2026, Business Analytics) 8th in the world (QS Business Master’s Rankings 2026, Business Analytics) 95% employed within six months (Class of 2024) 10 elective options Explore the programme London location Study in a global hub for business and finance, learn across our South Kensington and White City campuses , and benefit from ou || Business Analytics & AI graduates go on to work for leading companies such as Amazon, Bloomb..."
11,EU_08,primary,https://www.epfl.ch/education/master/programs/data-science/,"du fil d'Ariane Education Affiche les pages de même niveau About Education Research Innovation Schools Campus Laboratories list Master Affiche les pages de même niveau Admission Academic Calendar Preparatory year (CMS) Bachelor Master Doctorate SHS Program Continuing Education – Extension School Study management International Teaching Educational Initiatives Education and Science Outreach Infrastructures under development Engagement with Socie || emic records. EPFL degrees EPFL Bachelor’s degrees in another related field of science and engineering are also subject to a dossier-based analysis and are eligible if they are accompanied by excellent academic records. Prerequisites for all applications In addition, skills in mathematics, in particular in calculus, discrete mathematics, linear algebra and probability, as well as a solid understanding of algorithms, data structures, and databases a","nitiatives Education and Science Outreach Infrastructures under development Engagement with Society Master’s programs Affiche les pages de même niveau Study programs structure Master’s programs Master Info Days Double degrees, joint Master’s Master excellence fellowships EPFL Students Prizes Data Science Affiche les pages de même niveau Applied Mathematics Applied Physics Architecture Chemical Engineering and Biotechnology Civil Engineerin",<NA>,digm but also at the root of innovative applications in all sectors of the economy. The goal of this Master’s program is to place students at the forefront of this exciting development. Simplified study plan Master (120 ECTS credits) Please note that the information regarding programs’ structure as well as the simplified study plans may be subject to change and that they are not legally binding. Only the official regulations and study plans,"and Entrepreneurship Materials Science and Engineering Mathematics Mechanical Engineering Microengineering Molecular and Biological Chemistry Neuro-X Nuclear Engineering Physics Quantum Science and Engineering Robotics Statistics Sustainable Management and Technology Urban Systems About Education Research Innovation Schools Campus In the same section Applied Mathematics Applied Physics Architecture Chemical Engineering and Biotechnology Civil En || analysis and are eligible if they are accompanied by excellent academic records. Prerequisites for all applications In addition, skills in mathematics, in particular in calculus, discrete mathematics, linear algebra and probability, as well as a solid understanding of algorithms, data structures, and databases are required. Candidates should be proficient in programming languages (Python, Java, C++) and have experience in software development. Kno","thematics, in particular in calculus, discrete mathematics, linear algebra and probability, as well as a solid understanding of algorithms, data structures, and databases are required. Candidates should be proficient in programming languages (Python, Java, C++) and have experience in software development. Knowledge of operating systems, computer architecture, and the theory of computation is critical for developing and managing software systems ac || r in calculus, discrete mathematics, linear algebra and probability, as well as a solid understanding of algorithms, data structures, and databases are required. Candidates should be proficient in programming languages (Python, Java, C++) and have experience in software development. Knowledge of operating systems, computer architecture, and the theory of computation is critical for developing and managing software systems across various level","ge and often heterogeneous data. EPFL’s Master’s program in Data Science offers a comprehensive education, from the foundations to implementation, from algorithms to database architecture, and from information theory to machine learning. The Master’s program is offered by the School of computer and communication sciences in collaboration with the School of basic sciences (mathematics) and the School of engineering (electrical engineering). Program’s ob",<NA>,<NA>,<NA>

In [187]:
evidence_fields = [
    "prerequisites",
    "GRE_GMAT",
    "tuition",
    "duration",
    "statistics",
    "programming",
    "machine_learning",
    "visualization",
    "business_analytics",
    "outcomes"
]


coverage_rows = []

for programme_id in batch_ids:

    subset = successful_pages[
        successful_pages["programme_id"]
        == programme_id
    ]

    row = {
        "programme_id": programme_id
    }

    for field in evidence_fields:

        col = f"{field}_evidence"

        row[field] = int(
            subset[col]
            .notna()
            .any()
        ) if len(subset) > 0 else 0

    coverage_rows.append(row)


evidence_coverage = pd.DataFrame(
    coverage_rows
)

display(evidence_coverage)

,programme_id,prerequisites,GRE_GMAT,tuition,duration,statistics,programming,machine_learning,visualization,business_analytics,outcomes
0,EU_04,0,0,0,0,0,0,0,0,0,0
1,EU_05,1,1,1,1,1,1,1,1,1,1
2,EU_06,0,0,0,0,0,0,0,0,0,0
3,EU_07,0,0,0,0,0,0,0,0,0,0
4,EU_08,1,1,0,1,1,1,1,0,0,0
5,EU_09,1,1,1,1,1,0,1,0,0,0
6,EU_10,1,1,1,1,1,1,1,1,0,1
7,EU_11,1,1,1,1,1,1,0,0,1,1
8,EU_12,1,1,1,1,1,1,1,0,0,1
9,EU_13,1,1,0,1,0,0,1,0,0,0
10,EU_14,1,1,1,1,1,0,1,0,0,0
11,EU_15,1,1,1,1,1,1,1,0,1,1
12,EU_16,1,1,1,1,1,0,1,0,1,1
13,EU_17,1,1,1,1,1,0,1,1,0,0
14,EU_18,1,1,0,1,1,0,0,0,1,0
15,EU_19,1,1,0,1,1,1,1,1,1,0
16,EU_20,1,1,1,1,1,0,1,0,1,0

In [188]:
def combine_evidence(series, max_items=3):
    values = [
        str(x)
        for x in series.dropna()
        if str(x).strip()
    ]

    # Remove duplicates
    values = list(dict.fromkeys(values))

    if not values:
        return pd.NA

    return " || ".join(
        values[:max_items]
    )


review_rows = []

for programme_id in batch_ids:

    subset = successful_pages[
        successful_pages["programme_id"]
        == programme_id
    ]

    master_row = batch_review[
        batch_review["programme_id"]
        == programme_id
    ].iloc[0]

    row = {
        "programme_id":
            programme_id,

        "university":
            master_row["university"],

        "programme_name":
            master_row["programme_name"],

        "prerequisites_evidence":
            combine_evidence(
                subset["prerequisites_evidence"]
            ),

        "GRE_GMAT_evidence":
            combine_evidence(
                subset["GRE_GMAT_evidence"]
            ),

        "tuition_evidence":
            combine_evidence(
                subset["tuition_evidence"]
            ),

        "duration_evidence":
            combine_evidence(
                subset["duration_evidence"]
            ),

        "statistics_evidence":
            combine_evidence(
                subset["statistics_evidence"]
            ),

        "programming_evidence":
            combine_evidence(
                subset["programming_evidence"]
            ),

        "machine_learning_evidence":
            combine_evidence(
                subset["machine_learning_evidence"]
            ),

        "visualization_evidence":
            combine_evidence(
                subset["visualization_evidence"]
            ),

        "business_analytics_evidence":
            combine_evidence(
                subset["business_analytics_evidence"]
            ),

        "outcomes_evidence":
            combine_evidence(
                subset["outcomes_evidence"]
            ),

        "source_urls":
            " || ".join(
                subset["url"]
                .dropna()
                .drop_duplicates()
                .tolist()
            )
            if len(subset) > 0
            else pd.NA,

        "review_status":
            (
                "Pending review"
                if len(subset) > 0
                else "Manual review needed"
            )
    }

    review_rows.append(row)


programme_review = pd.DataFrame(
    review_rows
)

display(
    programme_review[
        [
            "programme_id",
            "university",
            "programme_name",
            "review_status"
        ]
    ]
)

,programme_id,university,programme_name,review_status
0,EU_04,UCL,MSc Data Science,Manual review needed
1,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),Pending review
2,EU_06,University of Oxford,MSc in Social Data Science,Manual review needed
3,EU_07,UCL,MSc Data Science and Public Policy,Manual review needed
4,EU_08,EPFL,Master in Data Science,Pending review
5,EU_09,Technical University of Munich,MSc Mathematics in Data Science,Pending review
6,EU_10,King's College London,MSc Data Science,Pending review
7,EU_11,University of Edinburgh,MSc Business Analytics,Pending review
8,EU_12,University of Edinburgh,MSc Data Science,Pending review
9,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,Pending review
10,EU_14,KU Leuven,Master of Statistics and Data Science,Pending review
11,EU_15,Lund University,MSc Data Analytics and Business Economics,Pending review
12,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,Pending review
13,EU_17,Utrecht University,MSc Data Science,Pending review
14,EU_18,RWTH Aachen University,MSc Data Science,Pending review
15,EU_19,Technical University of Denmark,MSc Business Analytics,Pending review
16,EU_20,Aalto University,Master's Programme in Business Analytics,Pending review

In [189]:
programme_review.to_csv(
    "../data/europe_2026_evidence_review.csv",
    index=False,
    encoding="utf-8-sig"
)

print(
    "Saved:",
    "../data/europe_2026_evidence_review.csv"
)

Saved: ../data/europe_2026_evidence_review.csv

In [190]:
europe_2026.to_csv(
    "../data/europe_2026_raw.csv",
    index=False,
    encoding="utf-8-sig"
)

validation_table.to_csv(
    "../data/europe_2026_validation.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Current progress saved.")

Current progress saved.

In [191]:
import re
import pandas as pd


def extract_duration_candidate(text):
    if pd.isna(text):
        return pd.NA

    text = str(text)

    patterns = [
        # 12 months / 18 months / 24 months
        r'\b(12|18|24)\s*months?\b',

        # 1 year / 2 years
        r'\b(1|2)\s*(?:calendar\s+)?years?\b'
    ]

    candidates = []

    for pattern in patterns:
        for match in re.finditer(
            pattern,
            text,
            flags=re.IGNORECASE
        ):
            value = int(match.group(1))

            if "year" in match.group(0).lower():
                value = value * 12

            candidates.append(value)

    if not candidates:
        return pd.NA

    return " | ".join(
        map(
            str,
            sorted(set(candidates))
        )
    )


programme_review[
    "duration_candidate"
] = programme_review[
    "duration_evidence"
].apply(
    extract_duration_candidate
)

In [192]:
def extract_tuition_candidates(text):
    if pd.isna(text):
        return pd.NA

    text = str(text)

    patterns = [
        r'£\s?[\d,]+',
        r'€\s?[\d,.]+',
        r'CHF\s?[\d,]+',
        r'DKK\s?[\d,.]+',
        r'EUR\s?[\d,.]+',
        r'GBP\s?[\d,.]+'
    ]

    candidates = []

    for pattern in patterns:
        matches = re.findall(
            pattern,
            text,
            flags=re.IGNORECASE
        )

        candidates.extend(matches)

    # remove duplicates
    candidates = list(
        dict.fromkeys(candidates)
    )

    if not candidates:
        return pd.NA

    return " | ".join(
        candidates[:10]
    )


programme_review[
    "tuition_candidate"
] = programme_review[
    "tuition_evidence"
].apply(
    extract_tuition_candidates
)

In [193]:
def classify_test_policy_candidate(text):
    if pd.isna(text):
        return "Not reported"

    text_lower = str(text).lower()

    not_required_patterns = [
        "gre is not required",
        "gre not required",
        "gmat is not required",
        "gmat not required",
        "not require the gre",
        "not require gre",
        "not require gmat"
    ]

    required_patterns = [
        "gre is required",
        "gre required",
        "gmat is required",
        "gmat required"
    ]

    optional_patterns = [
        "gre optional",
        "gmat optional",
        "gre is optional",
        "gmat is optional"
    ]

    if any(
        x in text_lower
        for x in not_required_patterns
    ):
        return "Possible: Not required"

    if any(
        x in text_lower
        for x in required_patterns
    ):
        return "Possible: Required"

    if any(
        x in text_lower
        for x in optional_patterns
    ):
        return "Possible: Optional"

    # GRE/GMAT appeared but context is unclear
    if (
        "gre" in text_lower
        or "gmat" in text_lower
    ):
        return "Mentioned - manual review"

    return "Not reported"


programme_review[
    "GRE_GMAT_candidate"
] = programme_review[
    "GRE_GMAT_evidence"
].apply(
    classify_test_policy_candidate
)

In [194]:
candidate_check = programme_review[
    [
        "programme_id",
        "university",
        "duration_candidate",
        "tuition_candidate",
        "GRE_GMAT_candidate",
        "review_status"
    ]
].copy()

display(candidate_check)

,programme_id,university,duration_candidate,tuition_candidate,GRE_GMAT_candidate,review_status
0,EU_04,UCL,<NA>,<NA>,Not reported,Manual review needed
1,EU_05,Imperial College London,12,<NA>,Mentioned - manual review,Pending review
2,EU_06,University of Oxford,<NA>,<NA>,Not reported,Manual review needed
3,EU_07,UCL,<NA>,<NA>,Not reported,Manual review needed
4,EU_08,EPFL,<NA>,<NA>,Mentioned - manual review,Pending review
5,EU_09,Technical University of Munich,<NA>,<NA>,Mentioned - manual review,Pending review
6,EU_10,King's College London,<NA>,<NA>,Mentioned - manual review,Pending review
7,EU_11,University of Edinburgh,12,<NA>,Mentioned - manual review,Pending review
8,EU_12,University of Edinburgh,12 | 24,<NA>,Mentioned - manual review,Pending review
9,EU_13,Delft University of Technology,24,<NA>,Mentioned - manual review,Pending review
10,EU_14,KU Leuven,<NA>,<NA>,Mentioned - manual review,Pending review
11,EU_15,Lund University,12,<NA>,Mentioned - manual review,Pending review
12,EU_16,Politecnico di Milano,12,"€100 | €25,000 | € 13,000.00",Mentioned - manual review,Pending review
13,EU_17,Utrecht University,24,<NA>,Mentioned - manual review,Pending review
14,EU_18,RWTH Aachen University,<NA>,<NA>,Mentioned - manual review,Pending review
15,EU_19,Technical University of Denmark,<NA>,<NA>,Mentioned - manual review,Pending review
16,EU_20,Aalto University,<NA>,<NA>,Mentioned - manual review,Pending review

In [195]:
pending_review = programme_review[
    programme_review["review_status"]
    == "Pending review"
][
    [
        "programme_id",
        "university",
        "programme_name",
        "duration_candidate",
        "duration_evidence",
        "tuition_candidate",
        "tuition_evidence",
        "GRE_GMAT_candidate",
        "GRE_GMAT_evidence"
    ]
].copy()

display(
    pending_review[
        [
            "programme_id",
            "university",
            "duration_candidate",
            "tuition_candidate",
            "GRE_GMAT_candidate"
        ]
    ]
)

,programme_id,university,duration_candidate,tuition_candidate,GRE_GMAT_candidate
1,EU_05,Imperial College London,12,<NA>,Mentioned - manual review
4,EU_08,EPFL,<NA>,<NA>,Mentioned - manual review
5,EU_09,Technical University of Munich,<NA>,<NA>,Mentioned - manual review
6,EU_10,King's College London,<NA>,<NA>,Mentioned - manual review
7,EU_11,University of Edinburgh,12,<NA>,Mentioned - manual review
8,EU_12,University of Edinburgh,12 | 24,<NA>,Mentioned - manual review
9,EU_13,Delft University of Technology,24,<NA>,Mentioned - manual review
10,EU_14,KU Leuven,<NA>,<NA>,Mentioned - manual review
11,EU_15,Lund University,12,<NA>,Mentioned - manual review
12,EU_16,Politecnico di Milano,12,"€100 | €25,000 | € 13,000.00",Mentioned - manual review
13,EU_17,Utrecht University,24,<NA>,Mentioned - manual review
14,EU_18,RWTH Aachen University,<NA>,<NA>,Mentioned - manual review
15,EU_19,Technical University of Denmark,<NA>,<NA>,Mentioned - manual review
16,EU_20,Aalto University,<NA>,<NA>,Mentioned - manual review

In [196]:
duration_review_batch = pending_review[
    [
        "programme_id",
        "university",
        "programme_name",
        "duration_candidate",
        "duration_evidence"
    ]
].copy()

pd.set_option(
    "display.max_colwidth",
    500
)

display(duration_review_batch)

,programme_id,university,programme_name,duration_candidate,duration_evidence
1,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),12,"day 30 September 2026 Request Info Add to course compare Course details Overview Structure Teaching and assessment Entry requirements How to apply Fees and funding Careers Request info Course key facts Qualification MSc Duration 1 year Start date October 2027 Study mode Full-time Delivered by Department of Mathematics Location South Kensington Applications: places 25:1 (2024-25) Minimum entry standard 2:1 in Statistics, Mathematics, Engineering || r an interruption, your fees will only incre..."
4,EU_08,EPFL,Master in Data Science,<NA>,digm but also at the root of innovative applications in all sectors of the economy. The goal of this Master’s program is to place students at the forefront of this exciting development. Simplified study plan Master (120 ECTS credits) Please note that the information regarding programs’ structure as well as the simplified study plans may be subject to change and that they are not legally binding. Only the official regulations and study plans
5,EU_09,Technical University of Munich,MSc Mathematics in Data Science,<NA>,athematics in Data Science combines a high-profile education in Mathematics with an emphasis on the burgeoning areas of Data Science and Artificial Intelligence. Course Homepage Key Data Type of Study Full-time Standard Duration of Studies 4 (fulltime) Credits 120 ECTS Main Locations Garching Application Period Winter semester: 01.02. – 31.05. Summer semester: 01.10. – 30.11. Admission Category Aptitude Assessment for Master Start of Degree || TUM in figures Rankings Awards and Honors Awards...
6,EU_10,King's College London,MSc Data Science,<NA>,"rview Our Data Science MSc provides you with the essential knowledge and advanced skills for a successful career in data science. You'll learn to collect, curate, and analyse data, gaining a rigorous grounding in all aspects of data analytics and big data. This programme is designed for graduates and professionals with a background in quantitative subjects who want to master current methods and techniques in data science. The course covers || d to submit both the original and official transl..."
7,EU_11,University of Edinburgh,MSc Business Analytics,12,"holars Ethics & Integrity Alumni Our Alumni Network Alumni Events Meet Our Alumni Aluminate Get Involved Stay Connected Support the School Update Your Details News Collaborate Opportunities for Collaboration Student Projects Share Your Insights Recruit Our Students Access Research Expertise Develop Your Talent Dissertation executive summaries Contact Events About Us The School Rankings, Achievements & Accreditation Mission, Vision & Values || velopment. It provided me with a solid foundation..."
8,EU_12,University of Edinburgh,MSc Data Science,12 | 24,"fairs, it provides resources such CV/cover letter reviews and constant updates on industry opportunities. Gwennan Drouillet MSc Data Science, graduated 2025 Fees, costs and funding Tuition fees Tuition fees by award and duration Tuition fees for full-time and part-time options are listed for one academic year. Part-time MSc Data Science (2 years) tuition fees MSc Data Science (3 years) tuition fees Full-time MSc Data Science (1 year) tuition fe || aster's degree. It is a substantial piece of..."
9,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,24,"d data science, including data management, as AI components and systems are often data-driven. Degree Master of Data Science and Artificial Intelligence Technology Accreditation Accredited by the NVAO Credits 120 EC, 24 Months Type Regular study programme Mode Full-time Language of instruction English Start September Explore this master's challenging themes This master enables you to obtain advanced knowledge and skills in subject areas of Da"
10,EU_14,KU Leuven,Master of Statistics and Data Science,<NA>,sp.) The Master of Statistics and Data Sciences will help you develop a problem-solving attitude and teach you how to apply statistical methodology. You'll be trained intensively in both the theoretical and practical aspects of statistics and data science. Leuven Master's 120 ECTS credits English Faculty of Science Apply now Discover the programme keyboard_arrow_down Discover the programme Programme structure Admission requirements Further
11,EU_15,Lund University,MSc Data Analytics and Business Economics,12,"tries. In this programme, you will learn how to work the numbers, draw conclusions, and communicate your results. Application dates Play video Programme video: MSc Data Analytics and Business Economics Start Autumn 2026 Duration 1 year Level Master's Language English Place of study Lund Application dates Overview Teaching and learning Career prospects Overview Have you noticed how Netflix and YouTube send you suggestions based on your previous || w the entry requirements and read the how to ..."
12,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,12,"pportunities available. To book your info session, complete the form and you will be contacted to schedule your appointment. REGISTER NOW Subject Artificial Intelligence & Data Science Intake October 2026 Location Milan Duration 12 months Format Full Time Language English Individuals €25,000 € 13,000.00 (POLIMI MSc Alumni) Experience Less than 3 years Apply Now DOWNLOAD BROCHURE INTERNATIONAL MASTERS OFFICE infomasters@gsom.polimi.it +39 02 239 || which means that they may close even before ..."
13,EU_17,Utrecht University,MSc Data Science,24,"ng. Have a research concept you would like to explore hands-on? Bring your idea, and they’ll help you make it yourself. Key facts Degree: Informatica (MSc) Language of instruction: English Mode of study: Full-time Study duration: 2 years Start: February, September Tuition fees: Dutch and other EU/EEA students (statutory fee, full-time) 2026-2027: € 2,694 Non-EU/EEA students (institutional fee) 2026-2027: 25,306 More information about fees Croho || esearch concept you would like to explore ha..."
14,EU_18,RWTH Aachen University,MSc Data Science,<NA>,-science@cs.rwth-aachen.de ). You might also be interested in general information about the Faculty of Computer Science of RWTH Aachen University and the Faculty of Computer Science’s chairs and institutes . Career Prospects Data-Science methods are used in a broad spectrum of applications in science and industry. Data science gains increasing importance in the industry due to the desire and the need for utilizing the information that becom
15,EU_19,Technical University of Denmark,MSc Business Analytics,<NA>,"ness Analytics Explore Frontpage Education Graduate MSc programmes Business Analytics Share on back Business Analytics Prerequisites Curriculum Specializations Career Master of Science (MSc) in Business Analytics In the years to come, digitization will have an enormous impact on the development of companies and on society as a whole. Oops, this feature requires cookies To view the content, you must change your cookie consent to allow functio || dy, you will work with quantitative methods, su..."
16,EU_20,Aalto University,Master's Programme in Business Analytics,<NA>,e eligibility of all its graduates at the end of each academic year. Academic performance is determined on the basis of the weighted average grade of all the studies towards the degree. The target time (or the normative duration of studies) is no more than 10 academic terms as an attending student for those pursuing both a bachelor’s and master’s degree at the Aalto University School of Business. no more than 4 academic terms as an attending st || tics. Graduates possess in-depth knowledge o...

In [197]:
def extract_duration_sentences(text):
    if pd.isna(text):
        return pd.NA

    text = re.sub(r"\s+", " ", str(text))

    # Split roughly into sentences / page fragments
    pieces = re.split(
        r'(?<=[.!?])\s+|(?=\bDuration\b)|(?=\bLength\b)',
        text
    )

    duration_patterns = [
        r'\b\d+\s*(?:calendar\s+)?years?\b',
        r'\b\d+\s*months?\b',
        r'\b\d+\s*ECTS\b',
        r'\bfull[- ]time\b',
        r'\bpart[- ]time\b'
    ]

    hits = []

    for piece in pieces:
        piece_lower = piece.lower()

        # Prefer pieces actually related to programme duration
        duration_context = any(
            word in piece_lower
            for word in [
                "duration",
                "full-time",
                "full time",
                "part-time",
                "part time",
                "programme",
                "program",
                "study",
                "ects"
            ]
        )

        has_duration_value = any(
            re.search(
                pattern,
                piece,
                flags=re.IGNORECASE
            )
            for pattern in duration_patterns[:3]
        )

        if duration_context and has_duration_value:
            hits.append(
                piece.strip()[:600]
            )

    hits = list(dict.fromkeys(hits))

    if not hits:
        return pd.NA

    return " || ".join(hits[:5])

In [198]:
duration_sentence_rows = []

for programme_id in batch_ids:

    subset = successful_pages[
        successful_pages["programme_id"]
        == programme_id
    ]

    evidence_list = []

    for _, page in subset.iterrows():

        evidence = extract_duration_sentences(
            page["page_text"]
        )

        if pd.notna(evidence):
            evidence_list.append(
                f"[{page['page_type']}] {evidence}"
            )

    duration_sentence_rows.append({
        "programme_id": programme_id,
        "duration_text":
            " || ".join(evidence_list)
            if evidence_list
            else pd.NA
    })


duration_sentence_review = pd.DataFrame(
    duration_sentence_rows
)

duration_sentence_review = (
    batch_review[
        [
            "programme_id",
            "university",
            "programme_name"
        ]
    ]
    .merge(
        duration_sentence_review,
        on="programme_id",
        how="left"
    )
)

pd.set_option(
    "display.max_colwidth",
    1000
)

display(duration_sentence_review)

,programme_id,university,programme_name,duration_text
0,EU_04,UCL,MSc Data Science,<NA>
1,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),"[primary] Duration 1 year Start date October 2027 Study mode Full-time Delivered by Department of Mathematics Location South Kensington Applications: places 25:1 (2024-25) Minimum entry standard 2:1 in Statistics, Mathematics, Engineering, Physics or Computer Science. || Optional modules You choose at least three modules from Group A and the remainder from Group B to total 25-27.5 ECTS. || Each module is worth 5 ECTS unless otherwise stated. || Deep Learning (7.5 ECTS) Explore the building blocks of deep learning models, and how to design network architectures for specific applications. || Probabilistic Generative Models (7.5 ECTS) You will gain a solid foundation in probabilistic generative models, learning training, inference, and model types such as autoregressive, implicit, and Bayesian nonparametric. || [outcomes] Duration: 12 months Next application deadline: 29 September 2026 Fee: £47,000 Location: London, UK Admissions Fees and funding Show page contents Overview Programme ..."
2,EU_06,University of Oxford,MSc in Social Data Science,<NA>
3,EU_07,UCL,MSc Data Science and Public Policy,<NA>
4,EU_08,EPFL,Master in Data Science,[primary] Simplified study plan Master (120 ECTS credits) Please note that the information regarding programs’ structure as well as the simplified study plans may be subject to change and that they are not legally binding.
5,EU_09,Technical University of Munich,MSc Mathematics in Data Science,"[primary] Mathematics in Data Science - Master of Science (M.Sc.) - TUM Show convenient version of this site Don't show this message again Skip to main content TUM Technical University of Munich News and Events Close menu News and Events See overview All News Events Events See overview Event overview Presidential Lunches Open House Garching Sustainability Day Welcome@TUM Dies Academicus Advent Concerts Magazine Magazine See overview TUM Magazine Issue 3/26 TUM Magazine Issue 2/25 TUM Magazine Issue 1/25 Podcasts Podcasts See overview We are TUM Series Series See overview NewIn One Topic, One Loop Search || Save settings Open search Open navigation Search navigation Reset search News and Events Back News and Events All News Events Back Events Event overview Presidential Lunches Open House Garching Sustainability Day Welcome@TUM Dies Academicus Advent Concerts Magazine Back Magazine TUM Magazine Issue 3/26 TUM Magazine Issue 2/25 TUM Magazine Issue 1/25 Podcasts Back Podcasts We are ..."
6,EU_10,King's College London,MSc Data Science,"[primary] Related courses Artificial Intelligence for Science MSc 1 year full-time, September to September Full-time In person Computational Finance MSc 1 year full-time Full-time In person Advanced Computing MSc One year full-time, September to September Full-time In person Cyber Security MSc 1 year full-time, September to September Full-time In person Study Degree courses Footer navigation link Postgraduate taught Footer navigation link Postgraduate research Footer navigation link International Footer navigation link Summer schools Footer navigation link Student experience Footer navigation link Infor"
7,EU_11,University of Edinburgh,MSc Business Analytics,"[tuition] Business Analytics MSc - Postgraduate taught programmes | The University of Edinburgh Skip to main content Study Global Visit Research News About Alumni Local Staff Students Schools & departments MyEd Submit search Degree finder Subsite menu Home Search degree programmes Search degree programmes Undergraduate degree programmes Postgraduate taught programmes Postgraduate research programmes A to Z of degree programmes A to Z of degree programmes Undergraduate degree programmes A to Z (2027 entry) Postgraduate taught degree programmes A to Z Postgraduate research degree programmes A to Z Degree || Full-time MSc Business Analytics (1 year) tuition fees Graduate discount If you are a University of Edinburgh graduate, you will be eligible for a 10% discount on your tuition fees for this programme. || Full-time MSc Business Analytics (1 year) (2026-2027) We link to the latest information available. || Select programme - Select a programme - MSc Business Analytics (1 year) Afte..."
8,EU_12,University of Edinburgh,MSc Data Science,"[primary] Level: Postgraduate taught Subject: Computing and Informatics Year of entry: 2026 Study options Mode of study On campus Part-time MSc | up to 3 years | Start date: multiple dates Full-time MSc | 1 year | Start date: September 2026 Key facts School School of Informatics College College of Science and Engineering Programme website Programme website Study location Central Area 17 to 19 November 2026: Postgraduate Virtual Open Days Join us live to explore postgraduate taught and research study at Edinburgh and gain key insights before you apply. || Study options This programme can be studied full-time over 1 year or part-time for up to 3 years. || Part-time MSc Data Science (2 years) tuition fees MSc Data Science (3 years) tuition fees Full-time MSc Data Science (1 year) tuition fees Graduate discount If you are a University of Edinburgh graduate, you will be eligible for a 10% discount on your tuition fees for this programme. || You should have experience of computer program..."
9,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,"[primary] Degree Master of Data Science and Artificial Intelligence Technology Accreditation Accredited by the NVAO Credits 120 EC, 24 Months Type Regular study programme Mode Full-time Language of instruction English Start September Explore this master's challenging themes This master enables you to obtain advanced knowledge and skills in subject areas of Data Science and AI Technology through inspiring themes, allowing you to work on specific types of challenges you might encounter as a professional. || [admissions] Programme Year 1 Quarter 1 Quarter 2 Quarter 3 Quarter 4 Data management and Engineering Software Engineering and Testing for AI Systems Responsible Data Science and AI Engineering Research course Machine and Deep Learning Theme 1 Theme 1 Theme 1 Probabilistic AI and Reasoning Theme 2 Theme 2 Theme 2 Year 2 Quarter 5 Quarter 6 Quarter 7 Quarter 8 Deepening / broadening electives Master Thesis Core courses Themes Research course Deepening / broadening electives Master ..."
10,EU_14,KU Leuven,Master of Statistics and Data Science,[primary] Leuven Master's 120 ECTS credits English Faculty of Science Apply now Discover the programme keyboard_arrow_down Discover the programme Programme structure Admission requirements Further studies More Objectives Non-binding personal development goals Quality of education Master of Statistics and Data Science Discover the Master of Statistics and Data Science at KU Leuven in Belgium. || [outcomes] Leuven Master's 120 ECTS credits English Faculty of Science Apply now Discover the programme keyboard_arrow_down Discover the programme Programme structure Admission requirements Further studies More Objectives Non-binding personal development goals Quality of education Master of Statistics and Data Science Discover the Master of Statistics and Data Science at KU Leuven in Belgium.
11,EU_15,Lund University,MSc Data Analytics and Business Economics,"[primary] Data Analytics and Business Economics - Master's Programme Master's programme • 1 year • 60 credits Transforming data into insights that can enhance decision-making is a key challenge for companies of every size, across all industries. || Duration 1 year Level Master's Language English Place of study Lund Application dates Overview Teaching and learning Career prospects Overview Have you noticed how Netflix and YouTube send you suggestions based on your previous views?"
12,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,"[primary] Please note that we’ve designed this programme for recent graduates with ideally no more than 3 years of work experience. || If you are a non-EU candidate, we recommend that you apply at least 3 months before the programme starts, to leave enough time for a Statement of Comparability of your degree and to apply for your student visa. || Duration 12 months Format Full Time Language English Individuals €25,000 € 13,000.00 (POLIMI MSc Alumni) Experience Less than 3 years Apply Now DOWNLOAD BROCHURE INTERNATIONAL MASTERS OFFICE infomasters@gsom.polimi.it +39 02 2399 2820 DOWNLOAD BROCHURE MIP Politecnico di Milano Graduate School of Business S.C.p.A Via Lambruschini 4/c – Building 26/a 20156 MILANO Phone: +39 02 23992820 C.F./P.IVA e iscrizione R.I."
13,EU_17,Utrecht University,MSc Data Science,"[primary] Related Master’s Programmes This programme operates in parallel to the 1 year Master’s programme in Applied Data Science , that instead aims on how to apply existing data science tools and solutions in different application domains. || Key facts Degree: Informatica (MSc) Language of instruction: English Mode of study: Full-time Study duration: 2 years Start: February, September Tuition fees: Dutch and other EU/EEA students (statutory fee, full-time) 2026-2027: € 2,694 Non-EU/EEA students (institutional fee) 2026-2027: 25,306 More information about fees Croho code: 66978 Accreditation: Accredited by the NVAO Faculty: Science Graduate school: School of Natural Sciences Brochure: Request a brochure Feedback Feedback Footer menu (EN) Go to Choose a programme Student information Jobs Alumni Giving Services Intranet for employees || [curriculum] Secondary electives can be considered any master course offered by any department of the university with at least 7.5 ECTS, that has ..."
14,EU_18,RWTH Aachen University,MSc Data Science,<NA>
15,EU_19,Technical University of Denmark,MSc Business Analytics,[primary] The MSc is a two-year graduate programme with a workload of 120 ECTS credit points. || [curriculum] Curriculum for Business Analytics Go to primary content (press enter) Education Continuing Education Research Innovation Collaboration About DTU News Contact Danish English Search All search results People Contents Publications News Contact Danish English Explore Frontpage Education Graduate MSc programmes Business Analytics Curriculum Share on back Prerequisites Curriculum Specializations Career Curriculum for Business Analytics Programme provision To obtain the MSc degree in Business Analytics the student must fulfil the following requirements: Have passed Polytechnical foundation courses ad || 02270 Cybersecurity Fundamentals 5 point Autumn E5B (Wed 13-17) 02417 Time Series Analysis 5 point Spring F4B (Fri 8-12) 02443 Stochastic Simulation 5 point June 02805 Social graphs and interactions 10 point Autumn E5 (Wed 8-17) 02806 Social data analysis and visualization 5 point ...
16,EU_20,Aalto University,Master's Programme in Business Analytics,"[curriculum] Degree structure Total 120 ECTS Programme studies* 85-87 ECTS Elective studies 33-35 ECTS *Including master's thesis 30 ECTS You can find course descriptions in Sisu . || Programme studies 85–87 ECTS Programme studies Code : BIZ235 Scope : 85–87 ECTS Programme director: Juuso Liesiö Code Course name ECTS Period 30E03000 Data Science for Business I 6 I, IV ISM-E1004 Business Analytics 2 6 III ISM-E1999 Master's Thesis Seminar 3 I-II, III-V BIZ.matr Maturity Test 0 ISM.thes Master's Thesis 30 Choose at least one of the following 30E03500 Capstone: Data Science for Business II 6 II 57E00500 Capstone: Business Intelligence 6 IV-V Choose one or two of the following Choose only one course from this section if you selected both Capstone courses above, otherwise choose || Elective studies 33–35 ECTS Instructions for choosing elective studies You can choose elective studies to your Master's degree so that the scope of the degree (120 credits) is fulfilled. || If you have comple..."

In [199]:
for _, row in duration_sentence_review.iterrows():

    print("=" * 90)

    print(
        row["programme_id"],
        "|",
        row["university"],
        "|",
        row["programme_name"]
    )

    print("-" * 90)

    if pd.isna(row["duration_text"]):
        print("NO AUTOMATED EVIDENCE")

    else:
        print(row["duration_text"])

    print()

==========================================================================================
EU_04 | UCL | MSc Data Science
------------------------------------------------------------------------------------------
NO AUTOMATED EVIDENCE

==========================================================================================
EU_05 | Imperial College London | MSc Statistics (Data Science and Machine Learning)
------------------------------------------------------------------------------------------
[primary] Duration 1 year Start date October 2027 Study mode Full-time Delivered by Department of Mathematics Location South Kensington Applications: places 25:1 (2024-25) Minimum entry standard 2:1 in Statistics, Mathematics, Engineering, Physics or Computer Science. || Optional modules You choose at least three modules from Group A and the remainder from Group B to total 25-27.5 ECTS. || Each module is worth 5 ECTS unless otherwise stated. || Deep Learning (7.5 ECTS) Explore the building blocks of deep learning models, and how to design network architectures for specific applications. || Probabilistic Generative Models (7.5 ECTS) You will gain a solid foundation in probabilistic generative models, learning training, inference, and model types such as autoregressive, implicit, and Bayesian nonparametric. || [outcomes] Duration: 12 months Next application deadline: 29 September 2026 Fee: £47,000 Location: London, UK Admissions Fees and funding Show page contents Overview Programme content Admissions Fees and funding Who attends Career impact Faculty FAQs Apply now Study your MSc Business Analytics & AI at a world-leading university 2nd in the world (Imperial College London, QS World University Rankings 2027) 3rd in Europe (Imperial College London, Times Higher Education World University Rankings 2026) #3 city for students (London, QS Best Student City Rankings 2027) Drive business transformation through data || We are pleased to offer an optional extended term , that will allow you to extend your programme duration to 16 months. || Almost all of the MSc programmes we have available are 12 month, full-time programmes.

==========================================================================================
EU_06 | University of Oxford | MSc in Social Data Science
------------------------------------------------------------------------------------------
NO AUTOMATED EVIDENCE

==========================================================================================
EU_07 | UCL | MSc Data Science and Public Policy
------------------------------------------------------------------------------------------
NO AUTOMATED EVIDENCE

==========================================================================================
EU_08 | EPFL | Master in Data Science
------------------------------------------------------------------------------------------
[primary] Simplified study plan Master (120 ECTS credits) Please note that the information regarding programs’ structure as well as the simplified study plans may be subject to change and that they are not legally binding.

==========================================================================================
EU_09 | Technical University of Munich | MSc Mathematics in Data Science
------------------------------------------------------------------------------------------
[primary] Mathematics in Data Science - Master of Science (M.Sc.) - TUM Show convenient version of this site Don't show this message again Skip to main content TUM Technical University of Munich News and Events Close menu News and Events See overview All News Events Events See overview Event overview Presidential Lunches Open House Garching Sustainability Day Welcome@TUM Dies Academicus Advent Concerts Magazine Magazine See overview TUM Magazine Issue 3/26 TUM Magazine Issue 2/25 TUM Magazine Issue 1/25 Podcasts Podcasts See overview We are TUM Series Series See overview NewIn One Topic, One Loop Search || Save settings Open search Open navigation Search navigation Reset search News and Events Back News and Events All News Events Back Events Event overview Presidential Lunches Open House Garching Sustainability Day Welcome@TUM Dies Academicus Advent Concerts Magazine Back Magazine TUM Magazine Issue 3/26 TUM Magazine Issue 2/25 TUM Magazine Issue 1/25 Podcasts Back Podcasts We are TUM Series Back Series NewIn One Topic, One Loop Studies Back Studies Degree Programs Back Degree Programs Bachelor’s degree programs Master’s degree programs Key Skill Programs Back Key Skill Programs Plug-in Modules  || Duration of Studies 4 (fulltime) Credits 120 ECTS Main Locations Garching Application Period Winter semester: 01.02.

==========================================================================================
EU_10 | King's College London | MSc Data Science
------------------------------------------------------------------------------------------
[primary] Related courses Artificial Intelligence for Science MSc 1 year full-time, September to September Full-time In person Computational Finance MSc 1 year full-time Full-time In person Advanced Computing MSc One year full-time, September to September Full-time In person Cyber Security MSc 1 year full-time, September to September Full-time In person Study Degree courses Footer navigation link Postgraduate taught Footer navigation link Postgraduate research Footer navigation link International Footer navigation link Summer schools Footer navigation link Student experience Footer navigation link Infor

==========================================================================================
EU_11 | University of Edinburgh | MSc Business Analytics
------------------------------------------------------------------------------------------
[tuition] Business Analytics MSc - Postgraduate taught programmes | The University of Edinburgh Skip to main content Study Global Visit Research News About Alumni Local Staff Students Schools & departments MyEd Submit search Degree finder Subsite menu Home Search degree programmes Search degree programmes Undergraduate degree programmes Postgraduate taught programmes Postgraduate research programmes A to Z of degree programmes A to Z of degree programmes Undergraduate degree programmes A to Z (2027 entry) Postgraduate taught degree programmes A to Z Postgraduate research degree programmes A to Z Degree  || Full-time MSc Business Analytics (1 year) tuition fees Graduate discount If you are a University of Edinburgh graduate, you will be eligible for a 10% discount on your tuition fees for this programme. || Full-time MSc Business Analytics (1 year) (2026-2027) We link to the latest information available. || Select programme - Select a programme - MSc Business Analytics (1 year) After you apply Once you have applied for this programme, you will be able to track the progress of your application and accept or decline any offers.

==========================================================================================
EU_12 | University of Edinburgh | MSc Data Science
------------------------------------------------------------------------------------------
[primary] Level: Postgraduate taught Subject: Computing and Informatics Year of entry: 2026 Study options Mode of study On campus Part-time MSc | up to 3 years | Start date: multiple dates Full-time MSc | 1 year | Start date: September 2026 Key facts School School of Informatics College College of Science and Engineering Programme website Programme website Study location Central Area 17 to 19 November 2026: Postgraduate Virtual Open Days Join us live to explore postgraduate taught and research study at Edinburgh and gain key insights before you apply. || Study options This programme can be studied full-time over 1 year or part-time for up to 3 years. || Part-time MSc Data Science (2 years) tuition fees MSc Data Science (3 years) tuition fees Full-time MSc Data Science (1 year) tuition fees Graduate discount If you are a University of Edinburgh graduate, you will be eligible for a 10% discount on your tuition fees for this programme. || You should have experience of computer programming equivalent to an introductory programming course and have completed the equivalent of 60 SCQF credits or 30 ECTS credits of mathematics during your degree that have typically covered the following subjects/topics: calculus (differentiation and integration), linear algebra (vectors and multi-dimensional matrices), discrete mathematics and mathematical reasoning (e.g. || Part-time MSc Data Science (2 years) (2026-2027) MSc Data Science (3 years) (2026-2027) Full-time MSc Data Science (1 year) (2026-2027) We link to the latest information available.

==========================================================================================
EU_13 | Delft University of Technology | MSc Data Science and Artificial Intelligence Technology
------------------------------------------------------------------------------------------
[primary] Degree Master of Data Science and Artificial Intelligence Technology Accreditation Accredited by the NVAO Credits 120 EC, 24 Months Type Regular study programme Mode Full-time Language of instruction English Start September Explore this master's challenging themes This master enables you to obtain advanced knowledge and skills in subject areas of Data Science and AI Technology through inspiring themes, allowing you to work on specific types of challenges you might encounter as a professional. || [admissions] Programme Year 1 Quarter 1 Quarter 2 Quarter 3 Quarter 4 Data management and Engineering Software Engineering and Testing for AI Systems Responsible Data Science and AI Engineering Research course Machine and Deep Learning Theme 1 Theme 1 Theme 1 Probabilistic AI and Reasoning Theme 2 Theme 2 Theme 2 Year 2 Quarter 5 Quarter 6 Quarter 7 Quarter 8 Deepening / broadening electives Master Thesis Core courses Themes Research course Deepening / broadening electives Master Thesis Questions? || [outcomes] Degree Master of Data Science and Artificial Intelligence Technology Accreditation Accredited by the NVAO Credits 120 EC, 24 Months Type Regular study programme Mode Full-time Language of instruction English Start September Explore this master's challenging themes This master enables you to obtain advanced knowledge and skills in subject areas of Data Science and AI Technology through inspiring themes, allowing you to work on specific types of challenges you might encounter as a professional.

==========================================================================================
EU_14 | KU Leuven | Master of Statistics and Data Science
------------------------------------------------------------------------------------------
[primary] Leuven Master's 120 ECTS credits English Faculty of Science Apply now Discover the programme keyboard_arrow_down Discover the programme Programme structure Admission requirements Further studies More Objectives Non-binding personal development goals Quality of education Master of Statistics and Data Science Discover the Master of Statistics and Data Science at KU Leuven in Belgium. || [outcomes] Leuven Master's 120 ECTS credits English Faculty of Science Apply now Discover the programme keyboard_arrow_down Discover the programme Programme structure Admission requirements Further studies More Objectives Non-binding personal development goals Quality of education Master of Statistics and Data Science Discover the Master of Statistics and Data Science at KU Leuven in Belgium.

==========================================================================================
EU_15 | Lund University | MSc Data Analytics and Business Economics
------------------------------------------------------------------------------------------
[primary] Data Analytics and Business Economics - Master's Programme Master's programme • 1 year • 60 credits Transforming data into insights that can enhance decision-making is a key challenge for companies of every size, across all industries. || Duration 1 year Level Master's Language English Place of study Lund Application dates Overview Teaching and learning Career prospects Overview Have you noticed how Netflix and YouTube send you suggestions based on your previous views?

==========================================================================================
EU_16 | Politecnico di Milano | Master in Business Analytics and Data Science
------------------------------------------------------------------------------------------
[primary] Please note that we’ve designed this programme for recent graduates with ideally no more than 3 years of work experience. || If you are a non-EU candidate, we recommend that you apply at least 3 months before the programme starts, to leave enough time for a Statement of Comparability of your degree and to apply for your student visa. || Duration 12 months Format Full Time Language English Individuals €25,000 € 13,000.00 (POLIMI MSc Alumni) Experience Less than 3 years Apply Now DOWNLOAD BROCHURE INTERNATIONAL MASTERS OFFICE infomasters@gsom.polimi.it +39 02 2399 2820 DOWNLOAD BROCHURE MIP Politecnico di Milano Graduate School of Business S.C.p.A Via Lambruschini 4/c – Building 26/a 20156 MILANO Phone: +39 02 23992820 C.F./P.IVA e iscrizione R.I.

==========================================================================================
EU_17 | Utrecht University | MSc Data Science
------------------------------------------------------------------------------------------
[primary] Related Master’s Programmes This programme operates in parallel to the 1 year Master’s programme in Applied Data Science , that instead aims on how to apply existing data science tools and solutions in different application domains. || Key facts Degree: Informatica (MSc) Language of instruction: English Mode of study: Full-time Study duration: 2 years Start: February, September Tuition fees: Dutch and other EU/EEA students (statutory fee, full-time) 2026-2027: € 2,694 Non-EU/EEA students (institutional fee) 2026-2027: 25,306 More information about fees Croho code: 66978 Accreditation: Accredited by the NVAO Faculty: Science Graduate school: School of Natural Sciences Brochure: Request a brochure Feedback Feedback Footer menu (EN) Go to Choose a programme Student information Jobs Alumni Giving Services Intranet for employees  || [curriculum] Secondary electives can be considered any master course offered by any department of the university with at least 7.5 ECTS, that has not been used as mandatory or primary elective.

==========================================================================================
EU_18 | RWTH Aachen University | MSc Data Science
------------------------------------------------------------------------------------------
NO AUTOMATED EVIDENCE

==========================================================================================
EU_19 | Technical University of Denmark | MSc Business Analytics
------------------------------------------------------------------------------------------
[primary] The MSc is a two-year graduate programme with a workload of 120 ECTS credit points. || [curriculum] Curriculum for Business Analytics Go to primary content (press enter) Education Continuing Education Research Innovation Collaboration About DTU News Contact Danish English Search All search results People Contents Publications News Contact Danish English Explore Frontpage Education Graduate MSc programmes Business Analytics Curriculum Share on back Prerequisites Curriculum Specializations Career Curriculum for Business Analytics Programme provision To obtain the MSc degree in Business Analytics the student must fulfil the following requirements: Have passed Polytechnical foundation courses ad || 02270 Cybersecurity Fundamentals 5 point Autumn E5B (Wed 13-17) 02417 Time Series Analysis 5 point Spring F4B (Fri 8-12) 02443 Stochastic Simulation 5 point June 02805 Social graphs and interactions 10 point Autumn E5 (Wed 8-17) 02806 Social data analysis and visualization 5 point Spring F3A (Tues 8-12) 02807 Computational Tools for Data Science 5 point E7 (Tues 18-22) 42112 Mathematical Programming Modelling 5 point January 42114 Integer Programming 5 point Autumn E4A (Tues 13-17) 42115 Network Optimization 5 point Autumn E4B (Fri 8-12) 42137 Optimization using metaheuristics 5 point Spring F

==========================================================================================
EU_20 | Aalto University | Master's Programme in Business Analytics
------------------------------------------------------------------------------------------
[curriculum] Degree structure Total 120 ECTS Programme studies* 85-87 ECTS Elective studies 33-35 ECTS *Including master's thesis 30 ECTS You can find course descriptions in Sisu . || Programme studies 85–87 ECTS Programme studies Code : BIZ235 Scope : 85–87 ECTS Programme director: Juuso Liesiö Code Course name ECTS Period 30E03000 Data Science for Business I 6 I, IV ISM-E1004 Business Analytics 2 6 III ISM-E1999 Master's Thesis Seminar 3 I-II, III-V BIZ.matr Maturity Test 0 ISM.thes Master's Thesis 30 Choose at least one of the following 30E03500 Capstone: Data Science for Business II 6 II 57E00500 Capstone: Business Intelligence 6 IV-V Choose one or two of the following Choose only one course from this section if you selected both Capstone courses above, otherwise choose || Elective studies 33–35 ECTS Instructions for choosing elective studies You can choose elective studies to your Master's degree so that the scope of the degree (120 credits) is fulfilled. || If you have completed your bachelor’s degree outside of Finland, you must complete minimum of 3 ECTS in English including both oral and written proficiency.

In [200]:
validated_duration = {
    "EU_05": 12,
    "EU_09": 24,
    "EU_11": 12,
    "EU_12": 12,
    "EU_13": 24,
    "EU_15": 12,
    "EU_16": 12,
    "EU_17": 24,
    "EU_19": 24
}

for programme_id, months in validated_duration.items():

    mask = (
        europe_2026["programme_id"]
        == programme_id
    )

    europe_2026.loc[
        mask,
        "duration_months"
    ] = months


display(
    europe_2026[
        [
            "programme_id",
            "university",
            "programme_name",
            "duration_months"
        ]
    ]
)

,programme_id,university,programme_name,duration_months
0,EU_01,Imperial College London,MSc Business Analytics & AI,12
1,EU_02,ETH Zurich,MSc Data Science,24
2,EU_03,UCL,MSc Business Analytics,12
3,EU_04,UCL,MSc Data Science,<NA>
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),12
5,EU_06,University of Oxford,MSc in Social Data Science,<NA>
6,EU_07,UCL,MSc Data Science and Public Policy,<NA>
7,EU_08,EPFL,Master in Data Science,<NA>
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,24
9,EU_10,King's College London,MSc Data Science,<NA>
10,EU_11,University of Edinburgh,MSc Business Analytics,12
11,EU_12,University of Edinburgh,MSc Data Science,12
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,24
13,EU_14,KU Leuven,Master of Statistics and Data Science,<NA>
14,EU_15,Lund University,MSc Data Analytics and Business Economics,12
15,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,12
16,EU_17,Utrecht University,MSc Data Science,24
17,EU_18,RWTH Aachen University,MSc Data Science,<NA>
18,EU_19,Technical University of Denmark,MSc Business Analytics,24
19,EU_20,Aalto University,Master's Programme in Business Analytics,<NA>

In [201]:
duration_missing = europe_2026[
    europe_2026["duration_months"].isna()
][
    [
        "programme_id",
        "university",
        "programme_name"
    ]
]

display(duration_missing)

,programme_id,university,programme_name
3,EU_04,UCL,MSc Data Science
5,EU_06,University of Oxford,MSc in Social Data Science
6,EU_07,UCL,MSc Data Science and Public Policy
7,EU_08,EPFL,Master in Data Science
9,EU_10,King's College London,MSc Data Science
13,EU_14,KU Leuven,Master of Statistics and Data Science
17,EU_18,RWTH Aachen University,MSc Data Science
19,EU_20,Aalto University,Master's Programme in Business Analytics

In [202]:
manual_duration_1 = {
    "EU_04": 12,
    "EU_06": 10,
    "EU_07": 12
}

for programme_id, months in manual_duration_1.items():

    mask = (
        europe_2026["programme_id"]
        == programme_id
    )

    europe_2026.loc[
        mask,
        "duration_months"
    ] = months

In [203]:
duration_missing = europe_2026[
    europe_2026["duration_months"].isna()
][
    [
        "programme_id",
        "university",
        "programme_name"
    ]
]

display(duration_missing)

,programme_id,university,programme_name
7,EU_08,EPFL,Master in Data Science
9,EU_10,King's College London,MSc Data Science
13,EU_14,KU Leuven,Master of Statistics and Data Science
17,EU_18,RWTH Aachen University,MSc Data Science
19,EU_20,Aalto University,Master's Programme in Business Analytics

In [204]:
manual_duration_2 = {
    "EU_08": 24,
    "EU_10": 12,
    "EU_14": 24,
    "EU_18": 24,
    "EU_20": 24
}

for programme_id, months in manual_duration_2.items():

    mask = (
        europe_2026["programme_id"]
        == programme_id
    )

    europe_2026.loc[
        mask,
        "duration_months"
    ] = months

In [205]:
duration_check = europe_2026[
    [
        "programme_id",
        "university",
        "programme_name",
        "duration_months"
    ]
].copy()

display(duration_check)

print(
    "\nMissing duration:",
    europe_2026["duration_months"].isna().sum()
)

,programme_id,university,programme_name,duration_months
0,EU_01,Imperial College London,MSc Business Analytics & AI,12
1,EU_02,ETH Zurich,MSc Data Science,24
2,EU_03,UCL,MSc Business Analytics,12
3,EU_04,UCL,MSc Data Science,12
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),12
5,EU_06,University of Oxford,MSc in Social Data Science,10
6,EU_07,UCL,MSc Data Science and Public Policy,12
7,EU_08,EPFL,Master in Data Science,24
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,24
9,EU_10,King's College London,MSc Data Science,12
10,EU_11,University of Edinburgh,MSc Business Analytics,12
11,EU_12,University of Edinburgh,MSc Data Science,12
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,24
13,EU_14,KU Leuven,Master of Statistics and Data Science,24
14,EU_15,Lund University,MSc Data Analytics and Business Economics,12
15,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,12
16,EU_17,Utrecht University,MSc Data Science,24
17,EU_18,RWTH Aachen University,MSc Data Science,24
18,EU_19,Technical University of Denmark,MSc Business Analytics,24
19,EU_20,Aalto University,Master's Programme in Business Analytics,24

Missing duration: 0

In [206]:
duration_sources = {
    "EU_04": "UCL official programme page",
    "EU_06": "Oxford official programme page",
    "EU_07": "UCL official programme page",
    "EU_08": "EPFL official programme/study plan",
    "EU_10": "King's official programme page",
    "EU_14": "KU Leuven official programme page",
    "EU_18": "DAAD programme record; cross-checked with RWTH Informatik",
    "EU_20": "Aalto official programme page"
}

for programme_id, source_note in duration_sources.items():

    mask = (
        validation_table["programme_id"]
        == programme_id
    )

    validation_table.loc[
        mask,
        "validation_notes"
    ] = (
        validation_table.loc[
            mask,
            "validation_notes"
        ]
        .fillna("")
        .astype(str)
        + " Duration validated: "
        + source_note
        + "."
    )

In [207]:
europe_2026.to_csv(
    "../data/europe_2026_raw.csv",
    index=False,
    encoding="utf-8-sig"
)

validation_table.to_csv(
    "../data/europe_2026_validation.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Duration completed and saved.")

Duration completed and saved.

In [208]:
tuition_status = europe_2026[
    [
        "programme_id",
        "university",
        "programme_name",
        "tuition_amount",
        "currency",
        "tuition_basis"
    ]
].copy()

display(tuition_status)

print(
    "\nMissing tuition:",
    europe_2026["tuition_amount"].isna().sum()
)

,programme_id,university,programme_name,tuition_amount,currency,tuition_basis
0,EU_01,Imperial College London,MSc Business Analytics & AI,47000,GBP,Total programme tuition (international)
1,EU_02,ETH Zurich,MSc Data Science,2190,CHF,Per semester; threefold tuition fee for students assigned to fee group 2
2,EU_03,UCL,MSc Business Analytics,46700,GBP,Full-time overseas tuition fee for 2026/27
3,EU_04,UCL,MSc Data Science,<NA>,<NA>,<NA>
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),<NA>,<NA>,<NA>
5,EU_06,University of Oxford,MSc in Social Data Science,<NA>,<NA>,<NA>
6,EU_07,UCL,MSc Data Science and Public Policy,<NA>,<NA>,<NA>
7,EU_08,EPFL,Master in Data Science,<NA>,<NA>,<NA>
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,<NA>,<NA>,<NA>
9,EU_10,King's College London,MSc Data Science,<NA>,<NA>,<NA>
10,EU_11,University of Edinburgh,MSc Business Analytics,<NA>,<NA>,<NA>
11,EU_12,University of Edinburgh,MSc Data Science,<NA>,<NA>,<NA>
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,<NA>,<NA>,<NA>
13,EU_14,KU Leuven,Master of Statistics and Data Science,<NA>,<NA>,<NA>
14,EU_15,Lund University,MSc Data Analytics and Business Economics,<NA>,<NA>,<NA>
15,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,<NA>,<NA>,<NA>
16,EU_17,Utrecht University,MSc Data Science,<NA>,<NA>,<NA>
17,EU_18,RWTH Aachen University,MSc Data Science,<NA>,<NA>,<NA>
18,EU_19,Technical University of Denmark,MSc Business Analytics,<NA>,<NA>,<NA>
19,EU_20,Aalto University,Master's Programme in Business Analytics,<NA>,<NA>,<NA>

Missing tuition: 17

In [209]:
tuition_missing = europe_2026[
    europe_2026["tuition_amount"].isna()
][
    [
        "programme_id",
        "university",
        "programme_name"
    ]
].copy()

display(tuition_missing)

,programme_id,university,programme_name
3,EU_04,UCL,MSc Data Science
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning)
5,EU_06,University of Oxford,MSc in Social Data Science
6,EU_07,UCL,MSc Data Science and Public Policy
7,EU_08,EPFL,Master in Data Science
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science
9,EU_10,King's College London,MSc Data Science
10,EU_11,University of Edinburgh,MSc Business Analytics
11,EU_12,University of Edinburgh,MSc Data Science
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology
13,EU_14,KU Leuven,Master of Statistics and Data Science
14,EU_15,Lund University,MSc Data Analytics and Business Economics
15,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science
16,EU_17,Utrecht University,MSc Data Science
17,EU_18,RWTH Aachen University,MSc Data Science
18,EU_19,Technical University of Denmark,MSc Business Analytics
19,EU_20,Aalto University,Master's Programme in Business Analytics

In [210]:
def extract_tuition_sentences(text):
    if pd.isna(text):
        return pd.NA

    text = re.sub(r"\s+", " ", str(text))

    # Split page into manageable pieces
    pieces = re.split(
        r'(?<=[.!?])\s+|(?=\bTuition\b)|(?=\bFees?\b)',
        text
    )

    # Currency / amount patterns
    money_patterns = [
        r'£\s?[\d,]+',
        r'€\s?[\d,.]+',
        r'CHF\s?[\d,]+',
        r'DKK\s?[\d,.]+',
        r'EUR\s?[\d,.]+',
        r'GBP\s?[\d,.]+'
    ]

    hits = []

    for piece in pieces:

        piece_lower = piece.lower()

        # Must be related to tuition / fees
        fee_context = any(
            word in piece_lower
            for word in [
                "tuition",
                "tuition fee",
                "tuition fees",
                "fee",
                "fees",
                "international",
                "overseas",
                "non-eu",
                "non-eu/eea",
                "institutional fee"
            ]
        )

        # Must contain a monetary amount
        has_money = any(
            re.search(
                pattern,
                piece,
                flags=re.IGNORECASE
            )
            for pattern in money_patterns
        )

        if fee_context and has_money:
            hits.append(
                piece.strip()[:800]
            )

    hits = list(dict.fromkeys(hits))

    if not hits:
        return pd.NA

    return " || ".join(hits[:6])

In [211]:
tuition_sentence_rows = []

for programme_id in batch_ids:

    subset = successful_pages[
        successful_pages["programme_id"]
        == programme_id
    ]

    evidence_list = []

    for _, page in subset.iterrows():

        evidence = extract_tuition_sentences(
            page["page_text"]
        )

        if pd.notna(evidence):

            evidence_list.append(
                f"[{page['page_type']}] {evidence}"
            )

    tuition_sentence_rows.append({
        "programme_id": programme_id,
        "tuition_text":
            " || ".join(evidence_list)
            if evidence_list
            else pd.NA
    })


tuition_sentence_review = pd.DataFrame(
    tuition_sentence_rows
)

tuition_sentence_review = (
    batch_review[
        [
            "programme_id",
            "university",
            "programme_name"
        ]
    ]
    .merge(
        tuition_sentence_review,
        on="programme_id",
        how="left"
    )
)

display(tuition_sentence_review)

,programme_id,university,programme_name,tuition_text
0,EU_04,UCL,MSc Data Science,<NA>
1,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),"[primary] The application fees for postgraduate courses are: £90 for all Master's applications, excluding those to Imperial Business School £125 for MSc applications to Imperial Business School £150 for MBA applications to Imperial Business School There is no application fee for Postgraduate Certificates, Postgraduate Diplomas, or courses such as PhDs and EngDs. || Fees and funding Home fee Overseas fee Home fee Home fee - Statistics streams 2027 entry Not set As a guide, the fee for 2026-27 was £22,400. || Martingale Scholarships: Full details and how to apply Overseas fee Overseas fee - Statistics streams 2027 entry Not set As a guide, the fee for 2026-27 was £39,900. || [outcomes] Fee: £47,000 Location: London, UK Admissions"
2,EU_06,University of Oxford,MSc in Social Data Science,<NA>
3,EU_07,UCL,MSc Data Science and Public Policy,<NA>
4,EU_08,EPFL,Master in Data Science,<NA>
5,EU_09,Technical University of Munich,MSc Mathematics in Data Science,<NA>
6,EU_10,King's College London,MSc Data Science,[admissions] A non-refundable application fee of £130 applies.
7,EU_11,University of Edinburgh,MSc Business Analytics,[tuition] Full details on the admissions process and the selection deadlines are available on the Business School website: Admissions strategy Deadlines for applicants applying to study in 2026/27 Round Application deadline Decisions by 1 15 October 2025 4 December 2025 2 10 December 2025 19 February 2026 3 11 February 2026 23 April 2026 4 22 April 2026 4 June 2026 5 10 June 2026 23 July 2026 Deadlines for applicants applying to study in 2027/28 Round Application deadline Decisions by 1 14 October 2026 3 December 2026 2 9 December 2026 18 February 2027 3 10 February 2027 22 April 2027 4 21 April 2027 3 June 2027 5 9 June 2027 22 July 2027 Application fee A non-refundable application fee of £60 is payable before your application can be considered.
8,EU_12,University of Edinburgh,MSc Data Science,"[primary] Find out how to receive your graduate discount Deposit If you receive an offer of admission you will need to pay a deposit to secure your place: £1,500 (this contributes towards your tuition fees) How and when to pay the deposit Costs Accommodation and living costs You will need to pay for your accommodation and living costs (such as rent, food and utility bills) for the duration of your programme."
9,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,<NA>
10,EU_14,KU Leuven,Master of Statistics and Data Science,<NA>
11,EU_15,Lund University,MSc Data Analytics and Business Economics,<NA>
12,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,"[primary] Fees and Benefits Hear from our Ambassadors Meet with us Subject Artificial Intelligence & Data Science Intake October 2026 Format Full Time Individuals €25,000 € 13,000.00 (POLIMI MSc Alumni) Apply Now DOWNLOAD BROCHURE Overview Data constitute the most precious resource in today’s digital economy and represent an asset of primary importance to drive key decisions, optimise actions, improve performance across all business functions, and pave the way to innovation. || Fee (EUR €100) 2. || Fees and Benefits The programme costs €25.000 . || A reduced fee of €13,000 is available for students who have graduated from Politecnico di Milano with a Master of Science degree, no more than 3 years before enrolling in the Master. || REGISTER NOW Subject Artificial Intelligence & Data Science Intake October 2026 Location Milan Duration 12 months Format Full Time Language English Individuals €25,000 € 13,000.00 (POLIMI MSc Alumni) Experience Less than 3 years Apply Now DOWNLOAD BROCHUR..."
13,EU_17,Utrecht University,MSc Data Science,"[primary] Tuition fees: Dutch and other EU/EEA students (statutory fee, full-time) 2026-2027: € 2,694 Non-EU/EEA students (institutional fee) 2026-2027: 25,306 More information about fees Croho code: 66978 Accreditation: Accredited by the NVAO Faculty: Science Graduate school: School of Natural Sciences Brochure: Request a brochure Feedback Feedback Footer menu (EN) Go to Choose a programme Student information Jobs Alumni Giving Services Intranet for employees Course planner My Timetable About UU Contact Directory Disclaimer Privacy Contact Follow UU Facebook Youtube LinkedIn Instagram Utrecht University Heidelberglaan 8 3584 CS Utrecht The Netherlands Tel."
14,EU_18,RWTH Aachen University,MSc Data Science,<NA>
15,EU_19,Technical University of Denmark,MSc Business Analytics,<NA>
16,EU_20,Aalto University,Master's Programme in Business Analytics,<NA>

In [212]:
tuition_found = tuition_sentence_review[
    tuition_sentence_review["tuition_text"].notna()
].copy()

print(
    "Programmes with automated tuition evidence:",
    len(tuition_found)
)

for _, row in tuition_found.iterrows():

    print("=" * 100)

    print(
        row["programme_id"],
        "|",
        row["university"],
        "|",
        row["programme_name"]
    )

    print("-" * 100)

    print(row["tuition_text"])

    print()

Programmes with automated tuition evidence: 6
====================================================================================================
EU_05 | Imperial College London | MSc Statistics (Data Science and Machine Learning)
----------------------------------------------------------------------------------------------------
[primary] The application fees for postgraduate courses are: £90 for all Master's applications, excluding those to Imperial Business School £125 for MSc applications to Imperial Business School £150 for MBA applications to Imperial Business School There is no application fee for Postgraduate Certificates, Postgraduate Diplomas, or courses such as PhDs and EngDs. || Fees and funding Home fee Overseas fee Home fee Home fee - Statistics streams 2027 entry Not set As a guide, the fee for 2026-27 was £22,400. || Martingale Scholarships: Full details and how to apply Overseas fee Overseas fee - Statistics streams 2027 entry Not set As a guide, the fee for 2026-27 was £39,900. || [outcomes] Fee: £47,000 Location: London, UK Admissions

====================================================================================================
EU_10 | King's College London | MSc Data Science
----------------------------------------------------------------------------------------------------
[admissions] A non-refundable application fee of £130 applies.

====================================================================================================
EU_11 | University of Edinburgh | MSc Business Analytics
----------------------------------------------------------------------------------------------------
[tuition] Full details on the admissions process and the selection deadlines are available on the Business School website: Admissions strategy Deadlines for applicants applying to study in 2026/27 Round Application deadline Decisions by 1 15 October 2025 4 December 2025 2 10 December 2025 19 February 2026 3 11 February 2026 23 April 2026 4 22 April 2026 4 June 2026 5 10 June 2026 23 July 2026 Deadlines for applicants applying to study in 2027/28 Round Application deadline Decisions by 1 14 October 2026 3 December 2026 2 9 December 2026 18 February 2027 3 10 February 2027 22 April 2027 4 21 April 2027 3 June 2027 5 9 June 2027 22 July 2027 Application fee A non-refundable application fee of £60 is payable before your application can be considered.

====================================================================================================
EU_12 | University of Edinburgh | MSc Data Science
----------------------------------------------------------------------------------------------------
[primary] Find out how to receive your graduate discount Deposit If you receive an offer of admission you will need to pay a deposit to secure your place: £1,500 (this contributes towards your tuition fees) How and when to pay the deposit Costs Accommodation and living costs You will need to pay for your accommodation and living costs (such as rent, food and utility bills) for the duration of your programme.

====================================================================================================
EU_16 | Politecnico di Milano | Master in Business Analytics and Data Science
----------------------------------------------------------------------------------------------------
[primary] Fees and Benefits Hear from our Ambassadors Meet with us Subject Artificial Intelligence & Data Science Intake October 2026 Format Full Time Individuals €25,000 € 13,000.00 (POLIMI MSc Alumni) Apply Now DOWNLOAD BROCHURE Overview Data constitute the most precious resource in today’s digital economy and represent an asset of primary importance to drive key decisions, optimise actions, improve performance across all business functions, and pave the way to innovation. || Fee (EUR €100) 2. || Fees and Benefits The programme costs €25.000 . || A reduced fee of €13,000 is available for students who have graduated from Politecnico di Milano with a Master of Science degree, no more than 3 years before enrolling in the Master. || REGISTER NOW Subject Artificial Intelligence & Data Science Intake October 2026 Location Milan Duration 12 months Format Full Time Language English Individuals €25,000 € 13,000.00 (POLIMI MSc Alumni) Experience Less than 3 years Apply Now DOWNLOAD BROCHURE INTERNATIONAL MASTERS OFFICE infomasters@gsom.polimi.it +39 02 2399 2820 DOWNLOAD BROCHURE MIP Politecnico di Milano Graduate School of Business S.C.p.A Via Lambruschini 4/c – Building 26/a 20156 MILANO Phone: +39 02 23992820 C.F./P.IVA e iscrizione R.I.

====================================================================================================
EU_17 | Utrecht University | MSc Data Science
----------------------------------------------------------------------------------------------------
[primary] Tuition fees: Dutch and other EU/EEA students (statutory fee, full-time) 2026-2027: € 2,694 Non-EU/EEA students (institutional fee) 2026-2027: 25,306 More information about fees Croho code: 66978 Accreditation: Accredited by the NVAO Faculty: Science Graduate school: School of Natural Sciences Brochure: Request a brochure Feedback Feedback Footer menu (EN) Go to Choose a programme Student information Jobs Alumni Giving Services Intranet for employees Course planner My Timetable About UU Contact Directory Disclaimer Privacy Contact Follow UU Facebook Youtube LinkedIn Instagram Utrecht University Heidelberglaan 8 3584 CS Utrecht The Netherlands Tel.

In [213]:
validated_tuition_1 = {
    "EU_05": {
        "amount": 39900,
        "currency": "GBP",
        "basis": "Full-time overseas tuition fee for 2026 entry"
    },

    "EU_16": {
        "amount": 25000,
        "currency": "EUR",
        "basis": "Total programme tuition; standard individual fee for October 2026 intake"
    },

    "EU_17": {
        "amount": 25306,
        "currency": "EUR",
        "basis": "Full-time Non-EU/EEA institutional tuition fee for 2026-2027"
    }
}


for programme_id, values in validated_tuition_1.items():

    mask = (
        europe_2026["programme_id"]
        == programme_id
    )

    europe_2026.loc[
        mask,
        "tuition_amount"
    ] = values["amount"]

    europe_2026.loc[
        mask,
        "currency"
    ] = values["currency"]

    europe_2026.loc[
        mask,
        "tuition_basis"
    ] = values["basis"]

In [214]:
tuition_missing = europe_2026[
    europe_2026["tuition_amount"].isna()
][
    [
        "programme_id",
        "university",
        "programme_name"
    ]
].copy()

display(tuition_missing)

print(
    "\nMissing tuition:",
    len(tuition_missing)
)

,programme_id,university,programme_name
3,EU_04,UCL,MSc Data Science
5,EU_06,University of Oxford,MSc in Social Data Science
6,EU_07,UCL,MSc Data Science and Public Policy
7,EU_08,EPFL,Master in Data Science
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science
9,EU_10,King's College London,MSc Data Science
10,EU_11,University of Edinburgh,MSc Business Analytics
11,EU_12,University of Edinburgh,MSc Data Science
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology
13,EU_14,KU Leuven,Master of Statistics and Data Science
14,EU_15,Lund University,MSc Data Analytics and Business Economics
17,EU_18,RWTH Aachen University,MSc Data Science
18,EU_19,Technical University of Denmark,MSc Business Analytics
19,EU_20,Aalto University,Master's Programme in Business Analytics

Missing tuition: 14

In [215]:
validated_tuition_2 = {
    "EU_04": {
        "amount": 46700,
        "currency": "GBP",
        "basis": "Full-time overseas tuition fee for 2026/27"
    },

    "EU_06": {
        "amount": 40730,
        "currency": "GBP",
        "basis": "Overseas annual course fee for 2026/27"
    },

    "EU_07": {
        "amount": 39200,
        "currency": "GBP",
        "basis": "Full-time overseas tuition fee for 2026/27"
    },

    "EU_10": {
        "amount": 40450,
        "currency": "GBP",
        "basis": "Full-time international tuition fee for 2026/27"
    },

    "EU_11": {
        "amount": 34800,
        "currency": "GBP",
        "basis": "International tuition fee for 2026 entry"
    }
}


for programme_id, values in validated_tuition_2.items():

    mask = europe_2026["programme_id"] == programme_id

    europe_2026.loc[
        mask, "tuition_amount"
    ] = values["amount"]

    europe_2026.loc[
        mask, "currency"
    ] = values["currency"]

    europe_2026.loc[
        mask, "tuition_basis"
    ] = values["basis"]

In [216]:
tuition_missing = europe_2026[
    europe_2026["tuition_amount"].isna()
][
    [
        "programme_id",
        "university",
        "programme_name"
    ]
].copy()

display(tuition_missing)

print(
    "\nMissing tuition:",
    len(tuition_missing)
)

,programme_id,university,programme_name
7,EU_08,EPFL,Master in Data Science
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science
11,EU_12,University of Edinburgh,MSc Data Science
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology
13,EU_14,KU Leuven,Master of Statistics and Data Science
14,EU_15,Lund University,MSc Data Analytics and Business Economics
17,EU_18,RWTH Aachen University,MSc Data Science
18,EU_19,Technical University of Denmark,MSc Business Analytics
19,EU_20,Aalto University,Master's Programme in Business Analytics

Missing tuition: 9

In [217]:
validated_tuition_3 = {
    "EU_08": {
        "amount": 2190,
        "currency": "CHF",
        "basis": "Tuition fee per semester for applicable foreign students"
    },

    "EU_12": {
        "amount": 45410,
        "currency": "GBP",
        "basis": "Full-time international tuition fee for 2026/27"
    },

    "EU_20": {
        "amount": 15000,
        "currency": "EUR",
        "basis": "Annual tuition fee for non-EU/EEA students"
    }
}


for programme_id, values in validated_tuition_3.items():

    mask = europe_2026["programme_id"] == programme_id

    europe_2026.loc[
        mask, "tuition_amount"
    ] = values["amount"]

    europe_2026.loc[
        mask, "currency"
    ] = values["currency"]

    europe_2026.loc[
        mask, "tuition_basis"
    ] = values["basis"]

In [218]:
tuition_missing = europe_2026[
    europe_2026["tuition_amount"].isna()
][
    [
        "programme_id",
        "university",
        "programme_name"
    ]
].copy()

display(tuition_missing)

print(
    "\nMissing tuition:",
    len(tuition_missing)
)

,programme_id,university,programme_name
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology
13,EU_14,KU Leuven,Master of Statistics and Data Science
14,EU_15,Lund University,MSc Data Analytics and Business Economics
17,EU_18,RWTH Aachen University,MSc Data Science
18,EU_19,Technical University of Denmark,MSc Business Analytics

Missing tuition: 6

In [219]:
validated_tuition_4 = {
    "EU_09": {
        "amount": 6000,
        "currency": "EUR",
        "basis": "Tuition fee per semester for international students from third countries"
    },

    "EU_15": {
        "amount": 150000,
        "currency": "SEK",
        "basis": "Full programme tuition fee for non-EU/EEA students"
    }
}

for programme_id, values in validated_tuition_4.items():

    mask = europe_2026["programme_id"] == programme_id

    europe_2026.loc[
        mask, "tuition_amount"
    ] = values["amount"]

    europe_2026.loc[
        mask, "currency"
    ] = values["currency"]

    europe_2026.loc[
        mask, "tuition_basis"
    ] = values["basis"]

In [220]:
tuition_missing = europe_2026[
    europe_2026["tuition_amount"].isna()
][
    [
        "programme_id",
        "university",
        "programme_name"
    ]
].copy()

display(tuition_missing)

print(
    "\nMissing tuition:",
    len(tuition_missing)
)

,programme_id,university,programme_name
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology
13,EU_14,KU Leuven,Master of Statistics and Data Science
17,EU_18,RWTH Aachen University,MSc Data Science
18,EU_19,Technical University of Denmark,MSc Business Analytics

Missing tuition: 4

In [221]:
validated_tuition_5 = {
    "EU_18": {
        "amount": 0,
        "currency": "EUR",
        "basis": (
            "No tuition fee, including for international students; "
            "semester contribution charged separately"
        )
    },

    "EU_19": {
        "amount": 7500,
        "currency": "EUR",
        "basis": (
            "Tuition fee per semester for fee-paying non-EU/EEA students; "
            "published total for 2-year MSc = EUR 30,000; "
            "DTU notes fees are expected to be revised for Autumn 2026"
        )
    }
}

for programme_id, values in validated_tuition_5.items():

    mask = europe_2026["programme_id"] == programme_id

    europe_2026.loc[
        mask, "tuition_amount"
    ] = values["amount"]

    europe_2026.loc[
        mask, "currency"
    ] = values["currency"]

    europe_2026.loc[
        mask, "tuition_basis"
    ] = values["basis"]

In [222]:
tuition_missing = europe_2026[
    europe_2026["tuition_amount"].isna()
][
    [
        "programme_id",
        "university",
        "programme_name"
    ]
].copy()

display(tuition_missing)

print(
    "\nMissing tuition:",
    len(tuition_missing)
)

,programme_id,university,programme_name
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology
13,EU_14,KU Leuven,Master of Statistics and Data Science

Missing tuition: 2

In [223]:
mask = europe_2026["programme_id"] == "EU_14"

europe_2026.loc[
    mask,
    "tuition_basis"
] = (
    "NR - official KU Leuven sources state that tuition depends "
    "on programme and nationality; no programme-specific 2026/27 "
    "non-EEA amount was directly verified."
)

In [224]:
mask = europe_2026["programme_id"] == "EU_13"

europe_2026.loc[
    mask,
    "tuition_basis"
] = (
    "NR - no programme-specific 2026/27 non-EU/EEA tuition amount "
    "was directly verified from the official TU Delft sources reviewed."
)

In [225]:
tuition_status = europe_2026[
    [
        "programme_id",
        "university",
        "tuition_amount",
        "currency",
        "tuition_basis"
    ]
].copy()

tuition_status["tuition_status"] = tuition_status.apply(
    lambda row:
        "Verified amount"
        if pd.notna(row["tuition_amount"])
        else (
            "NR - documented"
            if pd.notna(row["tuition_basis"])
            and str(row["tuition_basis"]).startswith("NR")
            else "Missing"
        ),
    axis=1
)

display(tuition_status)

print("\nStatus counts:")
print(tuition_status["tuition_status"].value_counts())

print(
    "\nUnresolved tuition:",
    (tuition_status["tuition_status"] == "Missing").sum()
)

,programme_id,university,tuition_amount,currency,tuition_basis,tuition_status
0,EU_01,Imperial College London,47000,GBP,Total programme tuition (international),Verified amount
1,EU_02,ETH Zurich,2190,CHF,Per semester; threefold tuition fee for students assigned to fee group 2,Verified amount
2,EU_03,UCL,46700,GBP,Full-time overseas tuition fee for 2026/27,Verified amount
3,EU_04,UCL,46700,GBP,Full-time overseas tuition fee for 2026/27,Verified amount
4,EU_05,Imperial College London,39900,GBP,Full-time overseas tuition fee for 2026 entry,Verified amount
5,EU_06,University of Oxford,40730,GBP,Overseas annual course fee for 2026/27,Verified amount
6,EU_07,UCL,39200,GBP,Full-time overseas tuition fee for 2026/27,Verified amount
7,EU_08,EPFL,2190,CHF,Tuition fee per semester for applicable foreign students,Verified amount
8,EU_09,Technical University of Munich,6000,EUR,Tuition fee per semester for international students from third countries,Verified amount
9,EU_10,King's College London,40450,GBP,Full-time international tuition fee for 2026/27,Verified amount
10,EU_11,University of Edinburgh,34800,GBP,International tuition fee for 2026 entry,Verified amount
11,EU_12,University of Edinburgh,45410,GBP,Full-time international tuition fee for 2026/27,Verified amount
12,EU_13,Delft University of Technology,<NA>,<NA>,NR - no programme-specific 2026/27 non-EU/EEA tuition amount was directly verified from the official TU Delft sources reviewed.,NR - documented
13,EU_14,KU Leuven,<NA>,<NA>,NR - official KU Leuven sources state that tuition depends on programme and nationality; no programme-specific 2026/27 non-EEA amount was directly verified.,NR - documented
14,EU_15,Lund University,150000,SEK,Full programme tuition fee for non-EU/EEA students,Verified amount
15,EU_16,Politecnico di Milano,25000,EUR,Total programme tuition; standard individual fee for October 2026 intake,Verified amount
16,EU_17,Utrecht University,25306,EUR,Full-time Non-EU/EEA institutional tuition fee for 2026-2027,Verified amount
17,EU_18,RWTH Aachen University,0,EUR,"No tuition fee, including for international students; semester contribution charged separately",Verified amount
18,EU_19,Technical University of Denmark,7500,EUR,"Tuition fee per semester for fee-paying non-EU/EEA students; published total for 2-year MSc = EUR 30,000; DTU notes fees are expected to be revised for Autumn 2026",Verified amount
19,EU_20,Aalto University,15000,EUR,Annual tuition fee for non-EU/EEA students,Verified amount

Status counts:
tuition_status
Verified amount    18
NR - documented     2
Name: count, dtype: int64

Unresolved tuition: 0

In [226]:
europe_2026.to_csv(
    "../data/europe_2026_raw.csv",
    index=False,
    encoding="utf-8-sig"
)

validation_table.to_csv(
    "../data/europe_2026_validation.csv",
    index=False,
    encoding="utf-8-sig"
)

print("2026 tuition stage saved.")

2026 tuition stage saved.

In [228]:
mask = europe_2026["programme_id"] == "EU_01"

europe_2026.loc[
    mask,
    "GRE_GMAT_policy"
] = "Optional / Recommended"

In [229]:
gre_status = europe_2026[
    [
        "programme_id",
        "university",
        "programme_name",
        "GRE_GMAT_policy"
    ]
].copy()

display(gre_status)

print("\nCurrent GRE/GMAT policy counts:")
print(
    gre_status["GRE_GMAT_policy"]
    .fillna("Missing")
    .value_counts()
)

,programme_id,university,programme_name,GRE_GMAT_policy
0,EU_01,Imperial College London,MSc Business Analytics & AI,Optional / Recommended
1,EU_02,ETH Zurich,MSc Data Science,Not reported
2,EU_03,UCL,MSc Business Analytics,Not reported
3,EU_04,UCL,MSc Data Science,<NA>
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),<NA>
5,EU_06,University of Oxford,MSc in Social Data Science,<NA>
6,EU_07,UCL,MSc Data Science and Public Policy,<NA>
7,EU_08,EPFL,Master in Data Science,<NA>
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,<NA>
9,EU_10,King's College London,MSc Data Science,<NA>
10,EU_11,University of Edinburgh,MSc Business Analytics,<NA>
11,EU_12,University of Edinburgh,MSc Data Science,<NA>
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,<NA>
13,EU_14,KU Leuven,Master of Statistics and Data Science,<NA>
14,EU_15,Lund University,MSc Data Analytics and Business Economics,<NA>
15,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,<NA>
16,EU_17,Utrecht University,MSc Data Science,<NA>
17,EU_18,RWTH Aachen University,MSc Data Science,<NA>
18,EU_19,Technical University of Denmark,MSc Business Analytics,<NA>
19,EU_20,Aalto University,Master's Programme in Business Analytics,<NA>

Current GRE/GMAT policy counts:
GRE_GMAT_policy
Missing                   17
Not reported               2
Optional / Recommended     1
Name: count, dtype: int64

In [230]:
validated_gre_1 = {
    "EU_04": "Not reported",
    "EU_06": "Not required"
}

for programme_id, policy in validated_gre_1.items():
    
    mask = europe_2026["programme_id"] == programme_id
    
    europe_2026.loc[
        mask,
        "GRE_GMAT_policy"
    ] = policy

In [231]:
gre_notes_1 = {
    "EU_04": (
        "GRE/GMAT not identified in the official 2026/27 "
        "programme entry requirements reviewed."
    ),
    
    "EU_06": (
        "Official Oxford programme page explicitly states that "
        "no GRE or GMAT scores are sought."
    )
}

for programme_id, note in gre_notes_1.items():
    
    mask = validation_table["programme_id"] == programme_id
    
    old_note = validation_table.loc[
        mask, "validation_notes"
    ].fillna("").astype(str)
    
    validation_table.loc[
        mask, "validation_notes"
    ] = old_note + " GRE/GMAT: " + note

In [232]:
gre_status = europe_2026[
    [
        "programme_id",
        "university",
        "programme_name",
        "GRE_GMAT_policy"
    ]
].copy()

display(gre_status)

print("\nCurrent GRE/GMAT policy counts:")
print(
    gre_status["GRE_GMAT_policy"]
    .fillna("Missing")
    .value_counts()
)

,programme_id,university,programme_name,GRE_GMAT_policy
0,EU_01,Imperial College London,MSc Business Analytics & AI,Optional / Recommended
1,EU_02,ETH Zurich,MSc Data Science,Not reported
2,EU_03,UCL,MSc Business Analytics,Not reported
3,EU_04,UCL,MSc Data Science,Not reported
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),<NA>
5,EU_06,University of Oxford,MSc in Social Data Science,Not required
6,EU_07,UCL,MSc Data Science and Public Policy,<NA>
7,EU_08,EPFL,Master in Data Science,<NA>
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,<NA>
9,EU_10,King's College London,MSc Data Science,<NA>
10,EU_11,University of Edinburgh,MSc Business Analytics,<NA>
11,EU_12,University of Edinburgh,MSc Data Science,<NA>
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,<NA>
13,EU_14,KU Leuven,Master of Statistics and Data Science,<NA>
14,EU_15,Lund University,MSc Data Analytics and Business Economics,<NA>
15,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,<NA>
16,EU_17,Utrecht University,MSc Data Science,<NA>
17,EU_18,RWTH Aachen University,MSc Data Science,<NA>
18,EU_19,Technical University of Denmark,MSc Business Analytics,<NA>
19,EU_20,Aalto University,Master's Programme in Business Analytics,<NA>

Current GRE/GMAT policy counts:
GRE_GMAT_policy
Missing                   15
Not reported               3
Optional / Recommended     1
Not required               1
Name: count, dtype: int64

In [233]:
gre_policy_update = {
    "EU_05": "Not reported",   # Imperial Statistics
    "EU_07": "Not reported",   # UCL Data Science & Public Policy
    "EU_08": "Not reported",   # EPFL Data Science
    "EU_09": "Not reported",   # TUM Mathematics in Data Science
    "EU_10": "Not reported",   # King's Data Science
    "EU_11": "Not reported",   # Edinburgh Business Analytics
    "EU_12": "Not reported",   # Edinburgh Data Science
    "EU_13": "Not reported",   # TU Delft DSAIT
    "EU_14": "Required",       # KU Leuven Statistics & Data Science
    "EU_15": "Not reported",   # Lund Data Analytics & Business Economics
    "EU_16": "Not reported",   # Polimi Business Analytics & Data Science
    "EU_17": "Not reported",   # Utrecht Data Science
    "EU_18": "Not reported",   # RWTH Data Science
    "EU_19": "Not reported",   # DTU Business Analytics
    "EU_20": "Conditional"     # Aalto Business Analytics
}

for programme_id, policy in gre_policy_update.items():
    europe_2026.loc[
        europe_2026["programme_id"] == programme_id,
        "GRE_GMAT_policy"
    ] = policy

In [234]:
display(
    europe_2026[
        [
            "programme_id",
            "university",
            "programme_name",
            "GRE_GMAT_policy"
        ]
    ]
)

print("\nMissing GRE/GMAT:",
      europe_2026["GRE_GMAT_policy"].isna().sum())

print("\nPolicy counts:")
print(europe_2026["GRE_GMAT_policy"].value_counts())

,programme_id,university,programme_name,GRE_GMAT_policy
0,EU_01,Imperial College London,MSc Business Analytics & AI,Optional / Recommended
1,EU_02,ETH Zurich,MSc Data Science,Not reported
2,EU_03,UCL,MSc Business Analytics,Not reported
3,EU_04,UCL,MSc Data Science,Not reported
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),Not reported
5,EU_06,University of Oxford,MSc in Social Data Science,Not required
6,EU_07,UCL,MSc Data Science and Public Policy,Not reported
7,EU_08,EPFL,Master in Data Science,Not reported
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,Not reported
9,EU_10,King's College London,MSc Data Science,Not reported
10,EU_11,University of Edinburgh,MSc Business Analytics,Not reported
11,EU_12,University of Edinburgh,MSc Data Science,Not reported
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,Not reported
13,EU_14,KU Leuven,Master of Statistics and Data Science,Required
14,EU_15,Lund University,MSc Data Analytics and Business Economics,Not reported
15,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,Not reported
16,EU_17,Utrecht University,MSc Data Science,Not reported
17,EU_18,RWTH Aachen University,MSc Data Science,Not reported
18,EU_19,Technical University of Denmark,MSc Business Analytics,Not reported
19,EU_20,Aalto University,Master's Programme in Business Analytics,Conditional

Missing GRE/GMAT: 0

Policy counts:
GRE_GMAT_policy
Not reported              16
Optional / Recommended     1
Not required               1
Required                   1
Conditional                1
Name: count, dtype: int64

In [235]:
# Correction discovered during prerequisite validation
europe_2026.loc[
    europe_2026["programme_id"] == "EU_09",
    "GRE_GMAT_policy"
] = "Conditional"


prerequisites_2026 = {

    "EU_01": (
        "Quantitative bachelor's degree; background typically including "
        "advanced calculus, probability, statistics and linear algebra."
    ),

    "EU_02": (
        "Bachelor's degree of at least 180 ECTS; substantial Mathematics "
        "and Computer Science background corresponding to a 76-ECTS "
        "discipline requirements profile."
    ),

    "EU_03": (
        "Normally an upper second-class bachelor's degree or equivalent; "
        "relevant experience may support applicants with a lower second-class degree."
    ),

    "EU_04": (
        "Quantitative bachelor's degree; university-level mathematical methods "
        "and linear algebra; introductory probability, statistics and computer "
        "programming; prior high-level programming experience required."
    ),

    "EU_05": (
        "Strong quantitative/mathematical bachelor's background appropriate "
        "for postgraduate study in statistics and data science."
    ),

    "EU_06": (
        "Normally first-class bachelor's degree; quantitative aptitude or "
        "experience in introductory calculus and matrix algebra expected."
    ),

    "EU_07": (
        "Upper second-class bachelor's degree or equivalent; at least one "
        "advanced undergraduate module in quantitative methods, statistics, "
        "data science or econometrics required."
    ),

    "EU_08": (
        "Bachelor's background in Computer Science, Communication Systems or "
        "related field; calculus, discrete mathematics, linear algebra, probability, "
        "algorithms, data structures, databases and programming required."
    ),

    "EU_09": (
        "Bachelor's degree in Mathematics, Informatics with a mathematics minor, "
        "or comparable field; relevant mathematics and computer-science competencies "
        "required; aptitude assessment applies."
    ),

    "EU_10": (
        "Quantitative bachelor's background with sufficient mathematical and "
        "computational preparation for postgraduate Data Science."
    ),

    "EU_11": (
        "2:1 bachelor's degree in a quantitative or related discipline; background "
        "should ideally include linear algebra, calculus, probability, statistics "
        "and computer programming."
    ),

    "EU_12": (
        "2:1 bachelor's degree in a quantitative discipline; introductory programming "
        "experience plus approximately 30 ECTS of mathematics including calculus, "
        "linear algebra, discrete mathematics and probability."
    ),

    "EU_13": (
        "Relevant bachelor's degree with sufficient mathematical, programming "
        "and technical preparation for Data Science and Artificial Intelligence."
    ),

    "EU_14": (
        "Relevant bachelor's-level preparation; prior statistical, mathematical "
        "and other quantitative coursework must be documented for admission review."
    ),

    "EU_15": (
        "Bachelor's degree of at least 180 credits with quantitative methods; "
        "specific statistics/mathematics, economics, informatics or business "
        "coursework pathways accepted, including regression/econometrics."
    ),

    "EU_16": (
        "Bachelor's background typically in computer science, economics, engineering, "
        "management, mathematics, science or statistics."
    ),

    "EU_17": (
        "Relevant research-university bachelor's degree, normally in Computer Science, "
        "Data Science or related field; programming, algorithms, data structures, "
        "data management, statistics, probability, logic and linear algebra expected."
    ),

    "EU_18": (
        "Relevant bachelor's degree with sufficient prior university-level "
        "mathematics, statistics and computer-science preparation."
    ),

    "EU_19": (
        "Relevant engineering/natural-science bachelor's degree; at least 60 ECTS "
        "across specified prerequisite areas including mathematics, statistics, "
        "optimization, programming, data science and natural sciences."
    ),

    "EU_20": (
        "Relevant bachelor's degree required; programme-specific academic "
        "background and admission criteria apply."
    )
}


for programme_id, prerequisite in prerequisites_2026.items():
    europe_2026.loc[
        europe_2026["programme_id"] == programme_id,
        "prerequisites"
    ] = prerequisite

In [236]:
display(
    europe_2026[
        [
            "programme_id",
            "university",
            "programme_name",
            "prerequisites"
        ]
    ]
)

print(
    "\nMissing prerequisites:",
    europe_2026["prerequisites"].isna().sum()
)

print(
    "Missing GRE/GMAT:",
    europe_2026["GRE_GMAT_policy"].isna().sum()
)

,programme_id,university,programme_name,prerequisites
0,EU_01,Imperial College London,MSc Business Analytics & AI,"Quantitative bachelor's degree; background typically including advanced calculus, probability, statistics and linear algebra."
1,EU_02,ETH Zurich,MSc Data Science,Bachelor's degree of at least 180 ECTS; substantial Mathematics and Computer Science background corresponding to a 76-ECTS discipline requirements profile.
2,EU_03,UCL,MSc Business Analytics,Normally an upper second-class bachelor's degree or equivalent; relevant experience may support applicants with a lower second-class degree.
3,EU_04,UCL,MSc Data Science,"Quantitative bachelor's degree; university-level mathematical methods and linear algebra; introductory probability, statistics and computer programming; prior high-level programming experience required."
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),Strong quantitative/mathematical bachelor's background appropriate for postgraduate study in statistics and data science.
5,EU_06,University of Oxford,MSc in Social Data Science,Normally first-class bachelor's degree; quantitative aptitude or experience in introductory calculus and matrix algebra expected.
6,EU_07,UCL,MSc Data Science and Public Policy,"Upper second-class bachelor's degree or equivalent; at least one advanced undergraduate module in quantitative methods, statistics, data science or econometrics required."
7,EU_08,EPFL,Master in Data Science,"Bachelor's background in Computer Science, Communication Systems or related field; calculus, discrete mathematics, linear algebra, probability, algorithms, data structures, databases and programming required."
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,"Bachelor's degree in Mathematics, Informatics with a mathematics minor, or comparable field; relevant mathematics and computer-science competencies required; aptitude assessment applies."
9,EU_10,King's College London,MSc Data Science,Quantitative bachelor's background with sufficient mathematical and computational preparation for postgraduate Data Science.
10,EU_11,University of Edinburgh,MSc Business Analytics,"2:1 bachelor's degree in a quantitative or related discipline; background should ideally include linear algebra, calculus, probability, statistics and computer programming."
11,EU_12,University of Edinburgh,MSc Data Science,"2:1 bachelor's degree in a quantitative discipline; introductory programming experience plus approximately 30 ECTS of mathematics including calculus, linear algebra, discrete mathematics and probability."
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,"Relevant bachelor's degree with sufficient mathematical, programming and technical preparation for Data Science and Artificial Intelligence."
13,EU_14,KU Leuven,Master of Statistics and Data Science,"Relevant bachelor's-level preparation; prior statistical, mathematical and other quantitative coursework must be documented for admission review."
14,EU_15,Lund University,MSc Data Analytics and Business Economics,"Bachelor's degree of at least 180 credits with quantitative methods; specific statistics/mathematics, economics, informatics or business coursework pathways accepted, including regression/econometrics."
15,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,"Bachelor's background typically in computer science, economics, engineering, management, mathematics, science or statistics."
16,EU_17,Utrecht University,MSc Data Science,"Relevant research-university bachelor's degree, normally in Computer Science, Data Science or related field; programming, algorithms, data structures, data management, statistics, probability, logic and linear algebra expected."
17,EU_18,RWTH Aachen University,MSc Data Science,"Relevant bachelor's degree with sufficient prior university-level mathematics, statistics and computer-science preparation."
18,EU_19,Technical University of Denmark,MSc Business Analytics,"Relevant engineering/natural-science bachelor's degree; at least 60 ECTS across specified prerequisite areas including mathematics, statistics, optimization, programming, data science and natural sciences."
19,EU_20,Aalto University,Master's Programme in Business Analytics,Relevant bachelor's degree required; programme-specific academic background and admission criteria apply.

Missing prerequisites: 0
Missing GRE/GMAT: 0

In [237]:
curriculum_1 = {
    "EU_01": [1, 1, 1, 1, 1],
    "EU_02": [1, 1, 1, 0, 0],
    "EU_03": [1, 1, 1, 0, 1],
    "EU_04": [1, 1, 1, 0, 0],
    "EU_05": [1, 1, 1, 0, 0]
}

curriculum_cols = [
    "statistics_core",
    "programming_core",
    "machine_learning_core",
    "data_visualization_core",
    "business_analytics_core"
]

for programme_id, values in curriculum_1.items():
    europe_2026.loc[
        europe_2026["programme_id"] == programme_id,
        curriculum_cols
    ] = values

In [238]:
curriculum_2 = {
    "EU_06": [1, 1, 1, 0, 0],
    "EU_07": [1, 1, 1, 0, 0],
    "EU_08": [1, 1, 1, 0, 0],
    "EU_09": [1, 1, 1, 0, 0],
    "EU_10": [1, 1, 0, 0, 0]
}

for programme_id, values in curriculum_2.items():
    europe_2026.loc[
        europe_2026["programme_id"] == programme_id,
        curriculum_cols
    ] = values

In [239]:
curriculum_3 = {
    "EU_11": [1, 1, 1, 0, 1],
    "EU_12": [1, 1, 1, 0, 0],
    "EU_13": [pd.NA, pd.NA, pd.NA, pd.NA, pd.NA],
    "EU_14": [1, 1, 1, 0, 0],
    "EU_15": [1, 1, 1, 1, 1]
}

for programme_id, values in curriculum_3.items():
    europe_2026.loc[
        europe_2026["programme_id"] == programme_id,
        curriculum_cols
    ] = values

In [240]:
curriculum_4 = {
    "EU_16": [1, 1, 1, 1, 1],
    "EU_17": [1, 1, 1, 1, 0],
    "EU_18": [1, 1, 1, 0, 0],
    "EU_19": [1, 1, 1, 0, 1],
    "EU_20": [1, 1, 1, 0, 1]
}

for programme_id, values in curriculum_4.items():
    europe_2026.loc[
        europe_2026["programme_id"] == programme_id,
        curriculum_cols
    ] = values

In [241]:
europe_2026["core_category_count"] = (
    europe_2026[curriculum_cols]
    .apply(pd.to_numeric, errors="coerce")
    .sum(axis=1, min_count=1)
)

display(
    europe_2026[
        ["programme_id", "programme_name"]
        + curriculum_cols
        + ["core_category_count"]
    ]
)

print(
    "\nProgrammes with fewer than 2 verified core categories:",
    (europe_2026["core_category_count"] < 2).sum()
)

print(
    "Programmes with curriculum completely NA:",
    europe_2026[curriculum_cols].isna().all(axis=1).sum()
)

,programme_id,programme_name,statistics_core,programming_core,machine_learning_core,data_visualization_core,business_analytics_core,core_category_count
0,EU_01,MSc Business Analytics & AI,1,1,1,1,1,5.0
1,EU_02,MSc Data Science,1,1,1,0,0,3.0
2,EU_03,MSc Business Analytics,1,1,1,0,1,4.0
3,EU_04,MSc Data Science,1,1,1,0,0,3.0
4,EU_05,MSc Statistics (Data Science and Machine Learning),1,1,1,0,0,3.0
5,EU_06,MSc in Social Data Science,1,1,1,0,0,3.0
6,EU_07,MSc Data Science and Public Policy,1,1,1,0,0,3.0
7,EU_08,Master in Data Science,1,1,1,0,0,3.0
8,EU_09,MSc Mathematics in Data Science,1,1,1,0,0,3.0
9,EU_10,MSc Data Science,1,1,0,0,0,2.0
10,EU_11,MSc Business Analytics,1,1,1,0,1,4.0
11,EU_12,MSc Data Science,1,1,1,0,0,3.0
12,EU_13,MSc Data Science and Artificial Intelligence Technology,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
13,EU_14,Master of Statistics and Data Science,1,1,1,0,0,3.0
14,EU_15,MSc Data Analytics and Business Economics,1,1,1,1,1,5.0
15,EU_16,Master in Business Analytics and Data Science,1,1,1,1,1,5.0
16,EU_17,MSc Data Science,1,1,1,1,0,4.0
17,EU_18,MSc Data Science,1,1,1,0,0,3.0
18,EU_19,MSc Business Analytics,1,1,1,0,1,4.0
19,EU_20,Master's Programme in Business Analytics,1,1,1,0,1,4.0

Programmes with fewer than 2 verified core categories: 0
Programmes with curriculum completely NA: 1

In [242]:
outcomes_update = {
    "EU_01": 1,   # Imperial BA & AI - programme-specific employment statistic
    "EU_02": 0,   # ETH Data Science
    "EU_03": 0,   # UCL Business Analytics

    "EU_04": 1,   # UCL Data Science - HESA Graduate Outcomes
    "EU_05": 0,   # Imperial Statistics DSML
    "EU_06": 0,   # Oxford Social Data Science
    "EU_07": 1,   # UCL Data Science & Public Policy - Graduate/Alumni Survey
    "EU_08": 0,   # EPFL Data Science
    "EU_09": 0,   # TUM Mathematics in Data Science
    "EU_10": 0,   # King's Data Science
    "EU_11": 0,   # Edinburgh Business Analytics
    "EU_12": 0,   # Edinburgh Data Science
    "EU_13": 0,   # TU Delft DSAIT
    "EU_14": 0,   # KU Leuven Statistics & Data Science
    "EU_15": 1,   # Lund DABE - programme-specific alumni career insights
    "EU_16": 0,   # Polimi BADS
    "EU_17": 0,   # Utrecht Data Science
    "EU_18": 0,   # RWTH Data Science
    "EU_19": 0,   # DTU Business Analytics
    "EU_20": 0    # Aalto Business Analytics
}

for programme_id, value in outcomes_update.items():
    europe_2026.loc[
        europe_2026["programme_id"] == programme_id,
        "outcomes_reported"
    ] = value

In [243]:
display(
    europe_2026[
        [
            "programme_id",
            "university",
            "programme_name",
            "outcomes_reported"
        ]
    ]
)

print(
    "\nMissing outcomes:",
    europe_2026["outcomes_reported"].isna().sum()
)

print("\nOutcome counts:")
print(europe_2026["outcomes_reported"].value_counts())

,programme_id,university,programme_name,outcomes_reported
0,EU_01,Imperial College London,MSc Business Analytics & AI,1
1,EU_02,ETH Zurich,MSc Data Science,0
2,EU_03,UCL,MSc Business Analytics,0
3,EU_04,UCL,MSc Data Science,1
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),0
5,EU_06,University of Oxford,MSc in Social Data Science,0
6,EU_07,UCL,MSc Data Science and Public Policy,1
7,EU_08,EPFL,Master in Data Science,0
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,0
9,EU_10,King's College London,MSc Data Science,0
10,EU_11,University of Edinburgh,MSc Business Analytics,0
11,EU_12,University of Edinburgh,MSc Data Science,0
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,0
13,EU_14,KU Leuven,Master of Statistics and Data Science,0
14,EU_15,Lund University,MSc Data Analytics and Business Economics,1
15,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,0
16,EU_17,Utrecht University,MSc Data Science,0
17,EU_18,RWTH Aachen University,MSc Data Science,0
18,EU_19,Technical University of Denmark,MSc Business Analytics,0
19,EU_20,Aalto University,Master's Programme in Business Analytics,0

Missing outcomes: 0

Outcome counts:
outcomes_reported
0    16
1     4
Name: count, dtype: int64

In [244]:
# Save completed 2026 checkpoint
europe_2026.to_csv(
    "../data/europe_2026_checkpoint.csv",
    index=False,
    encoding="utf-8-sig"
)

validation_table.to_csv(
    "../data/europe_2026_validation.csv",
    index=False,
    encoding="utf-8-sig"
)

print("2026 checkpoint saved.")
print("Rows:", len(europe_2026))
print("Columns:", len(europe_2026.columns))

2026 checkpoint saved.
Rows: 20
Columns: 26

In [245]:
historical_check = programme_master[
    ["programme_id", "university", "programme_name", "official_url"]
].copy()

historical_check["existed_in_2021"] = pd.NA
historical_check["archive_available_2021"] = pd.NA
historical_check["archive_url_2021"] = pd.NA
historical_check["historical_notes"] = pd.NA

display(historical_check)

,programme_id,university,programme_name,official_url,existed_in_2021,archive_available_2021,archive_url_2021,historical_notes
0,EU_01,Imperial College London,MSc Business Analytics & AI,https://www.imperial.ac.uk/business-school/masters/business-analytics/,<NA>,<NA>,<NA>,<NA>
1,EU_02,ETH Zurich,MSc Data Science,https://ethz.ch/en/studies/master/degree-programmes/engineering-sciences/data-science.html,<NA>,<NA>,<NA>,<NA>
2,EU_03,UCL,MSc Business Analytics,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/business-analytics-msc-2026,<NA>,<NA>,<NA>,<NA>
3,EU_04,UCL,MSc Data Science,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc,<NA>,<NA>,<NA>,<NA>
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),https://www.imperial.ac.uk/study/courses/postgraduate-taught/statistics-data-science/,<NA>,<NA>,<NA>,<NA>
5,EU_06,University of Oxford,MSc in Social Data Science,https://www.ox.ac.uk/admissions/graduate/courses/msc-social-data-science,<NA>,<NA>,<NA>,<NA>
6,EU_07,UCL,MSc Data Science and Public Policy,https://www.ucl.ac.uk/social-historical-sciences/economics/study/data-science-and-public-policy-msc,<NA>,<NA>,<NA>,<NA>
7,EU_08,EPFL,Master in Data Science,https://www.epfl.ch/education/master/programs/data-science/,<NA>,<NA>,<NA>,<NA>
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,https://www.tum.de/en/studies/degree-programs/detail/mathematics-in-data-science-master-of-science-msc,<NA>,<NA>,<NA>,<NA>
9,EU_10,King's College London,MSc Data Science,https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc,<NA>,<NA>,<NA>,<NA>
10,EU_11,University of Edinburgh,MSc Business Analytics,https://www.business-school.ed.ac.uk/msc/business-analytics,<NA>,<NA>,<NA>,<NA>
11,EU_12,University of Edinburgh,MSc Data Science,https://study.ed.ac.uk/programmes/postgraduate-taught/902-data-science,<NA>,<NA>,<NA>,<NA>
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,https://www.tudelft.nl/en/education/programmes/masters/dsait/msc-data-science-and-artificial-intelligence-technology,<NA>,<NA>,<NA>,<NA>
13,EU_14,KU Leuven,Master of Statistics and Data Science,https://onderwijsaanbod.kuleuven.be/opleidingen/e/SC_51016989/diploma_omschrijving,<NA>,<NA>,<NA>,<NA>
14,EU_15,Lund University,MSc Data Analytics and Business Economics,https://www.lunduniversity.lu.se/study/data-analytics-and-business-economics-masters-programme-EAGDA,<NA>,<NA>,<NA>,<NA>
15,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,https://www.gsom.polimi.it/en/course/master-business-analytics-data-science,<NA>,<NA>,<NA>,<NA>
16,EU_17,Utrecht University,MSc Data Science,https://www.uu.nl/en/masters/data-science,<NA>,<NA>,<NA>,<NA>
17,EU_18,RWTH Aachen University,MSc Data Science,https://sc.informatik.rwth-aachen.de/en/studium/master/master-data-science/,<NA>,<NA>,<NA>,<NA>
18,EU_19,Technical University of Denmark,MSc Business Analytics,https://www.dtu.dk/english/education/graduate/msc-programmes/business-analytics,<NA>,<NA>,<NA>,<NA>
19,EU_20,Aalto University,Master's Programme in Business Analytics,https://www.aalto.fi/en/programmes/masters-programme-in-business-analytics,<NA>,<NA>,<NA>,<NA>

In [246]:
import requests
import time

def find_2021_snapshot(url):
    cdx_url = "https://web.archive.org/cdx/search/cdx"

    params = {
        "url": url,
        "from": "2021",
        "to": "2021",
        "output": "json",
        "filter": "statuscode:200",
        "filter": "mimetype:text/html",
        "collapse": "digest",
        "fl": "timestamp,original,statuscode",
        "limit": "1"
    }

    try:
        r = requests.get(cdx_url, params=params, timeout=20)

        if r.status_code == 200:
            data = r.json()

            if len(data) > 1:
                timestamp = data[1][0]
                original = data[1][1]

                archive_url = (
                    f"https://web.archive.org/web/"
                    f"{timestamp}/{original}"
                )

                return 1, archive_url

        return 0, pd.NA

    except Exception:
        return pd.NA, pd.NA


for i, row in historical_check.iterrows():

    available, archive_url = find_2021_snapshot(
        row["official_url"]
    )

    historical_check.loc[
        i, "archive_available_2021"
    ] = available

    historical_check.loc[
        i, "archive_url_2021"
    ] = archive_url

    time.sleep(0.5)


display(
    historical_check[
        [
            "programme_id",
            "university",
            "programme_name",
            "archive_available_2021",
            "archive_url_2021"
        ]
    ]
)

print(
    "\n2021 snapshot found:",
    (historical_check["archive_available_2021"] == 1).sum()
)

print(
    "No snapshot for current URL:",
    (historical_check["archive_available_2021"] == 0).sum()
)

print(
    "Request/error unresolved:",
    historical_check["archive_available_2021"].isna().sum()
)

,programme_id,university,programme_name,archive_available_2021,archive_url_2021
0,EU_01,Imperial College London,MSc Business Analytics & AI,0,<NA>
1,EU_02,ETH Zurich,MSc Data Science,<NA>,<NA>
2,EU_03,UCL,MSc Business Analytics,<NA>,<NA>
3,EU_04,UCL,MSc Data Science,1,https://web.archive.org/web/20210612142325/https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),<NA>,<NA>
5,EU_06,University of Oxford,MSc in Social Data Science,1,https://web.archive.org/web/20210124204246/https://www.ox.ac.uk/admissions/graduate/courses/msc-social-data-science
6,EU_07,UCL,MSc Data Science and Public Policy,<NA>,<NA>
7,EU_08,EPFL,Master in Data Science,1,https://web.archive.org/web/20210122201057/https://www.epfl.ch/education/master/programs/data-science/
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,1,https://web.archive.org/web/20210621203634/https://www.tum.de/en/studies/degree-programs/detail/mathematics-in-data-science-master-of-science-msc/
9,EU_10,King's College London,MSc Data Science,<NA>,<NA>
10,EU_11,University of Edinburgh,MSc Business Analytics,<NA>,<NA>
11,EU_12,University of Edinburgh,MSc Data Science,0,<NA>
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,0,<NA>
13,EU_14,KU Leuven,Master of Statistics and Data Science,0,<NA>
14,EU_15,Lund University,MSc Data Analytics and Business Economics,0,<NA>
15,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,<NA>,<NA>
16,EU_17,Utrecht University,MSc Data Science,<NA>,<NA>
17,EU_18,RWTH Aachen University,MSc Data Science,<NA>,<NA>
18,EU_19,Technical University of Denmark,MSc Business Analytics,0,<NA>
19,EU_20,Aalto University,Master's Programme in Business Analytics,0,<NA>

2021 snapshot found: 4
No snapshot for current URL: 7
Request/error unresolved: 9

In [247]:
confirmed_2021 = ["EU_04", "EU_06", "EU_08", "EU_09"]

historical_check.loc[
    historical_check["programme_id"].isin(confirmed_2021),
    "existed_in_2021"
] = 1

historical_check.loc[
    historical_check["programme_id"].isin(confirmed_2021),
    "historical_notes"
] = "2021 archived official page found for current programme URL."

In [248]:
existence_update = {
    "EU_01": 1,
    "EU_04": 1,
    "EU_06": 1,
    "EU_08": 1,
    "EU_09": 1,
    "EU_11": 1,
    "EU_12": 1,
    "EU_20": 0
}

for programme_id, value in existence_update.items():
    historical_check.loc[
        historical_check["programme_id"] == programme_id,
        "existed_in_2021"
    ] = value


# Aalto Business Analytics is a genuinely new standalone programme
historical_check.loc[
    historical_check["programme_id"] == "EU_20",
    "historical_notes"
] = (
    "Standalone Master's Programme in Business Analytics "
    "started in autumn 2022; in 2021 Business Analytics existed "
    "as a specialisation within Information and Service Management."
)

# Update new_programme in the 2026 dataset
europe_2026.loc[
    europe_2026["programme_id"] == "EU_20",
    "new_programme"
] = 1

In [249]:
display(
    historical_check[
        [
            "programme_id",
            "university",
            "programme_name",
            "existed_in_2021",
            "archive_available_2021"
        ]
    ]
)

print(
    "\nConfirmed existed in 2021:",
    (historical_check["existed_in_2021"] == 1).sum()
)

print(
    "Confirmed new after 2021:",
    (historical_check["existed_in_2021"] == 0).sum()
)

print(
    "Still unresolved:",
    historical_check["existed_in_2021"].isna().sum()
)

,programme_id,university,programme_name,existed_in_2021,archive_available_2021
0,EU_01,Imperial College London,MSc Business Analytics & AI,1,0
1,EU_02,ETH Zurich,MSc Data Science,<NA>,<NA>
2,EU_03,UCL,MSc Business Analytics,<NA>,<NA>
3,EU_04,UCL,MSc Data Science,1,1
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),<NA>,<NA>
5,EU_06,University of Oxford,MSc in Social Data Science,1,1
6,EU_07,UCL,MSc Data Science and Public Policy,<NA>,<NA>
7,EU_08,EPFL,Master in Data Science,1,1
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,1,1
9,EU_10,King's College London,MSc Data Science,<NA>,<NA>
10,EU_11,University of Edinburgh,MSc Business Analytics,1,<NA>
11,EU_12,University of Edinburgh,MSc Data Science,1,0
12,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,<NA>,0
13,EU_14,KU Leuven,Master of Statistics and Data Science,<NA>,0
14,EU_15,Lund University,MSc Data Analytics and Business Economics,<NA>,0
15,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,<NA>,<NA>
16,EU_17,Utrecht University,MSc Data Science,<NA>,<NA>
17,EU_18,RWTH Aachen University,MSc Data Science,<NA>,<NA>
18,EU_19,Technical University of Denmark,MSc Business Analytics,<NA>,0
19,EU_20,Aalto University,Master's Programme in Business Analytics,0,0

Confirmed existed in 2021: 7
Confirmed new after 2021: 1
Still unresolved: 12

In [250]:
existence_update_2 = {
    "EU_02": 1,   # ETH Data Science
    "EU_03": 1,   # UCL Business Analytics
    "EU_05": 1,   # Imperial - existed as MSc Statistics (Data Science)
    "EU_13": 0,   # TU Delft DSAIT - new programme after 2021
    "EU_15": 1    # Lund DABE
}

for programme_id, value in existence_update_2.items():
    historical_check.loc[
        historical_check["programme_id"] == programme_id,
        "existed_in_2021"
    ] = value


# Historical notes for special cases
historical_check.loc[
    historical_check["programme_id"] == "EU_05",
    "historical_notes"
] = (
    "Programme existed in 2021 as MSc Statistics (Data Science); "
    "renamed MSc Statistics (Data Science and Machine Learning) from 2025."
)

historical_check.loc[
    historical_check["programme_id"] == "EU_13",
    "historical_notes"
] = (
    "Current MSc Data Science and Artificial Intelligence Technology "
    "was introduced as a new programme after 2021."
)


# Update new_programme for confirmed post-2021 programmes
europe_2026.loc[
    europe_2026["programme_id"].isin(["EU_13", "EU_20"]),
    "new_programme"
] = 1

In [251]:
display(
    historical_check.loc[
        historical_check["existed_in_2021"].isna(),
        ["programme_id", "university", "programme_name"]
    ]
)

print(
    "\nConfirmed existed:",
    (historical_check["existed_in_2021"] == 1).sum()
)

print(
    "Confirmed new after 2021:",
    (historical_check["existed_in_2021"] == 0).sum()
)

print(
    "Still unresolved:",
    historical_check["existed_in_2021"].isna().sum()
)

,programme_id,university,programme_name
6,EU_07,UCL,MSc Data Science and Public Policy
9,EU_10,King's College London,MSc Data Science
13,EU_14,KU Leuven,Master of Statistics and Data Science
15,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science
16,EU_17,Utrecht University,MSc Data Science
17,EU_18,RWTH Aachen University,MSc Data Science
18,EU_19,Technical University of Denmark,MSc Business Analytics

Confirmed existed: 11
Confirmed new after 2021: 2
Still unresolved: 7

In [252]:
existence_update_3 = {
    "EU_07": 0,   # UCL DS & Public Policy started in 2022
    "EU_14": 1,   # KU Leuven Statistics & Data Science existed in 2021
    "EU_16": 0    # Polimi BADS first edition started in 2024
}

for programme_id, value in existence_update_3.items():
    historical_check.loc[
        historical_check["programme_id"] == programme_id,
        "existed_in_2021"
    ] = value


historical_check.loc[
    historical_check["programme_id"] == "EU_07",
    "historical_notes"
] = "Programme started in 2022."

historical_check.loc[
    historical_check["programme_id"] == "EU_16",
    "historical_notes"
] = "First edition of the programme started in October 2024."


# These are new programmes relative to 2021
new_after_2021 = ["EU_07", "EU_13", "EU_16", "EU_20"]

europe_2026.loc[
    europe_2026["programme_id"].isin(new_after_2021),
    "new_programme"
] = 1

In [253]:
existence_update_4 = {
    "EU_17": 0,   # Utrecht Data Science appears from 2023-24
    "EU_18": 1,   # RWTH Data Science confirmed in 2021
    "EU_19": 1    # DTU Business Analytics confirmed in 2021
}

for programme_id, value in existence_update_4.items():
    historical_check.loc[
        historical_check["programme_id"] == programme_id,
        "existed_in_2021"
    ] = value


historical_check.loc[
    historical_check["programme_id"] == "EU_17",
    "historical_notes"
] = (
    "Current Data Science Research Master's programme appears "
    "in Utrecht's historical programme listings from 2023-24."
)


# Update new_programme
new_after_2021 = [
    "EU_07",   # UCL DS & Public Policy
    "EU_13",   # TU Delft DSAIT
    "EU_16",   # Polimi BADS
    "EU_17",   # Utrecht Data Science
    "EU_20"    # Aalto Business Analytics
]

europe_2026.loc[
    europe_2026["programme_id"].isin(new_after_2021),
    "new_programme"
] = 1

In [254]:
display(
    historical_check.loc[
        historical_check["existed_in_2021"].isna(),
        ["programme_id", "university", "programme_name"]
    ]
)

print(
    "\nConfirmed existed:",
    (historical_check["existed_in_2021"] == 1).sum()
)

print(
    "Confirmed new after 2021:",
    (historical_check["existed_in_2021"] == 0).sum()
)

print(
    "Still unresolved:",
    historical_check["existed_in_2021"].isna().sum()
)

  programme_id             university    programme_name
9        EU_10  King's College London  MSc Data Science

Confirmed existed: 14
Confirmed new after 2021: 5
Still unresolved: 1

In [255]:
historical_check.loc[
    historical_check["programme_id"] == "EU_10",
    "existed_in_2021"
] = 1

historical_check.loc[
    historical_check["programme_id"] == "EU_10",
    "historical_notes"
] = (
    "King's Data Science MSc existed before 2021; "
    "official King's sources document the programme prior to 2021."
)

In [256]:
existence_map = historical_check.set_index(
    "programme_id"
)["existed_in_2021"]

europe_2026["new_programme"] = (
    europe_2026["programme_id"]
    .map(existence_map)
    .map({1: 0, 0: 1})
)

print(
    europe_2026[
        ["programme_id", "programme_name", "new_programme"]
    ]
)

print(
    "\nExisting in 2021:",
    (historical_check["existed_in_2021"] == 1).sum()
)

print(
    "New after 2021:",
    (historical_check["existed_in_2021"] == 0).sum()
)

print(
    "Still unresolved:",
    historical_check["existed_in_2021"].isna().sum()
)

   programme_id                                           programme_name  \
0         EU_01                              MSc Business Analytics & AI
1         EU_02                                         MSc Data Science
2         EU_03                                   MSc Business Analytics
3         EU_04                                         MSc Data Science
4         EU_05       MSc Statistics (Data Science and Machine Learning)
5         EU_06                               MSc in Social Data Science
6         EU_07                       MSc Data Science and Public Policy
7         EU_08                                   Master in Data Science
8         EU_09                          MSc Mathematics in Data Science
9         EU_10                                         MSc Data Science
10        EU_11                                   MSc Business Analytics
11        EU_12                                         MSc Data Science
12        EU_13  MSc Data Science and Artificial Intelligence Technology
13        EU_14                    Master of Statistics and Data Science
14        EU_15                MSc Data Analytics and Business Economics
15        EU_16            Master in Business Analytics and Data Science
16        EU_17                                         MSc Data Science
17        EU_18                                         MSc Data Science
18        EU_19                                   MSc Business Analytics
19        EU_20                 Master's Programme in Business Analytics

    new_programme
0               0
1               0
2               0
3               0
4               0
5               0
6               1
7               0
8               0
9               0
10              0
11              0
12              1
13              0
14              0
15              1
16              1
17              0
18              0
19              1

Existing in 2021: 15
New after 2021: 5
Still unresolved: 0

In [257]:
# IDs of programmes that existed in 2021
existing_2021_ids = historical_check.loc[
    historical_check["existed_in_2021"] == 1,
    "programme_id"
].tolist()

# Copy the same programme structure from 2026
europe_2021 = europe_2026[
    europe_2026["programme_id"].isin(existing_2021_ids)
].copy()

# Change year
europe_2021["year"] = 2021

# These programmes are not "new" in the 2021 dataset
europe_2021["new_programme"] = 0


# Variables that MUST be recollected for 2021
historical_variables = [
    "statistics_core",
    "programming_core",
    "machine_learning_core",
    "data_visualization_core",
    "business_analytics_core",
    "core_category_count",
    "prerequisites",
    "GRE_GMAT_policy",
    "tuition_amount",
    "currency",
    "tuition_basis",
    "duration_months",
    "outcomes_reported",
    "source_type",
    "source_url",
    "access_date"
]

europe_2021[historical_variables] = pd.NA


print("2021 rows:", len(europe_2021))
print("2021 columns:", len(europe_2021.columns))

display(
    europe_2021[
        [
            "programme_id",
            "university",
            "programme_name",
            "year",
            "new_programme"
        ]
    ]
)

2021 rows: 15
2021 columns: 26

,programme_id,university,programme_name,year,new_programme
0,EU_01,Imperial College London,MSc Business Analytics & AI,2021,0
1,EU_02,ETH Zurich,MSc Data Science,2021,0
2,EU_03,UCL,MSc Business Analytics,2021,0
3,EU_04,UCL,MSc Data Science,2021,0
4,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),2021,0
5,EU_06,University of Oxford,MSc in Social Data Science,2021,0
7,EU_08,EPFL,Master in Data Science,2021,0
8,EU_09,Technical University of Munich,MSc Mathematics in Data Science,2021,0
9,EU_10,King's College London,MSc Data Science,2021,0
10,EU_11,University of Edinburgh,MSc Business Analytics,2021,0
11,EU_12,University of Edinburgh,MSc Data Science,2021,0
13,EU_14,KU Leuven,Master of Statistics and Data Science,2021,0
14,EU_15,Lund University,MSc Data Analytics and Business Economics,2021,0
17,EU_18,RWTH Aachen University,MSc Data Science,2021,0
18,EU_19,Technical University of Denmark,MSc Business Analytics,2021,0

In [258]:
duration_2021 = {
    "EU_01": 12,
    "EU_02": 24,
    "EU_03": 12,
    "EU_04": 12,
    "EU_05": 12,
    "EU_06": 10,
    "EU_08": 24,
    "EU_09": 24,
    "EU_10": 12,
    "EU_11": 12,
    "EU_12": 12,
    "EU_14": 24,
    "EU_15": 12,
    "EU_18": 24,
    "EU_19": 24
}

europe_2021["duration_months"] = (
    europe_2021["programme_id"].map(duration_2021)
)

display(
    europe_2021[
        ["programme_id", "programme_name", "duration_months"]
    ]
)

print(
    "\nMissing duration:",
    europe_2021["duration_months"].isna().sum()
)

,programme_id,programme_name,duration_months
0,EU_01,MSc Business Analytics & AI,12
1,EU_02,MSc Data Science,24
2,EU_03,MSc Business Analytics,12
3,EU_04,MSc Data Science,12
4,EU_05,MSc Statistics (Data Science and Machine Learning),12
5,EU_06,MSc in Social Data Science,10
7,EU_08,Master in Data Science,24
8,EU_09,MSc Mathematics in Data Science,24
9,EU_10,MSc Data Science,12
10,EU_11,MSc Business Analytics,12
11,EU_12,MSc Data Science,12
13,EU_14,Master of Statistics and Data Science,24
14,EU_15,MSc Data Analytics and Business Economics,12
17,EU_18,MSc Data Science,24
18,EU_19,MSc Business Analytics,24

Missing duration: 0

In [259]:
tuition_2021_batch1 = {
    "EU_02": {
        "amount": 730,
        "currency": "CHF",
        "basis": "per semester; standard ETH tuition fee applicable in 2021"
    },

    "EU_06": {
        "amount": 27460,
        "currency": "GBP",
        "basis": "annual course fee; overseas including EU; 2021/22"
    },

    "EU_08": {
        "amount": 730,
        "currency": "CHF",
        "basis": "per semester; EPFL tuition fee applicable in 2021"
    }
}

for programme_id, info in tuition_2021_batch1.items():

    mask = europe_2021["programme_id"] == programme_id

    europe_2021.loc[mask, "tuition_amount"] = info["amount"]
    europe_2021.loc[mask, "currency"] = info["currency"]
    europe_2021.loc[mask, "tuition_basis"] = info["basis"]


display(
    europe_2021[
        [
            "programme_id",
            "programme_name",
            "tuition_amount",
            "currency",
            "tuition_basis"
        ]
    ]
)

,programme_id,programme_name,tuition_amount,currency,tuition_basis
0,EU_01,MSc Business Analytics & AI,<NA>,<NA>,<NA>
1,EU_02,MSc Data Science,730,CHF,per semester; standard ETH tuition fee applicable in 2021
2,EU_03,MSc Business Analytics,<NA>,<NA>,<NA>
3,EU_04,MSc Data Science,<NA>,<NA>,<NA>
4,EU_05,MSc Statistics (Data Science and Machine Learning),<NA>,<NA>,<NA>
5,EU_06,MSc in Social Data Science,27460,GBP,annual course fee; overseas including EU; 2021/22
7,EU_08,Master in Data Science,730,CHF,per semester; EPFL tuition fee applicable in 2021
8,EU_09,MSc Mathematics in Data Science,<NA>,<NA>,<NA>
9,EU_10,MSc Data Science,<NA>,<NA>,<NA>
10,EU_11,MSc Business Analytics,<NA>,<NA>,<NA>
11,EU_12,MSc Data Science,<NA>,<NA>,<NA>
13,EU_14,Master of Statistics and Data Science,<NA>,<NA>,<NA>
14,EU_15,MSc Data Analytics and Business Economics,<NA>,<NA>,<NA>
17,EU_18,MSc Data Science,<NA>,<NA>,<NA>
18,EU_19,MSc Business Analytics,<NA>,<NA>,<NA>

In [260]:
tuition_2021_batch2 = {
    "EU_03": {
        "amount": 34100,
        "currency": "GBP",
        "basis": "full-time overseas tuition fee; 2021/22"
    },

    "EU_04": {
        "amount": 34100,
        "currency": "GBP",
        "basis": "full-time overseas tuition fee; 2021/22"
    }
}

for programme_id, info in tuition_2021_batch2.items():

    mask = europe_2021["programme_id"] == programme_id

    europe_2021.loc[mask, "tuition_amount"] = info["amount"]
    europe_2021.loc[mask, "currency"] = info["currency"]
    europe_2021.loc[mask, "tuition_basis"] = info["basis"]


print(
    europe_2021[
        ["programme_id", "tuition_amount", "currency", "tuition_basis"]
    ]
)

print(
    "\nTuition amounts filled:",
    europe_2021["tuition_amount"].notna().sum()
)

print(
    "Still without verified amount:",
    europe_2021["tuition_amount"].isna().sum()
)

   programme_id tuition_amount currency  \
0         EU_01           <NA>     <NA>
1         EU_02            730      CHF
2         EU_03          34100      GBP
3         EU_04          34100      GBP
4         EU_05           <NA>     <NA>
5         EU_06          27460      GBP
7         EU_08            730      CHF
8         EU_09           <NA>     <NA>
9         EU_10           <NA>     <NA>
10        EU_11           <NA>     <NA>
11        EU_12           <NA>     <NA>
13        EU_14           <NA>     <NA>
14        EU_15           <NA>     <NA>
17        EU_18           <NA>     <NA>
18        EU_19           <NA>     <NA>

                                                tuition_basis
0                                                        <NA>
1   per semester; standard ETH tuition fee applicable in 2021
2                     full-time overseas tuition fee; 2021/22
3                     full-time overseas tuition fee; 2021/22
4                                                        <NA>
5           annual course fee; overseas including EU; 2021/22
7           per semester; EPFL tuition fee applicable in 2021
8                                                        <NA>
9                                                        <NA>
10                                                       <NA>
11                                                       <NA>
13                                                       <NA>
14                                                       <NA>
17                                                       <NA>
18                                                       <NA>

Tuition amounts filled: 5
Still without verified amount: 10

In [261]:
tuition_2021_batch3 = {
    "EU_01": {
        "amount": pd.NA,
        "currency": pd.NA,
        "basis": (
            "NR - 2021/22 full-time MSc Business Analytics tuition "
            "amount was not directly verified from the official "
            "Imperial historical fee sources reviewed."
        )
    },

    "EU_05": {
        "amount": pd.NA,
        "currency": pd.NA,
        "basis": (
            "NR - 2021/22 full-time overseas MSc Statistics "
            "(Data Science) tuition amount was not directly verified "
            "from the official Imperial historical fee sources reviewed."
        )
    }
}

for programme_id, info in tuition_2021_batch3.items():

    mask = europe_2021["programme_id"] == programme_id

    europe_2021.loc[mask, "tuition_amount"] = info["amount"]
    europe_2021.loc[mask, "currency"] = info["currency"]
    europe_2021.loc[mask, "tuition_basis"] = info["basis"]


print(
    europe_2021.loc[
        europe_2021["programme_id"].isin(["EU_01", "EU_05"]),
        ["programme_id", "tuition_amount", "currency", "tuition_basis"]
    ]
)

  programme_id tuition_amount currency  \
0        EU_01           <NA>     <NA>
4        EU_05           <NA>     <NA>

                                                                                                                                                        tuition_basis
0                  NR - 2021/22 full-time MSc Business Analytics tuition amount was not directly verified from the official Imperial historical fee sources reviewed.
4  NR - 2021/22 full-time overseas MSc Statistics (Data Science) tuition amount was not directly verified from the official Imperial historical fee sources reviewed.

In [262]:
tuition_2021_batch4 = {
    "EU_09": {
        "amount": 0,
        "currency": "EUR",
        "basis": (
            "no tuition fee in 2021; students paid only the "
            "student union and semester ticket fee, approximately "
            "EUR 120 per semester"
        )
    }
}

for programme_id, info in tuition_2021_batch4.items():

    mask = europe_2021["programme_id"] == programme_id

    europe_2021.loc[mask, "tuition_amount"] = info["amount"]
    europe_2021.loc[mask, "currency"] = info["currency"]
    europe_2021.loc[mask, "tuition_basis"] = info["basis"]

print(
    europe_2021.loc[
        europe_2021["programme_id"] == "EU_09",
        ["programme_id", "tuition_amount", "currency", "tuition_basis"]
    ]
)

  programme_id tuition_amount currency  \
8        EU_09              0      EUR

                                                                                                              tuition_basis
8  no tuition fee in 2021; students paid only the student union and semester ticket fee, approximately EUR 120 per semester

In [263]:
tuition_2021_batch5 = {
    "EU_11": {
        "amount": pd.NA,
        "currency": pd.NA,
        "basis": (
            "NR - programme existed in 2021/22 and the University of "
            "Edinburgh maintains a 2021/22 historical fee archive, "
            "but the programme-specific overseas tuition amount was "
            "not directly verified from the official source reviewed."
        )
    },

    "EU_12": {
        "amount": pd.NA,
        "currency": pd.NA,
        "basis": (
            "NR - programme existed in 2021/22 and the University of "
            "Edinburgh maintains a 2021/22 historical fee archive, "
            "but the programme-specific overseas tuition amount was "
            "not directly verified from the official source reviewed."
        )
    },

    "EU_15": {
        "amount": pd.NA,
        "currency": pd.NA,
        "basis": (
            "NR - programme existed in autumn 2021, but a "
            "programme-specific 2021 tuition amount for non-EU/EEA "
            "students was not directly verified from the official "
            "historical sources reviewed."
        )
    }
}

for programme_id, info in tuition_2021_batch5.items():

    mask = europe_2021["programme_id"] == programme_id

    europe_2021.loc[mask, "tuition_amount"] = info["amount"]
    europe_2021.loc[mask, "currency"] = info["currency"]
    europe_2021.loc[mask, "tuition_basis"] = info["basis"]

In [264]:
verified = europe_2021["tuition_amount"].notna().sum()

documented_nr = (
    europe_2021["tuition_amount"].isna()
    & europe_2021["tuition_basis"].fillna("").str.startswith("NR")
).sum()

unresolved = europe_2021["tuition_basis"].isna().sum()

print("Verified amount:", verified)
print("NR - documented:", documented_nr)
print("Unresolved tuition:", unresolved)

Verified amount: 6
NR - documented: 5
Unresolved tuition: 4

In [265]:
tuition_2021_final = {
    "EU_10": {
        "amount": pd.NA,
        "currency": pd.NA,
        "basis": (
            "NR - programme-specific 2021/22 international tuition "
            "amount was not directly verified from the official "
            "King's College London historical sources reviewed."
        )
    },

    "EU_14": {
        "amount": pd.NA,
        "currency": pd.NA,
        "basis": (
            "NR - official KU Leuven sources confirm that students "
            "registered in 2021/22 were subject to the basic tuition "
            "fee, but the exact 2021/22 programme-specific amount "
            "was not directly verified."
        )
    },

    "EU_18": {
        "amount": 0,
        "currency": "EUR",
        "basis": (
            "no tuition fee in 2021/22; students paid a separate "
            "semester contribution of EUR 300.19 in winter semester "
            "2021/22, which is not coded as tuition"
        )
    },

    "EU_19": {
        "amount": pd.NA,
        "currency": pd.NA,
        "basis": (
            "NR - programme-specific 2021 tuition amount for "
            "non-EU/EEA students was not directly verified from "
            "the official DTU historical sources reviewed."
        )
    }
}

for programme_id, info in tuition_2021_final.items():

    mask = europe_2021["programme_id"] == programme_id

    europe_2021.loc[mask, "tuition_amount"] = info["amount"]
    europe_2021.loc[mask, "currency"] = info["currency"]
    europe_2021.loc[mask, "tuition_basis"] = info["basis"]

In [266]:
verified = europe_2021["tuition_amount"].notna().sum()

documented_nr = (
    europe_2021["tuition_amount"].isna()
    & europe_2021["tuition_basis"].fillna("").str.startswith("NR")
).sum()

unresolved = europe_2021["tuition_basis"].isna().sum()

print("Verified amount:", verified)
print("NR - documented:", documented_nr)
print("Unresolved tuition:", unresolved)

Verified amount: 7
NR - documented: 8
Unresolved tuition: 0

In [267]:
gre_2021 = {
    "EU_01": "Optional / Recommended",
    "EU_02": "Not reported",
    "EU_03": "Not reported",
    "EU_04": "Not reported",
    "EU_05": "Not reported",
    "EU_06": "Not required",
    "EU_08": "Not reported",
    "EU_09": "Not reported",
    "EU_10": "Not reported",
    "EU_11": "Not reported",
    "EU_12": "Not reported",
    "EU_14": "Not reported",
    "EU_15": "Not reported",
    "EU_18": "Not reported",
    "EU_19": "Not reported"
}

europe_2021["GRE_GMAT_policy"] = (
    europe_2021["programme_id"].map(gre_2021)
)

print(
    europe_2021[
        ["programme_id", "programme_name", "GRE_GMAT_policy"]
    ]
)

print(
    "\nMissing GRE/GMAT:",
    europe_2021["GRE_GMAT_policy"].isna().sum()
)

print("\nPolicy counts:")
print(
    europe_2021["GRE_GMAT_policy"].value_counts(dropna=False)
)

   programme_id                                      programme_name  \
0         EU_01                         MSc Business Analytics & AI
1         EU_02                                    MSc Data Science
2         EU_03                              MSc Business Analytics
3         EU_04                                    MSc Data Science
4         EU_05  MSc Statistics (Data Science and Machine Learning)
5         EU_06                          MSc in Social Data Science
7         EU_08                              Master in Data Science
8         EU_09                     MSc Mathematics in Data Science
9         EU_10                                    MSc Data Science
10        EU_11                              MSc Business Analytics
11        EU_12                                    MSc Data Science
13        EU_14               Master of Statistics and Data Science
14        EU_15           MSc Data Analytics and Business Economics
17        EU_18                                    MSc Data Science
18        EU_19                              MSc Business Analytics

           GRE_GMAT_policy
0   Optional / Recommended
1             Not reported
2             Not reported
3             Not reported
4             Not reported
5             Not required
7             Not reported
8             Not reported
9             Not reported
10            Not reported
11            Not reported
13            Not reported
14            Not reported
17            Not reported
18            Not reported

Missing GRE/GMAT: 0

Policy counts:
GRE_GMAT_policy
Not reported              13
Optional / Recommended     1
Not required               1
Name: count, dtype: int64

In [268]:
prerequisites_2021 = {
    "EU_01": (
        "Quantitative bachelor's degree; quantitative preparation "
        "including mathematics, statistics and related analytical coursework."
    ),

    "EU_02": (
        "Relevant bachelor's degree with substantial prior preparation "
        "in mathematics and computer science."
    ),

    "EU_03": (
        "Normally an upper second-class bachelor's degree or equivalent; "
        "strong quantitative aptitude expected."
    ),

    "EU_04": (
        "Quantitative bachelor's background with prior university-level "
        "mathematics, statistics and programming preparation."
    ),

    "EU_05": (
        "Strong quantitative or mathematical bachelor's background "
        "appropriate for postgraduate study in Statistics and Data Science."
    ),

    "EU_06": (
        "Strong bachelor's degree; quantitative aptitude and prior "
        "mathematical preparation expected."
    ),

    "EU_08": (
        "Relevant bachelor's background with substantial preparation "
        "in mathematics, computer science and programming."
    ),

    "EU_09": (
        "Bachelor's degree in Mathematics, Informatics with mathematics, "
        "or a comparable discipline; relevant mathematics and "
        "computer-science competencies required."
    ),

    "EU_10": (
        "Quantitative bachelor's background with sufficient mathematical "
        "and computational preparation for postgraduate Data Science."
    ),

    "EU_11": (
        "Relevant quantitative bachelor's degree with prior preparation "
        "in mathematics, statistics and computing."
    ),

    "EU_12": (
        "Relevant quantitative bachelor's degree with prior mathematical "
        "and programming preparation."
    ),

    "EU_14": (
        "Academic bachelor's or master's degree with at least two "
        "prior courses in statistics."
    ),

    "EU_15": (
        "Bachelor's degree with quantitative preparation relevant to "
        "data analytics, economics and statistical methods."
    ),

    "EU_18": (
        "Relevant bachelor's degree with sufficient prior university-level "
        "mathematics, statistics and computer-science preparation."
    ),

    "EU_19": (
        "Relevant bachelor's degree with quantitative preparation "
        "appropriate for Business Analytics."
    )
}

europe_2021["prerequisites"] = (
    europe_2021["programme_id"].map(prerequisites_2021)
)

print(
    europe_2021[
        ["programme_id", "programme_name", "prerequisites"]
    ]
)

print(
    "\nMissing prerequisites:",
    europe_2021["prerequisites"].isna().sum()
)

   programme_id                                      programme_name  \
0         EU_01                         MSc Business Analytics & AI
1         EU_02                                    MSc Data Science
2         EU_03                              MSc Business Analytics
3         EU_04                                    MSc Data Science
4         EU_05  MSc Statistics (Data Science and Machine Learning)
5         EU_06                          MSc in Social Data Science
7         EU_08                              Master in Data Science
8         EU_09                     MSc Mathematics in Data Science
9         EU_10                                    MSc Data Science
10        EU_11                              MSc Business Analytics
11        EU_12                                    MSc Data Science
13        EU_14               Master of Statistics and Data Science
14        EU_15           MSc Data Analytics and Business Economics
17        EU_18                                    MSc Data Science
18        EU_19                              MSc Business Analytics

                                                                                                                                                   prerequisites
0                                  Quantitative bachelor's degree; quantitative preparation including mathematics, statistics and related analytical coursework.
1                                                             Relevant bachelor's degree with substantial prior preparation in mathematics and computer science.
2                                                         Normally an upper second-class bachelor's degree or equivalent; strong quantitative aptitude expected.
3                                            Quantitative bachelor's background with prior university-level mathematics, statistics and programming preparation.
4                                   Strong quantitative or mathematical bachelor's background appropriate for postgraduate study in Statistics and Data Science.
5                                                                   Strong bachelor's degree; quantitative aptitude and prior mathematical preparation expected.
7                                                  Relevant bachelor's background with substantial preparation in mathematics, computer science and programming.
8   Bachelor's degree in Mathematics, Informatics with mathematics, or a comparable discipline; relevant mathematics and computer-science competencies required.
9                                   Quantitative bachelor's background with sufficient mathematical and computational preparation for postgraduate Data Science.
10                                                      Relevant quantitative bachelor's degree with prior preparation in mathematics, statistics and computing.
11                                                                  Relevant quantitative bachelor's degree with prior mathematical and programming preparation.
13                                                                         Academic bachelor's or master's degree with at least two prior courses in statistics.
14                                                Bachelor's degree with quantitative preparation relevant to data analytics, economics and statistical methods.
17                                   Relevant bachelor's degree with sufficient prior university-level mathematics, statistics and computer-science preparation.
18                                                                  Relevant bachelor's degree with quantitative preparation appropriate for Business Analytics.

Missing prerequisites: 0

In [269]:
curriculum_2021_batch1 = {
    "EU_11": [1, 1, 1, 0, 1],
    "EU_12": [1, 1, 1, 0, 0],
    "EU_15": [1, 1, 1, 1, 1]
}

curriculum_cols = [
    "statistics_core",
    "programming_core",
    "machine_learning_core",
    "data_visualization_core",
    "business_analytics_core"
]

for programme_id, values in curriculum_2021_batch1.items():

    mask = europe_2021["programme_id"] == programme_id

    for col, value in zip(curriculum_cols, values):
        europe_2021.loc[mask, col] = value


europe_2021["core_category_count"] = (
    europe_2021[curriculum_cols]
    .apply(pd.to_numeric, errors="coerce")
    .sum(axis=1, min_count=1)
)


display(
    europe_2021.loc[
        europe_2021["programme_id"].isin(
            ["EU_11", "EU_12", "EU_15"]
        ),
        ["programme_id"] + curriculum_cols + ["core_category_count"]
    ]
)

,programme_id,statistics_core,programming_core,machine_learning_core,data_visualization_core,business_analytics_core,core_category_count
10,EU_11,1,1,1,0,1,4.0
11,EU_12,1,1,1,0,0,3.0
14,EU_15,1,1,1,1,1,5.0

In [270]:
curriculum_2021_batch2 = {
    "EU_02": [1, 1, 1, 0, 0]
}

for programme_id, values in curriculum_2021_batch2.items():

    mask = europe_2021["programme_id"] == programme_id

    for col, value in zip(curriculum_cols, values):
        europe_2021.loc[mask, col] = value


europe_2021["core_category_count"] = (
    europe_2021[curriculum_cols]
    .apply(pd.to_numeric, errors="coerce")
    .sum(axis=1, min_count=1)
)

display(
    europe_2021[
        ["programme_id"] + curriculum_cols + ["core_category_count"]
    ]
)

print(
    "\nProgrammes coded:",
    europe_2021["core_category_count"].notna().sum()
)

print(
    "Still needing curriculum review:",
    europe_2021["core_category_count"].isna().sum()
)

,programme_id,statistics_core,programming_core,machine_learning_core,data_visualization_core,business_analytics_core,core_category_count
0,EU_01,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
1,EU_02,1,1,1,0,0,3.0
2,EU_03,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
3,EU_04,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
4,EU_05,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
5,EU_06,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
7,EU_08,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
8,EU_09,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
9,EU_10,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
10,EU_11,1,1,1,0,1,4.0
11,EU_12,1,1,1,0,0,3.0
13,EU_14,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
14,EU_15,1,1,1,1,1,5.0
17,EU_18,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
18,EU_19,<NA>,<NA>,<NA>,<NA>,<NA>,NaN

Programmes coded: 4
Still needing curriculum review: 11

In [271]:
curriculum_2021_batch3 = {
    "EU_01": [1, 1, 1, 0, 1],
    "EU_03": [1, 1, 0, 0, 1],
    "EU_04": [1, 1, 1, 0, 0],
    "EU_05": [1, 1, 1, 0, 0],
    "EU_06": [1, 1, 1, 0, 0]
}

for programme_id, values in curriculum_2021_batch3.items():
    mask = europe_2021["programme_id"] == programme_id

    for col, value in zip(curriculum_cols, values):
        europe_2021.loc[mask, col] = value


europe_2021["core_category_count"] = (
    europe_2021[curriculum_cols]
    .apply(pd.to_numeric, errors="coerce")
    .sum(axis=1, min_count=1)
)

display(
    europe_2021[
        ["programme_id"] + curriculum_cols + ["core_category_count"]
    ]
)

print(
    "\nProgrammes coded:",
    europe_2021["core_category_count"].notna().sum()
)

print(
    "Still needing curriculum review:",
    europe_2021["core_category_count"].isna().sum()
)

,programme_id,statistics_core,programming_core,machine_learning_core,data_visualization_core,business_analytics_core,core_category_count
0,EU_01,1,1,1,0,1,4.0
1,EU_02,1,1,1,0,0,3.0
2,EU_03,1,1,0,0,1,3.0
3,EU_04,1,1,1,0,0,3.0
4,EU_05,1,1,1,0,0,3.0
5,EU_06,1,1,1,0,0,3.0
7,EU_08,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
8,EU_09,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
9,EU_10,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
10,EU_11,1,1,1,0,1,4.0
11,EU_12,1,1,1,0,0,3.0
13,EU_14,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
14,EU_15,1,1,1,1,1,5.0
17,EU_18,<NA>,<NA>,<NA>,<NA>,<NA>,NaN
18,EU_19,<NA>,<NA>,<NA>,<NA>,<NA>,NaN

Programmes coded: 9
Still needing curriculum review: 6

In [ ]:
for _, row in duration_sentence_review.iterrows():

    print("=" * 90)

    print(
        row["programme_id"],
        "|",
        row["university"],
        "|",
        row["programme_name"]
    )

    print("-" * 90)

    if pd.isna(row["duration_text"]):
        print("NO AUTOMATED EVIDENCE")

    else:
        print(row["duration_text"])

    print()

==========================================================================================
EU_04 | UCL | MSc Data Science
------------------------------------------------------------------------------------------
NO AUTOMATED EVIDENCE

==========================================================================================
EU_05 | Imperial College London | MSc Statistics (Data Science and Machine Learning)
------------------------------------------------------------------------------------------
[primary] Duration 1 year Start date October 2027 Study mode Full-time Delivered by Department of Mathematics Location South Kensington Applications: places 25:1 (2024-25) Minimum entry standard 2:1 in Statistics, Mathematics, Engineering, Physics or Computer Science. || Optional modules You choose at least three modules from Group A and the remainder from Group B to total 25-27.5 ECTS. || Each module is worth 5 ECTS unless otherwise stated. || Deep Learning (7.5 ECTS) Explore the building blocks of deep learning models, and how to design network architectures for specific applications. || Probabilistic Generative Models (7.5 ECTS) You will gain a solid foundation in probabilistic generative models, learning training, inference, and model types such as autoregressive, implicit, and Bayesian nonparametric. || [outcomes] Duration: 12 months Next application deadline: 29 September 2026 Fee: £47,000 Location: London, UK Admissions Fees and funding Show page contents Overview Programme content Admissions Fees and funding Who attends Career impact Faculty FAQs Apply now Study your MSc Business Analytics & AI at a world-leading university 2nd in the world (Imperial College London, QS World University Rankings 2027) 3rd in Europe (Imperial College London, Times Higher Education World University Rankings 2026) #3 city for students (London, QS Best Student City Rankings 2027) Drive business transformation through data || We are pleased to offer an optional extended term , that will allow you to extend your programme duration to 16 months. || Almost all of the MSc programmes we have available are 12 month, full-time programmes.

==========================================================================================
EU_06 | University of Oxford | MSc in Social Data Science
------------------------------------------------------------------------------------------
NO AUTOMATED EVIDENCE

==========================================================================================
EU_07 | UCL | MSc Data Science and Public Policy
------------------------------------------------------------------------------------------
NO AUTOMATED EVIDENCE

==========================================================================================
EU_08 | EPFL | Master in Data Science
------------------------------------------------------------------------------------------
[primary] Simplified study plan Master (120 ECTS credits) Please note that the information regarding programs’ structure as well as the simplified study plans may be subject to change and that they are not legally binding.

==========================================================================================
EU_09 | Technical University of Munich | MSc Mathematics in Data Science
------------------------------------------------------------------------------------------
[primary] Mathematics in Data Science - Master of Science (M.Sc.) - TUM Show convenient version of this site Don't show this message again Skip to main content TUM Technical University of Munich News and Events Close menu News and Events See overview All News Events Events See overview Event overview Presidential Lunches Open House Garching Sustainability Day Welcome@TUM Dies Academicus Advent Concerts Magazine Magazine See overview TUM Magazine Issue 3/26 TUM Magazine Issue 2/25 TUM Magazine Issue 1/25 Podcasts Podcasts See overview We are TUM Series Series See overview NewIn One Topic, One Loop Search || Save settings Open search Open navigation Search navigation Reset search News and Events Back News and Events All News Events Back Events Event overview Presidential Lunches Open House Garching Sustainability Day Welcome@TUM Dies Academicus Advent Concerts Magazine Back Magazine TUM Magazine Issue 3/26 TUM Magazine Issue 2/25 TUM Magazine Issue 1/25 Podcasts Back Podcasts We are TUM Series Back Series NewIn One Topic, One Loop Studies Back Studies Degree Programs Back Degree Programs Bachelor’s degree programs Master’s degree programs Key Skill Programs Back Key Skill Programs Plug-in Modules  || Duration of Studies 4 (fulltime) Credits 120 ECTS Main Locations Garching Application Period Winter semester: 01.02.

==========================================================================================
EU_10 | King's College London | MSc Data Science
------------------------------------------------------------------------------------------
[primary] Related courses Artificial Intelligence for Science MSc 1 year full-time, September to September Full-time In person Computational Finance MSc 1 year full-time Full-time In person Advanced Computing MSc One year full-time, September to September Full-time In person Cyber Security MSc 1 year full-time, September to September Full-time In person Study Degree courses Footer navigation link Postgraduate taught Footer navigation link Postgraduate research Footer navigation link International Footer navigation link Summer schools Footer navigation link Student experience Footer navigation link Infor

==========================================================================================
EU_11 | University of Edinburgh | MSc Business Analytics
------------------------------------------------------------------------------------------
[tuition] Business Analytics MSc - Postgraduate taught programmes | The University of Edinburgh Skip to main content Study Global Visit Research News About Alumni Local Staff Students Schools & departments MyEd Submit search Degree finder Subsite menu Home Search degree programmes Search degree programmes Undergraduate degree programmes Postgraduate taught programmes Postgraduate research programmes A to Z of degree programmes A to Z of degree programmes Undergraduate degree programmes A to Z (2027 entry) Postgraduate taught degree programmes A to Z Postgraduate research degree programmes A to Z Degree  || Full-time MSc Business Analytics (1 year) tuition fees Graduate discount If you are a University of Edinburgh graduate, you will be eligible for a 10% discount on your tuition fees for this programme. || Full-time MSc Business Analytics (1 year) (2026-2027) We link to the latest information available. || Select programme - Select a programme - MSc Business Analytics (1 year) After you apply Once you have applied for this programme, you will be able to track the progress of your application and accept or decline any offers.

==========================================================================================
EU_12 | University of Edinburgh | MSc Data Science
------------------------------------------------------------------------------------------
[primary] Level: Postgraduate taught Subject: Computing and Informatics Year of entry: 2026 Study options Mode of study On campus Part-time MSc | up to 3 years | Start date: multiple dates Full-time MSc | 1 year | Start date: September 2026 Key facts School School of Informatics College College of Science and Engineering Programme website Programme website Study location Central Area 17 to 19 November 2026: Postgraduate Virtual Open Days Join us live to explore postgraduate taught and research study at Edinburgh and gain key insights before you apply. || Study options This programme can be studied full-time over 1 year or part-time for up to 3 years. || Part-time MSc Data Science (2 years) tuition fees MSc Data Science (3 years) tuition fees Full-time MSc Data Science (1 year) tuition fees Graduate discount If you are a University of Edinburgh graduate, you will be eligible for a 10% discount on your tuition fees for this programme. || You should have experience of computer programming equivalent to an introductory programming course and have completed the equivalent of 60 SCQF credits or 30 ECTS credits of mathematics during your degree that have typically covered the following subjects/topics: calculus (differentiation and integration), linear algebra (vectors and multi-dimensional matrices), discrete mathematics and mathematical reasoning (e.g. || Part-time MSc Data Science (2 years) (2026-2027) MSc Data Science (3 years) (2026-2027) Full-time MSc Data Science (1 year) (2026-2027) We link to the latest information available.

==========================================================================================
EU_13 | Delft University of Technology | MSc Data Science and Artificial Intelligence Technology
------------------------------------------------------------------------------------------
[primary] Degree Master of Data Science and Artificial Intelligence Technology Accreditation Accredited by the NVAO Credits 120 EC, 24 Months Type Regular study programme Mode Full-time Language of instruction English Start September Explore this master's challenging themes This master enables you to obtain advanced knowledge and skills in subject areas of Data Science and AI Technology through inspiring themes, allowing you to work on specific types of challenges you might encounter as a professional. || [admissions] Programme Year 1 Quarter 1 Quarter 2 Quarter 3 Quarter 4 Data management and Engineering Software Engineering and Testing for AI Systems Responsible Data Science and AI Engineering Research course Machine and Deep Learning Theme 1 Theme 1 Theme 1 Probabilistic AI and Reasoning Theme 2 Theme 2 Theme 2 Year 2 Quarter 5 Quarter 6 Quarter 7 Quarter 8 Deepening / broadening electives Master Thesis Core courses Themes Research course Deepening / broadening electives Master Thesis Questions? || [outcomes] Degree Master of Data Science and Artificial Intelligence Technology Accreditation Accredited by the NVAO Credits 120 EC, 24 Months Type Regular study programme Mode Full-time Language of instruction English Start September Explore this master's challenging themes This master enables you to obtain advanced knowledge and skills in subject areas of Data Science and AI Technology through inspiring themes, allowing you to work on specific types of challenges you might encounter as a professional.

==========================================================================================
EU_14 | KU Leuven | Master of Statistics and Data Science
------------------------------------------------------------------------------------------
[primary] Leuven Master's 120 ECTS credits English Faculty of Science Apply now Discover the programme keyboard_arrow_down Discover the programme Programme structure Admission requirements Further studies More Objectives Non-binding personal development goals Quality of education Master of Statistics and Data Science Discover the Master of Statistics and Data Science at KU Leuven in Belgium. || [outcomes] Leuven Master's 120 ECTS credits English Faculty of Science Apply now Discover the programme keyboard_arrow_down Discover the programme Programme structure Admission requirements Further studies More Objectives Non-binding personal development goals Quality of education Master of Statistics and Data Science Discover the Master of Statistics and Data Science at KU Leuven in Belgium.

==========================================================================================
EU_15 | Lund University | MSc Data Analytics and Business Economics
------------------------------------------------------------------------------------------
[primary] Data Analytics and Business Economics - Master's Programme Master's programme • 1 year • 60 credits Transforming data into insights that can enhance decision-making is a key challenge for companies of every size, across all industries. || Duration 1 year Level Master's Language English Place of study Lund Application dates Overview Teaching and learning Career prospects Overview Have you noticed how Netflix and YouTube send you suggestions based on your previous views?

==========================================================================================
EU_16 | Politecnico di Milano | Master in Business Analytics and Data Science
------------------------------------------------------------------------------------------
[primary] Please note that we’ve designed this programme for recent graduates with ideally no more than 3 years of work experience. || If you are a non-EU candidate, we recommend that you apply at least 3 months before the programme starts, to leave enough time for a Statement of Comparability of your degree and to apply for your student visa. || Duration 12 months Format Full Time Language English Individuals €25,000 € 13,000.00 (POLIMI MSc Alumni) Experience Less than 3 years Apply Now DOWNLOAD BROCHURE INTERNATIONAL MASTERS OFFICE infomasters@gsom.polimi.it +39 02 2399 2820 DOWNLOAD BROCHURE MIP Politecnico di Milano Graduate School of Business S.C.p.A Via Lambruschini 4/c – Building 26/a 20156 MILANO Phone: +39 02 23992820 C.F./P.IVA e iscrizione R.I.

==========================================================================================
EU_17 | Utrecht University | MSc Data Science
------------------------------------------------------------------------------------------
[primary] Related Master’s Programmes This programme operates in parallel to the 1 year Master’s programme in Applied Data Science , that instead aims on how to apply existing data science tools and solutions in different application domains. || Key facts Degree: Informatica (MSc) Language of instruction: English Mode of study: Full-time Study duration: 2 years Start: February, September Tuition fees: Dutch and other EU/EEA students (statutory fee, full-time) 2026-2027: € 2,694 Non-EU/EEA students (institutional fee) 2026-2027: 25,306 More information about fees Croho code: 66978 Accreditation: Accredited by the NVAO Faculty: Science Graduate school: School of Natural Sciences Brochure: Request a brochure Feedback Feedback Footer menu (EN) Go to Choose a programme Student information Jobs Alumni Giving Services Intranet for employees  || [curriculum] Secondary electives can be considered any master course offered by any department of the university with at least 7.5 ECTS, that has not been used as mandatory or primary elective.

==========================================================================================
EU_18 | RWTH Aachen University | MSc Data Science
------------------------------------------------------------------------------------------
NO AUTOMATED EVIDENCE

==========================================================================================
EU_19 | Technical University of Denmark | MSc Business Analytics
------------------------------------------------------------------------------------------
[primary] The MSc is a two-year graduate programme with a workload of 120 ECTS credit points. || [curriculum] Curriculum for Business Analytics Go to primary content (press enter) Education Continuing Education Research Innovation Collaboration About DTU News Contact Danish English Search All search results People Contents Publications News Contact Danish English Explore Frontpage Education Graduate MSc programmes Business Analytics Curriculum Share on back Prerequisites Curriculum Specializations Career Curriculum for Business Analytics Programme provision To obtain the MSc degree in Business Analytics the student must fulfil the following requirements: Have passed Polytechnical foundation courses ad || 02270 Cybersecurity Fundamentals 5 point Autumn E5B (Wed 13-17) 02417 Time Series Analysis 5 point Spring F4B (Fri 8-12) 02443 Stochastic Simulation 5 point June 02805 Social graphs and interactions 10 point Autumn E5 (Wed 8-17) 02806 Social data analysis and visualization 5 point Spring F3A (Tues 8-12) 02807 Computational Tools for Data Science 5 point E7 (Tues 18-22) 42112 Mathematical Programming Modelling 5 point January 42114 Integer Programming 5 point Autumn E4A (Tues 13-17) 42115 Network Optimization 5 point Autumn E4B (Fri 8-12) 42137 Optimization using metaheuristics 5 point Spring F

==========================================================================================
EU_20 | Aalto University | Master's Programme in Business Analytics
------------------------------------------------------------------------------------------
[curriculum] Degree structure Total 120 ECTS Programme studies* 85-87 ECTS Elective studies 33-35 ECTS *Including master's thesis 30 ECTS You can find course descriptions in Sisu . || Programme studies 85–87 ECTS Programme studies Code : BIZ235 Scope : 85–87 ECTS Programme director: Juuso Liesiö Code Course name ECTS Period 30E03000 Data Science for Business I 6 I, IV ISM-E1004 Business Analytics 2 6 III ISM-E1999 Master's Thesis Seminar 3 I-II, III-V BIZ.matr Maturity Test 0 ISM.thes Master's Thesis 30 Choose at least one of the following 30E03500 Capstone: Data Science for Business II 6 II 57E00500 Capstone: Business Intelligence 6 IV-V Choose one or two of the following Choose only one course from this section if you selected both Capstone courses above, otherwise choose || Elective studies 33–35 ECTS Instructions for choosing elective studies You can choose elective studies to your Master's degree so that the scope of the degree (120 credits) is fulfilled. || If you have completed your bachelor’s degree outside of Finland, you must complete minimum of 3 ECTS in English including both oral and written proficiency.

In [272]:
curriculum_2021_final = {
    "EU_08": [1, 1, 1, 0, 0],
    "EU_09": [1, 1, 1, 0, 0],
    "EU_10": [1, 1, 0, 0, 0],
    "EU_14": [1, 0, 0, 0, 0],
    "EU_18": [pd.NA, pd.NA, pd.NA, pd.NA, pd.NA],
    "EU_19": [1, 1, 1, 0, 1]
}

for programme_id, values in curriculum_2021_final.items():
    mask = europe_2021["programme_id"] == programme_id

    for col, value in zip(curriculum_cols, values):
        europe_2021.loc[mask, col] = value


europe_2021["core_category_count"] = (
    europe_2021[curriculum_cols]
    .apply(pd.to_numeric, errors="coerce")
    .sum(axis=1, min_count=1)
)

print(
    europe_2021[
        ["programme_id"] + curriculum_cols + ["core_category_count"]
    ].to_string(index=False)
)

print(
    "\nProgrammes with curriculum data:",
    europe_2021["core_category_count"].notna().sum()
)

print(
    "Insufficient historical evidence:",
    europe_2021["core_category_count"].isna().sum()
)

programme_id statistics_core programming_core machine_learning_core data_visualization_core business_analytics_core  core_category_count
       EU_01               1                1                     1                       0                       1                  4.0
       EU_02               1                1                     1                       0                       0                  3.0
       EU_03               1                1                     0                       0                       1                  3.0
       EU_04               1                1                     1                       0                       0                  3.0
       EU_05               1                1                     1                       0                       0                  3.0
       EU_06               1                1                     1                       0                       0                  3.0
       EU_08               1                1                     1                       0                       0                  3.0
       EU_09               1                1                     1                       0                       0                  3.0
       EU_10               1                1                     0                       0                       0                  2.0
       EU_11               1                1                     1                       0                       1                  4.0
       EU_12               1                1                     1                       0                       0                  3.0
       EU_14               1                0                     0                       0                       0                  1.0
       EU_15               1                1                     1                       1                       1                  5.0
       EU_18            <NA>             <NA>                  <NA>                    <NA>                    <NA>                  NaN
       EU_19               1                1                     1                       0                       1                  4.0

Programmes with curriculum data: 14
Insufficient historical evidence: 1

In [273]:
outcomes_2021 = {
    "EU_01": 1,
    "EU_02": 0,
    "EU_03": 0,
    "EU_04": 0,
    "EU_05": 0,
    "EU_06": 0,
    "EU_08": 0,
    "EU_09": 0,
    "EU_10": 0,
    "EU_11": 0,
    "EU_12": 0,
    "EU_14": 0,
    "EU_15": 0,
    "EU_18": 0,
    "EU_19": 0
}

europe_2021["outcomes_reported"] = (
    europe_2021["programme_id"].map(outcomes_2021)
)

print(europe_2021[
    ["programme_id", "programme_name", "outcomes_reported"]
].to_string(index=False))

print(
    "\nMissing outcomes:",
    europe_2021["outcomes_reported"].isna().sum()
)

print("\nOutcome counts:")
print(europe_2021["outcomes_reported"].value_counts(dropna=False))

programme_id                                     programme_name  outcomes_reported
       EU_01                        MSc Business Analytics & AI                  1
       EU_02                                   MSc Data Science                  0
       EU_03                             MSc Business Analytics                  0
       EU_04                                   MSc Data Science                  0
       EU_05 MSc Statistics (Data Science and Machine Learning)                  0
       EU_06                         MSc in Social Data Science                  0
       EU_08                             Master in Data Science                  0
       EU_09                    MSc Mathematics in Data Science                  0
       EU_10                                   MSc Data Science                  0
       EU_11                             MSc Business Analytics                  0
       EU_12                                   MSc Data Science                  0
       EU_14              Master of Statistics and Data Science                  0
       EU_15          MSc Data Analytics and Business Economics                  0
       EU_18                                   MSc Data Science                  0
       EU_19                             MSc Business Analytics                  0

Missing outcomes: 0

Outcome counts:
outcomes_reported
0    14
1     1
Name: count, dtype: int64

In [274]:
# 1. 最后检查 2021 和 2026 的行数
print("2021 rows:", len(europe_2021))
print("2026 rows:", len(europe_2026))

# 2. 检查两张表的列是否一致
print("Same columns:",
      list(europe_2021.columns) == list(europe_2026.columns))

# 3. 合并成 Europe panel dataset
europe_panel = pd.concat(
    [europe_2021, europe_2026],
    ignore_index=True
)

# 4. 按 programme_id + year 排序
europe_panel = (
    europe_panel
    .sort_values(["programme_id", "year"])
    .reset_index(drop=True)
)

# 5. 检查 programme-year 是否重复
duplicates = europe_panel.duplicated(
    subset=["programme_id", "year"]
).sum()

print("\nTotal panel rows:", len(europe_panel))
print("Unique programmes:",
      europe_panel["programme_id"].nunique())
print("Duplicate programme-years:", duplicates)

print("\nRows by year:")
print(europe_panel["year"].value_counts().sort_index())

# 6. 查看最终数据
display(europe_panel)

2021 rows: 15
2026 rows: 20
Same columns: True

Total panel rows: 35
Unique programmes: 20
Duplicate programme-years: 0

Rows by year:
year
2021    15
2026    20
Name: count, dtype: int64

,programme_id,university,programme_name,year,country,region,school_type,college_type,ranking_tier,statistics_core,...,GRE_GMAT_policy,tuition_amount,currency,tuition_basis,duration_months,outcomes_reported,new_programme,source_type,source_url,access_date
0,EU_01,Imperial College London,MSc Business Analytics & AI,2021,United Kingdom,Europe,NaN,NaN,NaN,1,...,Optional / Recommended,<NA>,<NA>,NR - 2021/22 full-time MSc Business Analytics tuition amount was not directly verified from the official Imperial historical fee sources reviewed.,12,1,0,NaN,NaN,NaN
1,EU_01,Imperial College London,MSc Business Analytics & AI,2026,United Kingdom,Europe,NaN,NaN,NaN,1,...,Optional / Recommended,47000,GBP,Total programme tuition (international),12,1,0,Official university website,https://www.imperial.ac.uk/business-school/masters/business-analytics/,2026-09-23
2,EU_02,ETH Zurich,MSc Data Science,2021,Switzerland,Europe,NaN,NaN,NaN,1,...,Not reported,730,CHF,per semester; standard ETH tuition fee applicable in 2021,24,0,0,NaN,NaN,NaN
3,EU_02,ETH Zurich,MSc Data Science,2026,Switzerland,Europe,NaN,NaN,NaN,1,...,Not reported,2190,CHF,Per semester; threefold tuition fee for students assigned to fee group 2,24,0,0,Official university website,https://ethz.ch/en/studies/master/degree-programmes/engineering-sciences/data-science.html,2026-09-23
4,EU_03,UCL,MSc Business Analytics,2021,United Kingdom,Europe,NaN,NaN,NaN,1,...,Not reported,34100,GBP,full-time overseas tuition fee; 2021/22,12,0,0,NaN,NaN,NaN
5,EU_03,UCL,MSc Business Analytics,2026,United Kingdom,Europe,NaN,NaN,NaN,1,...,Not reported,46700,GBP,Full-time overseas tuition fee for 2026/27,12,0,0,Official university website,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/business-analytics-msc-2026,2026-09-23
6,EU_04,UCL,MSc Data Science,2021,United Kingdom,Europe,NaN,NaN,NaN,1,...,Not reported,34100,GBP,full-time overseas tuition fee; 2021/22,12,0,0,NaN,NaN,NaN
7,EU_04,UCL,MSc Data Science,2026,United Kingdom,Europe,NaN,NaN,NaN,1,...,Not reported,46700,GBP,Full-time overseas tuition fee for 2026/27,12,1,0,<NA>,https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/data-science-msc,<NA>
8,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),2021,United Kingdom,Europe,NaN,NaN,NaN,1,...,Not reported,<NA>,<NA>,NR - 2021/22 full-time overseas MSc Statistics (Data Science) tuition amount was not directly verified from the official Imperial historical fee sources reviewed.,12,0,0,NaN,NaN,NaN
9,EU_05,Imperial College London,MSc Statistics (Data Science and Machine Learning),2026,United Kingdom,Europe,NaN,NaN,NaN,1,...,Not reported,39900,GBP,Full-time overseas tuition fee for 2026 entry,12,0,0,<NA>,https://www.imperial.ac.uk/study/courses/postgraduate-taught/statistics-data-science/,<NA>
10,EU_06,University of Oxford,MSc in Social Data Science,2021,United Kingdom,Europe,NaN,NaN,NaN,1,...,Not required,27460,GBP,annual course fee; overseas including EU; 2021/22,10,0,0,NaN,NaN,NaN
11,EU_06,University of Oxford,MSc in Social Data Science,2026,United Kingdom,Europe,NaN,NaN,NaN,1,...,Not required,40730,GBP,Overseas annual course fee for 2026/27,10,0,0,<NA>,https://www.ox.ac.uk/admissions/graduate/courses/msc-social-data-science,<NA>
12,EU_07,UCL,MSc Data Science and Public Policy,2026,United Kingdom,Europe,NaN,NaN,NaN,1,...,Not reported,39200,GBP,Full-time overseas tuition fee for 2026/27,12,1,1,<NA>,https://www.ucl.ac.uk/social-historical-sciences/economics/study/data-science-and-public-policy-msc,<NA>
13,EU_08,EPFL,Master in Data Science,2021,Switzerland,Europe,NaN,NaN,NaN,1,...,Not reported,730,CHF,per semester; EPFL tuition fee applicable in 2021,24,0,0,NaN,NaN,NaN
14,EU_08,EPFL,Master in Data Science,2026,Switzerland,Europe,NaN,NaN,NaN,1,...,Not reported,2190,CHF,Tuition fee per semester for applicable foreign students,24,0,0,<NA>,https://www.epfl.ch/education/master/programs/data-science/,<NA>
15,EU_09,Technical University of Munich,MSc Mathematics in Data Science,2021,Germany,Europe,NaN,NaN,NaN,1,...,Not reported,0,EUR,"no tuition fee in 2021; students paid only the student union and semester ticket fee, approximately EUR 120 per semester",24,0,0,NaN,NaN,NaN
16,EU_09,Technical University of Munich,MSc Mathematics in Data Science,2026,Germany,Europe,NaN,NaN,NaN,1,...,Conditional,6000,EUR,Tuition fee per semester for international students from third countries,24,0,0,<NA>,https://www.tum.de/en/studies/degree-programs/detail/mathematics-in-data-science-master-of-science-msc,<NA>
17,EU_10,King's College London,MSc Data Science,2021,United Kingdom,Europe,NaN,NaN,NaN,1,...,Not reported,<NA>,<NA>,NR - programme-specific 2021/22 international tuition amount was not directly verified from the official King's College London historical sources reviewed.,12,0,0,NaN,NaN,NaN
18,EU_10,King's College London,MSc Data Science,2026,United Kingdom,Europe,NaN,NaN,NaN,1,...,Not reported,40450,GBP,Full-time international tuition fee for 2026/27,12,0,0,<NA>,https://www.kcl.ac.uk/study/postgraduate-taught/courses/data-science-msc,<NA>
19,EU_11,University of Edinburgh,MSc Business Analytics,2021,United Kingdom,Europe,NaN,NaN,NaN,1,...,Not reported,<NA>,<NA>,"NR - programme existed in 2021/22 and the University of Edinburgh maintains a 2021/22 historical fee archive, but the programme-specific overseas tuition amount was not directly verified from the official source reviewed.",12,0,0,NaN,NaN,NaN
20,EU_11,University of Edinburgh,MSc Business Analytics,2026,United Kingdom,Europe,NaN,NaN,NaN,1,...,Not reported,34800,GBP,International tuition fee for 2026 entry,12,0,0,<NA>,https://www.business-school.ed.ac.uk/msc/business-analytics,<NA>
21,EU_12,University of Edinburgh,MSc Data Science,2021,United Kingdom,Europe,NaN,NaN,NaN,1,...,Not reported,<NA>,<NA>,"NR - programme existed in 2021/22 and the University of Edinburgh maintains a 2021/22 historical fee archive, but the programme-specific overseas tuition amount was not directly verified from the official source reviewed.",12,0,0,NaN,NaN,NaN
22,EU_12,University of Edinburgh,MSc Data Science,2026,United Kingdom,Europe,NaN,NaN,NaN,1,...,Not reported,45410,GBP,Full-time international tuition fee for 2026/27,12,0,0,<NA>,https://study.ed.ac.uk/programmes/postgraduate-taught/902-data-science,<NA>
23,EU_13,Delft University of Technology,MSc Data Science and Artificial Intelligence Technology,2026,Netherlands,Europe,NaN,NaN,NaN,<NA>,...,Not reported,<NA>,<NA>,NR - no programme-specific 2026/27 non-EU/EEA tuition amount was directly verified from the official TU Delft sources reviewed.,24,0,1,<NA>,https://www.tudelft.nl/en/education/programmes/masters/dsait/msc-data-science-and-artificial-intelligence-technology,<NA>
24,EU_14,KU Leuven,Master of Statistics and Data Science,2021,Belgium,Europe,NaN,NaN,NaN,1,...,Not reported,<NA>,<NA>,"NR - official KU Leuven sources confirm that students registered in 2021/22 were subject to the basic tuition fee, but the exact 2021/22 programme-specific amount was not directly verified.",24,0,0,NaN,NaN,NaN
25,EU_14,KU Leuven,Master of Statistics and Data Science,2026,Belgium,Europe,NaN,NaN,NaN,1,...,Required,<NA>,<NA>,NR - official KU Leuven sources state that tuition depends on programme and nationality; no programme-specific 2026/27 non-EEA amount was directly verified.,24,0,0,<NA>,https://onderwijsaanbod.kuleuven.be/opleidingen/e/SC_51016989/diploma_omschrijving,<NA>
26,EU_15,Lund University,MSc Data Analytics and Business Economics,2021,Sweden,Europe,NaN,NaN,NaN,1,...,Not reported,<NA>,<NA>,"NR - programme existed in autumn 2021, but a programme-specific 2021 tuition amount for non-EU/EEA students was not directly verified from the official historical sources reviewed.",12,0,0,NaN,NaN,NaN
27,EU_15,Lund University,MSc Data Analytics and Business Economics,2026,Sweden,Europe,NaN,NaN,NaN,1,...,Not reported,150000,SEK,Full programme tuition fee for non-EU/EEA students,12,1,0,<NA>,https://www.lunduniversity.lu.se/study/data-analytics-and-business-economics-masters-programme-EAGDA,<NA>
28,EU_16,Politecnico di Milano,Master in Business Analytics and Data Science,2026,Italy,Europe,NaN,NaN,NaN,1,...,Not reported,25000,EUR,Total programme tuition; standard individual fee for October 2026 intake,12,0,1,<NA>,https://www.gsom.polimi.it/en/course/master-business-analytics-data-science,<NA>
29,EU_17,Utrecht University,MSc Data Science,2026,Netherlands,Europe,NaN,NaN,NaN,1,...,Not reported,25306,EUR,Full-time Non-EU/EEA institutional tuition fee for 2026-2027,24,0,1,<NA>,https://www.uu.nl/en/masters/data-science,<NA>
30,EU_18,RWTH Aachen University,MSc Data Science,2021,Germany,Europe,NaN,NaN,NaN,<NA>,...,Not reported,0,EUR,"no tuition fee in 2021/22; students paid a separate semester contribution of EUR 300.19 in winter semester 2021/22, which is not coded as tuition",24,0,0,NaN,NaN,NaN
31,EU_18,RWTH Aachen University,MSc Data Science,2026,Germany,Europe,NaN,NaN,NaN,1,...,Not reported,0,EUR,"No tuition fee, including for international students; semester contribution charged separately",24,0,0,<NA>,https://sc.informatik.rwth-aachen.de/en/studium/master/master-data-science/,<NA>
32,EU_19,Technical University of Denmark,MSc Business Analytics,2021,Denmark,Europe,NaN,NaN,NaN,1,...,Not reported,<NA>,<NA>,NR - programme-specific 2021 tuition amount for non-EU/EEA students was not directly verified from the official DTU historical sources reviewed.,24,0,0,NaN,NaN,NaN
33,EU_19,Technical University of Denmark,MSc Business Analytics,2026,Denmark,Europe,NaN,NaN,NaN,1,...,Not reported,7500,EUR,"Tuition fee per semester for fee-paying non-EU/EEA students; published total for 2-year MSc = EUR 30,000; DTU notes fees are expected to be revised for Autumn 2026",24,0,0,<NA>,https://www.dtu.dk/english/education/graduate/msc-programmes/business-analytics,<NA>
34,EU_20,Aalto University,Master's Programme in Business Analytics,2026,Finland,Europe,NaN,NaN,NaN,1,...,Conditional,15000,EUR,Annual tuition fee for non-EU/EEA students,24,0,1,<NA>,https://www.aalto.fi/en/programmes/masters-programme-in-business-analytics,<NA>

In [275]:
# ===== FINAL DATA QUALITY CHECK =====

print("=== PANEL STRUCTURE ===")
print("Rows:", len(europe_panel))
print("Programmes:", europe_panel["programme_id"].nunique())
print("Duplicate programme-years:",
      europe_panel.duplicated(["programme_id", "year"]).sum())


print("\n=== MISSING VALUES BY COLUMN ===")
missing_summary = pd.DataFrame({
    "missing_n": europe_panel.isna().sum(),
    "missing_pct": (
        europe_panel.isna().mean() * 100
    ).round(1)
})

display(
    missing_summary[
        missing_summary["missing_n"] > 0
    ]
)


print("\n=== KEY VARIABLES BY YEAR ===")

key_variables = [
    "statistics_core",
    "programming_core",
    "machine_learning_core",
    "data_visualization_core",
    "business_analytics_core",
    "core_category_count",
    "prerequisites",
    "GRE_GMAT_policy",
    "tuition_amount",
    "duration_months",
    "outcomes_reported"
]

missing_by_year = (
    europe_panel
    .groupby("year")[key_variables]
    .agg(lambda x: x.isna().sum())
)

display(missing_by_year)

=== PANEL STRUCTURE ===
Rows: 35
Programmes: 20
Duplicate programme-years: 0

=== MISSING VALUES BY COLUMN ===

                         missing_n  missing_pct
school_type                     35        100.0
college_type                    35        100.0
ranking_tier                    35        100.0
statistics_core                  2          5.7
programming_core                 2          5.7
machine_learning_core            2          5.7
data_visualization_core          2          5.7
business_analytics_core          2          5.7
core_category_count              2          5.7
tuition_amount                  10         28.6
currency                        10         28.6
source_type                     32         91.4
source_url                      15         42.9
access_date                     32         91.4

=== KEY VARIABLES BY YEAR ===

,statistics_core,programming_core,machine_learning_core,data_visualization_core,business_analytics_core,core_category_count,prerequisites,GRE_GMAT_policy,tuition_amount,duration_months,outcomes_reported
year,,,,,,,,,,,
2021,1,1,1,1,1,1,0,0,8,0,0
2026,1,1,1,1,1,1,0,0,2,0,0

In [277]:
# 把 QS 2026 Rank 从 programme_master 映射到 panel

rank_map = (
    programme_master
    .set_index("programme_id")["QS 2026 Rank"]
)

europe_panel["QS_2026_Rank"] = (
    europe_panel["programme_id"].map(rank_map)
)


# 根据 QS rank 创建 ranking tier
def make_ranking_tier(rank):
    if pd.isna(rank):
        return pd.NA
    elif rank <= 25:
        return "Top 25"
    elif rank <= 50:
        return "26-50"
    elif rank <= 100:
        return "51-100"
    else:
        return "101-150"


europe_panel["ranking_tier"] = (
    europe_panel["QS_2026_Rank"].apply(make_ranking_tier)
)


# 检查三个变量
print(
    "Missing school_type:",
    europe_panel["school_type"].isna().sum()
)

print(
    "Missing college_type:",
    europe_panel["college_type"].isna().sum()
)

print(
    "Missing QS rank:",
    europe_panel["QS_2026_Rank"].isna().sum()
)

print(
    "Missing ranking_tier:",
    europe_panel["ranking_tier"].isna().sum()
)


display(
    europe_panel[
        [
            "programme_id",
            "university",
            "school_type",
            "college_type",
            "QS_2026_Rank",
            "ranking_tier"
        ]
    ].drop_duplicates("programme_id")
)

Missing school_type: 0
Missing college_type: 0
Missing QS rank: 0
Missing ranking_tier: 0

,programme_id,university,school_type,college_type,QS_2026_Rank,ranking_tier
0,EU_01,Imperial College London,Public,Business,2,Top 25
2,EU_02,ETH Zurich,Public,Computing,7,Top 25
4,EU_03,UCL,Public,Business,9,Top 25
6,EU_04,UCL,Public,Engineering-Technology,9,Top 25
8,EU_05,Imperial College London,Public,Mathematics-Statistics,2,Top 25
10,EU_06,University of Oxford,Public,Social Science,4,Top 25
12,EU_07,UCL,Public,Social Science,9,Top 25
13,EU_08,EPFL,Public,Computing,22,Top 25
15,EU_09,Technical University of Munich,Public,Mathematics-Statistics,22,Top 25
17,EU_10,King's College London,Public,Computing,31,26-50
19,EU_11,University of Edinburgh,Public,Business,34,26-50
21,EU_12,University of Edinburgh,Public,Computing,34,26-50
23,EU_13,Delft University of Technology,Public,Engineering-Technology,47,26-50
24,EU_14,KU Leuven,Public,Mathematics-Statistics,60,51-100
26,EU_15,Lund University,Public,Business,72,51-100
28,EU_16,Politecnico di Milano,Public,Business,98,51-100
29,EU_17,Utrecht University,Public,Computing,103,101-150
30,EU_18,RWTH Aachen University,Public,Computing,105,101-150
32,EU_19,Technical University of Denmark,Public,Engineering-Technology,107,101-150
34,EU_20,Aalto University,Public,Business,114,101-150

In [278]:
# ===== FINAL AUDIT + SAVE =====

# 1. 基础结构检查
print("=== FINAL PANEL ===")
print("Rows:", len(europe_panel))
print("Columns:", len(europe_panel.columns))
print("Programmes:", europe_panel["programme_id"].nunique())
print(
    "Duplicate programme-years:",
    europe_panel.duplicated(["programme_id", "year"]).sum()
)

# 2. 关键 ID 不允许缺失
essential_cols = [
    "programme_id",
    "university",
    "programme_name",
    "year",
    "country",
    "region",
    "school_type",
    "college_type",
    "ranking_tier",
    "duration_months"
]

print("\n=== ESSENTIAL VARIABLES ===")
print(europe_panel[essential_cols].isna().sum())

# 3. 查看仍然存在的合理 missing
print("\n=== REMAINING MISSING VALUES ===")
missing_final = pd.DataFrame({
    "missing_n": europe_panel.isna().sum(),
    "missing_pct": (
        europe_panel.isna().mean() * 100
    ).round(1)
})

display(
    missing_final[
        missing_final["missing_n"] > 0
    ]
)

# 4. 保存最终 panel
output_path = "../data/europe_programme_panel_2021_2026.csv"

europe_panel.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("\nSaved successfully:")
print(output_path)
print("Final shape:", europe_panel.shape)

=== FINAL PANEL ===
Rows: 35
Columns: 27
Programmes: 20
Duplicate programme-years: 0

=== ESSENTIAL VARIABLES ===
programme_id       0
university         0
programme_name     0
year               0
country            0
region             0
school_type        0
college_type       0
ranking_tier       0
duration_months    0
dtype: int64

=== REMAINING MISSING VALUES ===

                         missing_n  missing_pct
statistics_core                  2          5.7
programming_core                 2          5.7
machine_learning_core            2          5.7
data_visualization_core          2          5.7
business_analytics_core          2          5.7
core_category_count              2          5.7
tuition_amount                  10         28.6
currency                        10         28.6
source_type                     32         91.4
source_url                      15         42.9
access_date                     32         91.4

Saved successfully:
../data/europe_programme_panel_2021_2026.csv
Final shape: (35, 27)

In [279]:
# ===== COMPLETE 2026 SOURCE TRACKING =====

official_url_map = (
    programme_master
    .set_index("programme_id")["official_url"]
)

mask_2026 = europe_panel["year"] == 2026

europe_panel.loc[
    mask_2026, "source_type"
] = "Official university website"

europe_panel.loc[
    mask_2026, "source_url"
] = (
    europe_panel.loc[mask_2026, "programme_id"]
    .map(official_url_map)
)

print("2026 missing source_type:",
      europe_panel.loc[mask_2026, "source_type"].isna().sum())

print("2026 missing source_url:",
      europe_panel.loc[mask_2026, "source_url"].isna().sum())

2026 missing source_type: 0
2026 missing source_url: 0

In [280]:
# ===== 2021 SOURCE TRACKING =====

mask_2021 = europe_panel["year"] == 2021

# 所有 2021 observations 都经过 historical-source review
europe_panel.loc[
    mask_2021, "source_type"
] = "Official historical / archived university source"

# 已明确验证到的 historical source URL
historical_urls = {
    "EU_08": "https://www.epfl.ch/schools/ic/wp-content/uploads/2021/12/LC_DS-2021-2022.pdf"
}

# 只给有明确 historical URL 的项目填 URL
for programme_id, url in historical_urls.items():
    europe_panel.loc[
        (europe_panel["programme_id"] == programme_id) &
        (europe_panel["year"] == 2021),
        "source_url"
    ] = url


print(
    "2021 missing source_type:",
    europe_panel.loc[
        mask_2021, "source_type"
    ].isna().sum()
)

print(
    "2021 missing source_url:",
    europe_panel.loc[
        mask_2021, "source_url"
    ].isna().sum()
)

print(
    "\nOverall missing source_type:",
    europe_panel["source_type"].isna().sum()
)

2021 missing source_type: 0
2021 missing source_url: 14

Overall missing source_type: 0

In [281]:
output_path = "../data/europe_programme_panel_2021_2026.csv"

europe_panel.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("FINAL EUROPE PANEL SAVED")
print("Rows:", len(europe_panel))
print("Columns:", len(europe_panel.columns))
print("Programmes:", europe_panel["programme_id"].nunique())
print("Duplicate programme-years:",
      europe_panel.duplicated(["programme_id", "year"]).sum())
print("Path:", output_path)

FINAL EUROPE PANEL SAVED
Rows: 35
Columns: 27
Programmes: 20
Duplicate programme-years: 0
Path: ../data/europe_programme_panel_2021_2026.csv

In [282]:
# Fill access date for all Europe records
europe_panel["access_date"] = "2026-09-23"

print(europe_panel["access_date"].value_counts(dropna=False))

access_date
2026-09-23    35
Name: count, dtype: int64

In [283]:
# ===== FINAL SCHOOL TYPE + ACCESS DATE CLEANING =====

school_type_map = {
    "EU_01": "Independent",   # Imperial
    "EU_02": "Public",        # ETH Zurich
    "EU_03": "Independent",   # UCL
    "EU_04": "Independent",   # UCL
    "EU_05": "Independent",   # Imperial
    "EU_06": "Independent",   # Oxford
    "EU_07": "Independent",   # UCL
    "EU_08": "Public",        # EPFL
    "EU_09": "Public",        # TUM
    "EU_10": "Independent",   # King's
    "EU_11": "Independent",   # Edinburgh
    "EU_12": "Independent",   # Edinburgh
    "EU_13": "Public",        # TU Delft
    "EU_14": "Private",       # KU Leuven
    "EU_15": "Public",        # Lund
    "EU_16": "Public",        # Politecnico di Milano
    "EU_17": "Public",        # Utrecht
    "EU_18": "Public",        # RWTH Aachen
    "EU_19": "Public",        # DTU
    "EU_20": "Foundation"     # Aalto
}

# Apply school type to both 2021 and 2026 records
europe_panel["school_type"] = (
    europe_panel["programme_id"].map(school_type_map)
)

# Access date = date on which we accessed/verified the sources
europe_panel["access_date"] = "2026-09-23"


# ===== CHECK =====

print("Missing school_type:",
      europe_panel["school_type"].isna().sum())

print("Missing access_date:",
      europe_panel["access_date"].isna().sum())

print("\nSchool type by unique programme:")
print(
    europe_panel[
        ["programme_id", "school_type"]
    ]
    .drop_duplicates()
    ["school_type"]
    .value_counts()
)

print("\nAccess date:")
print(
    europe_panel["access_date"].value_counts(dropna=False)
)

Missing school_type: 0
Missing access_date: 0

School type by unique programme:
school_type
Independent    9
Public         9
Private        1
Foundation     1
Name: count, dtype: int64

Access date:
access_date
2026-09-23    35
Name: count, dtype: int64

In [284]:
# Rename for clearer cross-country interpretation
europe_panel = europe_panel.rename(
    columns={"school_type": "institution_type"}
)

# Final validation
print("Missing institution_type:",
      europe_panel["institution_type"].isna().sum())

print("Missing access_date:",
      europe_panel["access_date"].isna().sum())

print("\nInstitution type:")
print(
    europe_panel[
        ["programme_id", "university", "institution_type"]
    ]
    .drop_duplicates("programme_id")
    .sort_values("programme_id")
)

# Save corrected final version
output_path = "../data/europe_programme_panel_2021_2026.csv"

europe_panel.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("\nFINAL EUROPE PANEL UPDATED")
print("Shape:", europe_panel.shape)
print("Path:", output_path)

Missing institution_type: 0
Missing access_date: 0

Institution type:
   programme_id                       university institution_type
0         EU_01          Imperial College London      Independent
2         EU_02                       ETH Zurich           Public
4         EU_03                              UCL      Independent
6         EU_04                              UCL      Independent
8         EU_05          Imperial College London      Independent
10        EU_06             University of Oxford      Independent
12        EU_07                              UCL      Independent
13        EU_08                             EPFL           Public
15        EU_09   Technical University of Munich           Public
17        EU_10            King's College London      Independent
19        EU_11          University of Edinburgh      Independent
21        EU_12          University of Edinburgh      Independent
23        EU_13   Delft University of Technology           Public
24        EU_14                        KU Leuven          Private
26        EU_15                  Lund University           Public
28        EU_16            Politecnico di Milano           Public
29        EU_17               Utrecht University           Public
30        EU_18           RWTH Aachen University           Public
32        EU_19  Technical University of Denmark           Public
34        EU_20                 Aalto University       Foundation

PermissionError: [Errno 13] Permission denied: '../data/europe_programme_panel_2021_2026.csv'

In [285]:
output_path = "../data/europe_programme_panel_2021_2026.csv"

europe_panel.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("FINAL EUROPE PANEL UPDATED")
print("Shape:", europe_panel.shape)
print("Path:", output_path)

FINAL EUROPE PANEL UPDATED
Shape: (35, 27)
Path: ../data/europe_programme_panel_2021_2026.csv

In [286]:
europe_panel.to_csv(
    "../data/europe_programme_panel_2021_2026_FINAL.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Saved as FINAL version")

Saved as FINAL version

In [287]:
final_path = "../data/europe_programme_panel_2021_2026_FINAL.csv"

europe_panel.to_csv(
    final_path,
    index=False,
    encoding="utf-8-sig"
)

print("FINAL FILE SAVED")
print("Rows:", len(europe_panel))
print("Columns:", len(europe_panel.columns))
print("Programmes:", europe_panel["programme_id"].nunique())
print("Duplicate programme-years:",
      europe_panel.duplicated(["programme_id", "year"]).sum())
print("Missing institution_type:",
      europe_panel["institution_type"].isna().sum())
print("Missing access_date:",
      europe_panel["access_date"].isna().sum())
print("Path:", final_path)

FINAL FILE SAVED
Rows: 35
Columns: 27
Programmes: 20
Duplicate programme-years: 0
Missing institution_type: 0
Missing access_date: 0
Path: ../data/europe_programme_panel_2021_2026_FINAL.csv